### PR TITLE
Refactor: Throw error if specific type intrinsics are called with wrong type arguments

### PR DESCRIPTION
**Pull request by HarshitaKalani**
Fixes: https://github.com/lfortran/lfortran/issues/3849

### CODE REVIEW

**Comment by certik** [comment]
Is this ready for review?

**Comment by HarshitaKalani** [comment]
Yes, it can be reviewed. I wanted some suggestions if this approach looks fine to you. I was trying to make it modular.

**Review by certik — APPROVED** [review]
I think that this is fine. Thanks for cleaning it up!

**Comment by certik** [comment]
Thanks!

**Pull request merged**
