### PR TITLE
Refactor symbol duplications in template instantiation

### PR DESCRIPTION
**Pull request by ansharlubis**

### CODE REVIEW

**Comment by certik** [comment]
Let's finish and merge https://github.com/lfortran/lfortran/pull/2298 first, then we'll rebase this one and I'll review it. Overall it looks good so far.

**Comment by certik** [comment]
Conflicts have to be resolved.

**Comment by ansharlubis** [comment]
@certik Got it, I'll handle it once I have free time this week.

**Review by certik — APPROVED** [review]
I think this looks good, thanks!

**Pull request merged**
