### PR TITLE
Implement `function_call_in_declaration` pass

### LINKED ISSUE #3337: FunctionType is tied to scope
Requested in #3323

```fortran
pure function diag_rsp_mat(A) result(res)
real, intent(in) :: A(:,:)
real :: res(minval(shape(A)))
end function diag_rsp_mat
```

> LFortran

```console
% lfortran stdlib_linalg.f90 --show-llvm                  
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2372
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2256
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 847
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 292
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 314
    diagnostics, lm.files.back().in_filename);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9560
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 302
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 166
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: subroutine_from_function
```

```clojure
                    (FunctionType
                        [(Array
                            (Real 4)
                            [(()
                            ())
                            (()
                            ())]
                            DescriptorArray
                        )
                        (Array
                            (Real 4)
                            [((IntegerConstant 1 (Integer 4))
                            (FunctionCall
                                1 MinVal_4_1_0
                                1 MinVal_4_1_0
                                [((Var 2 __libasr__created__var__1__func_call_arg_tmp_))] --------- Incorrect FunctionType
                                (Integer 4)
                                ()
                                ()
                            ))]
                            PointerToDataArray
                        )]
                        ()
                        Source
                        Implementation
                        ()
                        .false.
                        .true.
                        .false.
                        .false.
                        .false.
                        []
                        .false.
                    )
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #3337, towards #3323

### CODE REVIEW

**Review by certik — APPROVED** [review]
Great job, very good!

Couple questions/comments:

* Does this only happen for functions that return arrays, or for any function? What if it is only one function, does it still get wrapped? Or only for nested functions?
* Can you add the pass to the `src/libasr/gen_pass.py` script and run it?

**Comment by Pranavchiku** [comment]
> Does this only happen for functions that return arrays, or for any function? 

Right now happens for any `IntrinsicArrayFunction`, we can restrict it to only for functions that return an integer.

> What if it is only one function, does it still get wrapped? Or only for nested functions?

It gets wrapped for every function.

**Comment by Pranavchiku** [comment]
TODO:

```console
pure function diag_rsp_mat(A, k) result(res)
real, intent(in) :: A(:,:)
integer, intent(in) :: k
real :: res(minval(shape(A)) - abs(k))

res = 123.71_4
end function diag_rsp_mat
```

Can be done in this or subsequent PRs, I have code ready though, few integration tests fail, will see to push in this PR or will open other.

**Comment by certik** [comment]
I think this is good then. We can improve upon this with subsequent PRs.

**Pull request merged**
