### PR TITLE
Enable single line end of nested loop

### PR DESCRIPTION
**Pull request by konradha**
Observe the example

```fortran
          do 100 k=1,2
            do 100 l=1,3
              do 100 m=1,4
                do 100 n=1,5
                  print *, k, l
 100      continue
```
While `gfortran -fdump-parse-tree` tells us that this is a deprecated feature, it executes and generates the following structure

```bash
  DO  100   main:k=1 2 1
    DO  100   main:l=1 3 1
      DO  100   main:m=1 4 1
        DO  100   main:n=1 5 1
          WRITE UNIT=6 FMT=-1
          TRANSFER main:k
          TRANSFER main:l
          DT_END
100       CONTINUE
```

While this PR does not work in the current state, it shouldn't be too hard to enable this feature.

### CODE REVIEW

**Comment by konradha** [comment]
@luizpbraga any suggestions?

**Comment by luizpbraga** [comment]
> @luizpbraga any suggestions?

Nop. I clicked in the wrong emoji ...  😬

**Comment by konradha** [comment]
There is an issue with declaring a variable with the same name as the scope name (ie. assigning `f=6` in a function called `f`) when using implicit typing.

**Review by certik — APPROVED** [review]
I think this is fine, thanks!

**Pull request merged**
