### PR TITLE
Detect kokkos at cmake time

### PR DESCRIPTION
**Pull request by junghans**
Let cmake try to find kokkos and if it found remember the include and library directory, so one doesn't have to set `LFORTRAN_KOKKOS_DIR`.

Bonus feature: support for custom lib and include dirs in cmake, e.g. most distros install kokkos in `/usr/lib64` and `/usr/nclude/kokkos`, which currently doesn't work.

### CODE REVIEW

**Comment by certik** [comment]
As long as it keeps working with Conda that installs the binary on a different system in a different location. I need to study the logic more.

**Comment by junghans** [comment]
> As long as it keeps working with Conda that installs the binary on a different system in a different location. I need to study the logic more.

It actually works with Conda's kokkos package now, too!

**Comment by junghans** [comment]
@certik this is ready for a review.

**Comment by junghans** [comment]
@certik please merge #2971 then I can do some more testing here.

**Comment by junghans** [comment]
@certik this is already for a review.

**Review by certik — APPROVED** [review]
I think that this is fine. Thank you!

If something breaks, we'll fix it as we go.

**Pull request merged**
