### PR TITLE
Added requirement, template as symbols in ASR

### PR DESCRIPTION
**Pull request by ansharlubis**
Also cleaned up some unnecessary fields from the FunctionType.

### CODE REVIEW

**Comment by certik** [comment]
@ansharlubis I think in general this is fine I don't see any major blockers. You said you still want to finish a few things. Why don't you finish it and I'll do a final detailed review.

**Comment by ansharlubis** [comment]
@certik I've moved the remaining work to a different branch, so this one is ready for merge once there is no more issues.

**Comment by certik** [comment]
@ansharlubis Ok. Can you please resolve conflicts here and prepare this PR for merging? Let's get it in.

**Comment by ansharlubis** [comment]
> > @certik Is there a specific command that can be used to update test_llvm.cpp or do I need to update them manually?
> 
> I think it needs to be updated manually.

I see! Thanks a lot, I've done it manually!

**Review by certik — APPROVED** [review]
I think that this is fine. I merged the latest main to ensure everything works. After that I'll squash it and merge it.

**Pull request merged**
