### PR TITLE
Add ```dsqrt```, ```datan```, ```dabs``` implementation

### PR DESCRIPTION
**Pull request by Pranavchiku**
This PR successfully compiles ```scipy/scipy/special/amos/zsqrt.f``` to ASR

>ASR

```
(TranslationUnit (SymbolTable 1 {azsqrt: (Function (SymbolTable 2 {ai: (Variable 2 ai Unspecified () () Default (Real 8 []) Source Public Required .false.), ar: (Variable 2 ar Unspecified () () Default (Real 8 []) Source Public Required .false.), azabs: (Variable 2 azabs Local () () Default (Real 8 []) Source Public Required .false.), bi: (Variable 2 bi Unspecified () () Default (Real 8 []) Source Public Required .false.), br: (Variable 2 br Unspecified () () Default (Real 8 []) Source Public Required .false.), dabs: (ExternalSymbol 2 dabs 226 dabs lfortran_intrinsic_math2 [] dabs Private), datan: (ExternalSymbol 2 datan 4 datan lfortran_intrinsic_math [] datan Private), dcos: (ExternalSymbol 2 dcos 4 dcos lfortran_intrinsic_math [] dcos Private), dpi: (Variable 2 dpi Local () (RealConstant 3.141593 (Real 8 [])) Default (Real 8 []) Source Public Required .false.), drt: (Variable 2 drt Local () (RealConstant 7.071068 (Real 8 [])) Default (Real 8 []) Source Public Required .false.), dsin: (ExternalSymbol 2 dsin 4 dsin lfortran_intrinsic_math [] dsin Private), dsqrt: (ExternalSymbol 2 dsqrt 4 dsqrt lfortran_intrinsic_math [] dsqrt Private), dtheta: (Variable 2 dtheta Local () () Default (Real 8 []) Source Public Required .false.), zm: (Variable 2 zm Local () () Default (Real 8 []) Source Public Required .false.)}) azsqrt [(Var 2 ar) (Var 2 ai) (Var 2 br) (Var 2 bi)] [] [(= (Var 2 zm) (ArrayItem (Var 2 azabs) [(() (Var 2 ar) ()) (() (Var 2 ai) ())] (Real 8 []) ()) ()) (= (Var 2 zm) (FunctionCall 2 dsqrt () [((Var 2 zm))] (Real 8 []) () ()) ()) (If (RealCompare (Var 2 ar) Eq (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(GoTo 10)] []) (If (RealCompare (Var 2 ai) Eq (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(GoTo 20)] []) (= (Var 2 dtheta) (FunctionCall 2 datan () [((RealBinOp (Var 2 ai) Div (Var 2 ar) (Real 8 []) ()))] (Real 8 []) () ()) ()) (If (RealCompare (Var 2 dtheta) LtE (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(GoTo 40)] []) (If (RealCompare (Var 2 ar) Lt (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(= (Var 2 dtheta) (RealBinOp (Var 2 dtheta) Sub (Var 2 dpi) (Real 8 []) ()) ())] []) (GoTo 50) (GoToTarget 10) (If (RealCompare (Var 2 ai) Gt (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(GoTo 60)] []) (If (RealCompare (Var 2 ai) Lt (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(GoTo 70)] []) (= (Var 2 br) (RealConstant 0.000000 (Real 8 [])) ()) (= (Var 2 bi) (RealConstant 0.000000 (Real 8 [])) ()) (Return) (GoToTarget 20) (If (RealCompare (Var 2 ar) Gt (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(GoTo 30)] []) (= (Var 2 br) (RealConstant 0.000000 (Real 8 [])) ()) (= (Var 2 bi) (FunctionCall 2 dsqrt () [((FunctionCall 2 dabs () [((Var 2 ar))] (Real 8 []) () ()))] (Real 8 []) () ()) ()) (Return) (GoToTarget 30) (= (Var 2 br) (FunctionCall 2 dsqrt () [((Var 2 ar))] (Real 8 []) () ()) ()) (= (Var 2 bi) (RealConstant 0.000000 (Real 8 [])) ()) (Return) (GoToTarget 40) (If (RealCompare (Var 2 ar) Lt (RealConstant 0.000000 (Real 8 [])) (Logical 4 []) ()) [(= (Var 2 dtheta) (RealBinOp (Var 2 dtheta) Add (Var 2 dpi) (Real 8 []) ()) ())] []) (GoToTarget 50) (= (Var 2 dtheta) (RealBinOp (Var 2 dtheta) Mul (RealConstant 0.500000 (Real 8 [])) (Real 8 []) ()) ()) (= (Var 2 br) (RealBinOp (Var 2 zm) Mul (FunctionCall 2 dcos () [((Var 2 dtheta))] (Real 8 []) () ()) (Real 8 []) ()) ()) (= (Var 2 bi) (RealBinOp (Var 2 zm) Mul (FunctionCall 2 dsin () [((Var 2 dtheta))] (Real 8 []) () ()) (Real 8 []) ()) ()) (Return) (GoToTarget 60) (= (Var 2 br) (RealBinOp (Var 2 zm) Mul (Var 2 drt) (Real 8 []) ()) ()) (= (Var 2 bi) (RealBinOp (Var 2 zm) Mul (Var 2 drt) (Real 8 []) ()) ()) (Return) (GoToTarget 70) (= (Var 2 br) (RealBinOp (Var 2 zm) Mul (Var 2 drt) (Real 8 []) ()) ()) (= (Var 2 bi) (RealBinOp (RealUnaryMinus (Var 2 zm) (Real 8 []) ()) Mul (Var 2 drt) (Real 8 []) ()) ()) (Return)] () Source Public Implementation () .false. .false. .false.), iso_c_binding: (IntrinsicModule lfortran_intrinsic_iso_c_binding), iso_fortran_env: (IntrinsicModule lfortran_intrinsic_iso_fortran_env), lfortran_intrinsic_builtin: (IntrinsicModule lfortran_intrinsic_builtin), lfortran_intrinsic_math: (IntrinsicModule lfortran_intrinsic_math), lfortran_intrinsic_math2: (IntrinsicModule lfortran_intrinsic_math2), lfortran_intrinsic_math3: (IntrinsicModule lfortran_intrinsic_math3)}) [])
```

### CODE REVIEW

**Comment by Smit-create** [comment]
Hi @Pranavchiku,
Thanks for the fix. Please use this commit for reference: https://github.com/lfortran/lfortran/pull/638/commits/0af1425d8bad9d082d26e6a104029d87d425f4a5#diff-df7c44ab1e9b9fcbbd630f74833d15e79fea8edb1b055a77539087e6c9a398b8

**Comment by Pranavchiku** [comment]
@certik this PR can have a final review

**Comment by Pranavchiku** [comment]
I guess these changes are already merged in #685

**Comment by Smit-create** [comment]
> I guess these changes are already merged in #685

No, they are different

**Pull request merged**
