### PR TITLE
Assume dimension at runtime for array arguments in a subroutine

### LINKED ISSUE #1642: Using module variables as dimensions in function arguments
Here is a minimal reproducible example that compiles with GFortran:
```fortran
module test_module_dim
implicit none
integer :: nx

contains

subroutine f(x)
real, intent(in) :: x(nx)
end subroutine

end module
```
and fails with LFortran:
```console
$ lfortran a.f90 
ASR verify pass error: ASR verify: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
  --> a.f90:7:1 - 10:1
   |
 7 |    subroutine f(x)
   |    ^^^^^^^^^^^^^^^...
...
   |
10 |    
   | ...^ failed here
```
But I don't understand the semantics of this yet, or if it is even valid Fortran. It is however used in SNAP here: https://github.com/lanl/SNAP/blob/e7ab43dfb0c16419d9a42d756141d5957ac526fc/src/geom.f90#L257, so we need to address this one way or the other.

I also asked here: https://fortran-lang.discourse.group/t/using-module-variables-as-dimensions-in-function-arguments/5742

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #1642 

```fortran
module test_module_dim
   implicit none
   integer :: nx
contains
   
   subroutine f(x)
      integer, intent(in) :: x(nx)
      print *, x
   end subroutine

end module
```

is transformed to

```fortran
module test_module_dim
   implicit none
   integer(4) :: nx

contains

   subroutine f(x)
      integer(4), dimension(:), intent(in) :: x
      print *, x
   end subroutine f

end module test_module_dim
```

We do this transformation in the AST -> ASR conversion, and only when a subroutine argument is an array which has an external dependency.

### Working
```fortran
module test_module_dim
   implicit none
   integer :: nx
contains

   subroutine f(x)
      integer, intent(in) :: x(nx)
      print *, x
   end subroutine

end module

program example
   use test_module_dim
   integer :: cs(6)
   cs = [1, 2, 3, 4, 5, 6]
   call f(cs)
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
1 2 3 4 5 6 
```

### CODE REVIEW

**Comment by kmr-srbh** [comment]
This PR does not fix #2430. I am pushing fixes to that in a separate PR.

**Comment by Shaikh-Ubaid** [comment]
I don't think converting the original code to `integer(4), dimension(:), intent(in) :: x` is the right approach. Can we not convert this to something like `integer, intent(in) :: x(__lcompilers_get_nx())` ?

**Comment by Shaikh-Ubaid** [comment]
@certik what are your thoughts on this?

**Comment by certik** [comment]
Yes, this has to be converted to `integer, intent(in) :: x(__lcompilers_get_nx())`. I thought we are already doing that for the simple cases.

**Comment by kmr-srbh** [comment]
> Can we not convert this to something like `integer, intent(in) :: x(__lcompilers_get_nx())` ?

This can be done. I tried to handle this in AST -> ASR following https://github.com/lfortran/lfortran/issues/1642#issuecomment-1787924605.

**Comment by Pranavchiku** [comment]
> I don't think converting the original code to `integer(4), dimension(:), intent(in) :: x` is the right approach. Can we not convert this to something like `integer, intent(in) :: x(__lcompilers_get_nx())` ?

I agree, we shall use this approach.

**Comment by kmr-srbh** [comment]
```c++
if (current_scope->get_symbol(ASRUtils::symbol_name(end_sym)) == nullptr) {
    end = get_transformed_function_call(end_sym);
}
```

Adding the above line to the `process_dims()` function in the `ast_common_visitor.h` file does the above transformation, but I think this is incomplete. The above code considers all cases where the `dimension` maybe out-of-scope. I think the correct way may be to check if we are inside a `Function` and then check whether the symbol is found or not. How do we know if a symbol is present inside the symbol table of a `Function`? I see that the ASR contains information about this. How do we access it?

```clojure
f:
   (Function        ;; This is the line I am talking about
      (SymbolTable
            7
            {
               x:
                  (Variable
                        7
                        x
                        [nx]
                        In
                        ()
                        ()
                        Default
                        (Array
                           (Integer 4)
                           [((IntegerConstant 1 (Integer 4))
                           (Var 6 nx))]
                           PointerToDataArray
                        )
                        ()
                        Source
                        Public
                        Required
                        .false.
                  )
            })
      f
      (FunctionType
            [(Array
               (Integer 4)
               [((IntegerConstant 1 (Integer 4))
               (Var 6 nx))]
               PointerToDataArray
            )]
            ()
            Source
            Implementation
            ()
            .false.
            .false.
            .false.
            .false.
            .false.
            []
            .false.
      )
      []
      [(Var 7 x)]
      []
      ()
      Public
      .false.
      .false.
      ()
   )
```

**Comment by Shaikh-Ubaid** [comment]
>How do we know if a symbol is present inside the symbol table of a Function?

To know if a symbol (of name let's say "abc") inside the symbol table of a `ASR::Function_t* x`, you can do `x->m_symtab->get_symbol("abc") != nullptr`. If you want to find a symbol which is either in the function or in one of its parent, then you can do `x->m_symtab->resolve_symbol("abc") != nullptr`.

**Comment by kmr-srbh** [comment]
> To know if a symbol (of name let's say "abc") inside the symbol table of a `ASR::Function_t* x`, you can do `x->m_symtab->get_symbol("abc") != nullptr`. If you want to find a symbol which is either in the function or in one of its parent, then you can do `x->m_symtab->resolve_symbol("abc") != nullptr`.

@Shaikh-Ubaid you are right about this, but I wish to know how to get the type of the current scope I am initially searching the symbol in. As the case is, we want the symbol to not exist in the current scope, to do the transformation. So for example, when we are processing the dimensions of an array, we wish to know whether that array is inside a subroutine, a program or a module. The code provided in https://github.com/lfortran/lfortran/pull/4104#issuecomment-2137308775 does the required code transformation, but we do not consider the scope. So, in case an array is declared in a program with the dimension variable present in a module, this will transform the code. In some cases, this even causes a `code generation error`.

**Comment by kmr-srbh** [comment]
I came up with this logic for the PR:
```c++
if (current_scope->get_symbol(ASRUtils::symbol_name(end_sym)) == nullptr) {
    if (current_scope->asr_owner != nullptr) {
        ASR::symbol_t* asr_owner_sym = ASR::down_cast<ASR::symbol_t>(current_scope->asr_owner);
        if (ASR::is_a<ASR::Function_t>(*asr_owner_sym)) {
            end = get_transformed_function_call(end_sym);
        }
}
```

On execution of the code and analyzing the result, I found that `current_scope->asr_owner` is a `nullptr` and we do not reach the block which does the transformation. Why is it so? Could someone please guide me over where I might be going wrong?

**Comment by assem2002** [comment]
I want to point to something.
If you're trying to pass this error 
```shell
ASR verify pass error: ASR verify: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
```

**Comment by assem2002** [comment]
I want to point to something.
If you're trying to pass this error 
```Fortran
real, intent(in) :: x(nx)
```
```shell
ASR verify pass error: ASR verify: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
```

When you use the dimension attribute
```Fortran
real, dimension(nx) ,intent(in) :: x
```
It passes this error and uses `_lcompiler_get_nx()`.

The problem is that it  `nx` value doesn't get changed, it just point to the constant provided in while declaring nx.

Do you think it's better way to just change the parser to handle it as `attrdimension` node ?

**Comment by kmr-srbh** [comment]
Great catch @assem2002! Instead of hardcoding the value of the variable, we can instead do something like
```
pure integer(4) function __lcompilers_get_nx() result(__nx)
   use test_module_dim
   __nx = nx
   end function __lcompilers_get_nx
```

**Comment by assem2002** [comment]
I'm glad it helps. but could you follow me up what exactly you trying to solve I'm feeling a little confused :) .

**Comment by kmr-srbh** [comment]
> I'm glad it helps. but could you follow me up what exactly you trying to solve I'm feeling a little confused :) .

The issue is that we are unable to set the dimension of an array argument in a subroutine using a variable which is present in a module. The important feature here is that both the variable and subroutine are part of the same module.

**Comment by assem2002** [comment]
cool I guess we already have `_lcompilers_get_nx` procedure that works in similar situations but as i've mentioned it returns the value provided in declaration even if you mutate that `nx` in remains constant.

**Comment by kmr-srbh** [comment]
> cool I guess we already have `_lcompilers_get_nx` procedure that works in similar situations but as i've mentioned it returns the value provided in declaration even if you mutate that `nx` in remains constant.

The issue is with this implementation only. Here is an example using a variable from module to set the dimension. We modify the dimension here and some random garbage value is printed.
```fortran

module test_module_dim
   implicit none
   integer(4), save :: nx = 4

end module test_module_dim

program example
   use test_module_dim, only: nx
   implicit none
   integer(4), dimension(6) :: cs

   cs = [1, 2, 3, 4, 5, 6]
   call f(cs)
   nx = 10
   call f(cs)

contains

   subroutine f(x)
      integer(4), dimension(nx), intent(in) :: x

      print *, x
   end subroutine f

end program example
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
1 2 3 4 
1 2 3 4 5 6 479546168 32766 -371031728 30089 
```

**Comment by assem2002** [comment]
Cool. I think i got it :) .

**Comment by Pranavchiku** [comment]
I'll close this PR with reference to #4130.

**Pull request closed without merging**
