### PR TITLE
chore: setup is_argument correctly while processing dims

### LINKED ISSUE #1642: Using module variables as dimensions in function arguments
Here is a minimal reproducible example that compiles with GFortran:
```fortran
module test_module_dim
implicit none
integer :: nx

contains

subroutine f(x)
real, intent(in) :: x(nx)
end subroutine

end module
```
and fails with LFortran:
```console
$ lfortran a.f90 
ASR verify pass error: ASR verify: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
  --> a.f90:7:1 - 10:1
   |
 7 |    subroutine f(x)
   |    ^^^^^^^^^^^^^^^...
...
   |
10 |    
   | ...^ failed here
```
But I don't understand the semantics of this yet, or if it is even valid Fortran. It is however used in SNAP here: https://github.com/lanl/SNAP/blob/e7ab43dfb0c16419d9a42d756141d5957ac526fc/src/geom.f90#L257, so we need to address this one way or the other.

I also asked here: https://fortran-lang.discourse.group/t/using-module-variables-as-dimensions-in-function-arguments/5742

### LINKED ISSUE #4129: bug: `asr_owner` is a `nullptr` when the current scope is of function type
This issue was found when investigating the cause of error in #4104 with the help of @certik.

```fortran
module test_module_dim
   implicit none
   integer :: nx = 4
contains

   subroutine f(x)
      integer, intent(in) :: x(nx)
      print *, x
   end subroutine

end module

program example
   use test_module_dim
   integer :: cs(6)
   cs = [1, 2, 3, 4, 5, 6]
   call f(cs)
end program
```

Executing the above code currently throws the error stated in #1642. We bypass it by constructing a working ASR, though not applicable for all programs, it enable us to construct a reliable ASR in this case. We can reproduce this bug by simply checking if the `asr_owner` of `current_scope` inside `process_dims()` function in `ast_common_visitor.h` is a `nullptr`.

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 1322248c2..8f0d292e3 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -1339,6 +1339,18 @@ public:
                 if (ASR::is_a<ASR::Var_t>(*end)) {
                     ASR::Var_t* end_var = ASR::down_cast<ASR::Var_t>(end);
                     ASR::symbol_t* end_sym = end_var->m_v;
+                    if (current_scope->asr_owner) {
+                        ASR::symbol_t* asr_owner_sym = ASR::down_cast<ASR::symbol_t>(current_scope->asr_owner);
+                        if (ASR::is_a<ASR::Function_t>(*asr_owner_sym)) {
+                            std::cout << "asr_owner is a function" << std::endl;
+                        }
+                        // force construction of an ASR
+                        end = get_transformed_function_call(end_sym);
+                    } else {
+                        std::cout << "asr_owner is nullptr" << std::endl;
+                        // force construction of an ASR
+                        end = get_transformed_function_call(end_sym);
+                    }
                     SymbolTable* symbol_scope = ASRUtils::symbol_parent_symtab(end_sym);
                     if (ASR::is_a<ASR::ExternalSymbol_t>(*end_sym) ||
                         (symbol_scope->counter != current_scope->counter && is_argument &&
```

When looking at the dimension of `x`, the current scope is a function, hence we check for it. The current output is:
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
asr_owner is nullptr
1 2 3 4 
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #4129. Fixes #1642.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
@kmr-srbh please checkout in this PR, and just list down all the issues that can be fixed with change in this PR. This will be real great help, there are bunch of issues linked to one another and it is really confusing.

**Comment by kmr-srbh** [comment]
> @kmr-srbh please checkout in this PR, and just list down all the issues that can be fixed with change in this PR. This will be real great help, there are bunch of issues linked to one another and it is really confusing.

I am checking it. :+1:

**Comment by kmr-srbh** [comment]
This implementation enables the code in #1642 to run, but the transformed code has the value of `nx` hardcoded.

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90 --show-fortran
module test_module_dim
implicit none
integer(4), save :: nx = 4

contains

subroutine f(x)
    integer(4), dimension(__lcompilers_get_nx()), intent(in) :: x
    interface
        pure integer(4) function __lcompilers_get_nx()
        end function __lcompilers_get_nx

    end interface
    print *, x
end subroutine f

end module test_module_dim

program example
use test_module_dim, only: f
use test_module_dim, only: nx
implicit none
integer(4), dimension(6) :: cs
cs = [1, 2, 3, 4, 5, 6]
call f(cs)

contains

pure integer(4) function __lcompilers_get_nx()
    integer(4), save :: nx = 4
    __lcompilers_get_nx = nx
end function __lcompilers_get_nx

end program example
```

Due to the above, the issue stated in #4125 occurs.

**Comment by kmr-srbh** [comment]
I don't think any other issue is related to the PR, is it?

**Comment by Pranavchiku** [comment]
Okay, my question is what is needed for SNAP? Do we need #4125?

**Comment by kmr-srbh** [comment]
I personally have not found instances of #4125 in SNAP till now, but #1642 is directly related.

**Review by certik — APPROVED** [review]
This looks good ot me.

**Pull request merged**
