### PR TITLE
CI: Building LFortran to WASM

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
towards https://github.com/lfortran/lcompilers_frontend/issues/3

### CODE REVIEW

**Review by certik — APPROVED** [review]
I think that this looks good. Details we can figure out as we go.

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval @certik. Please, could you possibly setup the required `SSH Keys`, please.

**Comment by Shaikh-Ubaid** [comment]
I am merging this as it seems to be approved.

**Comment by certik** [comment]
I setup the keys, let's test it out!

**Pull request merged**
