### PR TITLE
feat: add support for compile-time evaluation of logical arrays in `LogicalBinOp_t`

### LINKED ISSUE #4279: `x1 .neqv. .true.` throws compiler error
```fortran
program main
    logical, parameter :: x1(2) = [.true., .false.]
    print *, x1 .neqv. .true.
end program
```
```console
$ gfortran a.f90 && ./a.out
 F T
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);

...
 b.visit_TranslationUnit(ast);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 144, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4878, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4835, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4881, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4468, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1569, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 115, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4924, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4595, in ??
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3088, in LCompilers::LFortran::BodyVisitor::visit_Print(LCompilers::LFortran::AST::Print_t const&)
    visit_expr(*x.m_values[i]);
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4976, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_expr(LCompilers::LFortran::AST::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/harshita/Desktop/lfortran/src/lfortran/ast.h", line 4626, in ??
    case exprType::BoolOp: { v.visit_BoolOp((const BoolOp_t &)x); return; }
  File "/home/harshita/Desktop/lfortran/src/lfortran/semantics/ast_common_visitor.h", line 7461, in LCompilers::LFortran::CommonVisitor<LCompilers::LFortran::BodyVisitor>::visit_BoolOp(LCompilers::LFortran::AST::BoolOp_t const&)
    CommonVisitorMethods::visit_BoolOp(al, x, left, right, tmp, diag);
AssertFailed: ASR::is_a<ASR::Logical_t>(*dest_type)

```

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #4279 

```fortran
program main
   logical, parameter :: x1(2) = [.true., .false.]
   print *, x1 .neqv. .true.
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
 F T
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
False True
```

<br>

We throw an error for comparison of arrays with incompatible shapes.
```fortran
program main
   logical, parameter :: x1(3) = [.true., .false., .false.]
   print *, x1 .neqv. [.true., .true.]
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:3:11-21:

    3 |    print *, x1 .neqv. [.true., .true.]
      |           1         2
Error: Shapes for operands at (1) and (2) are not conformable
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
semantic error: Shapes for operands are not conformable
 --> ./examples/example.f90:3:13
  |
3 |    print *, x1 .neqv. [.true., .true.]
  |             ^^        ^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### CODE REVIEW

**Comment by kmr-srbh** [comment]
Pushing tests shortly.

**Comment by kmr-srbh** [comment]
Reversing the operands in the `LogicalBinOp_t` expression fails currently. So
```fortran
program main
   logical, parameter :: x1(2) = [.true., .false.]
   print *, x1 .neqv. .true.
end program
```
works, but
```fortran
program main
   logical, parameter :: x1(2) = [.true., .false.]
   print *, .true. .neqv. x1
end program
```
fails.

This occurs due to casting where the left type is not being casted to become an array. I am looking into it.

**Comment by certik** [comment]
Excellent, thanks for working on this. Once it is ready for review, click on "Ready for review".

**Comment by kmr-srbh** [comment]
This works now:
```fortran
program main
   logical, parameter :: x1(2) = [.true., .false.]
   print *, .true. .neqv. x1
end program main
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
False True 
```

**Comment by kmr-srbh** [comment]
This implementation is now ready.

**Comment by kmr-srbh** [comment]
The cause of CI failure is the test 'test_01_interface.f90' from #4220. It fails with the following error:
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
semantic error: Function 'test_01_interface' not found or not implemented yet (if it is intrinsic)
  --> ./examples/example.f90:38:16
   |
38 |         ret =  test_01_interface (len,arr)
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

@assem2002 could you please look into it?

**Comment by kmr-srbh** [comment]
I am unsure why the Windows CI fails. It is unrelated to the changes in this PR and had passed before I rebased the branch on top of latest main.

**Comment by certik** [comment]
It's failing with xonsh 0.17.0. The latest master was build with xonsh 0.16.0. We need to pin `xonsh==0.16.0`, probably everywhere for consistency.

**Review by certik — APPROVED** [review]

**Pull request merged**
