### PR TITLE
CI: Upload tarball

### PR DESCRIPTION
**Pull request by Smit-create**
cc @certik

### CODE REVIEW

**Comment by Smit-create** [comment]
@certik ,
I created and uploaded the tarball on my fork using this PR: https://github.com/Smit-create/lfortran/pull/5. The results are at: https://github.com/Smit-create/tarballs/tree/master/docs/testing. You will need to create the ssh-key pairs(I don't have that access), see  this docs: https://github.com/cpina/github-action-push-to-another-repository#setup-with-ssh-deploy-key. So the command will follow like this:
1. `ssh-keygen -t ed25519 -C "noreply@deploylfortran.com"`

Enter any file name say: `ci_generate`

Leave the paraphrase empty

2. Use base64 encoding using: `cat ci_generate | base64` and add the generated key to `lfortran/lfortran` Actions private key and name it as `SSH_DEPLOY_KEY`.

3. Add contents of `ci_generate.pub` in `lfortran/tarballs`. (See the doc link)

Once that is set, please let me know so that I can polish this PR and test it on our repo.

**Comment by certik** [comment]
Perfect, thanks for this. I'll do it soon.

**Comment by Smit-create** [comment]
@certik 
The tarball Job is ready. We can merge this and check if that creates a commit with a new folder from `main` branch.

**Comment by certik** [comment]
This looks good, thanks!

**Comment by Smit-create** [comment]
@certik Can you please rename master to main branch in tarballs repo too? It will fix the error.

**Comment by certik** [comment]
I would be careful with that --- I think it might break all links to older tarballs. I need to carefully check.

**Pull request merged**
