### PR TITLE
Minor fix to handle decimal formatting

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes https://github.com/lfortran/lfortran/issues/2861

### CODE REVIEW

**Comment by gptsarthak** [comment]
You correctly parsed it here! To complete the implemention, you can simply do this:
```diff
diff --git a/src/libasr/runtime/lfortran_intrinsics.c b/src/libasr/runtime/lfortran_intrinsics.c
index 4705d764e..490fbaabb 100644
--- a/src/libasr/runtime/lfortran_intrinsics.c
+++ b/src/libasr/runtime/lfortran_intrinsics.c
@@ -307,6 +307,12 @@ void handle_decimal(char* format, double val, int scale, char** result, char* c)
         i--;
     }
 
+    int exp = 2;
+    char* exp_loc = strchr(num_pos, 'e');
+    if (exp_loc != NULL) {
+        exp = atoi(++exp_loc);
+    }
+
     char* ptr = strchr(val_str, '.');
     if (ptr != NULL) {
         memmove(ptr, ptr + 1, strlen(ptr));

@@ -405,7 +411,7 @@ void handle_decimal(char* format, double val, int scale, char** result, char* c)
     if (atoi(num_pos) == 0) {
         sprintf(exponent, "%+02d", (integer_length > 0 && integer_part != 0 ? integer_length - scale : decimal));
     } else {
-        sprintf(exponent, "%+03d", (integer_length > 0 && integer_part != 0 ? integer_length - scale : decimal));
+        sprintf(exponent, "%+0*d", exp+1, (integer_length > 0 && integer_part != 0 ? integer_length - scale : decimal));
     }
 
     strcat(formatted_value, exponent);
```
Also, a minor fix for scaling: 
```diff
@@ -321,7 +327,7 @@ void handle_decimal(char* format, double val, int scale, char** result, char* c)
         memmove(val_str, val_str + 1, strlen(val_str));
         decimal--;
     }
-    if (format[1] == 'S') {
+    if (tolower(format[1]) == 's') {
         scale = 1;
         decimal--;
     }
```

**Comment by gptsarthak** [comment]
Also to implement `*`  in `*(1x,es15.8e2)`, which  I assume skips the newline and prints the rest of the the arguments space separated like a list, we can do this:

```diff
diff --git a/src/libasr/runtime/lfortran_intrinsics.c b/src/libasr/runtime/lfortran_intrinsics.c
index 3ad73c58f..4705d764e 100644
--- a/src/libasr/runtime/lfortran_intrinsics.c
+++ b/src/libasr/runtime/lfortran_intrinsics.c
@@ -444,6 +444,9 @@ char** parse_fortran_format(char* format, int *count, int *item_start) {
             case '/' :
                 format_values_2[format_values_count++] = substring(format, index, index+1);
                 break;
+            case '*' :
+                format_values_2[format_values_count++] = substring(format, index, index+1);
+                break;
             case '"' :
                 start = index++;
                 while (format[index] != '"') {
@@ -544,6 +547,7 @@ LFORTRAN_API char* _lcompilers_string_format_fortran(int count, const char* form
     char* result = (char*)malloc(sizeof(char));
     result[0] = '\0';
     int item_start = 0;
+    bool array = false;
     while (1) {
         int scale = 0;
         for (int i = item_start; i < format_values_count; i++) {
@@ -577,6 +581,8 @@ LFORTRAN_API char* _lcompilers_string_format_fortran(int count, const char* form
 
             if (value[0] == '/') {
                 result = append_to_string(result, "\n");
+            } else if (value[0] == '*') {
+                array = true;
             } else if (isdigit(value[0]) && tolower(value[1]) == 'p') {
                 // Scale Factor nP
                 scale = atoi(&value[0]);
@@ -642,7 +648,9 @@ LFORTRAN_API char* _lcompilers_string_format_fortran(int count, const char* form
 
         }
         if ( count > 0 ) {
-            result = append_to_string(result, "\n");
+            if (!array) {
+                result = append_to_string(result, "\n");
+            }
             item_start = item_start_idx;
         } else {
             break;
```

Let me know if it works

**Review by certik — APPROVED** [review]
I think that this is a good start, so I am going to merge it.

**Comment by certik** [comment]
@gptsarthak can you please submit a PR on top of the latest master, with your improvements?

**Comment by certik** [comment]
I opened up an issue to finish the implementation at: https://github.com/lfortran/lfortran/issues/2878.

**Pull request merged**
