### PR TITLE
Handle dim argument & array with rank 2 in Maxloc intrinsic

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
TODO:
- [ ] verify_args
- [ ] eval_Maxloc
- [ ] Pass tests in the CI
- [ ] Support 2D array
- [ ] Simplify
Arguments
- [ ] dim
- [ ] mask
- [ ] kind 
- [ ] back

**Comment by Thirumalai-Shaktivel** [comment]
This does seem to work! But, in some cases, reshape function returns wrong output!

**Comment by certik** [comment]
Great progress. If you need help, let me know.

**Comment by Thirumalai-Shaktivel** [comment]
I will implement `eval_maxloc` soon. After that, this PR is ready for review!

**Comment by Thirumalai-Shaktivel** [comment]
Ready for review!

**Review by czgdp1807 — CHANGES_REQUESTED** [review]
Instead of just extending to 2 rank, we should do it for any rank. Its simple to do, just increase the depth of the nested loop. I think we have the infrastructure for it already. See how we implement `sum` intrinsic, just change the function from `sum` to `maxloc`.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, it's the next step!
This is an optimized one. Here is the approach only for 2D array:
```py
_1d_array = reshape(arr, [_1d_array_size])
max_1d_index = maxloc(_1d_array)
2d_n_column = max_1d_i % arr_n_column
2d_n_row = max_1d_i / arr_n_column
```

**Comment by czgdp1807** [comment]
Actually, `reshape` deepcopies the array to a new one. I am not sure if that's a good idea for an optimal implementation.

**Comment by Thirumalai-Shaktivel** [comment]
I see, I didn't know this.
Cool, Let me try to implement `maxloc` the same as `sum` then.

**Comment by Thirumalai-Shaktivel** [comment]
Ready for review!
I will submit another PR for handling other dimensions.

**Review by czgdp1807 — COMMENTED** [review]
What about greater than 2 rank arrays? Are you doing some special handling for rank 2 arrays? If not then let's add test for rank 3 arrays as well.

**Comment by certik** [comment]
I think @Thirumalai-Shaktivel said:

>  I will submit another PR for handling other dimensions.

so he will submit another PR for higher than 2 dimensions. So rank 3 probably doesn't work?

Let's figure this out and let's keep things moving and merge, then we can send another PR.

**Comment by czgdp1807** [comment]
> so he will submit another PR for higher than 2 dimensions. So rank 3 probably doesn't work?

I think special case handling for 2 dimensions might not be needed unless there are some excellent optimisations done by it. So, let's merge this, add general implementation for any rank array and then benchmark the special case and general case for 2 dimensional arrays. If there is hardly any difference between the two then remove the special case.

**Review by czgdp1807 — APPROVED** [review]

**Comment by Thirumalai-Shaktivel** [comment]
I discussed your review: https://github.com/lfortran/lfortran/pull/2071#issuecomment-1659611438 with @certik in our meeting. And sir suggested we can keep the changes in this PR and optimize the `reshape` intrinsic later to benefit this approach. My apologies for not sharing this information with you and asked for a review again.

I needed this PR changes (with or without 2D implementation) to implement the approach suggested by you as this PR handles the return type in the `create_maxloc`.

**Pull request merged**
