### PR TITLE
feat: Implemented 'or' and 'xor' intrinsic functions

### PR DESCRIPTION
**Pull request by jinangshah21**
In continuation of #5059.

### CODE REVIEW

**Comment by jinangshah21** [comment]
In continuation of #5059.

**Review by certik — APPROVED** [review]
I think that this is fine.

**Comment by certik** [comment]
@gxyd go ahead and merge master into simplifier after each PR merge to main.

**Comment by gxyd** [comment]
> @gxyd go ahead and merge master into simplifier after each PR merge to main.

Done here: https://github.com/lfortran/lfortran/pull/5101

**Pull request merged**
