### PR TITLE
[STF] Fix some issues in ASR 

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
https://github.com/lfortran/lfortran/commit/1d1eaaca20426785d0126415a382cb1cbeddbd1d, https://github.com/lfortran/lfortran/commit/8369010066567d04ca89aeca860dc852e88e0ac7, https://github.com/lfortran/lfortran/commit/bd4f240db49d292a46c3c3f773c47821dffe6f42, https://github.com/lfortran/lfortran/commit/36ec2030027ec2d26591721d1fcbf359e6bf65a3, https://github.com/lfortran/lfortran/commit/a708951349ac6a31b33305b6a97a864c2e352a15, https://github.com/lfortran/lfortran/commit/8b34b51d444e88cb86092ea3406048a411e97af1, and https://github.com/lfortran/lfortran/commit/4a7e81e7a9a7ed37afc8eef91b3624690697c40e

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
This PR is ready for review.

**Review by certik — APPROVED** [review]
I think the changes are good, thanks @Thirumalai-Shaktivel !

**Comment by certik** [comment]
(just rebase it and you can merge)

**Comment by Thirumalai-Shaktivel** [comment]
Thanks for the review.

**Pull request merged**
