### PR TITLE
CI: Remove manual mangling fixes, uncomment all tests

### PR DESCRIPTION
**Pull request by Pranavchiku**
Last issue we have is: https://github.com/lfortran/lfortran/issues/2198

### CODE REVIEW

**Comment by Pranavchiku** [comment]
SciPy builds very well locally, on CI it got into some infinite loop at `test_nans_input`. I added verbose, let's check which test fails.

**Comment by Pranavchiku** [comment]
I am able to reproduce it locally.

**Comment by Pranavchiku** [comment]
I tried with GFortran, it also gives me the same error, steps to reproduce
```
git clone https://github.com/scipy/scipy
cd scipy
git checkout 41c61b2de9a2dbef6705f961fe6836f1b5916d31
mamba env create -f environment.yml --force

**Comment by Pranavchiku** [comment]
I opened an issue here: https://github.com/scipy/scipy/issues/19132

**Comment by certik** [comment]
@Pranavchiku we have to fix all dependencies. Currently SciPy env lists:
```
name: scipy-dev
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - compilers  # Currently unavailable for Windows. Comment out this line and download Rtools and add <path>\ucrt64\bin\ to your path: https://cran.r-project.org/bin/windows/Rtools/rtools40.html
  - meson
  - meson-python
  - ninja
  - numpy
  - openblas
  - pkg-config
  - libblas=*=*openblas  # helps avoid pulling in MKL
  - pybind11
  # scipy.datasets dependency
  - pooch
  # ---
  - pythran
  # For testing and benchmarking
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-timeout
  - asv<0.5
  # For type annotations
  - mypy
  - typing_extensions
  - types-psutil
  # For building docs
  - sphinx
  - numpydoc
  - ipython
  - setuptools<67.3  # avoid pkg_resources deprecation warnings from MPL/scikit-umfpack
  - matplotlib
  - pydata-sphinx-theme==0.9.0
  - sphinx-design
  - jupytext
  - myst-nb
  # Some optional test dependencies
  - mpmath
  - gmpy2
  - threadpoolctl
  # For CLI
  - rich-click
  - click
  - doit>=0.36.0
  - pydevtool
  # For linting
  - ruff
  - cython-lint
```
That's not how to do it. You have to fix all dependencies to be exactly the version that works. So let's update our scipy branch to list proper version for all scipy deps (I bet we don't need half of these anyway for our testing). Then this problem will be fixed.

**Comment by Pranavchiku** [comment]
Okay so, the CI gets halt somehow after `scipy/special/tests/test_nan_inputs.py::test_nan_inputs[eval_gegenbauer] PASSED [ 75%]`, locally it works well for me.

**Comment by Pranavchiku** [comment]
Responsible subroutine:
```fortran
        SUBROUTINE CHGM(A,B,X,HG)
C
C       ===================================================
C       Purpose: Compute confluent hypergeometric function
C                M(a,b,x)
C       Input  : a  --- Parameter
C                b  --- Parameter ( b <> 0,-1,-2,... )
C                x  --- Argument
C       Output:  HG --- M(a,b,x)
C       Routine called: CGAMA for computing complex ln[Г(x)]
C       ===================================================
C
```

**Comment by Pranavchiku** [comment]
I fixed it using https://github.com/certik/scipy/commit/13f9061e07fd0006a2af062941d70e4e71341fb5

**Comment by Pranavchiku** [comment]
I will fix https://github.com/lfortran/lfortran/pull/2243#issuecomment-1693566108 in a new PR.

**Review by certik — APPROVED** [review]
I think this looks great, it seems to work!

**Pull request merged**
