### PR TITLE
Template example with array

### PR DESCRIPTION
**Pull request by ansharlubis**
Made minor changes in handling types to support template with array.

### CODE REVIEW

**Comment by certik** [comment]
Same as with the other PR, if this runs, then I would just either only do integration test, or also the ASR test, but not AST test, unless you are testing some specific parsing or AST issue.

**Comment by ansharlubis** [comment]
> Same as with the other PR, if this runs, then I would just either only do integration test, or also the ASR test, but not AST test, unless you are testing some specific parsing or AST issue.

I've removed the AST tests for the new example here.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
The CI issue seems unrelated.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, I too had the same issue. Re-running the CI got it fixed.

**Pull request merged**
