### PR TITLE
feat: implement intrinsic logical

### PR DESCRIPTION
**Pull request by parth121101**
Towards: #492

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
I think `logical` should be implemented directly in AST->ASR (without involving intrinsic function registry) like we did for `complex()` here https://github.com/lfortran/lfortran/pull/3443. You can also go through the discussion in this thread https://github.com/lfortran/lfortran/pull/3443#discussion_r1495037303 on the same PR.

**Comment by Shaikh-Ubaid** [comment]
A minor concern is that either in the ASR or in the LLVM backend, I think we support logicals of kind `4` only. If logicals of other kinds work (as they seem to be as per the added test), then it is well and good for now. We can tackle later about extending logical kinds in ASR/LLVM (whichever does not support logicals of other than kind `4`).

**Comment by HarshitaKalani** [comment]
Yes, a similar discussion is done here too: https://github.com/lfortran/lfortran/pull/3691#issuecomment-2015247883
And the corresponding issue: https://github.com/lfortran/lfortran/issues/3690

**Comment by certik** [comment]
I recommend only allowing `logical(4)` as well, however there might be some Fortran codes out there that require `logical(8)`. If this works, then let it be for now, once we can compile all codes, we can redesign and possibly restrict to just `logical(4)`. I currently do not understand the requirements, but we will once we compile all codes.

Regarding how it is implemented: yes, it should be just an ASR node, but these need to also work with arrays, and just like for `real` and other such functions, we decided to use the intrinsic function mechanism for now.

@parth121101 can you add tests for arrays for all these `logical`, `real`, `integer` functions? 

Also, both compile time and runtime?

This can be done in subsequent PRs.

**Comment by parth121101** [comment]
@Shaikh-Ubaid I have incorporated the changes as suggested by you by implementing it in ast.

**Comment by HarshitaKalani** [comment]
I'm a little confused here. Since we have created a node for this intrinsic, it is no more elemental (will not work for arrays). 
Are we planning to add support for elemental intrinsics in the nodes? 
Or we did this since it is fine unless we need this intrinsic for arrays, and then when needed, we'll change the implementation. Is it so?

**Comment by parth121101** [comment]
> I'm a little confused here. Since we have created a node for this intrinsic, it is no more elemental (will not work for arrays). Are we planning to add support for elemental intrinsics in the nodes? Or we did this since it is fine unless we need this intrinsic for arrays, and then when needed, we'll change the implementation. Is it so?

Same concern with me. There were some intrinsic functions which were just mapped with existing functions and hence we didnt had elemental behaviour.

**Comment by certik** [comment]
There are many ways to design this. Currently all elemental behavior is implemented via a pass. To keep this pass simple, it just operates on elemental functions (not sure currently if it has any knowledge of elemental intrinsics, but it works with them). I think it does not have knowledge of other nodes and so they will not work for arrays. I recommend to keep it that way, since we already started with this approach. I don't know if it is the best approach, but I think it's good enough for beta. I think it's more important to be consistent.

So this logical should be added as an intrinsic function, and in the intrinsic function pass it should expand to call the logical ASR node. That way it will work with arrays. Just like we implemented `real`, `complex` and other such casts. After we reach beta, and we compile all codes and understand the usage well, we can try alternative designs as well. Right now I would not change the design.

**Comment by Shaikh-Ubaid** [comment]
>So this logical should be added as an intrinsic function, and in the intrinsic function pass it should expand to call the logical ASR node. That way it will work with arrays. Just like we implemented real, complex and other such casts.

I am slightly confused here. We implemented `complex()` directly in AST->ASR (as part of `intrinsics_present_in_ASR`) here https://github.com/lfortran/lfortran/pull/3443 (also see https://github.com/lfortran/lfortran/pull/3443#discussion_r1495037303). I do not think there is any intrinsic function pass involved for `complex()`. 

This PR currently implements `logical()` along the lines of `complex()`.

@certik what do you suggest:
- should we keep the currently implemented approach where `logical()` is a part of `intrinsics_present_in_ASR`?
- or should we implement `logical()` as an intrinsic function in the intrinsic function registry?

**Comment by certik** [comment]
Does "complex" work with arrays? If so, we can use that approach. If not, we should not.

**Comment by Shaikh-Ubaid** [comment]
>Does "complex" work with arrays? If so, we can use that approach. If not, we should not.

@parth121101 can you test this and proceed accordingly?

**Comment by parth121101** [comment]
> Does "complex" work with arrays? If so, we can use that approach. If not, we should not.

I went through the documentation of Complex intrinsic. I found that this function is not an elemental function while logical is an intrinsic elemental function.

Complex intrinsic: https://gcc.gnu.org/onlinedocs/gcc-3.4.6/g77/Complex-Intrinsic.html
Logical intrinsic: https://gcc.gnu.org/onlinedocs/gcc-4.7.4/gfortran/LOGICAL.html

Hence we should not provide array support for `Complex` function while we need it for `Logical`. 

```
cat a.f90 
program main
    logical :: a = .true.
    logical :: b = .false.
    print *, logical([.true., .false.], 4)
end program      
                                                                                                                                                   
gfortran a.f90 && ./a.out
 T F
```

```
cat a.f90                
program main
    print *, complex([1.0, 2.0], [3.0, 4.0])
end program         
                                                                                                                                                  
gfortran a.f90 && ./a.out
a.f90:2:21:

    2 |     print *, complex([1.0, 2.0], [3.0, 4.0])
      |                     1
Error: 'x' argument of 'complex' intrinsic at (1) must be a scalar
```

@certik I think the initial approach was correct wherein this function was implemented as an intrinsic function in the intrinsic function registry.
Can you please let me know how should I move further?

**Comment by certik** [comment]
I would implement it using the original approach, where it was added into our intrinsic elemental functions. Let's get it done that way, and we can refactor after we reach beta if needed.

**Review by certik — APPROVED** [review]
I think this is fine, thanks.

**Pull request merged**
