### PR TITLE
Refactor test suite: add `-b | --backend` option to specify backend (fix #756)

### LINKED ISSUE #756: Tests: only run explicitly specified tests
Currently, the tester does a fuzzy matching which might include unintended tests when using the `-t` option. We should strictly follow what is defined in `tests.toml`.

### PR DESCRIPTION
**Pull request by lucifer1004**
@certik Please review.

### CODE REVIEW

**Comment by certik** [comment]
Thanks, I'll test this tomorrow.

**Comment by lucifer1004** [comment]
Further improve the test suite to support

- multiple `-t` and `-b` options
- regex in `-t` options

So we can write

```sh
./run_tests.py -t "ar+ay" "sub*" -b julia cpp --sequential
```

And get

```
 START TEST:  subroutine1.f90
subroutine1.f90 * julia ✓ 
 START TEST:  subroutine2.f90
subroutine2.f90 * julia ✓ 
 START TEST:  subroutine3.f90
subroutine3.f90 * julia ✓ 
 START TEST:  subroutine3b.f90
subroutine3b.f90 * julia ✓ 
 START TEST:  subroutine4.f90
subroutine4.f90 * cpp ✓ 
subroutine4.f90 * julia ✓ 
 START TEST:  subroutine5.f90
subroutine5.f90 * cpp ✓ 
subroutine5.f90 * julia ✓ 
 START TEST:  subroutine6.f90
subroutine6.f90 * cpp ✓ 
subroutine6.f90 * julia ✓ 
 START TEST:  subroutine7.f90
subroutine7.f90 * julia ✓ 
 START TEST:  array1.f90
array1.f90 * cpp ✓ 
array1.f90 * julia ✓ 
 START TEST:  array2.f90
array2.f90 * cpp ✓ 
array2.f90 * julia ✓ 
 START TEST:  array3.f90
array3.f90 * cpp ✓ 
array3.f90 * julia ✓ 
TESTS PASSED
```

**Comment by lucifer1004** [comment]
I am also considering options to exclude specified backends, as a generalization of the current `--no-llvm` option.

**Comment by lucifer1004** [comment]
`--exclude-test` and `--exclude-backend` have been added.

**Review by konradha — APPROVED** [review]
That's a great addition, thanks. Would you mind making a pass with `autopep8 --aggressive --in-place src/libasr/compiler_tester/tester.py` ?

**Comment by lucifer1004** [comment]
Formatted.

**Review by certik — APPROVED** [review]
I tested it, it seems to work. If there are any bugs we discover later, we can fix it later.

Thanks!

**Pull request merged**
