### PR TITLE
Create ExternalSymbol for the FunctionCall

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Consider an example:
```fortran
module x
use, intrinsic :: iso_fortran_env, only : warn=>OUTPUT_UNIT
implicit none
contains
    function print_dictionary(header,stop) result(stop)
    character(len=*), intent(in), optional :: header
    logical, intent(in), optional          :: stop
    character(len=:),allocatable,save      :: keywords(:)
        write('(a,1x,a,1x,a,1x,a)') atleast('KEYWORD', 8), &             ! <--------------
            & 'SHORT', 'PRESENT', 'VALUE'
    end function print_dictionary

    function atleast(line,length,pattern) result(strout)
    character(len=*),intent(in)                :: line
    integer,intent(in)                         :: length
    character(len=*),intent(in),optional       :: pattern
    character(len=len(trim(line))) :: strout
    end function atleast
end module
```
Here I get the ASR verify error:
```py
ASR verify pass error: ASR verify: FunctionCall::m_name `len_trim` cannot point outside of its symbol table
 --> examples/expr2.f90:1:1
  |
1 | module expr2
  | ^ failed here
```
I think the error is caused by this:
https://github.com/lfortran/lfortran/blob/d2f947eed49002391830291420be48bcb74c767b/src/runtime/pure/lfortran_intrinsic_string.f90#L21-L23
After debugging I came across this:
```fortran
atleast:
    (Function
        (SymbolTable
            6
            {
                ...
            })
        atleast
        [len
        len_trim
        trim]
        ...
    ),
print_dictionary:
    (Function
        (SymbolTable
            5
            {
                header:
                    (Variable
                        5
                        header
                        []
                        In
                        ()
                        ()
                        Default
                        (Character 1 -1 () [])
                        Source
                        Public
                        Optional
                        .false.
                    ),
                keywords:
                    (Variable
                        5
                        keywords
                        []
                        Local
                        ()
                        ()
                        Save
                        (Character 1 -2 () [(()
                        ())])
                        Source
                        Public
                        Required
                        .false.
                    ),
                len:
                    (ExternalSymbol
                        5
                        len
                        8 len
                        lfortran_intrinsic_builtin
                        []
                        len
                        Private
                    ),
                stop:
                    (Variable
                        5
                        stop
                        []
                        ReturnVar
                        ()
                        ()
                        Default
                        (Logical 4 [])
                        Source
                        Public
                        Optional
                        .false.
                    ),
                trim:
                    (ExternalSymbol
                        5
                        trim
                        32 trim
                        lfortran_intrinsic_string
                        []
                        trim
                        Private
                    )

            })
        print_dictionary
        [atleast
        len
        trim]
        [(Var 5 header)
        (Var 5 stop)]
        [(FileWrite
            0
            (StringConstant
                "(a,1x,a,1x,a,1x,a)"
                (Character 1 18 () [])
            )
            ()
            ()
            ()
            ()
            [(FunctionCall
                2 atleast
                ()
                [((StringConstant
                    "KEYWORD"
                    (Character 1 7 () [])
                ))
                ((IntegerConstant 8 (Integer 4 [])))]
                (Character 1 -3 (FunctionCall
                    5 len
                    ()
                    [((FunctionCall
                        5 trim
                        ()
                        [((StringConstant
                            "KEYWORD"
                            (Character 1 7 () [])
                        ))]
                        (Character 1 -3 (FunctionCall
                            6 len_trim                             <---------------------- (1)
                            ()
                            [((Var 6 line))]
                            (Integer 4 [])
                            ()
                            ()
                        ) [])
                        ()
                        ()
                    ))]
                    (Integer 4 [])
                    ()
                    ()
                ) [])
                ()
                ()
            )
            (StringConstant
                "SHORT"
                (Character 1 5 () [])
            )
            (StringConstant
                "PRESENT"
                (Character 1 7 () [])
            )
            (StringConstant
                "VALUE"
                (Character 1 5 () [])
            )]
            ()
            ()
        )]
        (Var 5 stop)
        Source
        Public
        Implementation
        ()
        .false.
        .false.
        .false.
        .false.
        .false.
        []
        []
        .false.
    ),
```
From (1), we can see it points to the function called symbolTable. So the error.
I made some changes to modify the ASR. But still the issue persist.
Here is the current ASR output after compiling this PR changes:
```fortran
...
[(FunctionCall
    2 atleast
    ()
    [((StringConstant
        "KEYWORD"
        (Character 1 7 () [])
    ))
    ((IntegerConstant 8 (Integer 4 [])))]
    (Character 1 -3 (FunctionCall
        5 len
        ()
        [((FunctionCall
            5 trim
            ()
            [((StringConstant
                "KEYWORD"
                (Character 1 7 () [])
            ))]
            (Character 1 -3 (FunctionCall
                5 len_trim                          <--------
                ()
                [((Var 6 line))]
                (Integer 4 [])
                ()
                ()
            ) [])
            ()
            ()
        ))]
        (Integer 4 [])
        ()
        ()
    ) [])
    ()
    ()
)
...
```
@czgdp1807 @Smit-create any suggestions on fixing this issue?

**Comment by certik** [comment]
Let's create a minimal reproducible example. I think it is probably something like this:

Inside this function:
```fortran
    function f(line) result(r)
    character(len=*),intent(in) :: line
    character(len=len(trim(line))) :: r
    end function
```
The `len` attribute depends on the argument `line`. This is all properly stored in ASR (or should be) of this function.

Then when we call it, say:
```fortran
print *, f("abc")
```
We need to create such `FunctionCall` node that does not access any internal variables (such as `line`) from the function `f`. To do that, we declare the type of the first argument using only variables/entities in the current scope. So the first argument would be something like `StringConstant("abc", (Character len=len(trim("abc")))`.

**Comment by certik** [comment]
This substitution I think is done with this pass: https://github.com/lfortran/lfortran/blob/d2f947eed49002391830291420be48bcb74c767b/src/libasr/asr_utils.h#L1880

**Comment by Thirumalai-Shaktivel** [comment]
Now, this changes alters the return_type in function.
I don't know why this is happening? return_type of funcCall and return_type of function has some attachments
If we modify this, it alters there as well.
```clojure
...
[(FunctionCall
    2 f_2
    ()
    [((StringConstant
        "Calling f_2"
        (Character 1 11 () [])
    ))]
    (Character 1 -3 (FunctionCall
        3 len
        ()
        [((FunctionCall
            3 trim
            ()
            [((StringConstant
                "Calling f_2"
                (Character 1 11 () [])
            ))]
            (Character 1 -3 (FunctionCall
                3 len_trim									<------------------------
                ()
                [((StringConstant
                    "Calling f_2"
                    (Character 1 11 () [])
                ))]
                (Integer 4 [])
                ()
                ()
            ) [])
            ()
            ()
        ))]
        (Integer 4 [])
        ()
        ()
    ) [])
    ()
    ()
)]
...
(Character 1 -3 (FunctionCall
    4 len
    ()
    [((FunctionCall
        4 trim
        ()
        [((Var 4 line))]
        (Character 1 -3 (FunctionCall
            3 len_trim                                       <------------------------
            ()
            [((StringConstant
                "Calling f_2"
                (Character 1 11 () [])
            ))]
            (Integer 4 [])
            ()
            ()
        ) [])
        ()
        ()
    ))]
    (Integer 4 [])
    ()
    ()
)
...
```

**Comment by Thirumalai-Shaktivel** [comment]
Closing this PR in favor of https://github.com/lfortran/lfortran/pull/1147

**Pull request closed without merging**
