### PR TITLE
Implement double precision return value

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Ondrej, I created new test for double precision but it shows me the following error
```
(lf) C:\Users\lenovo\lfortran\integration_tests>..\inst\bin\lfortran functions_11.f90
semantic error: Return type not supported
  --> functions_11.f90:19:5 - 24:6
   |
19 |        double precision function f(a) result(b)
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
24 |
   | ...^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by certik** [comment]
I see where the problem is. You have to enable `--fixed-form`.

I think you might have discovered a problem in our free-form parser as well, which should be fixed separately.

**Comment by Pranavchiku** [comment]
is there any way to enable ```--fixed-form``` ?

**Comment by certik** [comment]
Yes, one way is to write the file with the `.f` extension, the `./run_tests.py` will enable the `--fixed-form` for it automatically.

**Comment by certik** [comment]
I see, in #151 you did it as an integration test ---- leave that one in there, I'll have a look, I think we need such a test and a fix. Maybe that is all we need.

**Comment by Pranavchiku** [comment]
> Yes, one way is to write the file with the `.f` extension, the `./run_tests.py` will enable the `--fixed-form` for it automatically.

okay so, do I need to update anything?
like I actually not got what you are trying to say...  as `./run_tests.py` don't workout for windows because of that `diff.exe`

**Comment by certik** [comment]
No, I think the fix in #151 is correct.

**Comment by certik** [comment]
This is already in master.

**Pull request closed without merging**
