### PR TITLE
[CMake] Save the mod files in the include_dirs (-I option) path

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
Fixes: https://github.com/lfortran/lfortran/issues/3047

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
This approach doesn't require copying the mod files but saves the mod files in both src and target directories.

**Comment by certik** [comment]
I don't like saving it twice, that seems wasteful. GFortran only saves it once.

Let's figure out what cmake option we need to obey and do that instead.

**Comment by Thirumalai-Shaktivel** [comment]
It seems the issue is within the CMake files. Adding VERBOSE=1 prints
```
cd /Users/thirumalai/Open_Source/stdlib/src && /Users/thirumalai/bin/lfortran  -I/Users/thirumalai/Open_Source/stdlib/src/mod_files  -c /Users/thirumalai/Open_Source/stdlib/src/stdlib_kinds.f90 -o CMakeFiles/fortran_stdlib.dir/stdlib_kinds.f90.o
```
Here is -J is not specified, this might be the reason for the failure.

**Comment by certik** [comment]
Something differs with gfortran (and other compilers I am guessing), we just need to figure out what it is.

**Comment by Thirumalai-Shaktivel** [comment]
Fixed here: https://github.com/lfortran/lfortran/pull/3387

**Pull request closed without merging**
