### PR TITLE
[LLVM] Fix opaque pointers for LLVM 17

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**
Towards: https://github.com/lfortran/lfortran/issues/4210

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
There seems to be a lot of work.
Currently, I get a seg fault for the examples/expr2.f90. I will try to fix tomorrow.

**Comment by certik** [comment]
Thanks for implementing this approach. Does it seem to work on simple examples at least?

If so, we can pass through `builder` as you did, and merge. Then implement the dict, merge. Etc. to keep the PRs small.

If it doesn't work, then maybe this approach can't work. I am hoping it works at least sometimes.

**Comment by Thirumalai-Shaktivel** [comment]
What needs to stored in the map? 
With this PR changes I store llvm::CreateAlloca and llvm::CreateLoad as llvm::Value, and later retrieve the llvm::Type from the map. I only checked for Allocatables. I will check for other cases and report back.

**Comment by certik** [comment]
> What needs to stored in the map? With this PR changes I store llvm::CreateAlloca and llvm::CreateLoad as llvm::Value, and later retrieve the llvm::Type from the map. I only checked for Allocatables. I will check for other cases and report back.

Yes, something like this. Does it work? Or is there a fundamental issue why this cannot work, such as if LLVM somehow changed the pointer value, so we can't look it up later from the dict.

**Comment by Thirumalai-Shaktivel** [comment]
It seems to work till now.

**Comment by Thirumalai-Shaktivel** [comment]
I'm splitting this PR into multiple PR's. CreateAlloca, CreateLoad, ...

**Comment by certik** [comment]
If this approach works, then let's get some smaller PRs to merge, that would be awesome.

**Comment by certik** [comment]
I think so. Let me know if you have any doubts.

**Pull request merged**
