### PR TITLE
Fix data attr initialization

### PR DESCRIPTION
**Pull request by Smit-create**
https://gitlab.com/lfortran/lfortran/-/issues/769

### CODE REVIEW

**Comment by certik** [comment]
This is precisely the kind of work that is needed, thank you for doing that.

**Comment by Smit-create** [comment]
In this PR, I'm trying to generate ASR for `scipy/stats/statlib/swilk.f`

**Comment by certik** [comment]
Awesome. Send smaller PRs that we can merge, each fixing some small thing. Then we just quickly merge it and we can use the fix.

**Comment by Smit-create** [comment]
On this PR, I get the following error after the above 4 fixes:
```
semantic error: Function 'dexp' not found or not implemented yet (if it is intrinsic)
   --> scipy/stats/statlib/swilk.f:253:17
    |
253 |       ZEXP(Z) = DEXP(Z)
    |                 ^^^^^^^ 

```
I suppose that it is already implemented in `lfortran/src/runtime/impure/lfortran_intrinsic_math.f90` then it should find `dexp` right?

**Comment by certik** [comment]
The `dexp` is not hooked into the AST->ASR, only `exp`, the modern Fortran version. In F77, you could access the individual functions as `sexp` and `dexp`. So we need to expose them.

**Comment by Smit-create** [comment]
After two minor changes in the file, I was able to generate the ASR. 
```diff
diff --git a/scipy/stats/statlib/swilk.f b/scipy/stats/statlib/swilk.f
index 3f926b4f3..49fc86611 100644
--- a/scipy/stats/statlib/swilk.f
+++ b/scipy/stats/statlib/swilk.f
@@ -250,7 +250,7 @@ CCCCC DATA LTONE, UTZERO /7.0D0, 18.66D0/
      $   5.29330324926D0,   4.8385912808D0,  15.1508972451D0,
      $  0.742380924027D0,   30.789933034D0,  3.99019417011D0/
 C
-      ZEXP(Z) = DEXP(Z)
+      ZEXP(Z) = EXP(Z)
 C
       UP = UPPER
       Z = X
@@ -320,7 +320,7 @@ C
 1     R = P
       IF (Q .GT. ZERO)R = ONE - P
       IF (R .LE. ZERO) GOTO 2
-      R = SQRT(-ALOG(R))
+      R = SQRT(-LOG(R))
```

Basically, the only issue now left is to expose the intrinsic functions: `DEXP` and `ALOG` to successfully generate ASR for this file.

**Comment by certik** [comment]
Perfect! Can you now please send small PRs of out this one, with tests?

I also made progress on other files.

**Comment by Smit-create** [comment]
The CI has started to fail because of this:
```
CMake Error at /usr/local/Cellar/cmake/3.24.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.24.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:[59](https://github.com/lfortran/lfortran/runs/7817365703?check_suite_focus=true#step:6:60)4 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.24.0/share/cmake/Modules/FindZLIB.cmake:150 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindStaticZLIB.cmake:7 (find_package)
  CMakeLists.txt:113 (find_package)
```

**Comment by Smit-create** [comment]
> Perfect! Can you now please send small PRs of out this one, with tests?
> 
> I also made progress on other files.

Yeah, will do them

**Comment by Smit-create** [comment]
Closing this since all the commits are in main now.

**Pull request closed without merging**
