### PR TITLE
[LLVM] Sprint for compiling STF

### PR DESCRIPTION
**Pull request by czgdp1807**
@Thirumalai-Shaktivel @Smit-create Please carry out the sprint for ASR to LLVM backend here. **Please follow the guidelines below so that is easy to add fixes here to `main` branch**,

1. Make sure that each commit of yours is as isolated to a single fix as possible. Also, please add test for each fix.
2. Do not change the git history of this PR. Do not rebase on top of `main`.

Commits to be added in `main` branch,

- [x] e99ba4b3aa0de47169f3783979fee317ff827efb - https://github.com/lfortran/lfortran/pull/1660 
- [x] 7d5d6284fcc5ead5e7fd3515212b5b053130baaf - https://github.com/lfortran/lfortran/pull/1660
- [x] df864a6b1fc00b7a07506636e655c3b8653ab1da - https://github.com/lfortran/lfortran/pull/1660
- [x] 4e1e7591cf50c181468fa180c3f5f422f652dcaa - https://github.com/lfortran/lfortran/pull/1661
- [x] 2dc1ef5931226f9ce90260d411972d89ad362715 - https://github.com/lfortran/lfortran/pull/1662
- [x] 4dc0c5253142c93455236a3577b7ec8e5ded57f8 - Partially in https://github.com/lfortran/lfortran/pull/1663, https://github.com/lfortran/lfortran/pull/1936
- [x] 8e872c86787f19f37468b856ac8679137c04bdd0 - https://github.com/lfortran/lfortran/pull/1659
- [x] 62772aeca53b0783d957805cb9eff177ae4114ac - https://github.com/lfortran/lfortran/pull/1659
- [x] 04e62d8790be3ef5a4cea746bfd0edf68295de9a - https://github.com/lfortran/lfortran/pull/1659
- [x] e5af76236b485b77d9e7c8b9a9bdb012f4cf3ae6 - https://github.com/lfortran/lfortran/pull/1702
- [x] cb7fa3f8cdc2b95378068f3f528ed5cf0aa9b020 - https://github.com/lfortran/lfortran/pull/1704
- [x] 9bcc9f26e143b92608f9f044de64434b723ce75c - https://github.com/lfortran/lfortran/pull/1704
- [x] 6736d16d476651a997dfc37575a0470b98144593 - https://github.com/lfortran/lfortran/pull/1699
- [x] f411c43acbf79f03c3058e7bc1acc7134cba3062 - https://github.com/lfortran/lfortran/pull/1699
- [x] 1e65a01f327cf5fb1240e777be0c01ceb9e07a7d - https://github.com/lfortran/lfortran/pull/1699
- [x] 0954cde0ca6d19cc62230495ea4311f5943f393f - https://github.com/lfortran/lfortran/pull/1664
- [x] 4e2bbb87c84e2e6035e9c4518e7f19fd2fadb8d6 - https://github.com/lfortran/lfortran/pull/1666
- [x] dafb585ef7648ab85dbc45754b10fca7278cafe7 - https://github.com/lfortran/lfortran/pull/1666
- [x] b3d97ce95d78a25d33c7c6e6dfe5945b96fc29d7 - https://github.com/lfortran/lfortran/pull/1826
- [x] 4711107dae148f53457ed189e8d4bb41e7a3f29d - https://github.com/lfortran/lfortran/pull/1721
- [x] 03bf99a3ca0243bd864a30765c77152b8e4f7e95 - https://github.com/lfortran/lfortran/pull/1722
- [x] 808e5d6bd940cf270643dfb50aa4ab579756822c - https://github.com/lfortran/lfortran/pull/1721
- [x] 01cc2e6a793aa8d8131e2ba440500238cab4ecdc - https://github.com/lfortran/lfortran/pull/1818
- [x] 716930f62865d93eaff6248d5031a8261a82476d - Partially in https://github.com/lfortran/lfortran/pull/1660, https://github.com/lfortran/lfortran/pull/1667
- [x] dc420ff3d712e4157b461b93338903452f1cf7b6 - https://github.com/lfortran/lfortran/pull/1667

Commits for allocatables,

- [x] 5bbeff9ca315f94080eb17e772ebf68df3fb6df2 - https://github.com/lfortran/lfortran/pull/1810
- [x] 8657f94a4aa96eca36a791307bf1c3c0c1c7fa37 - https://github.com/lfortran/lfortran/pull/1810
- [x] 0a1f69295ca2e403043cbc0fbd342eef4edf61cb - https://github.com/lfortran/lfortran/pull/1810
- [x] e853404cb08a709a50c192452b91cfd62fa1bc5b - https://github.com/lfortran/lfortran/pull/1810
- [x] 8efea0d5494c57109c6b0534ca1c58a780c6add3 - https://github.com/lfortran/lfortran/pull/1810
- [ ] 60bd50218f8e7c84eaac0dae2d2b947c829bbd74 - @czgdp1807 
- [x] 04a164aa1cbbd900d68c7aa7ec96deb077366458 - https://github.com/lfortran/lfortran/pull/1810
- [x] 24535bd2a85299c929df6cfe693c67c48bd01d58 - https://github.com/lfortran/lfortran/pull/1810
- [x] 9e3b9b69b1be04a589b8ba732c07939137245230 - https://github.com/lfortran/lfortran/pull/1810
- [x] 042d790ab758795ff39faaa6a3277c666baae66b - https://github.com/lfortran/lfortran/pull/1810

```zsh
(lf) 20:43:00:~/lfortran_project/fpm % FPM_FC=lfortran fpm build --flag="--cpp --verbose"
.
.
.
fpm.f90                                done.
install.f90                            done.
libfpm.a                               done.
main.f90                               compiling...
[ 97%] Compiling...sh: line 1: 22840 Abort trap: 6           lfortran -c app/main.f90 --cpp --verbose -J build/lfortran_06A05C8A5EFFBA56 -Ibuild/lfortran_06A05C8A5EFFBA56 -o build/lfortran_06A05C8A5EFFBA56/fpm/app_main.f90.o > build/lfortramain.f90                               failed.
[ 98%] Compiling...
ASR Pass starts: 'nested_vars'
ASR Pass ends: 'nested_vars'
ASR Pass starts: 'global_stmts'
ASR Pass ends: 'global_stmts'
ASR Pass starts: 'init_expr'
ASR Pass ends: 'init_expr'
ASR Pass starts: 'class_constructor'
ASR Pass ends: 'class_constructor'
ASR Pass starts: 'implied_do_loops'
ASR Pass ends: 'implied_do_loops'
ASR Pass starts: 'pass_list_expr'
ASR Pass ends: 'pass_list_expr'
ASR Pass starts: 'arr_slice'
ASR Pass ends: 'arr_slice'
ASR Pass starts: 'subroutine_from_function'
ASR Pass ends: 'subroutine_from_function'
ASR Pass starts: 'array_op'
ASR Pass ends: 'array_op'
ASR Pass starts: 'intrinsic_function'
ASR Pass ends: 'intrinsic_function'
ASR Pass starts: 'array_op'
ASR Pass ends: 'array_op'
ASR Pass starts: 'pass_array_by_data'
ASR Pass ends: 'pass_array_by_data'
ASR Pass starts: 'print_arr'
ASR Pass ends: 'print_arr'
ASR Pass starts: 'print_list_tuple'
ASR Pass ends: 'print_list_tuple'
ASR Pass starts: 'array_dim_intrinsics_update'
ASR Pass ends: 'array_dim_intrinsics_update'
ASR Pass starts: 'do_loops'
ASR Pass ends: 'do_loops'
ASR Pass starts: 'forall'
ASR Pass ends: 'forall'
ASR Pass starts: 'select_case'
ASR Pass ends: 'select_case'
ASR Pass starts: 'inline_function_calls'
ASR Pass ends: 'inline_function_calls'
ASR Pass starts: 'unused_functions'
ASR Pass ends: 'unused_functions'
ASR Pass starts: 'transform_optional_argument_functions'
ASR Pass ends: 'transform_optional_argument_functions'
Module.begin: __lcompilers_created__nested_context__build_target_list_
Module.end: __lcompilers_created__nested_context__build_target_list_
Module.begin: __lcompilers_created__nested_context__check_commandline_
Module.end: __lcompilers_created__nested_context__check_commandline_
Module.begin: __lcompilers_created__nested_context__cmd_args_to_dictionary_
Module.end: __lcompilers_created__nested_context__cmd_args_to_dictionary_
Module.begin: __lcompilers_created__nested_context__cmd_new_
Module.end: __lcompilers_created__nested_context__cmd_new_
Module.begin: __lcompilers_created__nested_context__cmd_run_
Module.end: __lcompilers_created__nested_context__cmd_run_
Module.begin: __lcompilers_created__nested_context__get_command_line_settings_
Module.end: __lcompilers_created__nested_context__get_command_line_settings_
Module.begin: __lcompilers_created__nested_context__get_prototype_
Module.end: __lcompilers_created__nested_context__get_prototype_
Module.begin: __lcompilers_created__nested_context__msg_one_
Module.end: __lcompilers_created__nested_context__msg_one_
Module.begin: __lcompilers_created__nested_context__msg_scalar_
Module.end: __lcompilers_created__nested_context__msg_scalar_
Module.begin: __lcompilers_created__nested_context__prune_build_targets_
Module.end: __lcompilers_created__nested_context__prune_build_targets_
Module.begin: lfortran_intrinsic_builtin
Module.end: lfortran_intrinsic_builtin
Module.begin: lfortran_intrinsic_iso_fortran_env
Module.end: lfortran_intrinsic_iso_fortran_env
Module.begin: lfortran_intrinsic_bit
Module.end: lfortran_intrinsic_bit
Module.begin: lfortran_intrinsic_string
Module.end: lfortran_intrinsic_string
Module.begin: lfortran_intrinsic_math3
Module.end: lfortran_intrinsic_math3
Module.begin: lfortran_intrinsic_math2
Module.end: lfortran_intrinsic_math2
Module.begin: lfortran_intrinsic_iso_c_binding
Module.end: lfortran_intrinsic_iso_c_binding
Module.begin: fpm_strings
Module.end: fpm_strings
Module.begin: fpm_error
Module.end: fpm_error
Module.begin: fpm_environment
Module.end: fpm_environment
Module.begin: lfortran_intrinsic_iso_c_binding
Module.end: lfortran_intrinsic_iso_c_binding
Module.begin: fpm_filesystem
Assertion failed: (Ty && "Invalid GetElementPtrInst indices for type!"), function checkGEPType, file Instructions.h, line 897.
Traceback (most recent call last):
  File "/Users/czgdp1807/lfortran_project/lfortran/src/bin/lfortran.cpp", line 1902
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/czgdp1807/lfortran_project/lfortran/src/bin/lfortran.cpp", line 856
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp", line 342
    compiler_options, run_fn, infile);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 8211
    v.visit_asr((ASR::asr_t&)asr);
  File "../libasr/asr.h", line 4544
  File "../libasr/asr.h", line 4520
  File "../libasr/asr.h", line 4545
  File "../libasr/asr.h", line 4276
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1400
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4547
  File "../libasr/asr.h", line 4284
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2757
    finish_module_init_function_prototype(x);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4282
    visit_Function(*s);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3919
    visit_procedures(x);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4233
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4562
  File "../libasr/asr.h", line 4334
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5350
    }, [=]() {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 346
    start_new_block(loopbody); {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5352
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4562
  File "../libasr/asr.h", line 4318
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5319
    }, [=]() {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 303
    builder->SetInsertPoint(thenBB); {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5317
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4562
  File "../libasr/asr.h", line 4318
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5319
    }, [=]() {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 308
    start_new_block(elseBB); {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5321
    this->visit_stmt(*x.m_orelse[i]);
  File "../libasr/asr.h", line 4562
  File "../libasr/asr.h", line 4318
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5319
    }, [=]() {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 303
    builder->SetInsertPoint(thenBB); {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5317
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4562
  File "../libasr/asr.h", line 4318
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5319
    }, [=]() {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 303
    builder->SetInsertPoint(thenBB); {
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 5317
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4562
  File "../libasr/asr.h", line 4306
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4821
    value = LLVM::CreateLoad(*builder, llvm_utils->create_gep(value, 0));
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_utils.cpp", line 121
    return LLVM::CreateGEP(*builder, ds, idx_vec);
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/codegen/llvm_utils.cpp", line 27
    return builder.CreateGEP(t2, x, idx);
  File "/Users/czgdp1807/mambaforge/envs/lf/include/llvm/IR/IRBuilder.h", line 1773
    return Insert(GetElementPtrInst::Create(Ty, Ptr, IdxList), Name);
  File "/Users/czgdp1807/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 943
    NameStr, InsertBefore);
  File "/Users/czgdp1807/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1151
    }
  File "/Users/czgdp1807/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1143
    : Instruction(getGEPReturnType(PointeeType, Ptr, IdxList), GetElementPtr,
  File "/Users/czgdp1807/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 1074
    Type *PtrTy = PointerType::get(checkGEPType(getIndexedType(ElTy, IdxList)),
  File "/Users/czgdp1807/mambaforge/envs/lf/include/llvm/IR/Instructions.h", line 897
    assert(Ty && "Invalid GetElementPtrInst indices for type!");
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18030ce43
  Binary file "/usr/lib/system/libsystem_c.dylib", local address: 0x18030dae7
  Binary file "/usr/lib/system/libsystem_pthread.dylib", local address: 0x1803ffc27
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x18042ea83
Abort: Signal SIGABRT (abort) received

<ERROR> Compilation failed for object " app_main.f90.o "
<ERROR>stopping due to failed compilation
STOP 1
```

### CODE REVIEW

**Comment by czgdp1807** [comment]
@Smit-create Please continue the sprint tomorrow.

**Comment by czgdp1807** [comment]
@Smit-create Please continue the sprint for Friday and Saturday. Note the, `allocatable_character_type` for allocatable strings.

**Comment by czgdp1807** [comment]
I am concluding this sprint here. We are able to compile the following FPM modules to LLVM successfully (see `Module.begin` and `Module.end` in the logs present in the description of this PR).

1. fpm_strings
2. fpm_error
3. fpm_environment

The compilation fails at `fpm_filesystem`. This is good progress. Now before moving on to the next sprint I would like to deal with the following issues,

1. Making `allocatable` part of the ASR ttype (I faced a lot of bugs in this sprint due to this.)
2. Using `Array` ASR ttype for arrays and removing `dimension` from `Integer`, `Real`, etc.
3. Making `any` work with `mask` generated from string comparison. See `replace` function in `integration_tests/modules_48.f90` (present in this PR). 

I will add the list of commits in the description of this PR tomorrow.

cc: @certik @Smit-create @Thirumalai-Shaktivel

**Comment by certik** [comment]
After implementing 1., 2., 3., let's also sync ASR with LPython. After that we can also slowly start making progress on "physical types" (say as the array descriptor) step by step.

**Comment by czgdp1807** [comment]
Closing in favour of #1975

**Pull request closed without merging**
