### PR TITLE
chore: untrack `.vscode/launch.json`

### PR DESCRIPTION
**Pull request by kmr-srbh**

### CODE REVIEW

**Comment by kmr-srbh** [comment]
I think we should not track the editor files with git. When using the debugger with changes to `launch.json`, I always had to worry about not pushing it with the commit. Now we can freely use a debugger according to our needs.

**Comment by gxyd** [comment]
I did highlight a possibility of similar concern here: https://github.com/lfortran/lfortran/pull/4913#pullrequestreview-2335708410, when we commited this change to our repo.

> When using the debugger with changes to launch.json, I always had to worry about not pushing it with the commit.

Do you often use `git add .`? Because, I personally never have had any problem with it's presence.

**Comment by kmr-srbh** [comment]
> Do you often use git add .? Because, I personally never have had any problem with it's presence.

Yes, when committing test references, I stage all of them at once. I have never accidentally committed changes to `launch.json`, but it adds some friction. The real problem occurs when rebasing branches, when I have to undo the changes and make them again.

**Comment by certik** [comment]
I would keep it in the repos, since this makes debugging work. Without it I always struggle how to set it up.

What modifications do you need to do in this file?

When creating commits, if I have dirty changes, I use `git add -p` to only select changes that I want.

**Comment by kmr-srbh** [comment]
> What modifications do you need to do in this file?

I modify the `args` field and sometimes use `gdb` instead of `lldb`.

If we need this file, we may surely keep it.

**Comment by gxyd** [comment]
> I modify the args field and sometimes use gdb instead of lldb.

That I often do as well, the modification of the filename to debug.

**Comment by certik** [comment]
I think you can add a section specifically for `gdb`, then you can select it from VSCode.

Regarding the binary to debug and command line arguments (if any), maybe there is some way to do this without modifying the file. I usually modify it for that, as I don't know any other way.

**Comment by kmr-srbh** [comment]
Closing this PR as it is not required. I will open a new PR for adding `gdb` as a debugger.

**Pull request closed without merging**
