### PR TITLE
TESTS: Remove `NO_EXPERIMENTAL_SIMPLIFIER` flag from working tests

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by czgdp1807** [comment]
I don't know what's wrong here. With `arrays_33` and LLVM 19 things work fine on my Linux machine. Here its failing.

**Comment by czgdp1807** [comment]
Fixed the bug. :-)

**Comment by czgdp1807** [comment]
Like this, the last few bugs will be debugged directly on CI if they cannot be reproduced locally. Will try to run the CI minimally. We should have `[skip ci]` functionality enabled so that we can skip running CI for draft PRs. Also, we can do `[skip job_name]` to skip jobs which we don't want to run. This is there in SciPy. We can have it here as well. Not urgent but a suggestion.

**Comment by Thirumalai-Shaktivel** [comment]
Yes, this feature is very much required.

**Comment by czgdp1807** [comment]
Yes. Something like, `[skip llvm19] [skip llvm10] .. ` in the commit message. So that we can debug on our own. In fact, in SciPy we can run CI on our own fork. I am not sure if we can do that in LFortran. If not then that should be supported as well.

**Comment by certik** [comment]
You can modify the CI.yml to adjust it as needed for debugging.

**Comment by czgdp1807** [comment]
Yes. That works too and is quick. Will do it for now.

**Pull request merged**
