### PR TITLE
ci: remove dim in `sum` intrinsic in stdlib to make `real` work

### PR DESCRIPTION
**Pull request by HarshitaKalani**
Towards: https://github.com/lfortran/lfortran/pull/4063, #4017

### CODE REVIEW

**Comment by HarshitaKalani** [comment]
https://github.com/czgdp1807/stdlib/commits/lf20

**Comment by Pranavchiku** [comment]
`sum(x, dim)` was previously working and with this PR it breaks, right?

**Comment by HarshitaKalani** [comment]
Right, with the new implementation of `real` #4063, it fails.

**Comment by HarshitaKalani** [comment]
I've opened #4409 for that.

**Comment by HarshitaKalani** [comment]
I think the workaround done with this is not really correct. Let me look for some other change that might just work.

**Comment by HarshitaKalani** [comment]
This is now ready for a review.

**Comment by certik** [comment]
Before we merge this PR, can you put it into #4063 and see that everything works? If so, we can then decide if to merge this or not.

**Comment by HarshitaKalani** [comment]
With the workaround, https://github.com/lfortran/lfortran/pull/4063 works.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
Ok.

**Review by Pranavchiku — APPROVED** [review]
I think we can merge this.

**Pull request merged**
