### PR TITLE
enh: support allocatable arrays in array reference

### LINKED ISSUE #5688: (PRIMA) Handle allocatable array in ArrayReference
MRE : 
```fortran
program test
   integer :: X(3,3) = reshape([1,2,3,4,5,6,7,8,9], [3,3])
   integer, allocatable :: Y(:)
   allocate(Y(size(X,1)))
   print *, X(Y,:)
end program
```

LFortran Error : 
```console
lfortran: /home/jinu2110/conda_root/envs/lf/include/llvm/IR/IRBuilder.h:1989: llvm::Value* llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, const llvm::Twine&): Assertion `V->getType()->isIntOrIntVectorTy() && DestTy->isIntOrIntVectorTy() && "Can only sign extend/truncate integers!"' failed.
Traceback (most recent call last):
  Binary file "/mnt/c/lfortran/src/bin/lfortran", in _start
  File "/build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c", line 308, in __libc_start_main
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2732, in main
    return main_app(argc, argv);
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 2670, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
  File "/mnt/c/lfortran/src/bin/lfortran.cpp", line 1049, in (anonymous namespace)::compile_src_to_object_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/mnt/c/lfortran/src/lfortran/fortran_evaluator.cpp", line 382, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10412, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    v.visit_asr((ASR::asr_t&)asr);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 316, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_asr(LCompilers::ASR::asr_t const&)
    void visit_asr(const asr_t &b) { visit_asr_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 292, in void LCompilers::ASR::visit_asr_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::asr_t const&, LCompilers::ASRToLLVMVisitor&)
    case asrType::unit: { v.visit_unit((const unit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 317, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_unit(LCompilers::ASR::unit_t const&)
    void visit_unit(const unit_t &b) { visit_unit_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 22, in void LCompilers::ASR::visit_unit_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::unit_t const&, LCompilers::ASRToLLVMVisitor&)
    case unitType::TranslationUnit: { v.visit_TranslationUnit((const TranslationUnit_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 988, in LCompilers::ASRToLLVMVisitor::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    visit_symbol(*item.second);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 319, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 30, in void LCompilers::ASR::visit_symbol_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::symbol_t const&, LCompilers::ASRToLLVMVisitor&)
    case symbolType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3292, in LCompilers::ASRToLLVMVisitor::visit_Program(LCompilers::ASR::Program_t const&)
    this->visit_stmt(*x.m_body[i]);
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 336, in LCompilers::ASR::BaseVisitor<LCompilers::ASRToLLVMVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/mnt/c/lfortran/src/libasr/../libasr/asr_base_visitor.h", line 57, in void LCompilers::ASR::visit_stmt_t<LCompilers::ASRToLLVMVisitor>(LCompilers::ASR::stmt_t const&, LCompilers::ASRToLLVMVisitor&)
    case stmtType::Associate: { v.visit_Associate((const Associate_t &)x); return; }
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4673, in LCompilers::ASRToLLVMVisitor::visit_Associate(LCompilers::ASR::Associate_t const&)
    handle_array_section_association_to_pointer(x);
  File "/mnt/c/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4660, in LCompilers::ASRToLLVMVisitor::handle_array_section_association_to_pointer(LCompilers::ASR::Associate_t const&)
    arr_descr->fill_descriptor_for_array_section_data_only(value_desc, value_el_type, target,
  File "/mnt/c/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 521, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::fill_descriptor_for_array_section_data_only(llvm::Value*, llvm::Type*, llvm::Value*, llvm::Value**, llvm::Value**, llvm::Value**, llvm::Value**, llvm::Value**, int, int)
    llvm::Value* target_offset = cmo_convertor_single_element_data_only(
  File "/mnt/c/lfortran/src/libasr/codegen/llvm_array_utils.cpp", line 642, in LCompilers::LLVMArrUtils::SimpleCMODescriptor::cmo_convertor_single_element_data_only(llvm::Value**, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&, int, bool, bool)
    curr_llvm_idx = builder->CreateSExtOrTrunc(curr_llvm_idx, llvm::Type::getInt32Ty(context));
  File "/home/jinu2110/conda_root/envs/lf/include/llvm/IR/IRBuilder.h", line 1989, in llvm::IRBuilderBase::CreateSExtOrTrunc(llvm::Value*, llvm::Type*, llvm::Twine const&)
    assert(V->getType()->isIntOrIntVectorTy() &&
  File "/build/glibc-LcI20x/glibc-2.31/assert/assert.c", line 101, in __assert_fail
  File "/build/glibc-LcI20x/glibc-2.31/assert/assert.c", line 92, in __assert_fail_base
  File "/build/glibc-LcI20x/glibc-2.31/stdlib/abort.c", line 79, in abort
  File "/build/glibc-LcI20x/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h", line 86, in raise
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in <invalid>
Abort: Signal SIGABRT (abort) received
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #5688

### CODE REVIEW

**Comment by Pranavchiku** [comment]
This is weird, example works perfect for me locally, not sure why `macos-latest` fails:

```console
make[2]: *** [CMakeFiles/arrays_63.dir/arrays_63.f90.o] Segmentation fault: 11
```

**Comment by jinangshah21** [comment]
With Changes of your PR my Output is : 
```console
(lf) jinu2110@JNSLAP:/mnt/c/lfortran$ lfortran c.f90 --skip-pass=print_arr
1    2    3    4    5    6    7    8    9
```
It is not giving any error.

**Comment by assem2002** [comment]
The issue is specific to release mode. so either dependency on lcompilers_assert or some real serious issue with the applied optimization.

**Comment by assem2002** [comment]
I hope this change is the main issue, it works on my machine btw.

**Comment by Pranavchiku** [comment]
Awesome, seems like CI is working! Thank you very much for completing this PR!

**Review by certik — APPROVED** [review]

**Pull request merged**
