### PR TITLE
do tests still pass?

### PR DESCRIPTION
**Pull request by gxyd**
I'm trying to better understand "array_op" pass, and trying to see what's the use of code added in https://github.com/lfortran/lfortran/pull/2604.

### CODE REVIEW

**Comment by gxyd** [comment]
I went back in history and noticed, that the commented out block of code was needed earlier, but since then there has been a bit of reorganization of code, and hence that block of code is never executed.

**Comment by Pranavchiku** [comment]
We now have `random_number` implemented as `IntrinsicImpureSubroutine`, hence no need for that code.

**Comment by certik** [comment]
@Pranavchiku can the code be removed now? If so, let's create a clean PR.

**Comment by gxyd** [comment]
I actually didn't intend to remove the code completely, as intend to fix #3730 , which might be able to reuse the code for all the elemental subroutines. I only intended to check initially if tests pass without it or not.

**Comment by gxyd** [comment]
I'll close the PR in favor of #3767

**Pull request closed without merging**
