### PR TITLE
Add Initial support for IntrinsicFunction in C & CPP

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Review by certik — APPROVED** [review]
This looks good and clean.

**Comment by Thirumalai-Shaktivel** [comment]
Don't we run `integration_tests` for `CPP` in the CI?

**Comment by certik** [comment]
If we don't run it, then we should. Maybe we didn't enable it when moving to GitHub.

**Review by czgdp1807 — COMMENTED** [review]
Please apply the same changes in ``libasr`` of LPython and test them there as well.

**Review by certik — APPROVED** [review]

**Pull request merged**
