### PR TITLE
Make `dflt_access = Public` after `visit_Module`

### LINKED ISSUE #1249: Bug in private
```fortran
module foo1
private
end module

module foo2
real :: y = 2
end module

program test
use foo2
print *, y
end program
```
This gives:
```console
 $ lfortran y.f90
semantic error: Variable 'y' is not declared
  --> y.f90:11:10
   |
11 | print *, y
   |          ^ 'y' is undeclared
```
And the reason is that the first "private" sets the private visitor flag, but then it does not get reset in the module "foo2", so "y" ends up being private and does not (correctly) get imported by `use foo2`.

The fix is to reset the private flag to be the default public for the module foo2, and this example should compile and run.

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #1249.
I looked at other references, those changes look good to me.

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
cc: @certik

**Review by czgdp1807 — CHANGES_REQUESTED** [review]

**Review by certik — APPROVED** [review]
Otherwise I think this is good to merge.

**Comment by Pranavchiku** [comment]
I tried to follow steps at https://github.com/lcompilers/lpython/blob/8fa533a43860f43ce10e6dee238147fad57ac205/doc/src/rebasing.md and did some refactoring of git history. I hope I did not make it worse.

**Comment by certik** [comment]
This looks good now, thanks!

**Pull request merged**
