### PR TITLE
Fix: Support for function variable pointer 

### LINKED ISSUE #5741: bug: codegen error thrown for procedure declared with `ExternalSymbol`
### Minimal Reproducible Example

```fortran
module main_module

contains

   subroutine sub(int)
      integer,intent(in) :: int
      print *, int
      if (int /= 6) error stop
   end subroutine sub

end module main_module


program main

   use main_module

   procedure(sub), pointer :: p_sub
   p_sub => sub
   call p_sub(6)

end program main
```

### Output

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ conda activate lf_release
(lf_release) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
6
(lf_release) saurabh-kumar@Awadh:~/Projects/System/lfortran$ conda deactivate
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
code generation error: Subroutine code not generated for 'sub'


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
This had worked before, as seen above by the `lfortran 0.42.0` release version output.

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #5741

### CODE REVIEW

**Comment by jinangshah21** [comment]
It is failing for WASM. I don't exactly know what is issue.

**Comment by certik** [comment]
You can disable WASM for this test.

**Review by certik — APPROVED** [review]

**Review by HarshitaKalani — APPROVED** [review]
Looks good.

**Review by Pranavchiku — APPROVED** [review]
Thank you! This is good.

**Pull request merged**
