### PR TITLE
Add 64 bit integer support for `huge` function

### PR DESCRIPTION
**Pull request by zoziha**
Add ~~8, 16,~~ 64 bit integer ~~(`i8, i16, i64`)~~ support for `huge` function.

image

### CODE REVIEW

**Comment by czgdp1807** [comment]
This looks good to me. Can you add some tests for the same in https://github.com/lfortran/lfortran/tree/main/integration_tests folder?

**Comment by certik** [comment]
Thanks for this!

Not sure how the failures are caused by this PR, but we need to figure out how to fix them.

**Comment by zoziha** [comment]
> This looks good to me. Can you add some tests for the same in https://github.com/lfortran/lfortran/tree/main/integration_tests folder?

Thanks for your review, @czgdp1807 .

The `huge` function already has a test ([intrinsics_23.f90](https://github.com/lfortran/lfortran/blob/f07bc66f885d4bc365be140b23a2b62f7e205d85/integration_tests/intrinsics_23.f90#L1)) for single-precision integers, and when I add double-precision integer test code, `LFortran` returns me this error:
```fortran
program intrinsics_23
implicit none
integer(kind=4), parameter :: i32 = huge(0)
integer(kind=8), parameter :: i64 = huge(0_8)
real(kind=4), parameter :: y = huge(0.0)
real(kind=8), parameter :: z = huge(0.0d0)

print *, i32, i64, y, z
print *, huge(0), huge(0_8), huge(0.0), huge(0.0d0)

end program
```

```sh
semantic error: Only int32 kind is supported
 --> tests/../integration_tests/intrinsics_23.f90:4:37
  |
4 | integer(kind=8), parameter :: i64 = huge(0_8)
  |                                     ^^^^^^^^^ 
```
This should be related to that part of the code ([comptime_eval.h](https://github.com/lfortran/lfortran/blob/main/src/lfortran/semantics/comptime_eval.h#L1061)).

Currently, test in `integration_tests/intrinsics_23.f90` has not been added to the `toml` table of `run_tests.py`([tests/tests.toml](https://github.com/lfortran/lfortran/blob/f07bc66f885d4bc365be140b23a2b62f7e205d85/tests/tests.toml#L1486))

**Comment by czgdp1807** [comment]
> This should be related to that part of the code ([comptime_eval.h](https://github.com/lfortran/lfortran/blob/main/src/lfortran/semantics/comptime_eval.h#L1061)).

I think you need to update the `huge` interface,

https://github.com/lfortran/lfortran/blob/f07bc66f885d4bc365be140b23a2b62f7e205d85/src/runtime/pure/lfortran_intrinsic_math2.f90#L47-L49

Add, `i8huge`, `i16huge`, `i64huge` in the list.

**Comment by zoziha** [comment]
Thanks to @czgdp1807 and @certik for the review!

Since I don't know enough about LFortran, it seems that LFortran's support for `int8` and `int16` integers is not yet complete? And I don't have the ability to handle `int8` and `int16` support for `huge` function.

> Add, i8huge, i16huge, i64huge in the list.

At present, the introduction of `i8huge` and `i16huge` will cause the following error:

```sh
...
code generation error: asr_to_llvm: module failed verification. Error:
Instruction does not dominate all uses!
  %4 = sub i16 0, %3
  store i16 %4, i16* %r, align 2
Instruction does not dominate all uses!
  %4 = sub i8 0, %3
  store i8 %4, i8* %r, align 1
...
```

**Review by czgdp1807 — COMMENTED** [review]
I will shepherd this PR this week.

**Comment by certik** [comment]
I merged in the latest main and resolved conflicts. It looks like everything is passing for me. Once tests pass it think we can merge this. 

Thank you so much @zoziha for this PR and my apologize for getting to it so late, I've been very busy the past month, but I am now getting on top of all the PRs again. :)

**Comment by certik** [comment]
I squashed the commits, so that we don't have merge from main in history.

Thanks @zoziha!

**Pull request merged**
