### PR TITLE
Implement ``ArrayBroadcast`` for ``Assignment`` statement

### PR DESCRIPTION
**Pull request by czgdp1807**
I will complete it for assignments first and then for BinOp nodes.

https://github.com/lfortran/lfortran/issues/2503

### CODE REVIEW

**Comment by czgdp1807** [comment]
@certik I implemented ``ArrayBroadcast`` for ``Assignment`` statement in this PR. I would recommend to merge it and you then can follow my pattern and implement ``ArrayBroadcast`` for ``BinOp`` nodes. If you get stuck then I will do it tomorrow.

**Comment by certik** [comment]
Awesome, great job! I will take it from here. Thank you so much for this excellent work.

**Comment by czgdp1807** [comment]
Okay. So I am putting it on auto merge.

**Comment by czgdp1807** [comment]
Ideally for `BinOp` the following needs to be done,

1. Call `ASRUtils::make_ArrayBroadcast_t_util` before creation of `BinOp` nodes. See my way of calling it before creation of `Assignment` statements.
2. Pass all the LLVM based test. Also, `array_op`, `implied_do_loops` pass may give problems. For that the ideal approach is to just by pass `ArrayBroadcast` and consider only the `ArrayBroadcast::m_array` (i.e., the thing which is getting broadcasted). See how I made updates here for `Assignment` statement. This might be tricky to do.

**Comment by Pranavchiku** [comment]
> This might be tricky to do.

Yes, for now we can move by considering `ArrayBroadcast::m_array` but, this may result in removal of an assignment node as in https://github.com/lfortran/lfortran/issues/2349.

**Comment by certik** [comment]
We can later probably simplify `ArrayBroadcast`: https://github.com/lfortran/lfortran/issues/2509.

**Pull request merged**
