### PR TITLE
ASR: Sync Libasr from LPython

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by certik** [comment]
Thanks @Shaikh-Ubaid! I only noticed one commented out test, otherwise this looks good I think.

**Comment by czgdp1807** [comment]
I will complete it tomorrow.

**Comment by czgdp1807** [comment]
See https://github.com/lcompilers/lpython/pull/1658#issuecomment-1493219835 as well.

**Comment by czgdp1807** [comment]
This needs to wait for #1480 and https://github.com/lcompilers/lpython/pull/1616

**Comment by certik** [comment]
#1480 is in, so now we need to finish https://github.com/lcompilers/lpython/pull/1616, then we can sync.

**Comment by Shaikh-Ubaid** [comment]
Closing as completed in https://github.com/lfortran/lfortran/pull/1501.

**Pull request closed without merging**
