### PR TITLE
Class procedure support for template, without refactor

### PR DESCRIPTION
**Pull request by ansharlubis**
Work supporting the example described in #2265.

### CODE REVIEW

**Comment by ansharlubis** [comment]
@certik I separated the refactorization to a different PR.

**Review by certik — APPROVED** [review]
I think this looks great, thanks!

**Comment by certik** [comment]
Can you register the template_vector in CMake? It now works, right?

**Comment by ansharlubis** [comment]
@certik I added a gfortran test to CMakeList for template vector.

**Comment by ansharlubis** [comment]
@certik Added it but without the method call.

**Review by certik — APPROVED** [review]
Look great, thanks!

**Pull request merged**
