### PR TITLE
Extend Location manger to handle multi-file import errors

### PR DESCRIPTION
**Pull request by czgdp1807**
Co-authored-by: Thirumalai Shaktivel <74826228+Thirumalai-Shaktivel@users.noreply.github.com>

Corresponding LPython PR - https://github.com/lcompilers/lpython/pull/1297

I get several build errors due to `processor.re` (see below),

```bash
[ 66%] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/cwrapper.cpp.o
[ 67%] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/ast_serialization.cpp.o
[ 68%] Building CXX object src/lfortran/CMakeFiles/lfortran_lib.dir/__/bin/tpl/whereami/whereami.cpp.o
preprocessor.re:147:8: error: no member named 'out_start0' in 'LFortran::LocationManager'
    lm.out_start0.push_back(output_len);
    ~~ ^
preprocessor.re:148:8: error: no member named 'in_start0' in 'LFortran::LocationManager'
    lm.in_start0.push_back(input_len);
    ~~ ^
preprocessor.re:149:8: error: no member named 'in_size0' in 'LFortran::LocationManager'
    lm.in_size0.push_back(input_interval_len);
    ~~ ^
preprocessor.re:150:8: error: no member named 'interval_type0' in 'LFortran::LocationManager'
    lm.interval_type0.push_back(interval_type);
    ~~ ^
preprocessor.re:155:47: error: no member named 'out_start0' in 'LFortran::LocationManager'
    size_t input_interval_len = output_len-lm.out_start0[lm.out_start0.size()-1];
                                           ~~ ^
preprocessor.re:155:61: error: no member named 'out_start0' in 'LFortran::LocationManager'
    size_t input_interval_len = output_len-lm.out_start0[lm.out_start0.size()-1];
                                                         ~~ ^
preprocessor.re:176:8: error: no member named 'preprocessor' in 'LFortran::LocationManager'
    lm.preprocessor = true;
    ~~ ^
preprocessor.re:177:28: error: no member named 'in_newlines0' in 'LFortran::LocationManager'
    get_newlines(input, lm.in_newlines0);
                        ~~ ^
preprocessor.re:178:8: error: no member named 'out_start0' in 'LFortran::LocationManager'
    lm.out_start0.push_back(0);
    ~~ ^
preprocessor.re:179:8: error: no member named 'in_start0' in 'LFortran::LocationManager'
    lm.in_start0.push_back(0);
    ~~ ^
preprocessor.re:182:57: error: no member named 'in_filename' in 'LFortran::LocationManager'
    macro_definitions["__FILE__"].expansion = "\"" + lm.in_filename + "\"";
                                                     ~~ ^
preprocessor.re:405:36: error: no member named 'current_line' in 'LFortran::LocationManager'
                            if (lm.current_line == 0) {
                                ~~ ^
preprocessor.re:408:65: error: too few arguments to function call, expected 4, have 3
                                lm.pos_to_linecol(pos, line, col);
                                ~~~~~~~~~~~~~~~~~               ^
/Users/czgdp1807/lfortran_project/lfortran/src/libasr/location.h:167:10: note: 'pos_to_linecol' declared here
    void pos_to_linecol(uint32_t position, uint32_t &line, uint32_t &col,
         ^
preprocessor.re:410:43: error: no member named 'current_line' in 'LFortran::LocationManager'
                                line = lm.current_line;
                                       ~~ ^
preprocessor.re:427:57: error: too few arguments to function call, expected 4, have 3
                        lm.pos_to_linecol(pos, line, col);
                        ~~~~~~~~~~~~~~~~~               ^
/Users/czgdp1807/lfortran_project/lfortran/src/libasr/location.h:167:10: note: 'pos_to_linecol' declared here
    void pos_to_linecol(uint32_t position, uint32_t &line, uint32_t &col,
         ^
preprocessor.re:428:32: error: no member named 'current_line' in 'LFortran::LocationManager'
                        lm_tmp.current_line = line;
                        ~~~~~~ ^
preprocessor.re:354:43: error: no member named 'in_filename' in 'LFortran::LocationManager'
                std::string base_dir = lm.in_filename;
                                       ~~ ^
preprocessor.re:460:8: error: no member named 'out_start0' in 'LFortran::LocationManager'
    lm.out_start0.push_back(output.size());
    ~~ ^
preprocessor.re:461:8: error: no member named 'in_start0' in 'LFortran::LocationManager'
    lm.in_start0.push_back(input.size());
    ~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/lfortran/CMakeFiles/lfortran_lib.dir/build.make:76: src/lfortran/CMakeFiles/lfortran_lib.dir/parser/preprocessor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:258:16: error: no member named 'out_start' in 'LFortran::LocationManager'
            lm.out_start.push_back(out.size());
            ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:259:16: error: no member named 'in_start' in 'LFortran::LocationManager'
            lm.in_start.push_back(pos);
            ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:301:12: error: no member named 'in_filename' in 'LFortran::LocationManager'
    lm_tmp.in_filename = include_filename;
    ~~~~~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:308:8: error: no member named 'out_start' in 'LFortran::LocationManager'
    lm.out_start.push_back(out.size());
    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:309:8: error: no member named 'in_start' in 'LFortran::LocationManager'
    lm.in_start.push_back(pos);
    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:333:31: error: no member named 'in_newlines' in 'LFortran::LocationManager'
        lm.get_newlines(s, lm.in_newlines);
                           ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:334:12: error: no member named 'out_start' in 'LFortran::LocationManager'
        lm.out_start.push_back(0);
        ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:335:12: error: no member named 'in_start' in 'LFortran::LocationManager'
        lm.in_start.push_back(0);
        ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:364:24: error: no member named 'out_start' in 'LFortran::LocationManager'
                    lm.out_start.push_back(out.size());
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:365:24: error: no member named 'in_start' in 'LFortran::LocationManager'
                    lm.in_start.push_back(pos);
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:371:24: error: no member named 'out_start' in 'LFortran::LocationManager'
                    lm.out_start.push_back(out.size());
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:372:24: error: no member named 'in_start' in 'LFortran::LocationManager'
                    lm.in_start.push_back(pos);
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:379:24: error: no member named 'out_start' in 'LFortran::LocationManager'
                    lm.out_start.push_back(out.size());
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:380:24: error: no member named 'in_start' in 'LFortran::LocationManager'
                    lm.in_start.push_back(pos);
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:388:24: error: no member named 'out_start' in 'LFortran::LocationManager'
                    lm.out_start.push_back(out.size());
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:389:24: error: no member named 'in_start' in 'LFortran::LocationManager'
                    lm.in_start.push_back(pos);
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:397:24: error: no member named 'out_start' in 'LFortran::LocationManager'
                    lm.out_start.push_back(out.size());
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:398:24: error: no member named 'in_start' in 'LFortran::LocationManager'
                    lm.in_start.push_back(pos);
                    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/parser/parser.cpp:406:24: error: no member named 'out_start' in 'LFortran::LocationManager'
                    lm.out_start.push_back(out.size());
                    ~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/lfortran/CMakeFiles/lfortran_lib.dir/build.make:118: src/lfortran/CMakeFiles/lfortran_lib.dir/parser/parser.cpp.o] Error 1
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp:54:8: error: no member named 'in_filename' in 'LFortran::LocationManager'
    lm.in_filename = "input";
    ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp:103:39: error: no member named 'in_filename' in 'LFortran::LocationManager'
        pass_manager, diagnostics, lm.in_filename);
                                   ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp:189:28: error: no member named 'in_filename' in 'LFortran::LocationManager'
            parent_path(lm.in_filename));
                        ~~ ^
/Users/czgdp1807/lfortran_project/lfortran/src/lfortran/fortran_evaluator.cpp:288:100: error: no member named 'in_filename' in 'LFortran::LocationManager'
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager, diagnostics, lm.in_filename);
                                                                                                ~~ ^
4 errors generated.
make[2]: *** [src/lfortran/CMakeFiles/lfortran_lib.dir/build.make:188: src/lfortran/CMakeFiles/lfortran_lib.dir/fortran_evaluator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: src/lfortran/CMakeFiles/lfortran_lib.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

cc: @Thirumalai-Shaktivel

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
This fixes the build. I will complete the rest tomorrow.

**Comment by certik** [comment]
Very good. @Thirumalai-Shaktivel if you get stuck, please let me know, I can help. This was a long standing big missing feature, thank you so much for fixing this so quickly.

Once this is merged in both LPython and LFortran, I'll test it very carefully and report all bugs.

**Comment by Thirumalai-Shaktivel** [comment]
Can anyone please help me to resolve the failure in Jupyter?
I don't know where to start or look for.

**Comment by Thirumalai-Shaktivel** [comment]
I think, I fixed the issue.

**Comment by Thirumalai-Shaktivel** [comment]
Also, the tests here builts very faster than LPython. We should do the same in LPython as well.

**Comment by certik** [comment]
Here we test it by having multiple modules in different files, and compile them into mod files, then use them in the main program and add some error messages. 

This might require some more work, so we can do that later. I'll test this by hand later today and I suggest we merge, and then iterate.

Roughly speaking:

* When serializing the mod file, does all location information only point to that file? (All other files are always referenced via ExternalSymbol?) If so, then when saving, we can reset all location information to start from 0.
* When loading, we shift the location information to start at the end of the stack.
* I think we might need to save the filename of the source file into the mod file, so that when we deserialize it, we can add the filename to the LocationManager.

**Comment by Thirumalai-Shaktivel** [comment]
> When serializing the mod file, does all location information only point to that file? 

Yup, apart from `lfortran.cpp`, we don't use FileLocations anywhere.

> - When loading, we shift the location information to start at the end of the stack.
- I think we might need to save the filename of the source file into the mod file, so that when we deserialize it, we can add the filename to the LocationManager.

+1. Yup, this makes sense

**Comment by certik** [comment]
I reviewed and this looks good. We can now iterate upon it.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks for the approval...

**Pull request merged**
