### PR TITLE
Add intrinsic float/dble conversion

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
In this PR, I'm trying to generate ASR for `scipy/stats/statlib/spearman.f`. After the fixes in this diff, only one fix remains for this:
```
semantic error: Function 'alnorm' not found or not implemented yet (if it is intrinsic)
  --> scipy/stats/statlib/spearman.f:75:33
   |
75 |       prho = u / exp(y / two) + alnorm(x, .true.)
   |                                 ^^^^^^^^^^^^^^^^^ 
```

The file has a comment:
`c     Auxiliary function required: ALNORM = algorithm AS66`

So I am not sure if `ALNORM` is intrinsic or not. Once removing this function from the file, it successfully generates ASR and LLVM code.

**Review by certik — APPROVED** [review]
I think this is great, thank you so much for fixing it!

**Comment by Smit-create** [comment]
@certik How should we handle this: https://github.com/lfortran/lfortran/pull/154#issuecomment-1214289747?

**Comment by certik** [comment]
For how to fix `alnorm`, see #607.

**Pull request merged**
