### PR TITLE
[test] Use `re.search` instead of `re.match` in tests

### PR DESCRIPTION
**Pull request by lucifer1004**
Currently, `-t bits` will not include `integration_tests/bits_01.f90` since it does not match `bits` from the beginning. We should use `re.search` instead of `re.match`.

### CODE REVIEW

**Comment by konradha** [comment]
Did you run `rm tests/reference/*; ./run_tests.py -u`?

**Comment by certik** [comment]
The change is fine with me. As @konradha said, let's make sure everything is still run.

**Comment by lucifer1004** [comment]
> rm tests/reference/*; ./run_tests.py -u

I checked and non-LLVM tests are OK. I could not check the LLVM tests locally due to some unknown LLVM version or setting issues.

**Comment by certik** [comment]
I think this works. Thanks!

**Pull request merged**
