### PR TITLE
ASR: Support Array storage order

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
Corresponding PR at LPython https://github.com/lcompilers/lpython/pull/1252

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Towards https://github.com/lcompilers/lpython/issues/1249

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by certik** [comment]
This looks good, thanks for this. Can you please merge the latest main and regenerate tests? We merged some other PRs first and the tests here are out of date.

**Review by certik — APPROVED** [review]

**Comment by Shaikh-Ubaid** [comment]
>Can you please merge the latest main and regenerate tests? We merged some other PRs first and the tests here are out of date.

Got it. I just rebased and updated the tests.

**Comment by Shaikh-Ubaid** [comment]
This seems to be approved. Therefore, I am adding this to auto-merge. Thank you for the approval.

**Comment by certik** [comment]
Thanks!

I wonder if this information shouldn't be part of the type, see https://github.com/lcompilers/lpython/issues/1249#issuecomment-1301088354, but we'll do it later.

**Pull request merged**
