### PR TITLE
ci: comment other CI to test c/c++ backend and iterate

### PR DESCRIPTION
**Pull request by Pranavchiku**

### CODE REVIEW

**Comment by assem2002** [comment]
I think emsdk got version `node-14.18.2` removed from the package

**Comment by assem2002** [comment]
This change should be pushed to the main as well

**Comment by Pranavchiku** [comment]
PR: https://github.com/lfortran/lfortran/pull/5080

**Comment by certik** [comment]
I see. We can also temporarily disable this WASM build, and work on this once we merge with master. Not ideal, but WASM is much lower priority than merging simplifier. Maybe @Shaikh-Ubaid can help us with this after we merge.

**Comment by Pranavchiku** [comment]
Resolved, by his suggestion to remove `--experimental-wasm-bigint`. Here is PR for main: https://github.com/lfortran/lfortran/pull/5080

**Pull request merged**
