### PR TITLE
chore: update ci for fpm

### PR DESCRIPTION
**Pull request by HarshitaKalani**

### CODE REVIEW

**Comment by certik** [comment]
Is this doing the workaround to make the new `trim` work?

**Comment by HarshitaKalani** [comment]
I just checked. This is not yet ready.

**Comment by HarshitaKalani** [comment]
With this workaround, `trim` and `len_trim` work fine.

**Comment by certik** [comment]
Here are the changes that were done in this PR.

Just one commit was added to fpm: https://github.com/certik/fpm/commit/a63eb805747f717d420c12de1984e5e15cdb6984. The commit doesn't make any changes to the source code of `fpm` itself, but modifies the `M_CLI2` dependency with this commit: https://github.com/HarshitaKalani/M_CLI2/commit/adaf33f4f82c08325ffa8d9563668c5d8880461f. All it does is it removes `trim` from a print statement inside a `type is` statement. It's a super simple change / workaround, and it's not related to `trim` itself, but rather our implementation of `type is`, which is not completely correct yet.

**Pull request merged**
