### PR TITLE
fix : Nested array ref in where

### LINKED ISSUE #4510: bug : `Where` doesn't loop on multiple dimension array.
```Fortran
program A
    integer ::arr(3,3,3)

    arr = 10
    arr(:,2,:) = 0
    where(arr == 0)
        arr = 555
    end where
    print *, arr
    if(any(arr(:,2,:) /= 555) .or. any(arr(:,1,:) /= 10) .or. any(arr(:,3,:) /= 10)) error stop    
end program A
```

This shouldn't raise an error. as the fortran code resulting from **where pass** is the following : 

_Not full code just the do loop part_
```Fortran
do __1_k = lbound(arr, 1), ubound(arr, 1), 1
    if (arr(__1_k) == 0) then
        arr(__1_k) = 555
    end if
end do
```

### PR DESCRIPTION
**Pull request by assem2002**
fixes #4510 

The fix creates nested do loops based on number of dimensions of the addressed array in the where statement.

fortran code of this initial code https://github.com/lfortran/lfortran/issues/4510#issue-2407913875 after **where** pass  :

```Fortran
do __1_k = lbound(arr, 1), ubound(arr, 1), 1
    do __2_k = lbound(arr, 2), ubound(arr, 2), 1
        do __3_k = lbound(arr, 3), ubound(arr, 3), 1
            if (arr(__1_k, __2_k, __3_k) == 0) then
                arr(__1_k, __2_k, __3_k) = 555
            end if
        end do
    end do
end do
```
_code snippet of nested do loop, not full code._

### CODE REVIEW

**Comment by kmr-srbh** [comment]
Thanks for this! The `where` pass in it's current state needs improvement. When we have a workaround, we should use it to move ahead with SNAP. The proper fix would be using the approach in #4330. Please see https://github.com/lfortran/lfortran/pull/4406#issuecomment-2198453478.

**Comment by assem2002** [comment]
Thanks for the notice, and yeah where pass really needs some refactoring, but such a bug addressed in this example doesn't raise an error and even do part of the job correctly which makes finding out which part of the code is causing this wrong computation a really hard thing. otherwise, we should address all the places where `where` statement exist in any of the packages we're trying to compile and replace them with do loops to avoid these subtle errors.

**Comment by kmr-srbh** [comment]
You are right, we need to handle this anyways. I request you to check the implementation of #4392 and try to handle assignment also. I had wanted to handle the case which this PR fixes, but then deferred it due to the proposed improvements in the `where` pass.

**Comment by assem2002** [comment]
That's great. I'd sure check your PR to know more the process.

**Review by certik — APPROVED** [review]
I think this looks good, thanks for the fix!

**Pull request merged**
