### PR TITLE
Add `--allow-implicit-interface` in compiler options

### LINKED ISSUE #607: Semantic error : Function 'alnorm' was not found or not implemented yet( if it is intrinsic)
while compiling ```spearman.f``` using lfortran, I got the following semantic error, I can try to solve this if provide the stack trace, but it is currently not working on my device.
```
(lf) pranavchiku@pranavchiku-Yoga-Slim-7-14IIL05:~/lfortran$ ./src/bin/lfortran --show-asr --fixed-form --implicit-typing ~/scipy/scipy/stats/statlib/spearman.f --show-stacktrace
Traceback (most recent call last):
semantic error: Function 'alnorm' not found or not implemented yet (if it is intrinsic)
  --> /home/pranavchiku/scipy/scipy/stats/statlib/spearman.f:75:33
   |
75 |       prho = u / exp(y / two) + alnorm(x, .true.)
   |                                 ^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

### LINKED ISSUE #689: [SciPy]: Missing intrinsic ```fpched```
on executing ```lfortran --show-asr --fixed-form --implicit-typing ../scipy/scipy/interpolate/fitpack/concur.f```
results in 
```
semantic error: Function 'fpched' not found or not implemented yet (if it is intrinsic)
   --> /home/pranavchiku/scipy/scipy/interpolate/fitpack/concur.f:333:7
    |
333 |       call fpched(u,m,t,n,k,ib,ie,ier)
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #607 
Fixes #689 
Added configuration for --allow-implicit-interface in lfortran.cpp and utils.h

### CODE REVIEW

**Comment by certik** [comment]
Yes. Now we need to implement it in AST->ASR.

**Comment by Pranavchiku** [comment]
> Yes. Now we need to implement it in AST->ASR.

yeah working on it :)

**Comment by Pranavchiku** [comment]
@certik okay, so I got the place from where this error is returned, I have mentioned that int #607 , and then checked ```comptime_eval.h``` which donot consists of ```alnorm``` implemeted in,

I am actually not getting what you meant by checking ```CompilerOptions``` at the location where it is showing error

**Comment by konradha** [comment]
> and not able to get, what is actually meant from the second point of [link](https://github.com/lfortran/lfortran/issues/607#issuecomment-1217960923)

I think what @certik means is that we should find the spot where it fails and introduce a stub (e.g. with `make_Function_t`) such that the linker can find the function later on.

**Comment by Pranavchiku** [comment]
I got the spot, it is located in ```ast_common_visitor.h```,

**Comment by Pranavchiku** [comment]
I guess, I will bave to work out on some smaller tasks before moving on to it, I prefer that @Smit-create take over this branch from here :)

I will be looking at other semantic errors in ```swilk.f```

**Comment by Smit-create** [comment]
With this PR, I'm able to generate the ASR for all the files under `scipy/stats/statlib/`.

**Comment by konradha** [comment]
Could you take out some of the relevant code pieces (not entire files) from `scipy/stats/statlib/`and add them as tests here? Having the ASR for some more examples would be really great.

**Comment by Smit-create** [comment]
> Could you take out some of the relevant code pieces (not entire files) from `scipy/stats/statlib/`and add them as tests here?

The new test file added in this PR: https://github.com/lfortran/lfortran/pull/615/files#diff-e0817a405273118c743fd439f59ae53c45415d5d4f495c88fa0df9ab3cca2c35 is taken from `scipy`, which previously was throwing an error.

**Comment by Smit-create** [comment]
@certik This looks ready to review.

**Comment by Smit-create** [comment]
This PR fixes and generates ASR for:
1. `scipy/stats/statlib/*.f`
2. `scipy/interpolate/fitpack/concur.f`
3. `scipy/linalg/src/det.f`

**Comment by Pranavchiku** [comment]
This PR generates ASR for:

1. ```scipy/integrate/quadpack/dqag.f```

**Review by certik — APPROVED** [review]
I think this is good enough to merge, thanks for the work.

Note that this is actually not implicit interface, but rather "external" function (with an implicit interface). Fortran also allows to call functions that are not even declared with "external". However, even the "external" feature should be discouraged, and so it is ok that we disable this with the default options and require to pass a command line option to compile. We can later slightly change which command line options handle this.

**Pull request merged**
