### PR TITLE
refactor: `ast_body_visitor` to throw `SemanticAbort()` instead at every place

### PR DESCRIPTION
**Pull request by AnshMehta1**
Pull Request aims to convert all SemanticAbort in ast_body_visitor file into diag.add + SemanticAbort.
With this PR , all SemanticErrors are covered for this file.

### CODE REVIEW

**Review by Pranavchiku — APPROVED** [review]
This is good, thanks for doing this in one go!

**Comment by Pranavchiku** [comment]
I'll wait for one more review before merging.

**Review by parth121101 — APPROVED** [review]
This looks good to me. Thanks

**Review by certik — APPROVED** [review]
I think that looks great, thanks for doing that!

**Pull request merged**
