### PR TITLE
Fix all save warnings in tests

### PR DESCRIPTION
**Pull request by certik**
The new save warning revealed mistakes which we fixed in this PR.

### CODE REVIEW

**Review by czgdp1807 — COMMENTED** [review]
> The new save warning revealed mistakes which we fixed in this PR.

Could you please explain in short what kind of mistakes are being fixed here? AFAICT, the tests are modified, so the warnings are silenced? Is there anything more to this PR?

**Comment by certik** [comment]
Yes, the warning says that you should either put the explicit `save` attribute in there (if that was intended), or initialize the variable as a regular statement (if that was intended), one or the other. The original code is a mistake.

**Review by czgdp1807 — APPROVED** [review]

**Comment by certik** [comment]
Should we improve the warning message to say "Either put explicit `save` attribute or initialize this variable in a separate statement" ?

**Comment by czgdp1807** [comment]
> Should we improve the warning message to say "Either put explicit `save` attribute or initialize this variable in a separate statement" ?

This makes more sense.

**Review by Pranavchiku — APPROVED** [review]
As per what I understood, this PR does minor refactoring at the initialization of variables. The changes look good to me!

**Comment by certik** [comment]
Ok, I merged this and created an issue for the better warning message: https://github.com/lfortran/lfortran/issues/1237

**Pull request merged**
