### PR TITLE
[Julia] add support for BlockCall (and some other improvements)

### PR DESCRIPTION
**Pull request by lucifer1004**
- [x] support BlockCall
- [x] fix RealToInteger cast: use `trunc(IntX, x)` instead of `IntX(x)` which might fail with `InexactError`.
- [x] remove `int` and `not` handling code in `visit_FunctionCall` since these two functions should have been transformed into `Cast` or `IntegerBitNot` nodes.
- [x] fix cast broadcasting (#808)
- [ ] make program-level variables global and do not wrap in main() function (#805)

### CODE REVIEW

**Comment by lucifer1004** [comment]
@certik These changes are ready for review.

**Comment by certik** [comment]
I am not sure if this is a good design.

Fortran cannot have executable statements in global scope, they have to be in a main program (or functions/subroutines). But we have extended Fortran to allow declarations and statements at global scope, and ASR allows it. They executable statements are in `TranslationUnit` in the `items` argument, and declarations in `global_scope`.

Try it:
```console
$ cat a.f90 
integer :: i
i = 5
$ lfortran --show-asr a.f90 --indent
(TranslationUnit 
    (SymbolTable
        1
        {
            i:
                (Variable 
                    1 
                    i 
                    Local 
                    () 
                    () 
                    Default 
                    (Integer 4 []) 
                    Source 
                    Public 
                    Required 
                    .false.
                )
            
        }) 
    [(= 
        (Var 1 i) 
        (IntegerConstant 5 (Integer 4 [])) 
        ()
    )]
)
```

You can even mix and match program and global scope:
```console
$ cat a.f90 
integer :: i
i = 5

program main
integer :: j
j = 5
print *, j
end program
$ lfortran a.f90 --show-asr --indent
(TranslationUnit 
    (SymbolTable
        1
        {
            i:
                (Variable 
                    1 
                    i 
                    Local 
                    () 
                    () 
                    Default 
                    (Integer 4 []) 
                    Source 
                    Public 
                    Required 
                    .false.
                ), 
            main:
                (Program 
                    (SymbolTable
                        2
                        {
                            j:
                                (Variable 
                                    2 
                                    j 
                                    Local 
                                    () 
                                    () 
                                    Default 
                                    (Integer 4 []) 
                                    Source 
                                    Public 
                                    Required 
                                    .false.
                                )
                            
                        }) 
                    main 
                    [] 
                    [(= 
                        (Var 2 j) 
                        (IntegerConstant 5 (Integer 4 [])) 
                        ()
                    )
                    (Print 
                        () 
                        [(Var 2 j)] 
                        () 
                        ()
                    )]
                )
            
        }) 
    [(= 
        (Var 1 i) 
        (IntegerConstant 5 (Integer 4 [])) 
        ()
    )]
)
```

As you can see, the ASR represents both. Our LLVM backend seems to ignore the global statements if there is a main program, but we should probably fix that.

I think the backends should simply translate what the ASR offers, whether global scope or a main function. The main program can be treated like a function "main" that gets called.

LPython has a similar issue, as Python does not have a main program, only global scope.

Now, let's say you actually want to transform some Fortran program to global scope. In that case let's write an ASR->ASR pass that does that at the ASR level. Then you can call it, and it would do what you want in the Julia backend.

CC @czgdp1807.

**Comment by certik** [comment]
(An alternative design is to get rid of the Program node, and only use global scope. I am not sure if we should do that.)

**Comment by lucifer1004** [comment]
@certik I have reverted the global part, could please review the rest parts to see if they can be merged?

**Review by certik — APPROVED** [review]
I think this looks good, thanks!

**Pull request merged**
