### PR TITLE
Fix intrinsic All

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/1970

On branch:
```bash
$ cat examples/expr3.f90                
program expr3
implicit none

logical :: x(3) = [.true., .true., .false.]
print *, all(x)

end program
$ gfortran examples/expr3.f90 && ./a.out
 F
$ lfortran examples/expr3.f90       
False
$ cat examples/expr2.f90         
program expr2
    implicit none

    logical :: x(2, 2)
    x(1, 1) = .true.
    x(1, 2) = .true.
    x(2, 1) = .true.
    x(2, 2) = .false.

    print *, all(x)
    if (all(x)) error stop
end program
$ gfortran examples/expr2.f90 && ./a.out
 F
$ lfortran examples/expr2.f90           
False
```

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
https://github.com/fortran-lang/fpm/blob/39fdc09c9f366c82652c94c790a6c7fb7a2f15bb/src/fpm/dependency.f90#L95

As declared above `done` is not an array. The fpm failure seems valid. @certik could you take a look into this, please?

```bash
$ cat examples/expr3.f90 
program expr3
implicit none

logical :: x = .true.

print *, all(x)

end program
$ gfortran examples/expr3.f90
examples/expr3.f90:6:13:

    6 | print *, all(x)
      |             1
Error: 'mask' argument of 'all' intrinsic at (1) must be a logical array
```

**Comment by Shaikh-Ubaid** [comment]
The previous `all()` implementation was buggy. It would just check the first element and return `true` if the first element is `true`, otherwise return `false`.

**Comment by certik** [comment]
We need to figure out why the CI fails.

**Comment by Shaikh-Ubaid** [comment]
Closing this in favour of https://github.com/lfortran/lfortran/pull/3926.

**Pull request closed without merging**
