### PR TITLE
feat: complete `openmp` ASR to ASR pass

### LINKED ISSUE #4137: openmp ASR to ASR pass
Towards #3777

Let's take the following example and document the ways to create an ASR pass.

<details>

<summary> a.f90 </summary>

```fortran
subroutine increment_ctr(n, ctr)
use omp_lib
implicit none
integer, intent(in) :: n
integer, intent(inout) :: ctr

integer :: local_ctr

integer :: i

!$omp parallel private(i) reduction(+:local_ctr)
!$omp do
do i = 1, n
    local_ctr = local_ctr + 1
end do
!$omp end do
!$omp end parallel

ctr = ctr + local_ctr
end subroutine

program openmp
integer, parameter :: n = 1000000
integer :: ctr

ctr = 0
call increment_ctr(n, ctr)

print *, ctr
end program
```

</details>

This will be an extensive pass containing multiple passes inside which will only be executed if `--openmp` flag is enabled. The first design I can think of is:

- Create a `BaseWalkVisitor`, that will track `current_scope` via visitors for `Program`, `Function`,` Module`, etc which will visit statements with a special handling for `DoConcurrentLoop`.
- As soon as we encounter `DoConcurrentLoop`, we'll create a function to retrieve all the variables and functions involved in it. Once we have it, we'll fetch ASR owner store it some data structure and update the symbols with correct `bind(C)` type, create and populate `thread_data_module` and then go on to create `lcompilers_*` function to do what is present in body of `DoConcurrentLoop`. 
- Creating `lcompilers_*` function will be simple, we just need to add the statements present in body of `DoConcurrentLoop` correctly and job is done.
- Once it is created, we'll create a function call to `GOMP_Parallel` and do what all is required.
- This way we handled the `openmp` part, now just because we updated symbols, we need to create a pass which is `CallReplacerOnExpressionsVisitor` which will visit the `asr_owner` only and that will replace all the expressions correctly.
- After this, we'll catch all the places where this function / subroutine was called ( maybe via another pass ) and then update it's arguments correctly and replace it with a correct function / subroutine call.
- That's it.

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #4137. We can now run the following example with LFortran. 

```fortran
subroutine omp_func(n)
implicit none
integer, intent(in) :: n
integer :: i

!$omp parallel private(i) shared(n)
!$omp do
do i = 1, n
    print *, "xyz"
end do
!$omp end do
!$omp end parallel

print *, "n = ", n
end subroutine

program openmp
integer :: n = 10
call omp_func(n)
print *, "Done for n = ", n

end program
```

```console
% lfortran a.f90 --openmp --openmp-lib-dir=$CONDA_PREFIX/lib
xyz
xyz
xyz
xyz
xyz
xyz
xyz
xyz
xyz
xyz
n =  10
Done for n =  10
```

Now, I am planning to support #4136, for that we need to support reduction in `DoConcurrentLoop` grammar. 

```diff
diff --git a/src/libasr/ASR.asdl b/src/libasr/ASR.asdl
index d1356151b..cc879b0da 100644
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -35,7 +35,7 @@ stmt
     | Cycle(identifier? stmt_name)
     | ExplicitDeallocate(expr* vars)
     | ImplicitDeallocate(expr* vars)
-    | DoConcurrentLoop(do_loop_head head, expr* shared, expr* local, stmt* body)
+    | DoConcurrentLoop(do_loop_head head, expr* shared, expr* local, reduction_expr* reduction, stmt* body)
     | DoLoop(identifier? name, do_loop_head head, stmt* body, stmt* orelse)
     | ErrorStop(expr? code)
     | Exit(identifier? stmt_name)
@@ -214,6 +214,7 @@ presence = Required | Optional
 abi = Source | LFortranModule | GFortranModule | BindC | BindPython | BindJS | Interactive | Intrinsic
 dimension = (expr? start, expr? length)
 alloc_arg = (expr a, dimension* dims, expr? len_expr, ttype? type)
+reduction_expr = (string op, expr arg)
 attribute = Attribute(identifier name, attribute_arg *args)
 attribute_arg = (identifier arg)
 call_arg = (expr? value)
```

Also there are a bunch of things that we need to do but are rather easy to fix for example add visitors for program, etc.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
There is one more bug which I know atm `DoConcurrentStatementVisitor` will not replace symbols. So symbols will still point to old symtab and it will throw 

```console
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: FunctionCall::m_name `xx` cannot point outside of its symbol table
```

Here is the example:

```fortran
subroutine omp_func(n)
use omp_lib
implicit none
integer, intent(in) :: n
integer :: i

!$omp parallel private(i) shared(n)
!$omp do
do i = 1, n
    print *, "xyz"
    print *, "i = ", i, "from thread = ", omp_get_thread_num()
end do
!$omp end do
!$omp end parallel

print *, "n = ", n
end subroutine

program openmp
integer :: n = 10
call omp_func(n)
print *, "Done for n = ", n

end program
```

```console
% lfortran a.f90 --openmp --openmp-lib-dir=$CONDA_PREFIX/lib
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.

ASR verify pass error: FunctionCall::m_name `omp_get_thread_num` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2478
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2442
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 954
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 363
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9898
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 315
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 173
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: openmp
```

**Review by certik — APPROVED** [review]
Great job!

Go ahead and merge.

What is going on with the Mod ordering? Is the ID hardwired in the openmp pass? I wasn't able to find it. Later we should refactor things so that we don't have things hardwired.

**Comment by Pranavchiku** [comment]
> What is going on with the Mod ordering?

To `make_IntrinsicElementalFunction_t` we need to specify `m_intrinsic_id` which is equal to `static_cast<int64_t>(ASRUtils::IntrinsicElementalFunction::Mod` but this was throwing me error and hence I had to hardwire it.

**Comment by certik** [comment]
There is a way to extract integer from the enumerator ordering. Can you create an issue for this?

It's important we don't introduce too much technical debt. We should not depend on the order of enumerators.

**Comment by Pranavchiku** [comment]
I agree I spent time to figure it out but then thought let me proceed and resolve it later on.  I opened https://github.com/lfortran/lfortran/issues/4212 for it

**Pull request merged**
