### PR TITLE
CI: Merge scipy build of special and minpack and test independently

### PR DESCRIPTION
**Pull request by Pranavchiku**
Refer: https://github.com/lfortran/lfortran/pull/2285#issuecomment-1703164445

### CODE REVIEW

**Review by HarshitaKalani — APPROVED** [review]

**Comment by HarshitaKalani** [comment]
I locally checked by putting an `error stop` to confirm it is referring our library. It is indeed.

**Review by certik — APPROVED** [review]
I think this is the way to do it. Is this ready?

**Comment by certik** [comment]
Minpack seems to just work, and specfun has two issues left. The `v(*)` arrays. And then this:
```diff
--- a/scipy/special/tests/test_hyp2f1.py
+++ b/scipy/special/tests/test_hyp2f1.py
@@ -474,7 +474,7 @@ class TestHyp2f1:
                     c=-15.5,
                     z=(1.1578947368421053-1.1578947368421053j),
                     expected=(0.9778506962676361+0.044083801141231616j),
-                    rtol=1e-12,
+                    rtol=1e-11,
                 ),
             ),
             pytest.param(
@@ -1378,7 +1378,7 @@ class TestHyp2f1:
                     c=-7.949900487447654,
                     z=(0.4172413793103451-0.8724137931034484j),
                     expected=(-2258.1590330318213+8860.193389158803j),
-                    rtol=1e-10,
+                    rtol=1e-9,
                 ),
             ),
         ]
@@ -1433,7 +1433,7 @@ class TestHyp2f1:
                     c=-15.964218273004214,
                     z=(0.6448275862068968+0.8724137931034486j),
                     expected=(85592537010.05054-8061416766688.324j),
-                    rtol=1e-14,
+                    rtol=1e-13,
                 ),
             ),
             pytest.param(
```
Why is LFortran's accuracy lower? Maybe it's not "lower", but it's lower with these reference results (which themselves are not accurate). So maybe we need to implement some compiler options to be exactly bit to bit reproducible with GFortran. As we discussed, I think it's worth it. Then we don't need to modify these tests at all.

**Comment by Pranavchiku** [comment]
> Is this ready?

Yes, ready to merge.

**Comment by Pranavchiku** [comment]
> Why is LFortran's accuracy lower? Maybe it's not "lower", but it's lower with these reference results (which themselves are not accurate). 

This tests fail with GFortran as well.

**Comment by certik** [comment]
Ok perfect. Can you send a PR against SciPy, showing the failure with GFortran on your local computer, that the PR fixes?

**Comment by Pranavchiku** [comment]
Yes, perfect.

**Pull request merged**
