### PR TITLE
Implemented Ceiling Again

### LINKED ISSUE #3314: Bug in implementation of Ceiling Intrinsic Function
```
$ cat b.f90
program expr2
    implicit none
    integer(kind = 8) :: res_8
    
        res_8 = Ceiling(1.000, 8)
        print *, res_8
        if (res_8 /= 1) error stop
end program
gfortran b.f90
./a.out
 1
 lfortran b.f90
2
ERROR STOP
```

We need to check if the argument is already an integer. In that case, the result should be the same integer.
Refer to the PR #3283

### PR DESCRIPTION
**Pull request by parth121101**
Fix #3314

### CODE REVIEW

**Comment by parth121101** [comment]
Please review the implementation of the ceiling function. I would try to reimplement the floor (#3330) in this PR itself.

**Review by certik — APPROVED** [review]
I think that's fine. Does it work for all combinations of positive and negative arguments?

**Comment by parth121101** [comment]
> I think that's fine. Does it work for all combinations of positive and negative arguments?

Yes, its working for all the combinations

**Comment by certik** [comment]
Excellent. Thanks for fixing it.

**Pull request merged**
