### PR TITLE
CI: Update Minpack (all tests now fully work)

### PR DESCRIPTION
**Pull request by certik**
All tests compile and run correctly, bit to bit exact results as GFortran. We test all answers.

Depends on #1227.

### CODE REVIEW

**Comment by certik** [comment]
I rebased it on top of the latest master. Everything should pass.

**Comment by certik** [comment]
Here is Minpack fully working:
```console
minpack/lf(scipy30) $ make
[  2%] Building Fortran object src/CMakeFiles/minpack.dir/minpack.f90.o
[  4%] Building Fortran object src/CMakeFiles/minpack.dir/covar.f.o
[  6%] Building Fortran object src/CMakeFiles/minpack.dir/errjac.f.o
[  8%] Building Fortran object src/CMakeFiles/minpack.dir/hybipt.f.o
[ 10%] Building Fortran object src/CMakeFiles/minpack.dir/lhesfcn.f.o
[ 12%] Building Fortran object src/CMakeFiles/minpack.dir/lmdipt.f.o
[ 14%] Building Fortran object src/CMakeFiles/minpack.dir/ocpipt.f.o
[ 16%] Building Fortran object src/CMakeFiles/minpack.dir/r1updt.f.o
[ 18%] Building Fortran object src/CMakeFiles/minpack.dir/vecjac.f.o
[ 20%] Building Fortran object src/CMakeFiles/minpack.dir/chkder.f.o
[ 22%] Building Fortran object src/CMakeFiles/minpack.dir/dmchar.f.o
[ 24%] Building Fortran object src/CMakeFiles/minpack.dir/fdjac1.f.o
[ 26%] Building Fortran object src/CMakeFiles/minpack.dir/hybrd1.f.o
[ 28%] Building Fortran object src/CMakeFiles/minpack.dir/lmder1.f.o
[ 30%] Building Fortran object src/CMakeFiles/minpack.dir/lmpar.f.o
[ 32%] Building Fortran object src/CMakeFiles/minpack.dir/qform.f.o
[ 34%] Building Fortran object src/CMakeFiles/minpack.dir/rwupdt.f.o
[ 36%] Building Fortran object src/CMakeFiles/minpack.dir/dogleg.f.o
[ 38%] Building Fortran object src/CMakeFiles/minpack.dir/fdjac2.f.o
[ 40%] Building Fortran object src/CMakeFiles/minpack.dir/hybrd.f.o
[ 42%] Building Fortran object src/CMakeFiles/minpack.dir/lmder.f.o
[ 44%] Building Fortran object src/CMakeFiles/minpack.dir/lmstr1.f.o
[ 46%] Building Fortran object src/CMakeFiles/minpack.dir/qrfac.f.o
[ 48%] Building Fortran object src/CMakeFiles/minpack.dir/ssqfcn.f.o
[ 51%] Building Fortran object src/CMakeFiles/minpack.dir/dpmpar.f.o
warning: Equivalence statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/src/dpmpar.f:39:7
   |
39 |       equivalence (dmach(1),mcheps(1))
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Equivalence statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/src/dpmpar.f:40:7
   |
40 |       equivalence (dmach(2),minmag(1))
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Equivalence statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/src/dpmpar.f:41:7
   |
41 |       equivalence (dmach(3),maxmag(1))
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
[ 53%] Building Fortran object src/CMakeFiles/minpack.dir/grdfcn.f.o
[ 55%] Building Fortran object src/CMakeFiles/minpack.dir/hybrj1.f.o
[ 57%] Building Fortran object src/CMakeFiles/minpack.dir/lmdif1.f.o
[ 59%] Building Fortran object src/CMakeFiles/minpack.dir/lmstr.f.o
[ 61%] Building Fortran object src/CMakeFiles/minpack.dir/qrsolv.f.o
[ 63%] Building Fortran object src/CMakeFiles/minpack.dir/ssqjac.f.o
[ 65%] Building Fortran object src/CMakeFiles/minpack.dir/enorm.f.o
[ 67%] Building Fortran object src/CMakeFiles/minpack.dir/hesfcn.f.o
[ 69%] Building Fortran object src/CMakeFiles/minpack.dir/hybrj.f.o
[ 71%] Building Fortran object src/CMakeFiles/minpack.dir/lmdif.f.o
[ 73%] Building Fortran object src/CMakeFiles/minpack.dir/objfcn.f.o
[ 75%] Building Fortran object src/CMakeFiles/minpack.dir/r1mpyq.f.o
[ 77%] Building Fortran object src/CMakeFiles/minpack.dir/vecfcn.f.o
[ 79%] Linking Fortran static library libminpack.a
[ 79%] Built target minpack
[ 81%] Building Fortran object examples/CMakeFiles/example_hybrd.dir/example_hybrd.f90.o
warning: Format statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd.f90:68:6 - 71:58
   |
68 |    1000 format(5x, "FINAL L2 NORM OF THE RESIDUALS", d15.7// &
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
71 |               5x, "FINAL APPROXIMATE SOLUTION"//(5x, 3d15.7))
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
warning: format string in write() is not implemented yet and it is currently treated as '*'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd.f90:50:20
   |
50 |     write (nwrite, 1000) fnorm, nfev, info !, (x(j), j=1, n)
   |                    ^^^^ treated as '*'

warning: unit in write() is not implemented yet and it is currently treated as '*'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd.f90:50:12
   |
50 |     write (nwrite, 1000) fnorm, nfev, info !, (x(j), j=1, n)
   |            ^^^^^^ treated as '*'


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
[ 83%] Linking Fortran executable example_hybrd
[ 83%] Built target example_hybrd
[ 85%] Building Fortran object examples/CMakeFiles/example_hybrd1.dir/example_hybrd1.f90.o
warning: Format statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd1.f90:47:6 - 50:24
   |
47 |    1000 format(5x, "FINAL L2 NORM OF THE RESIDUALS", d15.7// &
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
50 |               (5x, 3d15.7))
   | ...^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
warning: format string in write() is not implemented yet and it is currently treated as '*'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd1.f90:36:20
   |
36 |     write (nwrite, 1000) fnorm, info !, (x(j), j=1, n)
   |                    ^^^^ treated as '*'

warning: unit in write() is not implemented yet and it is currently treated as '*'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_hybrd1.f90:36:12
   |
36 |     write (nwrite, 1000) fnorm, info !, (x(j), j=1, n)
   |            ^^^^^^ treated as '*'


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
[ 87%] Linking Fortran executable example_hybrd1
[ 87%] Built target example_hybrd1
[ 89%] Building Fortran object examples/CMakeFiles/example_lmder1.dir/example_lmder1.f90.o
style suggestion: Use '>' instead of '.gt.'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_lmder1.f90:24:15
   |
24 |         if (i .gt. 8) tmp3 = tmp2
   |               ^^^^ help: write this as '>'

style suggestion: Use '>' instead of '.gt.'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_lmder1.f90:32:15
   |
32 |         if (i .gt. 8) tmp3 = tmp2
   |               ^^^^ help: write this as '>'

warning: Format statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_lmder1.f90:86:6 - 89:23
   |
86 |    1000 format(5x, 'FINAL L2 NORM OF THE RESIDUALS', d15.7 // &
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
89 |                5x, 3d15.7)
   | ...^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
[ 91%] Linking Fortran executable example_lmder1
[ 91%] Built target example_lmder1
[ 93%] Building Fortran object examples/CMakeFiles/example_lmdif1.dir/example_lmdif1.f90.o
style suggestion: Use '>' instead of '.gt.'
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_lmdif1.f90:26:11
   |
26 |     if (i .gt. 8) tmp3 = tmp2
   |           ^^^^ help: write this as '>'

warning: Format statement is not implemented yet, for now we will ignore it
  --> /Users/ondrej/repos/lfortran/minpack/examples/example_lmdif1.f90:57:6 - 60:23
   |
57 |    1000 format(5x, 'FINAL L2 NORM OF THE RESIDUALS', d15.7 // &
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
60 |                5x, 3d15.7)
   | ...^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
[ 95%] Linking Fortran executable example_lmdif1
[ 95%] Built target example_lmdif1
[ 97%] Building Fortran object examples/CMakeFiles/example_primes.dir/example_primes.f90.o
[100%] Linking Fortran executable example_primes
[100%] Built target example_primes
minpack/lf(scipy30) $ ctest 
Test project /Users/ondrej/repos/lfortran/minpack/lf
    Start 1: example_hybrd
1/5 Test #1: example_hybrd ....................   Passed    0.00 sec
    Start 2: example_hybrd1
2/5 Test #2: example_hybrd1 ...................   Passed    0.00 sec
    Start 3: example_lmder1
3/5 Test #3: example_lmder1 ...................   Passed    0.00 sec
    Start 4: example_lmdif1
4/5 Test #4: example_lmdif1 ...................   Passed    0.00 sec
    Start 5: example_primes
5/5 Test #5: example_primes ...................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 5

Total Test time (real) =   0.02 sec
minpack/lf(scipy30) $ 
```

**Comment by certik** [comment]
The linux failure is unrelated: https://github.com/lfortran/lfortran/issues/1229

**Comment by Pranavchiku** [comment]
Great work! Now LFortran is "Advanced Alpha" ;)

**Comment by Pranavchiku** [comment]
I rechecked all examples with latest main, and all compiles, output aligns with GFortran.

**Comment by certik** [comment]
Indeed, strong/advanced alpha it is now.

I discovered lots of bugs with callbacks / referencing parent scope variables. I want to get those fixed before calling LFortran beta. But for Minpack itself I think everything works. The last remaining issue is the implied do loops (needed for some of the original examples): https://github.com/lfortran/lfortran/issues/981, otherwise everything compiles as is.

**Comment by Pranavchiku** [comment]
Yeah, I have even encountered various callback bugs. Implied do loops is the one I tried but was not able to get it through, can think of giving it another shot but not sure though.

**Comment by certik** [comment]
If you don't know how to fix do loops, you can try to report all the various call back bugs and see if you can create a minimal reproducible example. Just use the original primes example, I discovered many.

**Pull request merged**
