### PR TITLE
Update reference tests

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
I fixed the tests in https://github.com/lfortran/lfortran/pull/3302.

**Comment by Shaikh-Ubaid** [comment]
I think in the one of the previous PRs, one simply committed the json changes and not the stdout, stderr updates. For example:
```console
./run_tests.py -u
git add tests/reference/*.json
git commit -m "update ref tests"
git push remote branch_name
```
 
So, the hashes in main branch are correct but the contents in the files (stdout/stderr) itself are not.

**Comment by certik** [comment]
Yes, I think so.

**Comment by certik** [comment]
Closing in favor of #3302.

**Pull request closed without merging**
