### PR TITLE
Implement ``merge`` intrinsic as ``IntrinsicFunction``

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lfortran/lfortran/commit/4dc0c5253142c93455236a3577b7ec8e5ded57f8

### CODE REVIEW

**Review by certik — APPROVED** [review]
Looks great!

**Comment by certik** [comment]
There is a nice error message that LFortran now gives:
```
semantic error: All arguments of `merge` should be of same rank and dimensions
    --> build/dependencies/M_CLI2/src/M_CLI2.F90:1499:23
     |
1499 |          ii=maxloc([0,merge(1, 0, shorts == long)],dim=1)
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```
Although in this case I think 1 and 0 are the same rank and dimensions --- I think the issue is that merge works for both arrays and scalars.

**Comment by czgdp1807** [comment]
I guess `shorts == long` is an array. 🫠. Let me debug and confirm though.

**Review by certik — APPROVED** [review]
Looks great to me! Thank you.

**Pull request merged**
