### PR TITLE
WASM: Use column-major for arrays

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
This is a breaking change that requires an update of the code in the gui: https://github.com/lfortran/lcompilers_frontend/pull/29, so we should test both locally first, to ensure everything still works.

**Comment by Shaikh-Ubaid** [comment]
I was wondering that since it seems many languages (`C++`, `Python`, etc.) follow `row-major` ordering, please, could you possibly share if it would be possible to support `row-major` ordering at the `ASR` level?

**Comment by Shaikh-Ubaid** [comment]
>I was wondering that since it seems many languages (C++, Python, etc.) follow row-major ordering, please, could you possibly share if it would be possible to support row-major ordering at the ASR level?

So, I guess the `AST->ASR` part should possibly change/handle the array indexing to follow `row-major` ordering.

**Comment by Shaikh-Ubaid** [comment]
**doubt:** If the `wasm` backend stores in `col-major` format, please, could you possibly share how it could/should support `lpython`.

**Comment by certik** [comment]
I tested this locally with the updated lcompilers_frontend (https://github.com/lfortran/lcompilers_frontend/pull/29) and it works.

Regarding ASR, I think it simply stores the array indices from left to right. It is independent of the internal order of the arrays.

Great question how this works with LPython. @czgdp1807 do you know how this currently works with the LLVM backend?

One option is to store the ordering in ASR as "memory_layout = RowMajor | ColumnMajor | ...", and the backend would support both. In LPython and LFortran we can optionally expose this to the source level so that the user can choose. The default would be ColumnMajor for Fortran and RowMajor for LPython.

**Comment by certik** [comment]
I implemented both orders in the WASM backend, and one can easily choose with a variable. This makes the code ready to be used if we add the flag into ASR itself. I tested both versions locally, they seem to work.

For now I suggest to use column major by default, since we currently only test WASM with LFortran. Later with LPython, we have to keep the column-major for Fortran, and enable row-major just for LPython. 

We should also add some tests for this. But that can be done later. I think it's important to do this breaking change soon, and update the demo code, so that it is conforming to Fortran. After we merge this, we will stay backwards compatible.

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks great!

**Comment by certik** [comment]
If I merge this, will it update correctly automatically online?

**Comment by Shaikh-Ubaid** [comment]
>If I merge this, will it update correctly automatically online?

It seems we need to first merge the corresponding `PR` https://github.com/lfortran/lcompilers_frontend/pull/29 and then merge merge this `PR` soon after it. I think the site `dev.lfortran.org` might not work or fail in the duration between which one `PR` is merged and other is yet to be merged.

**Comment by certik** [comment]
Yes, just ping me when this is ready to be merged.

**Comment by Shaikh-Ubaid** [comment]
>Yes, just ping me when this is ready to be merged.

Sure, I will message here when ready.

**Comment by Shaikh-Ubaid** [comment]
>I am pushing a change that would allow lcompilers_frontend to fetch the wasm builds from wasm_builds and thus the order of merging of both https://github.com/lfortran/lfortran/pull/621 and https://github.com/lfortran/lcompilers_frontend/pull/29 should/would not matter then.

It seems, we currently need to solve https://github.com/lfortran/lcompilers_frontend/issues/31 for the above to work.

**Comment by Shaikh-Ubaid** [comment]
>merging of both https://github.com/lfortran/lfortran/pull/621 and https://github.com/lfortran/lcompilers_frontend/pull/29 should/would not matter then.

It seems even currently the ordering does not matter. Both the `PRs` bring changes which coordinate with each other (one without the other might fail). So, it seems we need both the `PRs` to be merged at same/similar times.

**Comment by certik** [comment]
I think we can merge LFortran first. Then the frontend, which should update the website and in the process download the latest `lfortran.wasm`?

**Comment by czgdp1807** [comment]
> Great question how this works with LPython. @czgdp1807 do you know how this currently works with the LLVM backend?

For now its the same as LFortran (libasr is shared) i.e., Column Major Order (CMO). However I can implement Row Major Order as well and it should be a quick work (AFAICT). The question is how urgently we need Row Major Order (RMO) in LPython. If its not that critical then I will implement it later. In addition, how will the choice between RMO and CMO will be exposed in LPython. If it will be a variable attribute or type annotation then I think parser should be updated first to make that a part of AST, then in AST to ASR transition we can make it a part of ASR and finally LLVM/C/C++ backends will index the array according to the type annotation provided for each array.

**Comment by Shaikh-Ubaid** [comment]
>I think we can merge LFortran first. Then the frontend, which should update the website and in the process download the latest lfortran.wasm?

Yes, right. It looks like ordering matters currently. It seems ordering might now matter once we have https://github.com/lfortran/lcompilers_frontend/issues/31.

**Comment by certik** [comment]
@czgdp1807 it's a lower priority. Regarding how to expose in LPython: using the NumPy syntax in `array`, `reshape` and other functions, they all have the `order` argument which accepts `C`, `F` (for C or Fortran order).

**Comment by czgdp1807** [comment]
I see. Makes sense. I think then `C` and `F` should be constant inputs so that they are available at compile time. Not something like `array = empty(10, order=a_runtime_string)`, right?

P.S. I will add it to my list but keep it towards the bottom. Let me know whenever the support for this is needed, I will work on it then.

**Comment by certik** [comment]
I opened up an issue for this at https://github.com/lcompilers/lpython/issues/987. This is lower priority.

Yes, I would only do strictly compile time, see the issue.

**Pull request merged**
