### PR TITLE
WASM: Support integration_tests/template_array_04.f90

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
The initial `4` commits are part of https://github.com/lfortran/lfortran/pull/1408. I will rebase this PR after https://github.com/lfortran/lfortran/pull/1408 is complete/merged.

**Review by certik — APPROVED** [review]
I think this is fine, thanks!

**Comment by Shaikh-Ubaid** [comment]
I think there exist some integration_tests such that they have functions/subroutines (which are unused) that might fail at the ASR or LLVM level. The integration_tests would pass as such functions/subroutines would be removed by the `pass_unused_functions`.

I wonder if we should not use the `pass_unused_functions` for the `LLVM` backend so that we can catch such errors.

**Comment by Shaikh-Ubaid** [comment]
>I think there exist some integration_tests such that they have functions/subroutines (which are unused) that might fail at the ASR or LLVM level. The integration_tests would pass as such functions/subroutines would be removed by the pass_unused_functions.

I think one such test is https://github.com/lfortran/lfortran/blob/main/integration_tests/operator_overloading_05_module3.f90. I think it might fail if the `pass_unused_functions` is not used.

**Comment by certik** [comment]
We should improve such a test to actually use the function.

**Comment by Shaikh-Ubaid** [comment]
>We should improve such a test to actually use the function.

I created an issue for it at https://github.com/lfortran/lfortran/issues/1417.

**Comment by Shaikh-Ubaid** [comment]
I am adding this PR to auto-merge as it seems approved.

**Review by certik — APPROVED** [review]

**Pull request merged**
