### PR TITLE
test: test failure on x86 mac 

### PR DESCRIPTION
**Pull request by KGB99**
After building LFortran my mac would not pass all tests.
This file is changed on my intel mac after running `./run_test.py -u`. In the zulip chat i was advised to create a PR regarding this

### CODE REVIEW

**Comment by kmr-srbh** [comment]
The test in question here is `runtime_stacktrace_01.f90`. It tests for the creation of a stacktrace using llvm-dwarfdump. Ideally it should have created the file `run_dbg-runtime_stacktrace_01-dcc746e.stderr` with the stacktrace, but it created `run_dbg-runtime_stacktrace_01-dcc746e.stdout` on your machine.

Could you please post the output of `cat ./tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.stdout` here?

**Comment by KGB99** [comment]
The output of `./tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.stdout` is:
```
The stack address was not found in any shared library or the main program, the stack is probably corrupted.
Aborting...
```

**Comment by KGB99** [comment]
yes, should i deactivate it?

**Comment by kmr-srbh** [comment]
> yes, should i deactivate it?

Oh no, it was required to be activated. 

I think we have an issue here. I am guessing it is either related to your system architecture (Intel based mac) or some other issue. We need to dig in. Let's open an issue for it with the new file output.

**Comment by certik** [comment]
The stacktrace probably doesn't work on the Intel Mac. We would need to investigate.

The most important tests are in `integration_tests`. Do they all work?

**Comment by certik** [comment]
Excellent. Can you report the openmp failure?

**Comment by KGB99** [comment]
Yes, i did so now on issue #4288.

**Comment by KGB99** [comment]
I get the following error message:
```
 START TEST:  openmp1.f90
errors/sqrt_neg.f90 * asr ✓
char_arr_assignment.f90 * asr ✓
errors/dreal_arg_error.f90 * asr ✓
errors/coarray_01.f90 * asr ✓
errors/coarray_02.f90 * asr ✓
errors/atomic_01.f90 * asr ✓
errors/iostat_non_scalar_value.f90 * asr ✓
errors/iostat_constant_integer.f90 * asr ✓
openmp1.f90 * asr_openmp ✓
character_parameter_padding_trimming.f90 * asr ✓
errors/type_casting_01.f90 * asr ✓
Traceback (most recent call last):
  File "/Users/kerimbirgi/dev/lfortran/./run_tests.py", line 530, in <module>
    tester_main("LFortran", single_test)
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/compiler_tester/tester.py", line 493, in tester_main
    for f in futures:
  File "/Users/kerimbirgi/miniconda3/envs/lf/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kerimbirgi/miniconda3/envs/lf/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/kerimbirgi/miniconda3/envs/lf/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/kerimbirgi/miniconda3/envs/lf/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/kerimbirgi/miniconda3/envs/lf/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kerimbirgi/dev/lfortran/./run_tests.py", line 521, in single_test
    run_test(
  File "/Users/kerimbirgi/dev/lfortran/src/libasr/compiler_tester/tester.py", line 369, in run_test
    raise RunException(
compiler_tester.tester.RunException: Testing with reference output failed.
errors/runtime_stacktrace_01.f90 * run_dbg
The JSON metadata differs against reference results
Reference JSON: tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.json
Output JSON:    tests/output/run_dbg-runtime_stacktrace_01-dcc746e.json
Omitting 6 identical items
Differing items:
{'stdout': 'run_dbg-runtime_stacktrace_01-dcc746e.stdout'} != {'stdout': None}
{'returncode': 6} != {'returncode': 1}
{'stderr': None} != {'stderr': 'run_dbg-runtime_stacktrace_01-dcc746e.stderr'}
{'stdout_hash': '3bb54d94e2d111c5ecb9eb370562d40ff2806b07b914f3f3fa45f3ce'} != {'stdout_hash': None}
{'stderr_hash': None} != {'stderr_hash': 'eb3c044e48ac8bbaa776077b6c9cef2ef164ade8cddef1d6a7f06792'}No reference stdout_hash available for errors/runtime_stacktrace_01.f90
```
Sorry about opening the issue, I had misunderstood what you meant. Is this what you were asking for?

**Comment by certik** [comment]
Yes. The log might be confusing, since it runs in parallel. But the failure is coming from `stacktrace_01`.

**Comment by certik** [comment]
Excellent, so it seems there is just one issue: the stacktrace fails on Intel macOS. I opened https://github.com/lfortran/lfortran/issues/4312 for this. We can close this PR, since we need to actually fix this issue, we can't just update reference tests, since they will fail on other platforms where the stacktrace works.

**Pull request closed without merging**
