### PR TITLE
Fix array op tests for WASM

### PR DESCRIPTION
**Pull request by advikkabra**
The following tests fail when running integration tests. 
```
The following tests FAILED:
         38 - if_02 (SEGFAULT)
        146 - complex_sub_test (SEGFAULT)
        193 - template_add_01b (SEGFAULT)
        212 - template_lapack_01 (Failed)
Errors while running CTest
```
Once these are done, the PR is ready.

### CODE REVIEW

**Review by certik — APPROVED** [review]

**Comment by advikkabra** [comment]
The segfaults only show up when I run `./run_tests.py`, when I run the files individually, no segfault shows up.

**Comment by Pranavchiku** [comment]
Is it ready to merge?

**Comment by advikkabra** [comment]
Not yet, I'll comment out the failing test and enable it at CI, then we can merge.

**Comment by Pranavchiku** [comment]
If you can do it at priority, that'll be great. Let's try to wrap all these by tonight IST.

**Comment by advikkabra** [comment]
It should be ready now. `template_lapack_01` should ideally be supported for WASM, but we can get to it later.

**Comment by Pranavchiku** [comment]
Awesome, thanks for this! I am enabling auto-merge.

**Pull request merged**
