### PR TITLE
Refactor: remove old compile time implementations

### PR DESCRIPTION
**Pull request by HarshitaKalani**
Towards: #3169

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@HarshitaKalani I think you also need to remove their implementations (if any) from the pure runtime library.

**Comment by HarshitaKalani** [comment]
Oh okay, will do that. Thanks!

**Comment by Shaikh-Ubaid** [comment]
>I think you also need to remove their implementations (if any) from the pure runtime library.

If you plan to do it in a separate PR, I think that is also fine. Maybe create an issue about it so we do not forget.

**Review by certik — APPROVED** [review]
I think that this is good to merge as is.

**Review by Shaikh-Ubaid — APPROVED** [review]
Good to merge. Amazing work! Thanks for this. Also see https://github.com/lfortran/lfortran/pull/3246#issuecomment-1915105820.

**Pull request merged**
