### PR TITLE
Fix: Support for self-referencing procedure declaration

### LINKED ISSUE #5735: bug: self-referencing procedure pointers not supported
### Minimal Reproducible Example

```fortran
module main_module

contains

   recursive subroutine sub(int)
      integer, intent(in) :: int
      procedure(sub), pointer :: proc => sub

      if (int > 10) return

      if (mod(int, 2) /= 0) then
         print *, "Odd: ", int
         call proc(int + 1)
      else
         proc => alt_sub
         call proc(int)
      end if
   end subroutine sub

   subroutine alt_sub(int)
      integer, intent(in) :: int
      print *, "Even: ", int
      call sub(int + 1)
   end subroutine alt_sub

end module main_module


program main
   use main_module
   call sub(1)
end program main
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran test.f90 && ./a.out
 Odd:            1
 Even:            2
 Odd:            3
 Even:            4
 Odd:            5
 Even:            6
 Odd:            7
 Even:            8
 Odd:            9
 Even:           10
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
semantic error: Procedure type 'sub' not declared
 --> test.f90:7:7
  |
7 |       procedure(sub), pointer :: proc => sub
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### PR DESCRIPTION
**Pull request by jinangshah21**
Towards #5774 
Fixes #5735

### CODE REVIEW

**Review by kmr-srbh — APPROVED** [review]
We visit a self referencing procedure after we declare the subroutine/function in the parent scope. The changes look good. Thanks for doing this!

**Review by certik — APPROVED** [review]
I think this is fine. Does this work when saved in a module (`.mod`) file and loaded? To ensure the ASR can be properly serialized / deserialized and all these recursive references resolved.

**Comment by jinangshah21** [comment]
> I think this is fine. Does this work when saved in a module (`.mod`) file and loaded? To ensure the ASR can be properly serialized / deserialized and all these recursive references resolved.

Yes when I put module in other file and use it in different file, it works properly.

**Comment by certik** [comment]
Perfect!

**Pull request merged**
