### PR TITLE
Test runtime output for Dftatom

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by certik** [comment]
I think we are leaking too much memory. It's time to fix it. :)

**Comment by certik** [comment]
I am using lf21, 6eace72ebd20abc5e4e9d0d2f7aa31ebbc409c54. How do I compile it?
```console
$ make -f Makefile.manual
cd src; make -f Makefile.manual
lfortran  -c types.f90
lfortran  -c constants.f90
lfortran  -c dft_data.f90
lfortran  -c utils.f90
lfortran  -c energies.f90
lfortran  -c ode1d.f90
lfortran  -c mixings.f90
lfortran  -c rdirac.f90
lfortran  -c rschroed.f90
lfortran  -c reigen.f90
lfortran  -c rpoisson.f90
lfortran  -c dft.f90
lfortran  -c mesh.f90
lfortran  -c states.f90
lfortran  -c drivers.f90
lfortran  -c dftatom.f90
ar rcs libdftatom.a constants.o dft.o dft_data.o dftatom.o drivers.o energies.o mesh.o mixings.o ode1d.o rdirac.o reigen.o rpoisson.o rschroed.o states.o types.o utils.o
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: libdftatom.a the table of contents is empty (no object file members in the library define global symbols)
cd tests; make -f Makefile.manual
cd lda; make -f Makefile.manual
lfortran  -I../../src -c conv_lda.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2314
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 975
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9070
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 303
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 156
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 380
    u.apply_again = false;
  File "../libasr/asr.h", line 46057
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4774
  File "../libasr/asr.h", line 46075
  File "../libasr/asr.h", line 5060
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 46096
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 339
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5077
  File "../libasr/asr.h", line 4799
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 367
    resultvar2value[replacer.result_var] = original_value;
  File "../libasr/asr.h", line 46289
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 323
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 45036
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/subroutine_from_function.cpp", line 289
    ASR::stmt_t* subrout_call = ASRUtils::STMT(ASRUtils::make_SubroutineCall_t_util(al, loc,
  File "../libasr/asr_utils.h", line 4485
  File "../libasr/asr_utils.h", line 4442
  File "../libasr/asr.h", line 41
AssertFailed: is_a<T>(*f)
make[2]: *** [conv_lda.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

I want to test https://github.com/lfortran/lfortran/pull/2559.

**Comment by Thirumalai-Shaktivel** [comment]
I submitted a PR: https://github.com/lfortran/lfortran/pull/2600 to add the require fixes.

**Comment by Thirumalai-Shaktivel** [comment]
The CI works with 3 iterations.
This PR  is ready

**Review by certik — APPROVED** [review]
I think this looks good, great job!

**Comment by Thirumalai-Shaktivel** [comment]
Thank you!

**Pull request merged**
