### PR TITLE
Fix writing arrays to file

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/2720

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Now it saves arrays with format to a file (and they are also readable as shown in the added integration test in this PR):

```console
(base) ubaid@ubaids-MacBook-Pro pseudopotential % ./vloc_nonrel_dft
Ekin:  4.88932525632765014e+00
Ecoul: 7.53767594177921474e+00
Eenuc: -2.10799198892910944e+01
Exc:   -2.02921191739985929e+00
E_tot: -1.06821306085840888e+01
state    E            occupancy
1s          -1.613029    2.000
2p          -0.181696    3.000

The first 10 values of the radial grid:
9.99999999999999955e-08 1.54777085319871961e-07 2.09716679846322602e-07 2.64819265701435387e-07 3.20085326437619402e-07 3.75515347041852612e-07 4.31109813939941672e-07 4.86869215000797669e-07 5.42794039540704533e-07 5.98884778327623074e-07 

The first 10 values of the 1st and 2nd orbitals:
2.62750036851024360e+00 2.62750036851021873e+00 2.62750036851016100e+00 2.62750036851007573e+00 2.62750036851087376e+00 2.62750036851138402e+00 2.62750036851172508e+00 2.62750036851192537e+00 2.62750036851202751e+00 2.62750036851204349e+00 
1.40168222685969499e-07 2.16948289618008984e-07 2.93956142816606254e-07 3.71192458063715459e-07 4.48657913422719464e-07 5.26353188345882379e-07 6.04278964683904046e-07 6.82435926286435950e-07 7.60824759027656484e-07 8.39446150812580596e-07 

The first 10 values of the radial charge density:
1.09876724129603520e+00 1.09876724129602077e+00 1.09876724129598213e+00 1.09876724129592307e+00 1.09876724129660563e+00 1.09876724129705039e+00 1.09876724129735681e+00 1.09876724129754844e+00 1.09876724129766079e+00 1.09876724129770409e+00 
The first 10 values of the Hartree potential (V_h):
4.95823741022630493e+00 4.95823741022628894e+00 4.95823741022625075e+00 4.95823741022619480e+00 4.95823741022612285e+00 4.95823741022603581e+00 4.95823741022593456e+00 4.95823741022581821e+00 4.95823741022568676e+00 4.95823741022554021e+00 
(base) ubaid@ubaids-MacBook-Pro pseudopotential % 
```

**Comment by Shaikh-Ubaid** [comment]
Great! All the tests pass!

**Comment by Shaikh-Ubaid** [comment]
The generated `dftatom` file looks as follows:

Screenshot 2023-10-26 at 3 41 30 PM

**Review by Thirumalai-Shaktivel — APPROVED** [review]
LGTM, thank you!

**Comment by Shaikh-Ubaid** [comment]
Thank you for the review and approval!

**Pull request merged**
