### PR TITLE
Removing `getPointerElementType` usage in LLVM backend

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lfortran/lfortran/issues/900

### CODE REVIEW

**Comment by certik** [comment]
Make sure you enable opaque pointers by removing the lines in the `asr_to_llvm` function and see if the LLVM 15 CI tests passes. If it does, then we are in business.

**Comment by czgdp1807** [comment]
I tried it fails due to some issues in `CreateLoad` in `LLVMUtils`.

**Comment by certik** [comment]
I see. On Monday you can give it a shot, and if you figure it out that would be great. If not, even just doing what we have in this PR is a big step forward, so we should polish & merge.

**Comment by czgdp1807** [comment]
The problem is in the below linked code,

https://github.com/lfortran/lfortran/blob/ea5c5b90c45068ff41abc2c6a566763016d20789/src/libasr/codegen/llvm_utils.cpp#L9-L14

The scene is that in LLVM 15, pointers are opaque (no underlying type), so `llvm::Type *t2 = t->getContainedType(0);` will give out of index error but there is no type contained by a pointer type. So we need to update all the `LLVM::CreateLoad` calls by directly giving the underlying type. This is a separate issues than what's being dealt with here. So I think we should polish and merge this PR and update CreateLoad calls in a subsequent PR.

**Comment by certik** [comment]
That's fine, any way that works is fine with me, as long as we eventually get compatible with the default LLVM 15 opaque pointers.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
