### PR TITLE
Docs: Minor Refactor

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` slightly refactors the docs (`filename` changes and `ending/stray white space` removals ).

### CODE REVIEW

**Comment by certik** [comment]
We currently do not build the docs at the CI (we have to fix it), so I have to test this by hand, which I'll do soon.

**Comment by certik** [comment]
I won't have time to test this by hand. In order to move this forward, let's

* [ ] setup CI to test the documentation
* [ ] then let's rebase this on top.

**Comment by Shaikh-Ubaid** [comment]
Got it. I will setup the CI and then rebase this.

**Review by certik — APPROVED** [review]
I think that's fine.

**Comment by Shaikh-Ubaid** [comment]
>Note: SSH_PRIVATE_KEY_DOCS is empty, skipping...

It seems the job `upload_docs` is unable to receive the `SSH` keys.

**Comment by Shaikh-Ubaid** [comment]
It seems, we need the `SSH` keys to be named as `SSH_DEPLOY_KEY` to allow the `upload_docs` job access to the keys.

**Comment by certik** [comment]
I think it receives the SSH key, but the key does not work. Fortunately the CI works on a PR, which is the most important. It fails in master, so I need to figure out why the key does not work; but it's not urgent, we can keep merging other PRs.

**Comment by Shaikh-Ubaid** [comment]
Got it. Thank you for the clarification.

**Pull request merged**
