### PR TITLE
Fix dependencies related issues

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
@certik @czgdp1807 is this correct way to fix [this](https://github.com/lfortran/lfortran/pull/1037#issuecomment-1347674975)?

**Comment by Thirumalai-Shaktivel** [comment]
This issue is already fixed in [this PR](https://github.com/lfortran/lfortran/pull/1109).

**Comment by czgdp1807** [comment]
I think all the types in Fortran are static i.e., can be figured out at compile time, so erasing `kind` from dependencies should be okay because kind is a part of the type and it should be possible to evaluate it at compile time. If not then probably the source code is incorrect? cc: @certik.

**Comment by certik** [comment]
Should the subroutine depend on "kind"? I think it has to, so that the code for kind is generated before the code for this subroutine.

If this subroutine was part of a module, then module dependencies would take care of the dependency on the instrinsic module. Since this function is global, there is no such mechanism.

Also, take another example:
```
subroutine F()
use x, only: y
use z, only: u
...
end subroutine
```
If this is a global function, or even a local function in a module, this particular function depends on the modules `x` and `z`, so we should store this information somewhere.

**Comment by Thirumalai-Shaktivel** [comment]
https://github.com/lfortran/lfortran/pull/1113#issuecomment-1361755559
cc @czgdp1807

**Comment by czgdp1807** [comment]
> Should the subroutine depend on "kind"? I think it has to, so that the code for kind is generated before the code for this subroutine.

Do we need to implement support for "kind"? Isn't it possible to always evaluate "kind" to a compile time constant?



> If this is a global function, or even a local function in a module, this particular function depends on the modules `x` and `z`, so we should store this information somewhere.
> 
> I think every entity that can have the `use` statement must store such module dependencies. Such entities are: Program, Module, Function.
> 
> So we should probably add "module_dependencies" into Function.

Yes we should add a new attribute for "module_dependencies" in "Function" node.

**Comment by certik** [comment]
For now I would treat kind such as "dp" strictly in the frontend, not in ASR, where I would just set the kind as a number.

When we print ASR back to Fortran, I would like to print it using "dp" again, but we'll need to figure out how to do that.

**Comment by Thirumalai-Shaktivel** [comment]
This seems to be fixed in the main, so closing this PR.

**Pull request closed without merging**
