### PR TITLE
fix: printing of fixed size array

### LINKED ISSUE #5715: bug: assignment to arrays with lower-bound less than 1 is incorrect
### Minimal Reproducible Example

```fortran
program main
   integer x(0:2)
   x = [1,2,3]
   print *, x
end program
```

### Output

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90
2    3    1
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran test.f90 && ./a.out
           1           2           3
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #5715.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
@Thirumalai-Shaktivel MLIR does not support `ArrayBound` yet, shall I skip the test?

**Comment by Thirumalai-Shaktivel** [comment]
I have created an issue here: https://github.com/lfortran/lfortran/issues/5726

Yea, sure, @Pranavchiku. I will try to pick it up, soon.

**Comment by Thirumalai-Shaktivel** [comment]
If you are still not able to fix, maybe you can disable the test and reference that in the issue.

**Review by certik — APPROVED** [review]
That's fine.

**Pull request merged**
