### PR TITLE
Wrap args inside stringFormat in write + remove write visitor in `print_arr` pass

### LINKED ISSUE #4479: Using format with implied do loops raise error
MRE
```FORTRAN
program prog
    integer ::i
    201 FORMAT( 3I1 )
    write(*,201) (1,i=1,3) 
end program prog
```

```shell
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/assem/lfortran_test/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2481, in ??
    return main_app(argc, argv);
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 2442, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/assem/lfortran_test/lfortran/src/bin/lfortran.cpp", line 912, in ??
    result = fe.get_asr2(input, lm, diagnostics);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/fortran_evaluator.cpp", line 256, in LCompilers::FortranEvaluator::get_asr2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::diag::Diagnostics&)
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/fortran_evaluator.cpp", line 278, in LCompilers::FortranEvaluator::get_asr3(LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&)
    compiler_options.symtab_only, compiler_options);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 106, in LCompilers::LFortran::ast_to_asr(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::SymbolTable*, bool, LCompilers::CompilerOptions&)
    instantiate_types, instantiate_symbols, entry_functions, entry_function_arguments_mapping, data_structure);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 3804, in LCompilers::LFortran::body_visitor(Allocator&, LCompilers::LFortran::AST::TranslationUnit_t&, LCompilers::diag::Diagnostics&, LCompilers::ASR::asr_t*, LCompilers::CompilerOptions&, std::map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned long, LCompilers::ASR::symbol_t*, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, LCompilers::ASR::symbol_t*> > >&, std::map<unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::ttype_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::ttype_t*> > > > > >&, std::map<unsigned int, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, LCompilers::ASR::symbol_t*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, LCompilers::ASR::symbol_t*> > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<LCompilers::LFortran::AST::stmt_t*, std::allocator<LCompilers::LFortran::AST::stmt_t*> > > > > > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<int, std::allocator<int> > > > >&, std::vector<LCompilers::ASR::stmt_t*, std::allocator<LCompilers::ASR::stmt_t*> >&)
    b.visit_TranslationUnit(ast);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 146, in LCompilers::LFortran::BodyVisitor::visit_TranslationUnit(LCompilers::LFortran::AST::TranslationUnit_t const&)
    visit_ast(*x.m_items[i]);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/ast.h", line 4878, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_ast(LCompilers::LFortran::AST::ast_t const&)
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/lfortran/ast.h", line 4835, in ??
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/lfortran/ast.h", line 4881, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_mod(LCompilers::LFortran::AST::mod_t const&)
    void visit_mod(const mod_t &b) { visit_mod_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/lfortran/ast.h", line 4468, in ??
    case modType::Program: { v.visit_Program((const Program_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1571, in LCompilers::LFortran::BodyVisitor::visit_Program(LCompilers::LFortran::AST::Program_t const&)
    transform_stmts(body, x.n_body, x.m_body);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 117, in LCompilers::LFortran::BodyVisitor::transform_stmts(LCompilers::Vec<LCompilers::ASR::stmt_t*>&, unsigned long, LCompilers::LFortran::AST::stmt_t**)
    this->visit_stmt(*m_body[i]);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/ast.h", line 4924, in LCompilers::LFortran::AST::BaseVisitor<LCompilers::LFortran::BodyVisitor>::visit_stmt(LCompilers::LFortran::AST::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/assem/lfortran_test/lfortran/src/lfortran/ast.h", line 4604, in ??
    case stmtType::Write: { v.visit_Write((const Write_t &)x); return; }
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 734, in LCompilers::LFortran::BodyVisitor::visit_Write(LCompilers::LFortran::AST::Write_t const&)
    create_read_write_ASR_node(x.base, x.class_type);
  File "/home/assem/lfortran_test/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 713, in LCompilers::LFortran::BodyVisitor::create_read_write_ASR_node(LCompilers::LFortran::AST::stmt_t const&, LCompilers::LFortran::AST::stmtType)
    ASR::expr_t* string_format = ASRUtils::EXPR(ASRUtils::make_StringFormat_t_util(al, a_fmt->base.loc,
  File "/home/assem/lfortran_test/lfortran/src/libasr/asr_utils.h", line 5666, in ??
    promote_ints_to_kind_8(a_args, n_args, al, a_loc);
  File "/home/assem/lfortran_test/lfortran/src/libasr/asr_utils.h", line 5657, in ??
    m_args[i] = CastingUtil::perform_casting(m_args[i], dest_type, al, loc);
  File "/home/assem/lfortran_test/lfortran/src/libasr/casting_utils.cpp", line 147, in LCompilers::CastingUtil::perform_casting(LCompilers::ASR::expr_t*, LCompilers::ASR::ttype_t*, Allocator&, LCompilers::Location const&)
    return ASRUtils::EXPR(ASRUtils::make_Cast_t_value(al, loc, expr, cast_kind, dest));
  File "/home/assem/lfortran_test/lfortran/src/libasr/asr_utils.cpp", line 1434, in LCompilers::ASRUtils::make_Cast_t_value(Allocator&, LCompilers::Location const&, LCompilers::ASR::expr_t*, LCompilers::ASR::cast_kindType, LCompilers::ASR::ttype_t*)
    int64_t int_value = ASR::down_cast<ASR::IntegerConstant_t>(
AssertFailed: is_a<T>(*f)

```

### LINKED ISSUE #4480: Bug :implied do loop rewrites format with every element
**MRE**
```FORTRAN
program prog
    integer ::i
    write(*,201) ('*',i=1,10) 
    201 FORMAT( 10X, 'whatever', /, 10A )
end program prog
```
gfortran
```
          whatever
**********
```

lfortran
```
          whatever
*          whatever
*          whatever
*          whatever
*          whatever
*          whatever
*          whatever
*          whatever
*          whatever
*          whatever
*
```

***
**UPDATE**
A workaround with fixedSize arrays works, while a fix with allocatable array doesn't and do the same problem :) . This means the issue isn't just related to implied do loops.

### LINKED ISSUE #4507: implied do loops cause in segementation fault with `format`
MRE
```Fortran
program A
    integer ::i
    10 FORMAT (5A,I100)
    write (*,10) ('*',i=1,5), 12345678
end program A
```

It specifically happens when using format character `I` after an implied do loop (As I've tested it so far).

### PR DESCRIPTION
**Pull request by assem2002**
Fixes #4507 
Fixes #4480 
Fixes #4479 

We should be able to remove this commit https://github.com/lanl/SNAP/commit/d0b0e61685f5c11a873b7ae911db2c4cfb81d86b
BIG NOTICE : This [snippet of code](https://github.com/lanl/SNAP/blob/d0b0e61685f5c11a873b7ae911db2c4cfb81d86b/src/setup.f90#L794-L811) should stay the same as it's part of this issue https://github.com/lfortran/lfortran/issues/4173, We should be able to handle it easily now with the backend support for printing arrays.

### CODE REVIEW

**Comment by assem2002** [comment]
Sorry for the confusion in the commits, first 4 commits aren't related they are part of this closed PR https://github.com/lfortran/lfortran/pull/4615

**Comment by certik** [comment]
I tested this PR with SNAP, it can compile it with the implied do loop workarounds. If I remove the workarounds, it compiles all the way to the main program and there it fails in the `implied_do_loops` pass:
```console
$ time make FORTRAN=lfortran FFLAGS= MPI=no OPENMP=no
...
lfortran  -c outer.f90
lfortran  -c analyze.f90
lfortran  -c translv.f90
warning: Assuming implicit save attribute for variable declaration
  --> translv.f90:59:23
   |
59 |   CHARACTER(LEN=1) :: star='*'
   |                       ^^^^^^^^ help: add explicit save attribute or parameter attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c snap_main.f90
warning: Symbol 'iproc' from module 'plib_module' shadows 'iproc' in the current scope
  --> snap_main.f90:97:3 - 98:24
   |
97 |      USE plib_module, ONLY: pinit, iproc, root, comm_snap, bcast,         &
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
98 |        pcomm_set, pinit_omp
   | ...^^^^^^^^^^^^^^^^^^^^^^^^

warning: Symbol 'root' from module 'plib_module' shadows 'root' in the current scope
  --> snap_main.f90:97:3 - 98:24
   |
97 |      USE plib_module, ONLY: pinit, iproc, root, comm_snap, bcast,         &
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
98 |        pcomm_set, pinit_omp
   | ...^^^^^^^^^^^^^^^^^^^^^^^^

warning: Symbol 'swp_typ' from module 'control_module' shadows 'swp_typ' in the current scope
   --> snap_main.f90:100:3
    |
100 |   USE control_module, ONLY: otrdone, swp_typ
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran", in _start()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_start_main()
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __libc_init_first()
  File "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2482, in ??
    return main_app(argc, argv);
  File "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 2411, in main_app(int, char**)
    return compile_to_object_file(arg_file, outfile, false,
  File "/home/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 954, in ??
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 363, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10165, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 315, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 169, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 685, in LCompilers::pass_replace_implied_do_loops(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 46904, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 5137, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 4851, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 46922, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*a.second);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 5137, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 4852, in ??
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 46942, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 457, in LCompilers::ArrayConstantVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 5154, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 4882, in ??
    case stmtType::DoLoop: { v.visit_DoLoop((const DoLoop_t &)x); return; }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 47208, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_DoLoop(LCompilers::ASR::DoLoop_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 457, in LCompilers::ArrayConstantVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 5154, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 4897, in ??
    case stmtType::FileWrite: { v.visit_FileWrite((const FileWrite_t &)x); return; }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 652, in LCompilers::ArrayConstantVisitor::visit_FileWrite(LCompilers::ASR::FileWrite_t const&)
    this->visit_expr(*write_stmt->m_values[i]);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 5202, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_expr(LCompilers::ASR::expr_t const&)
    void visit_expr(const expr_t &b) { visit_expr_t(b, self()); }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 4982, in ??
    case exprType::StringFormat: { v.visit_StringFormat((const StringFormat_t &)x); return; }
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 588, in LCompilers::ArrayConstantVisitor::visit_StringFormat(LCompilers::ASR::StringFormat_t const&)
    this->call_replacer();
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 438, in LCompilers::ArrayConstantVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr.h", line 46097, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayConstant>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayConstructor(down_cast<ASR::ArrayConstructor_t>(x));
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/pass/implied_do_loops.cpp", line 240, in LCompilers::ReplaceArrayConstant::replace_ArrayConstructor(LCompilers::ASR::ArrayConstructor_t*)
    result_type_ = ASRUtils::TYPE(ASR::make_Allocatable_t(al, x->m_type->base.loc,
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr_utils.h", line 2682, in ??
    return duplicate_type(al, t, &empty_dims, physical_type, override_physical_type);
  File "/home/ondrej/repos/lfortran/lfortran/src/libasr/../libasr/asr_utils.h", line 2525, in ??
    ASR::ttype_t* duplicated_element_type = duplicate_type(al, tnew->m_type);
LCompilersException: Not implemented 8
make: *** [Makefile:180: snap_main.o] Error 1
```

**Comment by assem2002** [comment]
Snap works for me, I think you removed the workaroud mentioned here in this snippet in https://github.com/lanl/SNAP/blob/d0b0e61685f5c11a873b7ae911db2c4cfb81d86b/src/setup.f90#L794-L811. It's related to this issue https://github.com/lfortran/lfortran/issues/4173

**Comment by certik** [comment]
@assem2002 I see. I tried to put that workaround back in, but it still fails, although with my lfortran fixes above.

Can you please post a branch of SNAP that works for you? I will test that exactly.

**Comment by certik** [comment]
Looks like you fixed the CI issue. Anything else to do here, or is this ready for review?

**Comment by assem2002** [comment]
I'm creating a branch for the snap

**Review by certik — APPROVED** [review]
I think this PR is fine to merge as is. Thanks for this work!

**Comment by assem2002** [comment]
I'll make sure SNAP works then we could review it.

**Comment by certik** [comment]
Maybe you can add an integration test into this PR that fails in main, but now works.

**Comment by assem2002** [comment]
yeah that would be great. I think I can't use assertion, Is that okay? It would be just a test that compiles with no compilation errors.

**Comment by certik** [comment]
Yes, perfect!

**Comment by assem2002** [comment]
https://github.com/assem2002/SNAP/tree/Test-certik-lf8, This works It's branching from lf8 here https://github.com/certik/SNAP/tree/lf8

**Comment by assem2002** [comment]
@certik I don't know how you specifically do speed testing, but I think with this PR we might have got a little bump

**Comment by assem2002** [comment]
For the tuple issue. As we have only the case of creating tuple is when we're printing or writing, We can create consecutive arrays in the ASR and with special integer type we can detect this in the backend and loop on these consecutive arrays. Does this seem good or overwhelming ? @certik

**Comment by certik** [comment]
@assem2002 thanks! Your branch works for me now also.

**Comment by certik** [comment]
Updated SNAP here: https://github.com/lfortran/lfortran/pull/4672

**Pull request merged**
