### PR TITLE
CI: test scipy/integrate/quadpack 

### PR DESCRIPTION
**Pull request by HarshitaKalani**
After #2800 gets merged, this will be good to merge too.
Ref: https://github.com/certik/scipy/commits/merge_special_minpack_minpack2_fitpack_integrate_01

### CODE REVIEW

**Comment by certik** [comment]
@Pranavchiku go ahead and review this.

**Comment by Pranavchiku** [comment]
This is weird, when I try to run it locally it throws me:

```console
.....
[100%] Linking C shared library quadpack.so
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture arm64:
  "_dgtsv_", referenced from:
      _dqc25f_ in dqc25f.f.o
ld: symbol(s) not found for architecture arm64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [quadpack.so] Error 1
make[1]: *** [CMakeFiles/quadpack.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Pranavchiku** [comment]
I suspect this to fail stating duplicate symbols in `_d1mach_`  or some file of `integrate/mach`.

**Comment by Pranavchiku** [comment]
CMake is behaving differently in mac and linux, is this expected? If no, then we may either need to add CI to test SciPy for mac or will need to improve current CMake.

**Comment by Pranavchiku** [comment]
`Test Fortran Backend` fails. Failure is not related to this PR.

```console
f951: Fatal Error: Cannot rename module file 'lfortran_intrinsic_builtin.mod0' to 'lfortran_intrinsic_builtin.mod': No such file or directory
compilation terminated.
The command 'gfortran -o CMakeFiles/bits_02_FAST.dir/bits_02.f90.o -c CMakeFiles/bits_02_FAST.dir/bits_02.f90.o.tmp.f90' failed.
make[2]: *** [CMakeFiles/bits_02_FAST.dir/build.make:75: CMakeFiles/bits_02_FAST.dir/bits_02.f90.o] Error 11
make[1]: *** [CMakeFiles/Makefile2:1889: CMakeFiles/bits_02_FAST.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 92%] Linking Fortran executable bits_06_FAST
[ 92%] Built target file_15_FAST
[ 93%] Linking Fortran executable assign_to3_FAST
[ 93%] Built target abs_03_FAST
[ 93%] Built target abs_01_FAST
[ 93%] Built target abs_02_FAST
[ 93%] Linking Fortran executable array_section_01_FAST
[ 93%] Built target bits_06_FAST
[ 93%] Built target assign_to3_FAST
[ 93%] Built target array_section_01_FAST
make: *** [Makefile:101: all] Error 2
```

**Review by Pranavchiku — APPROVED** [review]
This is good to merge. We have 9 / 18 ( 50% ) SciPy compiled, tested correctly on CI.

**Comment by certik** [comment]
Let's add a Mac test for all 3rd party tests.

**Pull request merged**
