### PR TITLE
[ASR] Convert do loops without a header into while loops

### PR DESCRIPTION
**Pull request by lucifer1004**
@certik I reverted the changes in #823 and made the change at ASR level instead.

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
This makes sense to me. Let's see if the tests pass.

**Comment by lucifer1004** [comment]
I forgot to update the references.

**Comment by czgdp1807** [comment]
Can you do `git rebase main` and then force push here?

**Comment by lucifer1004** [comment]
> Can you do `git rebase main` and then force push here?

We can also do squash merge. I am working on another branch at the moment.

**Review by certik — APPROVED** [review]
I think that this is fine, but we need to be enforcing this either by changing ASR nodes, or in verify().

The ideal change would be this:
```diff
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -382,7 +382,7 @@ tbind = Bind(string lang, string name)
 
 array_index = (expr? left, expr? right, expr? step)
 
-do_loop_head = (expr? v, expr? start, expr? end, expr? increment)
+do_loop_head = (expr v, expr start, expr end, expr? increment)
 
 case_stmt = CaseStmt(expr* test, stmt* body) | CaseStmt_Range(expr? start, expr? end, stmt* body)
```
But I don't know if there can be a problem with this, it needs to be tried. (The `increment` can also be always included, but I think one will be checking for the default (1) all the time, so that can be the nullptr.)

If this cannot be done like that, then let's implement (and document) the exact conditions in verify().

**Comment by certik** [comment]
This can be merged and the above implemented in subsequent PRs.

**Pull request merged**
