### PR TITLE
try to speed up CI with micromamba

### PR DESCRIPTION
**Pull request by wolfv**
This PR switches to micromamba, and uses `sscache` and `ninja` wherever possible.

### CODE REVIEW

**Comment by wolfv** [comment]
This is all I can do for now :) I think it shaves off a couple of minutes, especially with a warm cache.

- Ubuntu from 12 -> 3 minutes
- macOS from 22 -> 12 minutes
- Windows from 21 -> 12 minutes

And the others are sped up, too.

**Comment by certik** [comment]
Awesome, much better! Let me review it and make sure it works well.

**Comment by wolfv** [comment]
it's a very similar setup that we're using in mamba's CI and works well since 6 months or so :)

**Comment by certik** [comment]
I think the changes are fine. Thank you @wolfv !

**Comment by certik** [comment]
It failed right away in master. :)

Error: Unable to resolve action `wolfv/provision-with-micromamba@unix_sel`, unable to find version `unix_sel`

https://github.com/lfortran/lfortran/runs/7558652443?check_suite_focus=true

**Comment by certik** [comment]
Can you send a PR that fixes this?

**Comment by wolfv** [comment]
Yes. Sorry I deleted the branch after it was merged into upstream

**Pull request merged**
