### PR TITLE
Fix alloc for func ret var in pass_sub_from_fn

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/2562

### CODE REVIEW

**Review by czgdp1807 — APPROVED** [review]
Any workaround it helps in reverting from ``dftatom``?

**Comment by Shaikh-Ubaid** [comment]
>Any workaround it helps in reverting from dftatom?

I looked up the commits in the `dftatom`, but could not find where this issue helps. I will revert it when I find it in future.

**Comment by Shaikh-Ubaid** [comment]
Thank you so much for the review and approval @czgdp1807!

**Comment by Shaikh-Ubaid** [comment]
I am merging this as it seems approved.

**Pull request merged**
