### PR TITLE
Support include path in C Preprocessor

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/1669

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Please ignore the changes in the commit [tmp](https://github.com/lfortran/lfortran/pull/1670/commits/2afdb263306258e5b439484c1f8a2e6859e0f75d). I will be removing it.

**Comment by Shaikh-Ubaid** [comment]
This PR fixes/supports the use of user specified include path in `C Preprocessor`. How do we add a test for this? It seems in `integration_tests` we do not have support for `--cpp` flag and in `reference tests` we do not have support for include flag.

**Comment by Shaikh-Ubaid** [comment]
Ready for review.

**Review by certik — APPROVED** [review]
I think that looks good, thanks!

**Comment by certik** [comment]
I think we only have some tests for `--cpp` in the `tests/` directory, not `integration_tests` yet. I think this PR is fine for now, it fixes the issue. We should carefully test all this in integration_tests by adding specific tests for that, similar to how we test include in LPython.

**Pull request merged**
