### PR TITLE
Fix formatted printing issues

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Ready!

**Comment by certik** [comment]
I think it looks good, but unfortunately tests fail, so they need to be fixed. I am rerunning it just in case.

**Comment by Thirumalai-Shaktivel** [comment]
GFortran stdlib fails, I will look into it tomorrow.

**Comment by certik** [comment]
I rebased this using https://github.com/lfortran/lfortran/issues/3589.

**Comment by Thirumalai-Shaktivel** [comment]
Thank you!

**Review by certik — APPROVED** [review]
I think that works, thanks!

**Pull request merged**
