### PR TITLE
chore: merge `main` into `simplifier_pass` branch

### PR DESCRIPTION
**Pull request by kmr-srbh**

### CODE REVIEW

**Comment by certik** [comment]
For me this PR shows

image


Does it mean it is not based on the latest `simplifier_pass` branch?

**Comment by kmr-srbh** [comment]
> Does it mean it is not based on the latest `simplifier_pass` branch?

I think it shows this message because we just merged a change to the CI for the `simplifier_pass` branch. We are now testing `Legacy Minpack (SciPy)`. It works with these changes.

**Comment by kmr-srbh** [comment]
The newly added test `intrinsics_316.f90` fails with the changes in the `simplifier_pass` branch. It passes on `main`. I am commenting out the test and reporting the MRE for it.

**Comment by kmr-srbh** [comment]
I think the conflict is due to commenting out the last test, `associate_07` which is uncommented on the branch currently.

**Comment by gxyd** [comment]
Looks good to me, once we resolve the conflicts, I think we should be good to merge this.

**Review by Pranavchiku — APPROVED** [review]

**Pull request merged**
