### PR TITLE
pre-commit and clang-format configuration

### PR DESCRIPTION
**Pull request by wolfv**
This is just _one_ proposal for a pre-commit + clang-format configuration.

I am happy to only add the pre-commit & clang-format files and let someone else run it for the first time (otherwise it looks as if I had worked a lot on lfortran whcih isn't true ;)

Also obviously we can discuss the style you want to use. 

And lastly -- should we exclude the `stderr` and `stdout` and `json` files in the tests folders?

### CODE REVIEW

**Comment by certik** [comment]
The format itself seems fine. 4 spaces is the most important.

I would not indent namespaces, since it's kind of 4 spaces (or more) lost.

I would format `if` and `while` like this:
```
if () {
    ...
} else if () {
    ...
} else {
    ...
}
```
Otherwise I think everything else does not matter to me.

**Comment by wolfv** [comment]
You might still want to run some fixes on `.f*` files -- e.g. end of line whitespace deletion or no newline at the end of the file?

**Comment by certik** [comment]
Sure, that's not a big deal I think.

**Comment by wolfv** [comment]
I just re-ran it with an updated clang-format file for you to check.

**Comment by certik** [comment]
I think the format is good now. Do you want to submit just the formatting config files?

**Comment by wolfv** [comment]
sure, let me do that.

**Comment by wolfv** [comment]
done, removed all changes except for the two configuration files.

**Comment by certik** [comment]
Thanks! Let's merge this and I'll try to set it up locally and document how to use this.

**Comment by wolfv** [comment]
`conda install pre-commit -c conda-forge` or `pip install pre-commit` should give you everything you need. After that, just execute `pre-commit run --all`, or you can install the hooks to run on every git commit using `pre-commit install`.

**Comment by certik** [comment]
I think it works. It seems to be *very* slow, about 10s for each run:
```console
$ time pre-commit run --all
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
check yaml...............................................................Passed
check toml...............................................................Passed
check json...............................................................Passed
check for merge conflicts................................................Passed
pretty format json.......................................................Passed
debug statements (python)................................................Passed
clang-format.............................................................Passed
pre-commit run --all  16.36s user 0.92s system 157% cpu 10.983 total
```

**Comment by certik** [comment]
I see, that's because it runs everything. Just `pre-commit run` is fast the second time, about 0.2s.

**Comment by lucifer1004** [comment]
Seems that the current `main` branch needs a reformatting. I ran `pre-commit run --all` locally and lots of files were modified.

**Comment by certik** [comment]
Yes, we don't have the infrastructure setup for this and I have not run it in the main branch yet, so for now just format by hand.

**Comment by lucifer1004** [comment]
Should we add a git pre-commit hook for this?

**Comment by certik** [comment]
Let's do this after we can compile SciPy or a substantial parts thereof. We are right now still heavily modifying the frontend and I want to keep the barrier low.

**Comment by wolfv** [comment]
@certik just FYI there is this bot that you can enable which would fix all PRs automatically: https://pre-commit.ci/

It might just make history look a bit more annoying if you don't squash-merge.

**Comment by certik** [comment]
@wolfv yes, we'll use it, but let's get to "beta" first. I opened up an issue https://github.com/lfortran/lfortran/issues/882 for this.

**Pull request merged**
