### PR TITLE
fix: program without line generates ast with continue compilation flag

### PR DESCRIPTION
**Pull request by parth121101**
Towards: #5713

### CODE REVIEW

**Comment by parth121101** [comment]
with this PR `program_without_line.f90` files generates ast when continue-compilation flag is used. Here's the example:
```
cat tests/errors/program_without_line_01.f90
print *, "OK"
contains
```

```
lfortran tests/errors/program_without_line_01.f90 --con
tinue-compilation --show-ast
syntax error: Expected program end
 --> tests/errors/program_without_line_01.f90:1:1 - 2:8
  |
1 |    print *, "OK"
  |    ^^^^^^^^^^^^^...
...
  |
2 |    contains
  | ...^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
(TranslationUnit
    [(Print
        0
        ()
        [(String "OK")]
        ()
    )
    contains]
)
```

**Comment by Thirumalai-Shaktivel** [comment]
I think AST is invalid here, don't you think?

Is this required in interactive shell?
I think the statements needs to be included inside a Module, Function or Subroutine. So, previously it used to throw correct error only right?

Would this change generate an ASR, can you please share it?

**Comment by parth121101** [comment]
> I think AST is invalid here, don't you think?
> 
> Is this required in interactive mode? I think the statements needs to be included inside a Module, Function or Subroutine. So, previously it used to throw correct error.
> 
> Would this PR generate an ASR, can you please share it?

@Thirumalai-Shaktivel this does not generate ASR. Even the main branch is unable to generate the ASR at this point of time. So I believe this needs to be fixed as well.

**Comment by Thirumalai-Shaktivel** [comment]
I have some doubts here, can you please clarify them?
From the issue, I can see you are trying to generate AST for the following tests:
```
tests/errors/program_without_line_01.f90
tests/errors/program_without_line_02.f90
tests/errors/program_without_line_03.f90
tests/errors/program_without_line_04.f90
```
- Why do we need to generate AST for these tests using continue-compilation flag?
- Where is it used?
- I checked GFortran, all the tests seems to be failing as invalid syntax, why generate ASR?

**Comment by Thirumalai-Shaktivel** [comment]
Oh okay. But, I was curious to know where would this be used.

Thanks for the response.

**Comment by certik** [comment]
Should we add some test for this?

**Comment by parth121101** [comment]
> Should we add some test for this?

Sure @certik

**Comment by Pranavchiku** [comment]
I think a new file will works.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
