### PR TITLE
Add provision for `fmt` to point a label in `WRITE`

### LINKED ISSUE #766: [SciPy] Semantic Error: `fmt` must be of character type
```
semantic error: `fmt` must be of type Character
  --> /home/pranavchiku/scipy/scipy/sparse/linalg/_eigen/arpack/ARPACK/UTIL/dvout.f:51:7
   |
51 |       WRITE( LOUT, FMT = 9999 )IFMT, LINE( 1: LLL )
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #766.

### CODE REVIEW

**Comment by certik** [comment]
Can this compile to LLVM? I would make it a regular test, maybe modify the format a bit to run, and then just run it all the way.

**Comment by Pranavchiku** [comment]
Yes, it runs.

**Comment by certik** [comment]
Then let's just make it an integration test, not tests/tests.toml.

**Comment by Pranavchiku** [comment]
It is a bit weird, when I have test in `.f90` format, it do not throw me error.

**Comment by certik** [comment]
Maybe implicit typing has to be enabled?

**Comment by Pranavchiku** [comment]
Yes, I am running this with `lfortran a.f90 --show-asr --implicit-typing --implicit-interface`

**Comment by Pranavchiku** [comment]
Ahh got it, this is because in example we have `FMT=9999` and internally it does check for `arg == std::string("fmt")`, upper case lower case issue.

**Comment by Shaikh-Ubaid** [comment]
@Pranavchiku it seems after merging of this PR, the CI fails in the main branch.

Also it seems commits like [rename program name in test](https://github.com/lfortran/lfortran/pull/1909/commits/1e6139d407bd4e21dd0d924bb0791f2e20ca8709) could be rebased/squashed into its parent commit (where you added the test). I would suggest to keep a clean commit history.

**Comment by Pranavchiku** [comment]
Sorry for this. I will take care of it in upcoming PRs. 
Here is the fix for the test: https://github.com/lfortran/lfortran/pull/1918

**Comment by certik** [comment]
If possible, wait for a review --- it doesn't have to be from me, if Ubaid, Smit, Thirumalai or Gagandeep approves, you can also merge it.

**Pull request merged**
