### PR TITLE
Ref: append errors in diagnostics for `ast_common_visitor` file and removed Semantic Errors

### PR DESCRIPTION
**Pull request by parth121101**
Towards: #5036

### CODE REVIEW

**Comment by parth121101** [comment]
Initially, we were throwing semantic errors in the `ast_common_visitor` file in about 180 different locations. 165 of these 180 have been refactored.
Rest 15 have some issues. While do that in a separate PR.

**Review by certik — APPROVED** [review]
I think this looks good, thank you for doing it.

**Comment by certik** [comment]
@parth121101 watch the CI in `main`, there might be some failures, as we merged several big PRs that might introduce some failures. If so, it should not be difficult to fix.

**Comment by parth121101** [comment]
> @parth121101 watch the CI in `main`, there might be some failures, as we merged several big PRs that might introduce some failures. If so, it should not be difficult to fix.

Sure @certik

**Pull request merged**
