### PR TITLE
Reimplemented a part of Nint intrinsic function

### LINKED ISSUE #3364: Add int64_t for result variable in implementation of Nint
```
% cat examples/expr2.f90 
program expr2

implicit none
print *, nint(1e12_8, 8)
if (nint(1e12_8, 8) /= 1000000000000_8) error stop

end program

% gfortran examples/expr2.f90
% ./a.out 
        1000000000000

% lfortran examples/expr2.f90
2147483647
ERROR STOP
```

Add int64_t in implementation of Nint.

### PR DESCRIPTION
**Pull request by parth121101**
Fix #3364

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
I would add stronger/robust test cases to ensure this works perfectly for compile time as well as run time.

**Comment by Shaikh-Ubaid** [comment]
@parth121101 Can you show the output of the example at https://github.com/lfortran/lfortran/issues/3364#issue-2125382071 for compile-time as well as run-time values?

**Review by certik — APPROVED** [review]
I think this PR is fine. @Shaikh-Ubaid can decide how to proceed here.

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks good to me. Thanks for this. Amazing work! I appreciate it.

**Pull request merged**
