### PR TITLE
Parser: Allow declarations in an if statement

### PR DESCRIPTION
**Pull request by certik**
This is needed in order to allow DATA to be used inside an if statement. Right now all the declarations are ignored. We will need to improve this to only allow DATA and allow it to be represented in AST somehow.

Test added.

Towards #778.

### CODE REVIEW

**Comment by certik** [comment]
@czgdp1807, @Thirumalai-Shaktivel here is one addition to the parser that we need to do, apparently Fortran allows (and GFortran supports) declaring DATA inside an if statement. This PR parses it, but ignores the declaration(s), so AST does not have it yet.

What would be the best way to represent this in AST?

I don't quite understand the semantics of DATA, but it seems it would only get executed if the if branch gets executed, so it almost looks like an assignment. In that case, I think we can create an AST statement node (DataStatement), and then in semantics.h extract these declaration, give an error message for all declarations except DATA, which will get turned into a DataStatement and just put as a regular statement. Then in AST->ASR we can take care of this and probably turn it into an assignment.

**Comment by awvwgk** [comment]
> I don't quite understand the semantics of DATA, but it seems it would only get executed if the if branch gets executed, so it almost looks like an assignment. In that case, I think we can create an AST statement node (DataStatement), and then in semantics.h extract these declarations inside an if statement, give an error message for all declarations except DATA, which will get turned into a DataStatement and just put as a regular statement. Then in AST->ASR we can take care of this and probably turn it into an array assignment.

I don't think this is correct, DataStatement implies implicit save, like in the example below

```
❯ cat test.f90
call stateful_data
call stateful_data
contains
subroutine stateful_data
  real a(5)
  print *, a
  if (any(a > 0)) then
    data a /1, 2, 3, 4, 5/
    a = 0
  end if
end subroutine stateful_data
end
❯ ifort test.f90 && ./a.out
   1.000000       2.000000       3.000000       4.000000       5.000000    
  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00  0.0000000E+00
❯ gfortran test.f90 && ./a.out
   1.00000000       2.00000000       3.00000000       4.00000000       5.00000000    
   0.00000000       0.00000000       0.00000000       0.00000000       0.00000000
```

**Comment by certik** [comment]
Heh, I found so many surprising things about Fortran while writing a compiler. :)

I still don't understand this at all. Consider this:
```fortran
call stateful_data
call stateful_data
call stateful_data
contains
subroutine stateful_data
  real a(5)
  print *, a
  if (.false.) then
    data a /1, 2, 3, 4, 5/
    a = 1
  else
    data a /5, 4, 3, 2, 1/
    a = 2
  end if
end subroutine stateful_data
end
```
This prints:
```
   1.00000000       2.00000000       3.00000000       4.00000000       5.00000000    
   2.00000000       2.00000000       2.00000000       2.00000000       2.00000000    
   2.00000000       2.00000000       2.00000000       2.00000000       2.00000000    
```
So it's the "data" from the first if branch is being used to initialized "a", but this branch is never taken! As you can see, it prints 2 eventually, because it's the else branch that is taken.

**Comment by certik** [comment]
Here is my best theory so far:

* All "data" lines are collected *in order* from the whole subroutine, including all if statements, do loops, while loops, *irrespective* of the control flow logic; it doesn't matter if it is in a dead branch, or in a loop, it is simply treated as a line that you can magically lift out of the loop
* The first "data" for a given variable is executed when the function is first called; the other data lines for the same variable are ignored
* It turns on "save" for the given variable...

**Comment by certik** [comment]
I created a better PR (https://github.com/lfortran/lfortran/pull/804) which I think can parse Data anywhere, but it needs more work to update everything to pass again.

**Comment by certik** [comment]
Closing in favor of #804.

**Comment by certik** [comment]
The main problem was fixed by #851.

I opened up issues for the remaining problems:

* https://github.com/lfortran/lfortran/issues/852
* https://github.com/lfortran/lfortran/issues/853

**Pull request closed without merging**
