### PR TITLE
Fix: avoid n-d array name collisions (#747)

### PR DESCRIPTION
**Pull request by lucifer1004**
Implement new `trim_dims` to avoid array name collisions.

### CODE REVIEW

**Comment by lucifer1004** [comment]
So there are quite a few tests that need to be modified. I will look at them later.

**Comment by lucifer1004** [comment]
@certik I need your help to regenerate the test reference files since I am not familiar with this part.

**Comment by konradha** [comment]
@lucifer1004 remove all test references (ie. `rm tests/reference/*`) and regenerate all files `./run_tests.py -u`

**Comment by lucifer1004** [comment]
Related references have been updated.

**Review by certik — APPROVED** [review]
I think this change is fine. Thanks!

**Pull request merged**
