### PR TITLE
test: add array tests for adjustl and adjustr

### PR DESCRIPTION
**Pull request by shivimathur**
Fixes : https://github.com/lfortran/lfortran/issues/4174

### CODE REVIEW

**Review by Pranavchiku — APPROVED** [review]
great, thanks!

**Comment by Pranavchiku** [comment]
It would be worth reading https://www.conventionalcommits.org/en/v1.0.0/, will help in future :)

**Comment by shivimathur** [comment]
> It would be worth reading https://www.conventionalcommits.org/en/v1.0.0/, will help in future :)

Sure, thanks!

**Comment by certik** [comment]
Excellent, thanks!

**Pull request merged**
