### PR TITLE
WASM: Support defining functions in any order

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` adds support for defining `functions` in any order in the `wasm` backend.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by Shaikh-Ubaid** [comment]
I am adding an `integration_test` for this.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]
Looks good to me, thanks for fixing it!

**Pull request merged**
