### PR TITLE
CI: Test dftatom with ``--experimental-simplifier --fast``

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lfortran/lfortran/issues/5717

### CODE REVIEW

**Comment by czgdp1807** [comment]
The failure - https://github.com/lfortran/lfortran/actions/runs/12354791911/job/34479319114?pr=5725 - seems irrelevant to me.

**Review by gxyd — APPROVED** [review]
Looks good to me.

**Comment by gxyd** [comment]
Because of the failing CI, it will probably not let it merge.

**Comment by certik** [comment]
Thanks! I force merged it, since the failure is unrelated and I merged the other PR to fix it.

**Pull request merged**
