### PR TITLE
AST/R: Support Tree Printing

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
Related PR at LPython: https://github.com/lcompilers/lpython/pull/1451

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and share feedback.

**Comment by Thirumalai-Shaktivel** [comment]
I always wanted the `--tree` option in LFortran but didn't had time to add it. Thanks for working on this.

**Comment by Thirumalai-Shaktivel** [comment]
The test seems to be passing on my machine.

But I don't know why it fails here. We have to debug this
```
Internal Compiler Error: Unhandled exception
Command failed.
Traceback (most recent call last):
LCompilersException: read_int64: String is too short for deserialization.
```

**Comment by Thirumalai-Shaktivel** [comment]
I restarted the test and it passed 😁.

**Comment by certik** [comment]
That's not good, we got a failure
```
Internal Compiler Error: Unhandled exception
Command failed.
Traceback (most recent call last):
LCompilersException: read_int64: String is too short for deserialization.
```
and restarting it "fixed" it? I think the bug is still there. Can you post the full stacktrace? Let's create an issue for this, as it will come again.

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
I think this PR is fine to merge. @Thirumalai-Shaktivel if you wouldn't mind creating an issue for the failure, unless you think the bug is not there.

**Comment by Thirumalai-Shaktivel** [comment]
I saw a test (for macOS) fail here, so I fetched the changes and built them on my machine. But I was not able to reproduce any failure, as all the tests passed on my local machine.
Then, I thought the test's failure might be because of the parallel threading or concurrent running of tests. So, I restarted the test, and it passed.
Yup, as you said, there might be a bug. This was the first time I came across such a failure. If I encounter it again, I will try to debug it and report it as an issue.

**Comment by Thirumalai-Shaktivel** [comment]
The stack trace was not available in the CI, https://github.com/lfortran/lfortran/actions/runs/3974613514/jobs/6813980200

**Comment by certik** [comment]
Ah:
```
Internal Compiler Error: Unhandled exception
Command failed.
Traceback (most recent call last):
LCompilersException: read_int64: String is too short for deserialization.
```
This suggests that indeed the mod file was overwritten. So that's a bug in our cmake that we write mod files with the same name, indeed coming from parallel tests. That's fine, that's not a bug in LFortran, at least not directly.

**Pull request merged**
