### PR TITLE
Merge main into simplifier pass

### PR DESCRIPTION
**Pull request by gxyd**
After the discussion on Zulip, we concluded that periodically merging *main* into *simplifier_pass* branch is a good idea. Also, we need some changes present on *main* into our *simplifier_pass* branch.

### CODE REVIEW

**Comment by gxyd** [comment]
In the last two commits, I've:
1. Disabled the build on Linux/macOS, as it needs changes in simplifier_pass to actually make it pass. And since it didn't succeed, I disabled test_lfortran_cmdline as well
2. Disabled matrix_01_transpose, as that test case needs investigation for why it's flaky

@kmr-srbh if you could kindly review this, once the tests pass.

**Review by kmr-srbh — APPROVED** [review]
I think the changes look good! Thanks for this!

I have a minor suggestion. I think the conflicts are due to the `llvm_17` tag that we now have in `main`. I think the number of conflicts might be large. Can we merge changes related to the `CMakeLists.txt` file in a separate PR resolving all the conflicts in the way? I think the `matrix_01_transpose` test may pass on a rerun (as it previously did). If the conflicts are less, we can continue in this PR too. :)

**Comment by gxyd** [comment]
> I think the matrix_01_transpose test may pass on a rerun (as it previously did)

As it's flaky on *simplifier pass* branch, but not on *main* (I've never seen that failure on *main*), which suggests that there is actually something wrong with `matrix_01_transpose` integration test now. So, we definitely need to look at it anyway. That's why I commented it out for now.

**Comment by gxyd** [comment]
> Can we merge changes related to the CMakeLists.txt file in a separate PR resolving all the conflicts in the way?

Are you suggesting we do that for when merging *main* into *simplifier pass*, maybe for later merges? Or for this one as well?

**Comment by gxyd** [comment]
Though the conflicts I resolved this time only pertained to `.github/workflows/CI.yml`, none of the conflict was in `integration_tests/CMakeLists.txt`

**Comment by kmr-srbh** [comment]
> Are you suggesting we do that for when merging _main_ into _simplifier pass_, maybe for later merges? Or for this one as well?

Ah, I suggested that for only this time. I faced quite some conflicts related to the `llvm_17` tag in my recent PRs. I see that this branch cannot be rebased due to conflicts. I suspect this change, it maybe something else too.

**Comment by gxyd** [comment]
>  I see that this branch cannot be rebased due to conflicts

I tried locally to merge this branch into *simplifier pass*, and works just fine, and then the merging *simplifier pass* into *main*, which also works without any conflicts (all done locally). I can proceed with doing this.

But if you don't like it doing it this way, maybe you can create a separate PR and we can go ahead with that, instead of the changes I made here? (I've no problem with that)

**Comment by gxyd** [comment]
I'm sorry, I think I'm going to merge this now, but going forward maybe you can help with merging *main* into *simplifier pass*?

**Comment by kmr-srbh** [comment]
> I'm sorry, I think I'm going to merge this now, but going forward maybe you can help with merging _main_ into _simplifier pass_?

Thank you! :) We can always divide the effort and do it alternatively. Anything that works. We may merge `main` whenever we have an important change or a burst of commits. Thoughts?

**Comment by gxyd** [comment]
> > I'm sorry, I think I'm going to merge this now, but going forward maybe you can help with merging _main_ into _simplifier pass_?
> 
> Thank you! :) We can always divide the effort and do it alternatively. Anything that works. We may merge `main` whenever we have an important change or a burst of commits. Thoughts?

Yes, this time, I actually needed some commits, which were pushed into *main* branch. Definitely, we can work together on that part as well.

**Pull request merged**
