### PR TITLE
Feat: Enable to register logo image on Jupyter Lab launcher page

### PR DESCRIPTION
**Pull request by eunos-1128**
#4303

I added lFortran logo file to the kernel directory on installation.

It resulted in lFortran Logo shown like below.

image

### CODE REVIEW

**Comment by certik** [comment]
Awesome, thanks for the PR! After CI passes, we can merge it.

**Comment by certik** [comment]
Thanks! Do you know why the logo svg file in this PR is rectangular instead of square? Is it how it was, or did you have to make it rectangular to work?

**Comment by eunos-1128** [comment]
@certik 

I'm not sure of that.

I've just copied `doc/src/_static/img/lfortran-logo.svg` to have it as `share/jupyter/kernels/fortran/lfortran-logo.svg`.

You would like to the ratio?

**Comment by certik** [comment]
I just used GitHub, this is what I can see there:

image

**Review by certik — APPROVED** [review]
I think that this is fine, thanks!

**Comment by eunos-1128** [comment]
Thank you for merging this PR.

By the way, this is the image I see on Github

image

**Pull request merged**
