### PR TITLE
IntrinsicFuncRegistry: Refactor array intrinsics

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This PR refactors and removes the duplicated code for `Sum`, `Product`, `MaxVal` array intrinsic functions. This helps in better code maintainability.

In this PR, we define a common `ArrIntrinsic` namespace with the common functions defined inside this namespace. The functions in the namespaces `Sum`, `Product`, `MaxVal` reuse the `ArrIntrinsic` functions.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@certik I think the PR https://github.com/lfortran/lfortran/pull/1916 is related. I suggest we merge one and rebase the other. I think any PR can be merged and the other rebased.

**Comment by certik** [comment]
I think we should split `IntrinsicFunction` into `IntrinsicScalarFunction` (and possibly even introduce a node for Elemental; for now it would be implicit in the types of the arguments as it is now) and `IntrinsicArrayFunction`, since the two have different implementations. CC @czgdp1807

**Review by certik — APPROVED** [review]
I think that this is good, thanks!

This is towards simplifying how we construct these ASR implementations. We need to do a few more of these. :)

**Comment by czgdp1807** [comment]
I would recommend not to merge it until physical types aren’t in. I will complete the sync for physical types tomorrow.

**Comment by certik** [comment]
@czgdp1807 I forgot about your PR, sorry about that. Yes, go ahead and finish it on Monday, we can wait 1 day. The physical types are the highest priority.

**Comment by certik** [comment]
The physical types PR is now merged. @Shaikh-Ubaid do you mind rebasing this PR on top of the latest master?

**Comment by Shaikh-Ubaid** [comment]
Adding this PR to auto-merge as it seems approved.

**Review by certik — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
