### PR TITLE
Feat: Multiple Headed DoConcurrentLoop: Update of each loop variables

### PR DESCRIPTION
**Pull request by adit4443ya**
This PR aims to correctly update the loop variables for each head of DoConcurrentLoop,  continuing #5542 and hence moving towards #4900 and #4818 completion

### CODE REVIEW

**Comment by certik** [comment]
Is the idea here that we are flattening the nested parallel loops?

**Comment by adit4443ya** [comment]
> Is the idea here that we are flattening the nested parallel loops?

Yeah we can say that 
As we are representing collapse with multiple headed doconcurrent loops

**Review by certik — APPROVED** [review]
I think that this is fine.

**Comment by adit4443ya** [comment]
> The code can be further improved as needed, I think it's good to merge.

If this gets merged then both issues 
- Support multi control statement inside DoConcurrentLoop #4900
- Implementation of collapse() clause for OpenMp support #4818
 are resolved as the main aim is to have properly functioning multiple headed doconcurrent loop

**Comment by certik** [comment]
We should add more thorough tests, such as assigning some value to a multidimensional array and such, which might reveal bugs that need to be fixed. But the initial implementation is done, thank you!

**Comment by adit4443ya** [comment]
Yeah I will look at it !! And will report bugs and resolve them right away if there comes any

**Comment by adit4443ya** [comment]
> We should add more thorough tests, such as assigning some value to a multidimensional array and such, which might reveal bugs that need to be fixed. But the initial implementation is done, thank you!
> 
> For example I noticed without `--openmp` it still fails, but it shouldn't. We need to properly implement `DoConcurrent` using nested regular (serial) loops without `--openmp`.



This might be because in the 'do_loop.cpp' we are replacing doconcurrent with do loops and do loops only have one head and hence it is failing..

**Comment by adit4443ya** [comment]
> We should add more thorough tests, such as assigning some value to a multidimensional array and such, which might reveal bugs that need to be fixed. But the initial implementation is done, thank you!
> 
> For example I noticed without `--openmp` it still fails, but it shouldn't. We need to properly implement `DoConcurrent` using nested regular (serial) loops without `--openmp`.

PR #5586

**Comment by certik** [comment]
Thanks!

**Review by Pranavchiku — COMMENTED** [review]
Thanks for the PR! Looks good to me.

**Pull request merged**
