### PR TITLE
fix: Spread error for Scalar Source in Spread function

### LINKED ISSUE #4801: Spread intrinsic raises semantic error for scalar first argument
## Minimal reproducible example

```f90

PROGRAM test_spread
  INTEGER :: a = 1
  WRITE(*,*) SPREAD(A, 1, 2)
END PROGRAM
```

the above fortran program, taken from https://gcc.gnu.org/onlinedocs/gfortran/SPREAD.html. On compilation with LFortran raises the below error:
```bash
semantic error: The argument `source` in `spread` must be of type Array
   --> test.f90:280:23
    |
280 |     WRITE(*,*) SPREAD(A, 1, 2)
    |                       ^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

I think this issue is also needed for compilation of `IO` of `stdlib`, see: https://github.com/lfortran/lfortran/issues/3406#issue-2133452997

### PR DESCRIPTION
**Pull request by jinangshah21**
Fixes #4801.
I have Added more tests in `intrinsics_288.f90` (which is integration test for spread function).

### CODE REVIEW

**Comment by jinangshah21** [comment]
In 
```
Program test_spread
integer :: a = 1
Write(*,*) SPREAD(a, 1, 2)
end Program
```
Here Fortran Backend gives 2D array and GFortran gives 1D array for above Spread function.

**Comment by certik** [comment]
Let's do what GFortran does.

**Comment by jinangshah21** [comment]
I have done what GFortran do. But then Fortran Backend CI Fails.

**Comment by certik** [comment]
The Fortran backend needs to be improved. It shouldn't be hard.

**Comment by Pranavchiku** [comment]
You can do it in `asr_to_fortran` file.

**Comment by certik** [comment]
To fix the Fortran printer, here is a start:
```diff
--- a/src/libasr/codegen/asr_to_fortran.cpp
+++ b/src/libasr/codegen/asr_to_fortran.cpp
@@ -1345,6 +1345,7 @@ public:
         std::string out;
         std::string intrinsic_func_name = ASRUtils::get_array_intrinsic_name(static_cast<int64_t>(x.m_arr_intrinsic_id));
         if(intrinsic_func_name == "DotProduct") intrinsic_func_name = "dot_product";
+        if (intrinsic_func_name == "Spread") { /* Special case it here */ }
         visit_IntrinsicArrayFunction_helper(out, intrinsic_func_name, x);
     }
```

**Comment by jinangshah21** [comment]
Here in `asr_to_fortran` I have a `ArrayPhysicalCast` node, how can we convert it to `IntegerConstant` if array is having only one element?

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
```diff
diff --git a/src/libasr/pass/intrinsic_array_function_registry.h b/src/libasr/pass/intrinsic_array_function_registry.h
index ea8c3d860..30789826c 100644
--- a/src/libasr/pass/intrinsic_array_function_registry.h
+++ b/src/libasr/pass/intrinsic_array_function_registry.h
@@ -1816,6 +1816,7 @@ namespace Spread {
         ASR::ttype_t *ret_type = expr_type(source);
         ASRBuilder b(al, loc);
 
+        int overload_id = 2;
         if(ASR::is_a<ASR::Integer_t>(*type_source) || ASR::is_a<ASR::Real_t>(*type_source) || 
             ASR::is_a<ASR::Character_t>(*type_source) || ASR::is_a<ASR::Logical_t>(*type_source) ){
             // Case : When Scalar is passed as source in Spread() 
@@ -1826,6 +1827,7 @@ namespace Spread {
             source = EXPR(ASRUtils::make_ArrayConstructor_t_util(al, loc,m_eles.p, 
                           m_eles.n, fixed_size_type, ASR::arraystorageType::ColMajor));
             type_source = ASRUtils::expr_type(source);
+            overload_id = -1;
         }
 
         if ( !is_array(type_source) ) {
@@ -1843,7 +1845,6 @@ namespace Spread {
         ASR::dimension_t* source_dims = nullptr;
         int source_rank = extract_dimensions_from_ttype(type_source, source_dims);
         ASRUtils::require_impl(source_rank > 0, "The argument `source` in `spread` must be of rank > 0", source->base.loc, diag);
-        int overload_id = 2;
         int dim1 = ASR::down_cast<ASR::IntegerConstant_t>(ASRUtils::expr_value(args[1]))->m_n;
         if( is_scalar ){
             Vec<ASR::dimension_t> result_dims; result_dims.reserve(al, 1);
```

And use this `overload_id` to identify that it is a scalar and passed as an Array by code changes

**Review by Pranavchiku — APPROVED** [review]
awesome, LGTM!

**Pull request merged**
