### PR TITLE
[CI] Test third party applications with LLVM 17

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
I have disabled fastGPT and stdlib for llvm 17.

**Review by certik — APPROVED** [review]
This looks good. I rebased just in case. The 3rd party tests actually run fast (less than 10 minutes), so let's test LLVM 11 and 17 on linux/mac, as is done in this PR. 

Once this is merged, we can update it to LLVM 11 and 19 only. That will do.

Later we probably also want to take some fast subset of 3rd party tests and just run them as part of the LLVM 10-19 tests themselves (linux only).

**Comment by certik** [comment]
If everything passes, I will force merge this and then update the "required" tests.

**Comment by certik** [comment]
The tests changed in this PR as well as LLVM 17 tests all work, so I merged it.

**Pull request merged**
