### PR TITLE
Fix Incorrect handling of statements after return in entry function

### LINKED ISSUE #2690: [SciPy][cdflib]: TestCephes::test_bdtrin goes into infinte loop
> test_basic.py

```python
    def test_bdtrin(self):
        assert_equal(cephes.bdtrin(1,0,1),5.0)
```

> Responsible file

`scipy/special/cdflib/cdfbin.f`

```fortran
      SUBROUTINE cdfbin(which,p,q,s,xn,pr,ompr,status,bound)
C**********************************************************************
C
C      SUBROUTINE CDFBIN ( WHICH, P, Q, S, XN, PR, OMPR, STATUS, BOUND )
C               Cumulative Distribution Function
C                         BINomial distribution
C
C
C                              Function
C
```

The code goes into infinite loop here, function `dinvr` should perform `status=0` (status=0 implies calculation is correct) but it is not. Hence, the trouble lies in `scipy/special/cdflib/dinvr.f`

```fortran
  410     IF (.NOT. (status.EQ.1)) GO TO 440
          CALL cumbin(s,xn,pr,ompr,cum,ccum)
          IF (.NOT. (qporq)) GO TO 420
          fx = cum - p
          GO TO 430

  420     fx = ccum - q
  430     CALL dinvr(status,xn,fx,qleft,qhi)
          GO TO 410
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes https://github.com/lfortran/lfortran/issues/2740. Fixes #2690.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
With this PR we get all tests passing for `cdflib` without any divergence. 

One test fail, but it fails both for GFortran and LFortran


> GFortran


```console
============================================== FAILURES ==============================================
_______________________________________ TestCephes.test_gdtrib _______________________________________
scipy/special/tests/test_basic.py:419: in test_gdtrib
    assert_equal(cephes.gdtrib(1,0,1),5.0)
E   AssertionError: 
E   Items are not equal:
E    ACTUAL: 394.999998025
E    DESIRED: 5.0
        self       = <scipy.special.tests.test_basic.TestCephes object at 0x11d47c050>
====================================== short test summary info =======================================
FAILED scipy/special/tests/test_basic.py::TestCephes::test_gdtrib - AssertionError: 
========= 1 failed, 3110 passed, 53 skipped, 184 deselected, 43 xfailed, 2 xpassed in 6.92s ==========
```


> LFortran

```console
============================================================== FAILURES ===============================================================
_______________________________________________________ TestCephes.test_gdtrib ________________________________________________________
scipy/special/tests/test_basic.py:419: in test_gdtrib
    assert_equal(cephes.gdtrib(1,0,1),5.0)
E   AssertionError: 
E   Items are not equal:
E    ACTUAL: 394.999998025
E    DESIRED: 5.0
        self       = <scipy.special.tests.test_basic.TestCephes object at 0x11c3bb690>
======================================================= short test summary info =======================================================
FAILED scipy/special/tests/test_basic.py::TestCephes::test_gdtrib - AssertionError: 
========================== 1 failed, 3110 passed, 53 skipped, 184 deselected, 43 xfailed, 2 xpassed in 7.52s ==========================
```

**Comment by certik** [comment]
How can a test fail with GFortran? Does SciPy have a failing test in their master?

**Review by certik — APPROVED** [review]

**Comment by Pranavchiku** [comment]
> How can a test fail with GFortran? Does SciPy have a failing test in their master?

That might be because of a small change present somewhere on the old branch. I created a new branch, performed a clean build, everything works perfectly.

**Comment by Pranavchiku** [comment]
Actually, we have entire `scipy.special.*` working with LFortran :)

**Pull request merged**
