### PR TITLE
CI: test `scipy/special/cdflib`

### PR DESCRIPTION
**Pull request by Pranavchiku**
With this we have 6 / 18 packages ( 1/3rd of SciPy ) compiled and being tested at our CI. More specifically, entire `scipy.special.*` that includes `amos`, `cdflib`, `specfun`, `mach`, also, `minpack`, `fitpack` works with LFortran with no modification.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
I tested locally it works for me, let's wait and check if CI pass smoothly.

**Comment by certik** [comment]
CC @ilayn. When we started, it looks like there were 21 Fortran packages in SciPy. Now there are only 18. However we can now compile 6.

I think it's time to start testing LFortran with the 6 packages that work, so that we can iterate and improve the various interface issues, from the meson build system, to LFortran command line options, and ensure LFortran becomes a reliable tool that just works on all platforms and one can depend on it. 

@ilayn, what are some things you would be interested in? I know one of your wishes is to translate to another language, right now only our LLVM backend works for SciPy, however our other backends, such as C, are not far behind, but would still require some work. But what we could try now is maybe WASM compilation via LLVM? Or do you have some issues on Windows with gfortran+MSVC (so far we only tested SciPy on Linux/macOS, likely we probably have some bugs on Windows, but they are most likely integration issues that many people can help us fix). Or if you have some other ideas, please let us know.

**Comment by rgommers** [comment]
Very nice progress @certik and @Pranavchiku!

> But what we could try now is maybe WASM compilation via LLVM? Or do you have some issues on Windows with gfortran+MSVC (so far we only tested SciPy on Linux/macOS, likely we probably have some bugs on Windows, but they are most likely integration issues that many people can help us fix). Or if you have some other ideas, please let us know.

Yes, we certainly do have Windows issues. We finally got a SciPy build on Windows in conda-forge working with the brand-new Flang 17, and that required a bunch of worarounds. MSVC + gfortran is not a thing, it's either "all Mingw-w64" or MSVC + Flang/ifort, or "all Intel". Or maybe now "Clang-cl/MSVC + LFortran".

Either Windows or WASM seems like diving in at the deep end to me though. Or is that orthogonal to further progress on Linux/macOS? I don't have a strong preference; for SciPy contributors Windows is probably more critical, but making the life of folks working on Pyodide/Emscripten better is equally valuable I'd say.

**Comment by ilayn** [comment]
Sorry for the delay. Somehow I thought this is a SciPy issue and overlooked. That's great progress @certik and @Pranavchiku. It must have been a challenging year to iron out all the wrinkles. Congratulations for the milestone.

> CC @ilayn. When we started, it looks like there were 21 Fortran packages in SciPy. Now there are only 18. However we can now compile 6.

Yes you can take 3 more out of that 18 as ARPACK, PROPACK and SLSQP is also going away; as soon as I can spare some more time for finishing up the testing. I'd like to see `scipy.optimize` F77-free if I could ever get to that point. But as I am running out of low-hanging-fruits not sure if I would ever accomplish that. 

The unicorn case for me would be only needing a fortran compiler just to deal with BLAS/LAPACK and no other F77 code in SciPy. Hence probably that's a good place to start; that is compiling reference BLAS/LAPACK and getting a decent performance out of it in case folks want to link to it instead of OpenBLAS/MKL.

We also have a very active  `special` overhaul going on specifically https://github.com/scipy/scipy/issues/19404 and also some offline communications for F77 rewrites. I'd ping @steppi and @ev-br for the specifics and the prioritization. 

> @ilayn, what are some things you would be interested in?

Nothing I can think of really. Like we discussed a few times, it's the interplay between Python/Fortran and also the packaging to Windows is the major issue. Other than that, I think we can live with "all Mingw-w64" workflow for now. Not ideal but certainly serving us well so far.

For the F77 conversion, the parts that were rubbing me the wrong way, I started to rewrite myself. Not an epsilon of fun but getting somewhere slowly. We also started to notice the open source alternatives for the dusty F77 code in https://github.com/scipy/scipy/issues/18566 For example, AMOS in particular https://github.com/scipy/scipy/issues/19079#issuecomment-1682108384

Hence, I'd say if PRIMA manages to get Python bindings or we figure out how things work with "modern" Fortran without `f2py` then probably that would be the first use case for LFortran but others might have more candidates that I did not know about.

**Comment by certik** [comment]
Awesome, thank you @rgommers and @ilayn for the feedback. We are here to help, and our main motivation is to make LFortran useful and get more users. Both of you would be excellent users and collaborators.

Our nearest term focus is to just compile all of SciPy, on Linux/macOS. We have progressed since last week, right now we are at 9 / 18, so 50%. If you cut ARPACK, PROPACK and SLSQP, then we got lucky and we are at 9 / 15, so at 60%. @Pranavchiku, @HarshitaKalani skip those three packages. I say let us compile all of SciPy since we are this far.

@ilayn by when do you expect SciPy to not have any Fortran at all? I think at our rate, we should be able to compile all of SciPy by next summer almost for sure, and possibly a lot faster, depending on how things go. We also have C and C++ backends, that we can fix up to transpile some of the old Fortran packages, if it is useful.

Both the Windows support and WASM is orthogonal to our progress on the Linux/macOS, so we can start with what we have already. However, especially the Windows support can take a lot of effort, so we want to only do if it would be helpful to you. It looks like you already have a path forward on Windows with Flang, so it's not as critical anymore.  So maybe the WASM and better Python wrappers/interoperability and PRIMA might be higher priority.

I am hoping that an outside contributor gets interested in these issues, so that we can focus on just raw compilation on Linux/macOS.

**Comment by ilayn** [comment]
> when do you expect SciPy to not have any Fortran at all? 

Probably we will always have Fortran simply because BLAS/LAPACK. But if you mean actual code written in F77 that we vendor, that's probably this year depending on grant applications being accepted. Then more people would be replacing F77 code instead of just me doing it. 

> We also have C and C++ backends, that we can fix up to transpile some of the old Fortran packages, if it is useful.

I think some folks over SciPy might be interested in that. I know https://github.com/stevengj/nlopt/ did partially that and hand-cleaned the resulting C++ (don't know which tool they used). 

> However, especially the Windows support can take a lot of effort, so we want to only do if it would be helpful to you. 

Indeed for us it's not that important however if you want LFortran to be widely adopted, you can't omit it, in my opinion. People tend to overlook the fact that a big portion of Rust or Python's popularity and adoption is because they work on Windows natively, no hoop jumps needed. I would have never picked up python if it needed mingw or cygwin or whatever it was needed back in the day. But I'll leave it to your judgement. 

>  So maybe the WASM and better Python wrappers/interoperability and PRIMA might be higher priority.

I would think so but again, these are just mild suggestions. I wouldn't know what the killer use-case should be.

Finally, since you reminded me let me also add `cdflib` to those three that you cut. Because I just checked it and I think it's small chunks of a lot of functions so easy to convert right away.

**Comment by certik** [comment]
@ilayn thanks. I didn't realize Fortran might be so short lived in SciPy. It's been there for 22 years, so I assumed it would be there for a few more years. If the plan is to not vendor any Fortran at all in SciPy within a year from now, then it probably does not make sense for us to invest into the SciPy integration (such as build system and other issues), since that will not be relevant in a year from now, but only treat it as a vehicle to ensure LFortran can compile such code, since similar code is present in other projects.

Yes, Windows support is extremely important, and we test every commit with Windows, but we don't have the SciPy tests setup on Windows, since it took us quite some time to at least get it working on Linux/macOS.

**Comment by rgommers** [comment]
> I didn't realize Fortran might be so short lived in SciPy. It's been there for 22 years, so I assumed it would be there for a few more years. If the plan is to not vendor any Fortran at all in SciPy within a year from now,

Given the current pace of changes in SciPy, I don't think that the above assessment from @ilayn is likely to materialize in that timeline. We would like to modernize the SciPy code base, and are preparing a grant application to help accelerate that. However, it isn't even submitted yet and in case it does get accepted, work on that won't start before June'24. And we all know grant applications are a bit of a lottery.

Right now we went from 21 to 18 modules. I think if @ilayn's work lands to get rid of both PROPACK and ARPACK, that's already an impressive achievement. But going from ~15 to ~2 is still a long way to go. And it's all volunteer effort, so the timeline of that, and likelihood of achieving all goals, is very hard to predict. I'd encourage you to continue on the current track @certik. 

> We also have a very active `special` overhaul going on specifically [scipy/scipy#19404](https://github.com/scipy/scipy/issues/19404) and also some offline communications for F77 rewrites. 

Right now that is focused on Cython -> C++ for better reusability. It may touch on F77 code for the same reasons too. The main target is the top ~50 or so functions right now though, and there's ~300 functions in total. So the other 250 won't disappear overnight - there's a very long tail there, and a lot of it is Fortran code.

**Comment by Pranavchiku** [comment]
> But going from ~15 to ~2 is still a long way to go. And it's all volunteer effort, so the timeline of that, and likelihood of achieving all goals, is very hard to predict. I'd encourage you to continue on the current track @certik.


Yes, I agree, we should try to compile as many packages as possible. Talking about prioritising the packages, as stated by @ilayn let's see how far are we to get `BLAS/LAPACK` compiled, I think we have an issue open at https://github.com/lfortran/lfortran/issues/1232. We can work on other packages simultaneously, we are short of 6 packages only ( not considering ARPACK, PROPACK and SLSQP ) , the end goal is visible let's push and try to get it done.

**Comment by ilayn** [comment]
By the way, some of the modules are just too big to rewrite such as COBYLA (hence my remark about PRIMA) so replacing them are also inside that plan. Hence anything that is definitely better than existing ones are quite welcome additions. I have to repeat this very often, this is not a crusade against fortran, but dormant and unmaintained F77 code.

**Comment by certik** [comment]
> I have to repeat this very often, this is not a crusade against fortran, but dormant and unmaintained F77 code.

Of course. I don't like maintaining old F77 code either! I also have to repeat this often: nobody on the LFortran team is being offended. 

Our goal is to deliver a nice modern compiler, simple and lean, that is a joy to use, fast compilation, fast runtime, good language interoperability, good errors, runs in the browser and all platforms, interactive, many backends, etc. We want to get to the point that people are eager to find excuses to use LFortran. :) A robust versatile tool that just works and gets out of your way. We are not there yet, but making good strides.

We will finish our job with the current SciPy, that way we are done. Either SciPy or somebody else will use it. I think you are right, we should get Lapack and PRIMA compiling next.

**Comment by ilayn** [comment]
Just want to leave it for future readers, or folks who want to write the un-gotofied version of `cdflib` again in newer Fortran; , the code is converted and we are trying to fix the plumbing to integrate it in https://github.com/scipy/scipy/pull/19560 (currently written in Cython)

It took 2 weeks instead of 1 week that I was anticipating due to many new things in Fortran I had to learn and not being a special function expert. So the plan above maybe indeed seems a bit too optimistic. However, the other libraries have new implementations in other languages, so that might play a big role in covering distance in relatively short time.

**Comment by zaikunzhang** [comment]
Thank @certik and the team very much for these important and nontrivial efforts, and warm congratulations on the impressive advancements!

Since the [PRIMA](http://libprima.net) and its Python binding have been mentioned a few times, I would like to mention that we are making good progress, thanks to @nbelakovski, @jschueller, @HaoZeke (from the SciPy community),  and many others (especially those from the SciPy community):

https://github.com/libprima/prima/issues/112

I look forward to seeing PRIMA integrated into SciPy and compiled by LFortran. I think it will be a milestone for many of us. 

Thanks to all!

**Comment by certik** [comment]
Thank you @zaikunzhang for working on PRIMA. We will get it to compile as well with LFortran, it will indeed be a big milestone for us.

**Pull request merged**
