### PR TITLE
Fix importing modules in interactive mode

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/1588.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Example:
```fortran
$ cat a.f90 
module funcmod
implicit none
contains
function add(x,y)
real :: x, y
real :: add
add = x+y
end function add
function subtract(x,y)
real :: x, y
real :: subtract
subtract = x-y
end function subtract
end module funcmod
```
Compile using:
```bash
$ lfortran -c a.f90 -o a.o
```
and import using:
```bash
$ lfortran                         
Interactive Fortran. Experimental prototype, not ready for end users.
LFortran version: 0.19.0-7-g893b67af7
  * Use Ctrl-D to exit
  * Use Enter to submit
  * Use Alt-Enter or Ctrl-N to make a new line
    - Editing (Keys: Left, Right, Home, End, Backspace, Delete)
    - History (Keys: Up, Down)
>>> use funcmod, only : add, subtract                                                                        1,34  ]
>>> add(2.0, 5.0)                                                                                            1,14  ]
7
>>> subtract(2.0, 5.0)                                                                                       1,19  ]
-3
>>> 
```

**Comment by certik** [comment]
Awesome, thanks!

Can you please also add a test for this? It would go here: https://github.com/lfortran/lfortran/blob/a0c531829220eb37f3bcb8bffa6f90e267eeee50/src/lfortran/tests/test_llvm.cpp#L587, at the end of the "FortranEvaluator" section. If it is not easy, because we can't input a full module as a prompt yet, then we can add a test for this later.

**Comment by certik** [comment]
It looks like it is possible:
```
>>> module A                                                                   ┐
... integer :: i                                                               │
... end module                                                           3,11  ┘
>>> use A, only: i                                                       1,15  ]
>>> i = 5                                                                1,6   ]
```
so just input the module as a cell, and the "use" it.

**Review by certik — APPROVED** [review]
I think that this looks good. If tests pass, this can be merged.

**Pull request merged**
