### PR TITLE
Implement 'F' formatting for float values

### PR DESCRIPTION
**Pull request by gptsarthak**
Fixes https://github.com/lfortran/lfortran/issues/2325
```fortran
PROGRAM TEST
    DOUBLE PRECISION :: R,S,T
    R = 12345678
    S = 23.5678
    T = 0.345678
    PRINT '( F13.3,1X,F9.6,1X, F0.2 )', R, S, T
    PRINT '( F13.3,1X,F9.6,1X, F0.2 )', -R, -S, -T
END 
```
```console
 12345678.000 23.567800 .35
-12345678.000 ********* -.35
```
I might have missed some corner cases, let me know if this is working as expected with fastGPT

### CODE REVIEW

**Comment by certik** [comment]
I am getting some warnings on macOS:
```
/Users/ondrej/repos/lfortran/lfortran/src/libasr/runtime/lfortran_intrinsics.c:196:29: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
    sprintf(int_str, "%ld", integer_part);
                      ~~~   ^~~~~~~~~~~~
                      %lld
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/secure/_stdio.h:47:56:/Users/ondrej/repos/lfortran/lfortran/src/libasr/runtime/lfortran_intrinsics.c:196:29: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
     sprintf(int_str, "%ld", integer_part);
                      ~~~   ^~~~~~~~~~~~note
: expanded from macro 'sprintf'                      %lld

/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)                                                       ^~~~~~~~~~~

                                                       ^~~~~~~~~~~
```

**Comment by certik** [comment]
A test seems to differ:
```console
$ lfortran format_04.f90 
ok b
okb
Success!
          Hello World!
danc  in themoon
ab  cdef  ghi  jkl  qwerty 12
123     00456
012345  ***
  0.12D+03  -0.123457D+03  0.12D+02  *******
 -1.23D+02   12.34568D+01 -1.23D+01   1.23D+02
 -0.01E+04   0.001235E+05 -1.23E+01   1.23E+02
  1  2  3  4  5  6  7  8  9 10 11 12
  1  2  3  4 hello
  5  6  7  8 hello
  9 10 11 12 hello
 13 14
12345
-12345
0.123456001D+3 0.1D+3 0.12D+2
-0.123456001D+3 -0.1D+3 -0.12D+2
Hello
$ echo $?
5
$ gfortran format_04.f90 && ./a.out 
 okb
okb
Success!
          Hello World!
danc  in themoon
ab  cdef  ghi  jkl  qwerty 12
123     00456
012345  ***
  0.12D+03  -0.123457D+03  0.12D+02  *******
 -1.23D+02   12.34568D+01 -1.23D+01   1.23D+02
 -0.01E+04   0.001235E+05 -1.23E+01   1.23E+02
  1  2  3  4  5  6  7  8  9 10 11 12
  1  2  3  4 hello
  5  6  7  8 hello
  9 10 11 12 hello
 13 14
12345
-12345
0.123456001D+3 0.1D+3 0.12D+2
-0.123456001D+3 -0.1D+3 -0.12D+2
Hello
 12345678.000 23.567801 .35
-12345678.000 ********* -.35
$ echo $?
0
```

**Comment by certik** [comment]
fastGPT seems to segfault probably for the same reason:
```
$ ./gpt2 
Loading the model...
zsh: trace trap  ./gpt2
```

**Comment by gptsarthak** [comment]
> argument has type 'int64_t' (aka 'long long') [-Wformat]

Thats weird, clangd as well as compilation of my pc gives me the opposite warning when i use ```%lld``` and says that ```‘int64_t’ {aka ‘long int’}```.
```console
/home/sarthak/lfortran/src/libasr/runtime/lfortran_intrinsics.c:196:26: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
  196 |     sprintf(int_str, "%lld", integer_part);
      |                       ~~~^   ~~~~~~~~~~~~
      |                          |   |
      |                          |   int64_t {aka long int}
      |                          long long int
      |                       %ld
```
Maybe i should just use ```long``` 
> A test seems to segfault:

It does not segfault on my linux system. How should I find whats causing it in macos?

**Comment by certik** [comment]
The `lld` vs `ld` is a common issue, I believe one has to use some ifdefs and have different handling on each system. It's annoying. Let's see if your fix works.

Regarding the segfault, we'll have to debug it. I am guessing there is a bug in the C code of the floating point handling introduced in this PR.

**Comment by gptsarthak** [comment]
MacOS CI passes successfully now

**Review by certik — APPROVED** [review]
Great job @gptsarthak !!

It works for fastGPT. Merging. Thank you.

**Pull request merged**
