### PR TITLE
Add a compiler option to enable mangling of bindc abi type functions

### PR DESCRIPTION
**Pull request by Pranavchiku**
Refer: https://github.com/lfortran/lfortran/pull/2263#issuecomment-1701441308

### CODE REVIEW

**Comment by Pranavchiku** [comment]
I locally tested [minpack](https://github.com/certik/scipy/tree/minpack1) with this PR, it works perfect. 
```
git checkout -t ondrej/minpack1
git checkout 9ee9208fc52ccc04d3128132888c0798e7ae677a
```

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
@Pranavchiku beautiful!

This PR is not needed for specfun? I thought there you also had to manually mangle.

**Comment by Pranavchiku** [comment]
> This PR is not needed for specfun? 

No, specfun has only one file, and it works perfectly. The trouble occurs when we have a subroutine defined in one file and calles in other. In this case, the subroutine call creates an implicit interface with bindc which causes trouble.

**Comment by certik** [comment]
Got it, perfect!

**Pull request merged**
