### PR TITLE
ASR -> Fortran: Check whether the variable is allocated before deallocating

### LINKED ISSUE #4053: Check if variable is allocated using the allocated intrinsic before using `deallocate`
```fortran
program intrinsic_122
    implicit none
    integer(4), dimension(2, 3) :: a
    integer(4), dimension(3, 2) :: b
    integer(4), dimension(2) :: c
    integer(4) :: d
    real(4), dimension(:, :), allocatable :: e
    a = reshape([1, 2, 3, 4, 5, 6], [2, 3])
    b = reshape([10, 20, 30, 40, 50, 60], [3, 2])
    print *, rank(1)
    if (rank(1) /= 0) then
        error stop
    end if
    print *, rank([.true., .false.])
    if (rank([.true., .false.]) /= 1) then
        error stop
    end if
    print *, rank(a)
    if (rank(a) /= 2) then
        error stop
    end if
    print *, rank(b)
    if (rank(b) /= 2) then
        error stop
    end if
    print *, rank(c)
    if (rank(c) /= 1) then
        error stop
    end if
    print *, rank(d)
    if (rank(d) /= 0) then
        error stop
    end if
    print *, rank(e)
    if (rank(e) /= 2) then
        error stop
    end if
    deallocate(e) ! Implicit deallocate
    end program intrinsic_122
```
```console
$ gfortran b.f90 && ./a.out
           0
           1
           2
           2
           1
           0
           2
At line 38 of file b.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'e'

Error termination. Backtrace:
#0  0x7bac6ae23960 in ???
#1  0x7bac6ae244d9 in ???
#2  0x7bac6ae24ad6 in ???
#3  0x56438461252b in ???
#4  0x564384612581 in ???
#5  0x7bac6aa29d8f in __libc_start_call_main
        at ../sysdeps/nptl/libc_start_call_main.h:58
#6  0x7bac6aa29e3f in __libc_start_main_impl
        at ../csu/libc-start.c:392
#7  0x5643846120d4 in ???
#8  0xffffffffffffffff in ???
$ lfortran b.f90
0
1
2
2
1
0
2
```
The error occurs with GFortran because we are trying to deallocate an unallocated array e. In Fortran, attempting to deallocate an unallocated allocatable array results in a runtime error.
Before deallocating e, if we check if it is allocated using the allocated intrinsic function, then it works fine.

```fortran
program intrinsic_122
    implicit none
    integer(4), dimension(2, 3) :: a
    integer(4), dimension(3, 2) :: b
    integer(4), dimension(2) :: c
    integer(4) :: d
    real(4), dimension(:, :), allocatable :: e
    a = reshape([1, 2, 3, 4, 5, 6], [2, 3])
    b = reshape([10, 20, 30, 40, 50, 60], [3, 2])
    print *, rank(1)
    if (rank(1) /= 0) then
        error stop
    end if
    print *, rank([.true., .false.])
    if (rank([.true., .false.]) /= 1) then
        error stop
    end if
    print *, rank(a)
    if (rank(a) /= 2) then
        error stop
    end if
    print *, rank(b)
    if (rank(b) /= 2) then
        error stop
    end if
    print *, rank(c)
    if (rank(c) /= 1) then
        error stop
    end if
    print *, rank(d)
    if (rank(d) /= 0) then
        error stop
    end if
    print *, rank(e)
    if (rank(e) /= 2) then
        error stop
    end if
    if (allocated(e)) then
        deallocate(e) ! Implicit deallocate
    end if
end program intrinsic_122
```
The above code executes correctly.
```console
$ lfortran b.f90
0
1
2
2
1
0
2
$ gfortran b.f90 && ./a.out
           0
           1
           2
           2
           1
           0
           2
```
Note: the above program is generated with the following command
```console
$ lfortran integration_tests/intrinsics_122.f90 --show-fortran
```

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #4053 

```fortran
deallocate(x, y, z)
```
is converted to
```fortran
if (allocated(x)) then
    deallocate(x)
end if
if (allocated(y)) then
    deallocate(y)
end if
if (allocated(z)) then
    deallocate(z)
end if
```

### CODE REVIEW

**Comment by certik** [comment]
Let's add a test that failed previously but now works.

**Comment by kmr-srbh** [comment]
> Let's add a test that failed previously but now works.

@certik, none of the tests had failed previously despite of the changes in this PR and there is a catch here. GFortran throws an error when we try to deallocate a variable which was not allocated. We perform a check to see if the variable was previously allocated in the back-end. We deallocate the variable if it was allocated, but silently move ahead if it was not.

https://github.com/lfortran/lfortran/blob/3ba0a398dd0c932f4bc4167b4ff482a7380b01d9/src/libasr/codegen/asr_to_llvm.cpp#L1160-L1213

I think we should throw an error here.

**Comment by HarshitaKalani** [comment]
With these changes you can try to add the `fortran` label with intrinsics_122 test in CmakeLists.txt and then run the following command:
```
$ ./integration_tests/run_tests.py -b fortran
```

**Comment by kmr-srbh** [comment]
> With the changes in this PR, you can try to add the `fortran` label with intrinsics_122 test in CmakeLists.txt and then run the following command:
> 
> ```
> $ ./integration_tests/run_tests.py -b fortran
> ```

@HarshitaKalani this implementation is independent of #2763, right? If so, then we can add the tests and merge this. I am working on that issue and have posted questions there.

**Comment by HarshitaKalani** [comment]
Hey @kmr-srbh , rather that asking questions over suggestions, would you mind trying them first? That will really help you learn more.

**Comment by kmr-srbh** [comment]
@nikabot could you please confirm if this PR is independent of #2763? Is #2763 the chief issue whose fix will also resolve the issue linked with this PR? 

Let's wrap up this one if it is done.

**Pull request closed without merging**
