### PR TITLE
Sync `libasr` with LPython

### PR DESCRIPTION
**Pull request by czgdp1807**
@certik @Shaikh-Ubaid @lucifer1004 @konradha @Pranavchiku @Smit-create @Thirumalai-Shaktivel Please go through the diff and let me know if there's any change that got reverted. I will restore it. I will wait for an hour or so before I create sync PR in LPython repository. Thanks.

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
LGTM, Thank you!

**Review by konradha — APPROVED** [review]
I think this looks good as far as I can tell. Thanks!

**Review by Smit-create — APPROVED** [review]
LGTM, thanks

**Review by Pranavchiku — APPROVED** [review]
Looks good to me, Thanks :)

**Review by certik — APPROVED** [review]
I reviewed this carefully and I don't see any regressions. Thank you so much for syncing it, this was a lot of work!

Go ahead and polish the commits (or even squash) and merge.

**Pull request merged**
