### PR TITLE
Implement common blocks - 1

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
The following example in F77 style:
```fortran
        subroutine f()
        common / c1 / a, b, c
        integer a, b, c
        a = b
        b = 4
        end

        subroutine g()
        common / c1 / x, y, z
        integer x, y, z
        x = y
        y = 4
        end

        program common_01
        common / c1 / a, b, c
        integer a, b, c
        a = 1
        b = 2
        print *, a, b
        if (a /= 1) print *, "fail"
        if (b /= 2) print *, "fail"
        call f()
        print *, a, b
        if (a /= 2) print *, "fail"
        if (b /= 4) print *, "fail"

        a = 1
        b = 2
        print *, a, b
        if (a /= 1) print *, "fail"
        if (b /= 2) print *, "fail"
        call g()
        print *, a, b
        if (a /= 2) print *, "fail"
        if (b /= 4) print *, "fail"
        end
```
translates to C using f2c into:
```c
#include "f2c.h"

/* Common Block Declarations */

union {
    struct {
    integer a, b, c__;
    } _1;
    struct {
    integer x, y, z__;
    } _2;
} c1_;

#define c1_1 (c1_._1)
#define c1_2 (c1_._2)

/* Table of constant values */

static integer c__3 = 3;
static integer c__1 = 1;
static integer c__9 = 9;

/* Subroutine */ int f_(void)
{
    c1_1.a = c1_1.b;
    c1_1.b = 4;
    return 0;
} /* f_ */

/* Subroutine */ int g_(void)
{
    c1_2.x = c1_2.y;
    c1_2.y = 4;
    return 0;
} /* g_ */

/* Main program */ int MAIN__(void)
{
    /* Builtin functions */
    integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen), 
        e_wsle(void);

    /* Local variables */
    extern /* Subroutine */ int f_(void), g_(void);

    /* Fortran I/O blocks */
    static cilist io___1 = { 0, 6, 0, 0, 0 };
    ...


    c1_1.a = 1;
    c1_1.b = 2;
    s_wsle(&io___1);
    do_lio(&c__3, &c__1, (char *)&c1_1.a, (ftnlen)sizeof(integer));
    do_lio(&c__3, &c__1, (char *)&c1_1.b, (ftnlen)sizeof(integer));
    e_wsle();
    if (c1_1.a != 1) {
    s_wsle(&io___2);
    do_lio(&c__9, &c__1, "fail", (ftnlen)4);
    e_wsle();
    }
...
```

**Comment by certik** [comment]
There are a few options what to generate at the ASR level. Let's start bottom up. The following f77 code:
```fortran
        subroutine f()
        common / c1 / a, b, c
        integer a, b, c
        a = b
        b = 4
        end
```
Gives the following C code via f2c:
```c
struct {
    integer a, b, c__;
} c1_;

#define c1_1 c1_

/* Subroutine */ int f_(void)
{
    c1_1.a = c1_1.b;
    c1_1.b = 4;
    return 0;
} /* f_ */
```
The above C code generates the following LLVM code via Clang:
```llvm
%struct.anon = type { i32, i32, i32 }

@c1_ = common global %struct.anon zeroinitializer, align 4

; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @f_() #0 {
  %1 = load i32, i32* getelementptr inbounds (%struct.anon, %struct.anon* @c1_, i32 0, i32 1), align 4
  store i32 %1, i32* getelementptr inbounds (%struct.anon, %struct.anon* @c1_, i32 0, i32 0), align 4
  store i32 4, i32* getelementptr inbounds (%struct.anon, %struct.anon* @c1_, i32 0, i32 1), align 4
  ret i32 0
}
```
So it's a global structure, but it has this `common global` attribute. In the object file, it is the "C" symbol type:
```console
$ nm a.o 
000000000000000c C _c1_
0000000000000000 T _f_
0000000000000000 t ltmp0
0000000000000020 s ltmp1
```

**Comment by certik** [comment]
GFortran also produces the "common" symbols in object files. Clang with `-fno-common` will create just "global" symbols, but things will then fail at linking time:
```
$ clang -o x a.o b.o c.o $CONDA_PREFIX/lib/libf2c.a 
duplicate symbol '_c1_' in:
    a.o
    b.o
duplicate symbol '_c1_' in:
    a.o
    c.o
ld: 2 duplicate symbols for architecture arm64
```

**Comment by certik** [comment]
@czgdp1807 what do you think is the best way forward here? The common block is mostly needed for old codes such as in SciPy, where they compile each file individually to an object file and then create a shared library. One approach that will work is to use a global "union of structs" that is implemented in LLVM as a "common global" variable. Then as things get linked into a shared library, the linker allocates the storage correctly (just once).

It's a little fragile, but it should work and that's how gfortran and f2c also does it.

The alternative is to use a module, such as `_common_c1` (for the `c1` common block above). This will be clean and using our existing ASR features. The problem is that it will not work out of the box for the SciPy usage of compiling to o files and then linking them to a shared library, as we would have to then compile that "common module" (and all such modules for each common block), and link it. There can be a lot of common blocks and this would complicate the build system. What we could do is to have a special flag, and if passed, the LLVM backend would handle the "common module" differently, it would use the "common global" linkage. So in a way, we would use the existing ASR features, but we would have special handling of the common module in LLVM, to preserve the existing build system structure. However, there is another problem: the common module cannot be treated as a regular module (to be compiled to `.mod` file), because its contents is upgraded every time the common block is declared (it adds a new struct to the union, unless it is already there). So for each translation unit, we can maintain one common module per common block. But then when compiling to `.o` if the `--generate-object-code` is used, we need to take the common module and create the "common global" unions out of it, no `.mod` file generated. Then in another translation unit, we also construct a "common module", potentially different. And again implement it using "common global" LLVM linkage. If `--generate-object-code` is not used, then we can treat the "common module" as a regular module, everything should work, since we have access to the ASR of the whole program. I think this can work.

**Comment by czgdp1807** [comment]
> And again implement it using "common global" LLVM linkage.

I think this is happening in both the approaches. So how is having second approach better than the first one because eventually `common global` will be needed in both the approaches.

**Comment by certik** [comment]
Great improvement from @czgdp1807:
* each translation unit creates a unique common module for the common block `c1`, such as `file_a1_common_block_c1`, the file a2 will create `file_a2_common_block_c1` and so on.
* If `--generate-object-code` is passed, then each a1, a2 file just creates the proper "common global" LLVM symbol and that's it.
* If `--generate-object-code` is not passed, then each translation unit gets compiled into mod files (assuming just modules are used) and then when compiling the main program, all modules (including common modules) are loaded into ASR and we can implement ASR->ASR pass that identifies `file_a1_common_block_c1` and `file_a2_common_block_c1` and merges them into just one `common_block_c1`, and updates all references to it appropriately. This effectively implements the "common symbol" at the ASR level. Then compilation proceeds as usual and everything should just work.

**Comment by Pranavchiku** [comment]
@certik @czgdp1807 you can have a review. This PR adds a test and corresponding error message. 
I am planning to start by adding support to ASR first then will proceed to LLVM.

**Comment by Pranavchiku** [comment]
I checked into a few examples and came up across #1653. Looks like COMMON blocks are not parsed correctly to ASR and will have to make provisions for that as well. I have a logic for it ready, I will open a PR soon.

**Comment by certik** [comment]
This looks good, thanks! The comment https://github.com/lfortran/lfortran/pull/1260#issuecomment-1421289735 has the roadmap how to proceed.

**Pull request merged**
