### PR TITLE
CI: test LLVM compilation of `stdlib_stats_cov`

### PR DESCRIPTION
**Pull request by HarshitaKalani**
Fixes https://github.com/lfortran/lfortran/issues/3755
https://github.com/czgdp1807/stdlib/commits/lf-stats-cov
https://github.com/czgdp1807/stdlib/commits/lf19

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Have to cherry-picked the commits on top of `lf19` branch?

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
Please cherry-pick commits on top of `lf19` branch, put correct hash and then test.

**Comment by HarshitaKalani** [comment]
I'm sorry for the mistake. Can you please review it now?

**Review by Pranavchiku — APPROVED** [review]
No worries. Awesome job! I tested locally, everything works well.

**Pull request merged**
