### PR TITLE
Test references 

### PR DESCRIPTION
**Pull request by HarshitaKalani**
Related to #3179

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Yes, I am also getting these. I will wait for one more approval before merging this.

**Comment by certik** [comment]
Can you explain the context here? The main CI is not failing, so why are the test references changes needed? How is it that it does not affect the CI?

**Comment by Pranavchiku** [comment]
I am also wondering the same. On executing `./run_tests.py` the tests pass, but when I do `./run_tests.py -u`, references get updated.

```console
% git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   tests/reference/asr_json-modules_10-93cd62d.stdout
	modified:   tests/reference/ast-end_module_name-8436c0b.json
	modified:   tests/reference/ast-end_module_name-8436c0b.stderr
	modified:   tests/reference/ast-end_submodule_name-68b3188.json
	modified:   tests/reference/ast-end_submodule_name-68b3188.stderr

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by certik** [comment]
I closed this, it seems it's not needed anymore.

**Pull request closed without merging**
