### PR TITLE
Implementation of `procedure(fn) :: x` (IV)

### PR DESCRIPTION
**Pull request by certik**
Last commit has a TODO list how to fix:
```console
$ lfortran  procedure_01.f90     
code generation error: FunctionType not implemented
 --> procedure_01.f90:5:5 - 7:17
  |
5 |        integer function fn(n)
  |        ^^^^^^^^^^^^^^^^^^^^^^...
...
  |
7 |        end function
  | ...^^^^^^^^^^^^^^^^^ 
```
The ASR for this test is already correct (contains `type_declaration` correctly populated in `Variable`).

This should fix one bug. There might be more, we'll see.

### CODE REVIEW

**Comment by certik** [comment]
@czgdp1807 let me know if you see any issues so far with this PR series. I think this will lead to success.

**Comment by czgdp1807** [comment]
I read about `type_declaration` in other threads. So basically it just points to the symbol which declares the user defined type. For example it will point to the `Struct` which is being used as the type of current variable? If so then it makes sense. Just to make sure that I didn't miss anything, I would like to know if we are storing only names in types and not the symbols. 

P.S. Variable is not a type so its fine if it points to another symbols as it is already scope dependent. However types shouldn't be scope dependent (which happens if they point to a symbol).

**Comment by certik** [comment]
> So basically it just points to the symbol which declares the user defined type. For example it will point to the `Struct` which is being used as the type of current variable?

Yes.

> Just to make sure that I didn't miss anything, I would like to know if we are storing only names in types and not the symbols.

Actually we are not storing any names at all (and no symbols) in types. That's the beauty of this design. All the names and other data (all the various flags that we need to keep track of) is stored in the symbol (`Struct`, `Function`, etc.). The symbol is not linked from the type. So it's a clean design, the only downside is that we need to link `Struct` from `Variable` via this new `type_declaration` member, but I think that's ok for now.

**Comment by certik** [comment]
I think the above bug is now fixed by this PR, now there is another one:
```console
$ lfortran integration_tests/procedure_01.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1933
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 856
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 342
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7776
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "../libasr/asr.h", line 4542
  File "../libasr/asr.h", line 4518
  File "../libasr/asr.h", line 4543
  File "../libasr/asr.h", line 4273
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 1338
    ASR::symbol_t *mod = x.m_global_scope->get_symbol(item);
  File "../libasr/asr.h", line 4545
  File "../libasr/asr.h", line 4282
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 2597
    finish_module_init_function_prototype(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4039
    if (ASRUtils::get_FunctionType(s)->n_type_params == 0) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3682
    visit_procedures(x);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 3991
    this->visit_stmt(*x.m_body[i]);
  File "../libasr/asr.h", line 4560
  File "../libasr/asr.h", line 4304
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4568
    this->visit_expr_wrapper(x.m_value, true);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 4706
    this->visit_expr(*x);
  File "../libasr/asr.h", line 4605
  File "../libasr/asr.h", line 4356
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7531
    ASR::ClassProcedure_t>(proc_sym);
  File "../libasr/asr.h", line 41
AssertFailed: is_a<T>(*f)
```
Which we will fix in subsequent PRs.

**Comment by certik** [comment]
I think that this change is good, so I am going to merge it. @czgdp1807 if it is not good, we can refactor it later.

**Pull request merged**
