### PR TITLE
Register `Tan` in the IntrinsicFunction

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
All the test seems to pass on my local machine.
It fails here: https://github.com/lfortran/lfortran/actions/runs/4635497505/jobs/8202599849?pr=1505
@czgdp1807, Can this be related to different LLVM versions?

**Comment by certik** [comment]
The failure is related to complex numbers in LLVM being platform dependent. In general we can't test them in LLVM output, only in compiling to executable and running it.

**Comment by Thirumalai-Shaktivel** [comment]
Cool, then I will remove the LLVM tests.

**Review by certik — APPROVED** [review]
Looks great, thanks!

**Comment by Thirumalai-Shaktivel** [comment]
Thanks for the review!

**Pull request merged**
