### PR TITLE
Ensure current_body is not nullptr

### PR DESCRIPTION
**Pull request by certik**
Fix a bug that caused it. Test added.

### CODE REVIEW

**Comment by certik** [comment]
This PR now gets Minpack returning exactly the same floating point numbers to all bits it seems.

**Comment by certik** [comment]
@Smit-create I am going to go ahead and merge it, I hope you don't mind. :)

**Comment by Pranavchiku** [comment]
That's great progress! Awesome :))

**Review by Smit-create — COMMENTED** [review]
Looks perfect. Thanks for the fix!!

**Pull request merged**
