### PR TITLE
Remove unneeded visit expr

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
and get back stdin read working.

```console
% lfortran examples/chat_01.f90 
Please enter your name:
Joe
---------WELCOME TO CHAT_01---------
Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat

Enter your choice:
1
Hi Joe

Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat

Enter your choice:
2
Hello Joe

Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat

Enter your choice:
3
Good Morning Joe

Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat

Enter your choice:
4
Happy Birthday Joe!

Please pick an option:
1) Say Hi
2) Say Hello
3) Say Good Morning
4) Say Happy Birthday
5) Exit the chat

Enter your choice:
5
```

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@certik how should we add a test for this to ensure it does not break in future?

**Comment by Shaikh-Ubaid** [comment]
I am merging this as the changes seem trivial. I think we can add the test in a separate PR.

**Comment by certik** [comment]
Thanks! I saw that it failed too yesterday.

**Comment by Shaikh-Ubaid** [comment]
>@certik how should we add a test for this to ensure it does not break in future?

Do you know/suggest any approach to test this?

**Comment by certik** [comment]
Can the input in be tested using a bash script that feeds the input on stdin?

**Comment by Shaikh-Ubaid** [comment]
>Can the input in be tested using a bash script that feeds the input on stdin?

We can simply redirect the input stream to a file using `<` in a bash script. For example:

```console
% cat expr2.f90
program expr2
implicit none

    character(len = 10) :: name

    print *, "Name:"
    read(*, *) name

    print *, "Name: ", name
    if (name /= "Joe") error stop

end program
% cat tmp.txt  
Joe
% cat test.sh  
#!/usr/bin/env bash

lfortran expr2.f90 -o expr2
./expr2 < tmp.txt
% ./test.sh 
Name:
Name: Joe
% echo $?
0
```

**Comment by certik** [comment]
Let's add a cmake test for this, a new category/lable, and in cmake pass in the input to stdin, and ensure it fails if there is a bug like it was before this PR.

**Pull request merged**
