### PR TITLE
Remove old runtime code in lfortran_intrinsic_optimization file

### PR DESCRIPTION
**Pull request by HarshitaKalani**

### CODE REVIEW

**Review by Pranavchiku — COMMENTED** [review]
I am not sure why we had this file, I will wait for an approval before merging this.

**Comment by Shaikh-Ubaid** [comment]
>I am not sure why we had this file, I will wait for an approval before merging this.

I think these are now implemented via the intrinsic registry functions. Hence, it is safe to remove them.

**Review by Shaikh-Ubaid — APPROVED** [review]
It looks good to me! Thanks for this! Good catch and Great work!

**Comment by Shaikh-Ubaid** [comment]
I am squash merging this.

**Pull request merged**
