### PR TITLE
Fix width and scaling issue in `ES` formatting

### PR DESCRIPTION
**Pull request by gptsarthak**
Fixes https://github.com/lfortran/lfortran/issues/2642 and https://github.com/lfortran/lfortran/issues/2643
```fortran
print '("x:", ES10.2)', 0.999, 0.1
```
```console
(base) ➜  lfortran git:(fmt3) ✗ lfortran examples/temp.f90           
x:  9.99E-01
x:  1.00E-01
(base) ➜  lfortran git:(fmt3) ✗ gfortran examples/temp.f90 && ./a.out
x:  9.99E-01
x:  1.00E-01
```

### CODE REVIEW

**Comment by certik** [comment]
@Thirumalai-Shaktivel can you please check if this fixes the issue?

**Comment by Shaikh-Ubaid** [comment]
@gptsarthak can you add a `--run` reference test (like we have  for `advance`) on this so that we ensure it does not break in future?

**Comment by Thirumalai-Shaktivel** [comment]
Testing...

**Comment by gptsarthak** [comment]
> can you add a --run reference test (like we have for advance) on this so that we ensure it does not break in future?

Yes now that i found out about the --run tests that can save the output, i am planning to move the whole format_04.f90 test as a run test. Should I do it in this PR itself?

**Comment by Shaikh-Ubaid** [comment]
>Yes now that i found out about the --run tests that can save the output, i am planning to move the whole format_04.f90 test as a run test. Should I do it in this PR itself?

Yes, I think that verifies the printing bug/issue fix and also makes the PR complete by making tests strong.

**Comment by Shaikh-Ubaid** [comment]
> > Yes now that i found out about the --run tests that can save the output, i am planning to move the whole format_04.f90 test as a run test. Should I do it in this PR itself?
> 
> Yes, I think that verifies the printing bug/issue fix and also makes the PR complete by making tests strong.

It should just be a minor change like enabling the test in `.toml` file and then updating the reference tests, right?

**Review by Thirumalai-Shaktivel — COMMENTED** [review]
Only the following fails, rest looks good, thank you @gptsarthak!
```fortran
program expr2
    implicit none

    real(8) :: x

    x = 0.102
    print '("x:", ES10.2)', x

end program
```
```console
$ gfortran examples/expr2.f90 && ./a.out
x:  1.02E-01
$ lfortran examples/expr2.f90
x:  1.00E-01
```

**Comment by gptsarthak** [comment]
> It should just be a minor change like enabling the test in .toml file and then updating the reference tests, right?

Almost. I observed that if the file location is not in the tests directory itself we get a `runtime_error: raw_fd_ostream failed` error. But If i move/copy the file from `integration_tests` to `tests` directory it'll work fine.

> Only the following fails, rest looks good, thank you @gptsarthak!

I'll check it out right now.

**Comment by gptsarthak** [comment]
@Thirumalai-Shaktivel it has been fixed.
```fortran
print '("x:", ES15.5)', 0.102212
```
```console
(base) ➜  lfortran git:(fmt3) ✗ lfortran examples/temp.f90      
x:    1.02212E-01
(base) ➜  lfortran git:(fmt3) ✗ gfortran examples/temp.f90 && ./a.out
x:    1.02212E-01
```

**Review by certik — APPROVED** [review]
Thanks @gptsarthak that looks good to me.

@Thirumalai-Shaktivel does the fix work now?

**Comment by certik** [comment]
I think the differences might be with some numerical differences between gfortran/lfortran, not printing differences. There are some printing differences in default prints like `print *, a, b, c`, but there I think the LFortran printing is better, and we can further refine it as needed. And enable the rest with compiler options.

**Comment by gptsarthak** [comment]
Yeah, in some cases Lfortran is more precise. Like here:
```fortran
program format_04
    double precision :: s
    s = 23.5678
    print '(F9.6,1X)',s
end program
```
```console
(base) ➜  lfortran git:(fmt3) ✗ lfortran examples/temp.f90           
23.567800 
(base) ➜  lfortran git:(fmt3) ✗ gfortran examples/temp.f90 && ./a.out
23.567801
```

**Pull request merged**
