### PR TITLE
chore: merge `main` into `simplifier_pass`

### PR DESCRIPTION
**Pull request by kmr-srbh**

### CODE REVIEW

**Comment by kmr-srbh** [comment]
Looking into the CI failure.

**Comment by kmr-srbh** [comment]
We have the `asr_verify` changes here now.

**Comment by certik** [comment]
Yes. CI has to pass first.

**Comment by kmr-srbh** [comment]
Looking into the failure.

**Comment by kmr-srbh** [comment]
https://github.com/lfortran/lfortran/pull/5126#discussion_r1817723957 is a concern, but we can merge now if required.

**Pull request merged**
