### PR TITLE
WASM: Declaring a fixed enough memory

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
This `PR` adds support for a fixed and (hopefully) sufficient sized linear memory declaration.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
In [WASM: Fix linear memory size to 6.4 Mb](https://github.com/lfortran/lfortran/pull/126/commits/9e97ab8d08a8cd3e097b031d6ba760b47da80f71), I allocated the linear memory to a fixed value of `6.4 Mb`. Please, could someone possibly share if `6.4 Mb` could/would be enough for the examples shared at https://github.com/lfortran/lcompilers_frontend/issues/8

**Review by certik — APPROVED** [review]
That should be enough for now. We can always increase or change this later as needed.

**Comment by Shaikh-Ubaid** [comment]
It seems the `CI` failed. I am looking into it.

**Comment by Shaikh-Ubaid** [comment]
>It seems the CI failed. I am looking into it.

It seems few test cases did not update previously. I am unsure how it occured. I updated them and pushed the commit. With the latest changes, I am hoping the `CI` would pass now.

**Pull request merged**
