### PR TITLE
Some changes needed for cmake support

### PR DESCRIPTION
**Pull request by meow464**
Some changes needed to work with cmake. The cmake branch I'm working on is here: https://gitlab.kitware.com/meow464/cmake/-/tree/lfortran?ref_type=heads

### CODE REVIEW

**Comment by certik** [comment]
Thanks! Can you show the use case when this is needed? As far as I know, these C defines should always be defined.

**Comment by meow464** [comment]
I haven't run into any use case.
I made this branch a few months ago and after opening the PR today realized some changes were no longer necessary or already made. I reverted those changes and that's all that remained.

**Comment by certik** [comment]
I am trying to understand the error message that you are getting with master. You should not be getting any, because cmake creates those defines automatically.

**Comment by meow464** [comment]
I was not getting any error, this is part of some previous work I'm now realizing has already being done by someone else.
I will close this PR.

**Pull request closed without merging**
