### PR TITLE
Use ExternalSymbol to refer enum members

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lfortran/lfortran/commit/2cd04dd99772c691713de89fb5ed73962121ae4f

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
LGTM, thank you!

**Review by certik — APPROVED** [review]
It compiles to a binary, but doesn't run correctly yet?

**Comment by czgdp1807** [comment]
Yes.

**Comment by certik** [comment]
Ok! Good to merge then.

**Pull request merged**
