### PR TITLE
[misc] Add star history in README

### PR DESCRIPTION
**Pull request by lucifer1004**

### CODE REVIEW

**Comment by awvwgk** [comment]
I don't know whether this actually adds any value to the project README, which is kept quite short. Also, the style of the graphic is not matching the usual LFortran style on its webpage or documentation.

**Comment by certik** [comment]
The star history is a nice graph. I don't know if it should be in the README, but maybe we can have it somewhere in documentation. Let me think of it.

**Review by certik — APPROVED** [review]
I decided to merge this, the graph is accelerating due to our move to github, and being close to beta. It shows that we have are an active project. We can iteratively improve the README to be more consistent, but I think this might help with outreach.

**Comment by lucifer1004** [comment]
Yes, the recent steep upward trend has been very encouraging.

**Pull request merged**
