### PR TITLE
CI: Rename job to 'Third party code compilation'

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
towards https://github.com/lfortran/lfortran/pull/2254#discussion_r1306571610

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Shall we also include `fpm` compilation and `Check Production Codes with LFortran` jobs in the `Third party code compilation` Job?

**Comment by certik** [comment]
I would merge "fpm" with this. And the "Check Production Codes with LFortran" should be merged with SciPy.

The reason to keep the SciPy test separate is because SciPy takes about 20 minutes to build and we are testing just a small part, and also SciPy has a lot of dependencies, so potentially something can go wrong there (as it did recently with cython).

The tests in this PR are all 100% Fortran programs that build very quickly, so I think they can all be in the same CI test.

**Comment by Shaikh-Ubaid** [comment]
>I would merge "fpm" with this. And the "Check Production Codes with LFortran" should be merged with SciPy.

Done.

**Comment by certik** [comment]
I think the PR is fine I rebased it to see. If everything passes, we can merge it. Then we need to update the required tests at github.

**Pull request merged**
