### PR TITLE
Simple generics

### PR DESCRIPTION
**Pull request by ansharlubis**
Added a new construct `TemplatedFunction` to support function with template arguments (#2261)
```fortran
pure function generic_sum{T, add, cast}(arr) result(res)
    requires operator_r(T, T, T, add)
    requires cast_r(T, cast)
    type(T), intent(in) :: arr(:)
    type(T) :: res
    integer :: n, i
    n = size(arr)
    res = cast(0)
    if (n > 0) then
        res = arr(1)
        do i=2,n
            res = add(res, arr(i))
        end do
    end if
end function generic_sum
```

### CODE REVIEW

**Comment by ansharlubis** [comment]
Questions for @certik:
1. Should I add a new construct like what I've done so far for functions with template arguments, or should I just add another field to the existing `Function` in AST?
2. I got some shift/reduce problems that I couldn't solve while extending the parser with a new type of function
```
templated_function
    : fn_mod_plus KW_FUNCTION id "{" id_list "}" "(" id_list_opt ")"
        result_opt
        sep
        decl_statements
        end_function sep {
            LLOC(@$, @14); $$ = TEMPLATED_FUNCTION($1, $3, $5, $8, $10, nullptr,
                TRIVIA($11, $14, @$), SPLIT_DECL(p.m_a, $12),
                SPLIT_STMT(p.m_a, $12), @$); } 
```
If I add the rest of the function's fields in the grammar, it always ended up with some shift/reduce problems.

**Comment by ansharlubis** [comment]
Next would be to support this
``` fortran
    write(*,*) generic_sum{real, operator(+), cast_real}(xr) !! expect to print 6.0
    write(*,*) generic_sum{integer, operator(+), cast_integer}(xi) !! expect to print 6
```
To do we need:
- [ ] Instantiation through templated function calls
- [ ] Instantiation overloading

**Comment by certik** [comment]
Awesome, great job! Looks good so far. Once all tests pass and you are ready for a detailed review, just ping me.

**Comment by ansharlubis** [comment]
> Awesome, great job! Looks good so far. Once all tests pass and you are ready for a detailed review, just ping me.

Can you help with my questions above?

**Comment by certik** [comment]
Regarding your quesiton 1., can you show the modifications to ASR for both of the approaches that you are thinking? Then we'll choose one once I can see the details.

For 2., we need to play with the parser, sometimes it's tricky to ensure no conflicts happen. I can help with this if you are stuck there.

**Comment by ansharlubis** [comment]
I'm adding a new construct to the _AST_ actually.
```
program_unit
    = ...
    | Function(identifier name, arg* args, decl_attribute* attributes,
        expr? return_var, bind? bind, trivia? trivia, unit_decl1* use, import_statement* import,
        implicit_statement* implicit, unit_decl2* decl, stmt* body,
        program_unit* contains)
    | TemplatedFunction(identifier name, identifier* temp_args, arg* args,
        decl_attribute* attributes, expr? return_var, bind? bind, trivia? trivia,
        unit_decl1* use, import_statement* import, implicit_statement* implicit,
        unit_decl2* decl, stmt* body, program_unit* contains)
```
The new `TemplatedFunction` is exactly the same as `Function` except for `temp_args` which is for the template arguments surrounded by the braces like in:
```
pure function generic_sum{T, add, cast}(arr) result(res)
  ...
end function
```

**Comment by ansharlubis** [comment]
For the parser. Currently `TemplatedFunction` is parsed like this:
```
templated_function
    : fn_mod_plus KW_FUNCTION id "{" id_list "}" "(" id_list_opt ")"
        result_opt
        sep
        decl_statements
        end_function sep {
            LLOC(@$, @14); $$ = TEMPLATED_FUNCTION($1, $3, $5, $8, $10, nullptr,
                TRIVIA($11, $14, @$), SPLIT_DECL(p.m_a, $12),
                SPLIT_STMT(p.m_a, $12), @$); }
```
But I want to add the rest of the fields necessary for a function to make it into:
```
templated_function
    : fn_mod_plus KW_FUNCTION id "{" id_list "}" "(" id_list_opt ")"
        result_opt
        sep use_statement_star import_statement_star implicit_statement_star decl_statements
        contains_block_opt
        end_function sep { ... }
```

**Comment by certik** [comment]
For AST, if the only difference is the addition of `identifier* temp_args`, then I would just add it to the existing Function, meaning if it is empty, it's not a generic function.

**Comment by ansharlubis** [comment]
Gotcha, I'll make that change.

**Review by certik — APPROVED** [review]
I think this looks good. Is this ready to be merged?

**Comment by certik** [comment]
I merged it, I think this good enough to merge. Thanks @ansharlubis !

@dacarnazzola, here is a first implementation of the simple generics.

**Comment by ansharlubis** [comment]
This is only for the function definition for now, I'll handle the instantiation in a different PR.

**Pull request merged**
