### PR TITLE
lfortran: improve handling of linker flags

### LINKED ISSUE #3281: linking a shared library
I am trying to link a shared library.
```
lfortran -v -fPIC --generate-object-code --implicit-interface -shared -Wl,-soname,libworld.so -o libworld.so world.f.o
```

We don't have `-shared` option, as this needs to go to `clang`, I thought
```
lfortran -v -fPIC --generate-object-code --implicit-interface -W,-shared -Wl,-soname,libworld.so -o libworld.so world.f.o
```
but that fails with:
```
lfortran -v -fPIC --generate-object-code --implicit-interface -W,-shared -Wl,-soname,libworld.so -olibworld.so world.f.o
clang -o libworld.so world.f.o  -L"/usr/bin/../lib64" -Wl,-rpath,"/usr/bin/../lib64" -llfortran_runtime -lm
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../lib64/crt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
For some reason, the `-shared` is missing in the `clang` call.

Running:
```
clang -o libworld.so world.f.o  -L"/usr/bin/../lib64" -shared -Wl,-rpath,"/usr/bin/../lib64" -llfortran_runtime -lm
```
works, so somewhere there is a bug in the `-W` option parsing....

### PR DESCRIPTION
**Pull request by junghans**
Fix #3281

This PR hand through all `-l`, `-L`, `-W` and the `--shared` flag, the ordering changes a bit, but good enough for now I guess.

### CODE REVIEW

**Comment by junghans** [comment]
Ok, I need to understand this error:
```
/usr/bin/ld: cannot find -l/usr/lib/gcc/x86_64-linux-gnu/11: No such file or directory
```

**Comment by certik** [comment]
Thanks for working on this. Once it is ready I want to test it by hand as well, to ensure everything works. Overall it looks good so far.

**Comment by junghans** [comment]
> Thanks for working on this. Once it is ready I want to test it by hand as well, to ensure everything works. Overall it looks good so far.

Please give it some testing, I think it is as good as it gets for now. 

The other thing we might want to implement at some point soon, is `-O*`, even if we just ignore it for now.

**Review by certik — APPROVED** [review]
I didn't have time to thoroughly check this by hand, but the CI passes for all 3rd party apps, so it probably works.

Let's merge it and we'll collectively test it and if we discover any bugs, we'll fix them with subsequent PRs.

**Pull request merged**
