### PR TITLE
Fix bugs in ``inline_function_calls`` ASR pass

### PR DESCRIPTION
**Pull request by czgdp1807**
https://github.com/lfortran/lfortran/issues/2063

### CODE REVIEW

**Comment by czgdp1807** [comment]
So @certik. I couldn’t work on it because I was out for collecting my passport from VFS Global centre (which is around 700 kilometres from my home). Now there are two ways to complete this PR,

1. Re-instate `NOFAST` tags in the rest of the tests which fail because of the bugs in this pass. Then merge this PR. Then create multiple PRs removing the `NOFAST` tags gradually (4-5 in each). I would recommend going with this approach.
2. Fix all the bugs in this pass until the tests go green. Only then merge. This will take a week minimum and it will look like I am making no progress but I would be working hard to get this done. I would recommend to not follow this approach.

@certik Please let me know what you think would work. I would do that.

**Comment by certik** [comment]
Either approach should work.

**Comment by czgdp1807** [comment]
Okay. I just got home. Let me get this merged and then I will open multiple PRs from next onwards (if I get time from my other priorities higher up, will email you my plan for next week as you asked).

**Comment by certik** [comment]
There are several CI failures that need to be fixed.

**Comment by certik** [comment]
I think it's fine, but it added a lot more NOFAST exceptions --- do you know why that is happening? We need to remove all NOFAST quite soon, since it prevents to compile bigger packages in fast mode.

**Pull request merged**
