### PR TITLE
Throw error when length of argument `c` to `ichar` and `iachar` is not one

### LINKED ISSUE #3734: Throw error for argument of `ichar` not equal to length 1
```fortran
program main
  character(5):: x = "Hello"
  print*, ichar(x)
end
```
```console
$ lfortran a.f90
72
$ gfortran a.f90 && ./a.out
a.f90:3:16:

    3 |   print*, ichar(x)
      |                1
Error: Argument of ichar at (1) must be of length one
```
LFortran should be throwing error if the argument provided to `ichar` has length not equal to 1.

### PR DESCRIPTION
**Pull request by kmr-srbh**
fixes #3734 

### Compile-time
```fortran
program main
   print*, iachar("Hello")
end
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
semantic error: Argument to Iachar must be of length one
 --> ./examples/example.f90:2:19
  |
2 |    print*, iachar("Hello")
  |                   ^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### Run-time
```fortran
program main
   character(5):: x = "Hello"
   print*, iachar(x)
end
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Error: Argument to Iachar must be of length one
```

### TODO

- [ ] Handle compile-time argument verification for `ichar`.

### CODE REVIEW

**Comment by kmr-srbh** [comment]
@HarshitaKalani you had informed me that we use a python script for generating the `verify_args` method for intrinsic functions. I see that no verification is being performed on the argument length for intrinsic functions and the utility script script does not have support for it too. Can we do this in the current state? If yes, could you please guide me on it?

**Comment by HarshitaKalani** [comment]
```fortran
program main
   character :: x = "Hello" !-----------------> This should work.
   character(5) :: x = "Hello" !----------------> This shouldn't work.
   print*, iachar(x)
end
```

>Unicode characters have different lengths.

I hope you understood why the test cases in `intrinsics_60.f90` are correct from the example given above.

>@HarshitaKalani you had informed me that we use a python script for generating the verify_args method for intrinsic functions. I see that no verification is being performed on the argument length for intrinsic functions and the utility script script does not have support for it too. Can we do this in the current state? If yes, could you please guide me on it?

We'll need to add the support in the script only.

**Review by HarshitaKalani — COMMENTED** [review]
Thanks for working on this. LMK if your queries are resolved.

**Comment by kmr-srbh** [comment]
> Thanks for working on this. LMK if your queries are resolved.

Thank you very much for the guidance @HarshitaKalani! I have understood the requirement. I will make the changes accordingly. :+1:

**Comment by certik** [comment]
Regarding:
```
program main
   character :: x = "Hello" !-----------------> This should work.
   character(5) :: x = "Hello" !----------------> This shouldn't work.
   print*, iachar(x)
end
```
Shouldn't this be the

**Comment by certik** [comment]
(Sorry I closed and reopened the PR, I clicked the wrong button.)

**Comment by kmr-srbh** [comment]
> ```fortran
> program main
>    character :: x = "Hello" !-----------------> This should work.
>    character(5) :: x = "Hello" !----------------> This shouldn't work.
>    print*, iachar(x)
> end
> ```


@HarshitaKalani @certik the provided example works correctly with the changes in this PR. 
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
72                                                                          # for the first declaration
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Error: Argument to Iachar must be of length one                             # for the second declaration
```

The real issue is with the `len()` function. It gives wrong output for Unicode characters. 
```fortran
program intrinsics_60
    character :: c, d, e, f
    open(11, file="intrinsics_60_data.txt", form="formatted", access="stream", status="old")
    read(11, *) c, d, e, f
    print *, c, d, e, f
    print *, len(c)
    print *, len(d)
    print *, len(e)
    print *, len(f)
    print *, iachar(c)
    print *, iachar(d)
    print *, iachar(e)
    print *, iachar(f)
    ! if (iachar(c) /= 97) error stop
    ! if (iachar(d) /= 90) error stop
    ! if (iachar(e) /= 195) error stop
    ! if (iachar(f) /= 194) error stop
  end program
```
#### LFortran
```console
aZÿ©
1
1
2
2
97
90
Error: Argument to Iachar must be of length one
```

#### GFortran
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ gfortran intrinsics_60.f90
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ ./a.out
 aZ��
           1
           1
           1
           1
          97
          90
         195
         194
```

I am opening an issue for this. Another interesting observation is how GFortran handles these characters. LFortran prints the characters as it is to the console, but GFortran does not.

**Comment by kmr-srbh** [comment]
This is confusing, the `len()` function works correctly, but still we get the above wrong outputs.
```fortran
program main
   print *, len("ÿ")
   print *, len("©")
end
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
2
2
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
           2
           2
```

The issue is with reading the file?

**Comment by certik** [comment]
I think `len()` in Fortran is simply counting the number of bytes, so utf-8 can have multiple bytes per character ("unicode codepoint").

Regarding the failure above, we need to investigate which part is wrong.

**Comment by HarshitaKalani** [comment]
>The issue is with reading the file?

Yes, it is with the reading I guess.
I just checked
```fortran
program main
    character :: c
    open(11, file="intrinsics_60_data.txt", form="formatted", access="stream", status="old")
    read(11, *) c
    print *, c
    print*, len(c)
end
```
```console
$ gfortran b.f90 && ./a.out
 H
           1
$ lfortran b.f90 --no-warnings
Hello
5
```

**Comment by certik** [comment]
Tests have to pass. Once they do, click on "Ready for review".

**Comment by kmr-srbh** [comment]
@certik I explored some ways to add a check for the argument length. Is the requirement such that we may consider adding a new key `arg_len` to the `intrinsic_funcs_args` dictionary in the generator python script? 

If not, the other way we can do this is by using regular expressions. We use the string `"char"` for denoting an argument of type string. The `is_character` ASR utility function is the verifier for it. We can support optionally adding the argument with a length, like `"char(1)"`. The regex search `re.search('\d', s)` will get us the length if provided and `None` otherwise.

```console
>>> import re
>>> arg = "char"
>>> arg_len = re.search("\d", arg)
>>> if arg_len is None:
...     print("No length provided")
... else:
...     print(arg_len.group())
... 
No length provided
>>> arg = "char(1)"
>>> arg_len = re.search("\d", arg)
>>> if arg_len is None:
...     print("No length provided")
... else:
...     print(arg_len.group())
... 
1
```

Using this fetched argument length for an argument of type `char`, we can go ahead checking if it is a compile-time value and then get the length of the passed string argument.

With this change, we can incorporate verification for argument length without breaking the existing infrastructure. If in the future we need this check on more argument types, we can consider adding a new key for it as stated above.

**Comment by Shaikh-Ubaid** [comment]
First things first: In the PR description, please first test your example with `gfortran` (in case of `lfortran`) and `python` (in case of `lpython`) and post the expected output. Next post the output you currently get with `lfortran`/`lpython`.

It seems for the runtime example, `gfortran` prints error at the compilation stage itself since the length of the string is available at compile-time:

```console
% cat examples/expr2.f90 
program main
    character(5):: x = "Hello"
    print*, iachar(x)
 end
% gfortran examples/expr2.f90
examples/expr2.f90:3:19:

    3 |     print*, iachar(x)
      |                   1
Error: Argument of iachar at (1) must be of length one
```

When the length of the string is not available at compile-time, for example when the string is an allocatable string:

```console
% cat examples/expr2.f90     
program main
    character(len=:), allocatable:: x
    allocate(character(len=10) :: x)
    x = "Bat"
    print*, iachar(x)
end
% gfortran examples/expr2.f90
% ./a.out 
          66
```

`gfortran` does not seem to print any error. Instead it seems to simply use the first character of the allocatable string.

Second:

Removed unused/old intrinsic code here https://github.com/lfortran/lfortran/pull/4075. Now you have `ichar` implemented as an intrinsic registry function and `iachar` implemented at the ASR level in `ast_common_visitor`. 

Adding checks for `iachar` might be straigthforward as it currently implemented in AST->ASR. Also, checking length for compile-time argument length should be straightforward for registry functions and can be done in the `eval_*()` (For example `eval_Ichar()`) function.

Now considering the case of checking for runtime-time argument with compile-time length. I think for this we need to add support in the generator script. We recently updated the script to support checking for `complex64` (complex of kind 8) here https://github.com/lfortran/lfortran/pull/3955#discussion_r1596121132. I think you can similarly define

```c++
template <int32_t length>
static inline bool is_character(ASR::ttype_t &x) {
    if (is_character(x)) {
        // check if length is < 0 which means length is not available at compile-time
        // if length is not available simply return true (gfortran seems to work with runtime length)

        // if length >= 0 which means length is available at compile-time
        return compile_time_length == length;
    }
    return false;
}
```

The only concern I have with the above is it would detect runtime-args with compile-time lengths not equal to `1`, but it might not be able to produce a very descriptive error. We might need to think/investigate how to print a good/descriptive error for this. If you have any ideas on this, please feel free to share.

**Comment by kmr-srbh** [comment]
Closing this with reference to changes made in #4075. I will open a new PR for this.

**Pull request closed without merging**
