### PR TITLE
Change `--allow-implicit-interface` to `--implicit-interface`

### PR DESCRIPTION
**Pull request by Pranavchiku**

### CODE REVIEW

**Comment by Pranavchiku** [comment]
I am not sure why `windows-2019` test failed previously.

**Comment by certik** [comment]
The Windows error is most likely due to https://github.com/lfortran/lfortran/issues/1097.

**Comment by certik** [comment]
Awesome, thanks for that. When regenerating tests, make sure to `rm -rf tests/reference/*` first, that will remove no longer used reference results, since the hashes changed.

**Comment by Pranavchiku** [comment]
Yeah, on it!

**Pull request merged**
