### PR TITLE
[C, Julia] convert no-var do-loop into while (fix #821)

### LINKED ISSUE #821: dev.lfortran.org: the example program throws a runtime error on the cpp tab
I was checking out the online playground at https://dev.lfortran.org/ and when I run the default program on the website the code executes successfully but in the cpp tab it shows an error saying:

```
RuntimeError: Aborted(native code called abort())
ERROR: CPP could not be generated from the code
```

<details>
  <summary>Relevant screenshots</summary>

## stdout tab

image

## cpp tab

image
</details>

I also checked with a simple hello world program and the cpp tab works and generates code.

### PR DESCRIPTION
**Pull request by lucifer1004**
Since I cannot push commits to @certik's branch, I start a new PR. I do not add tests in this PR and would like to leave that for @sloorush.

### CODE REVIEW

**Comment by lucifer1004** [comment]
For @sloorush, it is easy to add the test, you need to:

- Add a new `.f90` source file in `integration_tests`. You can name it `doloop_08.f90` since we already have 7. This file should contain a `do` loop without a loop var.
- In `tests/tests.toml`, add a new item whose `filename` is `"../integration_tests/doloop_08.f90"`, and has options `c = true`, `cpp = true` and `julia = true`.
- Go to the repo root to run tests and generate the new references.

```sh
# First build the project
export LFORTRAN_RUNTIME_LIBRARY_DIR="your-build-dir/src/runtime"
export PATH="your-build-dir/src/bin:$PATH"
python3 run_tests.py -b julia c cpp -u
```

Then make a PR.

**Comment by sloorush** [comment]
Thank you! Seems doable! I'll make a PR soon

**Review by certik — APPROVED** [review]

**Comment by lucifer1004** [comment]
> Thank you! Seems doable! I'll make a PR soon

You can make the test PR now that the changes have been merged.

**Comment by lucifer1004** [comment]
@certik Maybe a better way is to handle this in ASR? Then we do not need to write duplicate code in different backends.

**Comment by certik** [comment]
I think so, we have a while loop and if it is exactly equivalent to  the for loop without the header, then I think we should just not allow this in ASR and the frontend would convert the do loop into a while loop.

**Pull request merged**
