### PR TITLE
enh: support StructInstanceMember in SelectType

### PR DESCRIPTION
**Pull request by HarshitaKalani**
Fixes: https://github.com/lfortran/lfortran/issues/5515

### CODE REVIEW

**Review by certik — APPROVED** [review]
Looks good, thanks!

**Comment by kmr-srbh** [comment]
With the following code:
```fortran
module fortuno_basetypes
   implicit none

   type, abstract :: test_base
      character(:), allocatable :: name
   end type test_base

   type, extends(test_base) :: test_base_derived
   end type test_base_derived


   type :: test_ptr_item
      class(test_base), pointer :: item => null()
   end type test_ptr_item


   type :: test_list
      type(test_ptr_item), pointer :: storage_(:) => null()
      integer :: nitems = 0
   contains
      procedure :: free => test_list_free
   end type


contains

   subroutine test_list_free(this)
      class(test_list), intent(inout) :: this

      select type (item => this%storage_(1)%item)
       type is (test_base_derived)
         print *, "type is test_base"
       class default
      end select

   end subroutine test_list_free

end module fortuno_basetypes

program fortuno_01
   use fortuno_basetypes
   implicit none

   type(test_list) :: my_list
   allocate(my_list%storage_(1))
   allocate(test_base_derived::my_list%storage_(1)%item)

   call my_list%free()

   print *, "Test list has been freed successfully."
end program
```

The output is:
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
 type is test_base
 Test list has been freed successfully.
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
code generation error: test_base doesn't have any member named storage_
  --> ./examples/example.f90:30:28
   |
30 |       select type (item => this%storage_(1)%item)
   |                            ^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by certik** [comment]
@kmr-srbh thanks for finding another example that fails. Is this a blocker to merge this PR, or can this be fixed after this PR is merged?

**Comment by kmr-srbh** [comment]
Yeah we can handle the type statement body in a different PR. With the changes in this PR we add support for `StructInstanceMember` as `selector`.

**Comment by certik** [comment]
We got a CI failure:
```
[ 71%] Building Fortran object CMakeFiles/fortuno_01.dir/fortuno_01.f90.o
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0xd5d514
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", local address: 0x29e3f
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", local address: 0x29d8f
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0xd805e6
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0xd7cae7
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0xd70cfe
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0xf15f4b
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bbaef4
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bdfa75
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bec267
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bd182b
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1be0bd6
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bec267
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bd18a3
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1be2500
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bec267
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bd18eb
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1be2bed
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bec231
  Binary file "/home/runner/work/lfortran/lfortran/src/bin/lfortran", local address: 0x1bd16bf
LCompilersException: visit_PointerNullConstant() not implemented
make[2]: *** [CMakeFiles/fortuno_01.dir/build.make:75: CMakeFiles/fortuno_01.dir/fortuno_01.f90.o] Error 1
```

**Comment by tanay-man** [comment]
The CI failure is due to fortran backend. Can we remove it for now?

**Comment by kmr-srbh** [comment]
> The CI failure is due to fortran backend. Can we remove it for now?

@tanay-man yes I think it is safe to remove it.

**Pull request merged**
