### PR TITLE
PASS: Update flip_sign to use Intrinsic function

### PR DESCRIPTION
**Pull request by Smit-create**
https://github.com/lcompilers/lpython/pull/2301

### CODE REVIEW

**Comment by certik** [comment]
The changes are good. But I have a question: in `--fast` mode, we first create such a FlipSign function. But then it seems we substitute it for the ASR implementation (instantiation), this is good for backends that don't support it directly. However, in the LLVM backend, we want to implement it directly via an efficient "bit hacks" implementation. How does this work --- are we turning of instantiation for the LLVM backend? If not, what would be a good design to do it? (In that case, we should probably wait with this PR, since it would be a regression.)

**Comment by Smit-create** [comment]
> How does this work --- are we turning off instantiation for the LLVM backend?

I don't think that's done presently.

> we want to implement it directly via an efficient "bit hacks" implementation

Yeah, that's correct and would be faster for sure as we play with the bits directly.

> since it would be a regression.

I guess the previous design was identical to the current one (using ExternalSymbol from optimization_module instead of a generated Intrinsic Function in this case) and shouldn't be a regression?

**Comment by certik** [comment]
Is LLVM using the efficient bit implementation? If so, then it's not a regression.

**Comment by Smit-create** [comment]
Right now it isn't using fast LLVM bits implementation because of the following function:
https://github.com/lfortran/lfortran/blob/94a950998d1a46e5e67c8dfa204a11a54e4313b1/src/libasr/asr_utils.h#L764-L773

We need some design `optimization_function?` so that we can rightly detect the intrinsic optimization functions, and generate them correctly in LLVM. Right now as seen, we are using the module name `lfortran_intrinsic_optimization` to catch the same.

**Comment by Smit-create** [comment]
One way to detect the same is by checking if the function name contains a substring `lcompilers_optimization` in its name then it's an optimization function.

**Comment by certik** [comment]
One way is to check for the newly generated ASR function in the LLVM backend. The other way is to turn off instantiation of this particular function (only) for the LLVM backend. 

I would almost implement the second. Why not pass an option to the intrinsic function pass, some `std::vector` of "intrinsic function IDs" that should not be instantiated? Then in the LLVM, pass an ID for this FlipSign function. And that's it, I think that should be quite simple.

**Comment by Smit-create** [comment]
With the current diff, where we instantiate and create a FunctionCall to replace the function, we have this potential drawback: The last pass is `inline_function_calls`, it inlines optimization function calls, and so LLVM can't do fast bits implementation. If we change the order of passes and put `flip_sign`, `fma`, etc at the bottom, then it should be fine.

The second approach, where we skip instantiation and just create an `IntrinsicFunction` node will be less generic in my opinion

**Comment by Smit-create** [comment]
Sounds good to me. Just a small suggestion in that case for the implementation -- let's pass which backend we are using in `PassOptions` and maintain a vector/map of Optimizations Function IDs that need to be skipped for each of the available backends where they have a fast implementation. This sounds perfect.

**Comment by certik** [comment]
I think it's more natural to decouple the backends from the pass, that is, the pass should not know anything about the backends. However, in order to move forward, go ahead and implement what you suggested. I think we can always refactor this later, I don't think your design closes any doors.

**Review by czgdp1807 — APPROVED** [review]

**Comment by certik** [comment]
It looks like `arrays_intrin_04_FAST` now fails, so probably has to be disabled for now.

Otherwise this PR looks great to me.

**Review by czgdp1807 — APPROVED** [review]

**Pull request merged**
