### PR TITLE
SIMD: C: Fix memory issue and enable matmul_01

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
The memory fix is taken from https://github.com/lfortran/lfortran/pull/2865.

### CODE REVIEW

**Review by Thirumalai-Shaktivel — APPROVED** [review]
LGTM!

**Comment by Thirumalai-Shaktivel** [comment]
I think `matmul_02` (with `--ignore-pragma`?), would also work. Can you check it out?

**Comment by Shaikh-Ubaid** [comment]
@Thirumalai-Shaktivel Is it good to merge or shall we wait for @certik?

**Comment by Thirumalai-Shaktivel** [comment]
Let's create a MRE (`print *, "Error: ", maxval(abs(C-C2))`), report an issue, and then merge it?

**Review by certik — APPROVED** [review]
I think this is a strict improvement, so it's fine to merge with me.

@Thirumalai-Shaktivel let me know if you see an issue against merging it.

**Comment by Thirumalai-Shaktivel** [comment]
It's fine for me to merge. But we will keep note of this issue: https://github.com/lfortran/lfortran/pull/2865#issuecomment-1816079164

**Comment by certik** [comment]
Ok, I merged it, and we'll iterate upon this.

**Pull request merged**
