### PR TITLE
[Refactor] Use a LLVMUtils functions to call LLVM APIs

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
I will make the changes for CreateLoad and CreateGEP as well here

**Comment by Thirumalai-Shaktivel** [comment]
Ready

**Review by certik — APPROVED** [review]
I think this is fine.

Is this preparing the backend to use the dict mapping of pointer types?

**Comment by Thirumalai-Shaktivel** [comment]
Yes.

**Pull request merged**
