### PR TITLE
ASR: implement IntrinsicFunction

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
A possible improvement is:
```diff
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -223,7 +223,7 @@ expr
     | NamedExpr(expr target, expr value, ttype type)
     | FunctionCall(symbol name, symbol? original_name, call_arg* args,
             ttype type, expr? value, expr? dt)
-    | IntrinsicFunction(expr* args, int intrinsic_id, ttype type, expr? value)
+    | IntrinsicFunction(expr* args, int intrinsic_id, int overload, ttype type, expr? value)
     | StructTypeConstructor(symbol dt_sym, expr* args, ttype type, expr? value)
     | EnumTypeConstructor(symbol dt_sym, expr* args, ttype type, expr? value)
     | UnionTypeConstructor(symbol dt_sym, expr* args, ttype type, expr? value)
```
Where `intrinsic_id` is just `Sin`, and `overload` is 0, 1, 2, for each signature for `Sin` (`Real4`, `Real8`, `Complex4`, `Complex8`, `Symbolic`).

**Comment by czgdp1807** [comment]
I guess this is the same as grouping all the functions into a single node and identifying them on the basis of the attribute, `intrinsic_id`. If so then I guess its the same as what I shared in our offline discussions few days back. Hence I am +1 for it as it satisfies one of my important constraints that is, avoiding too many nodes in the ASR.

**Comment by czgdp1807** [comment]
I think we need to use `IntrinsicFunction` and test it with LPython as well to get this in? So for now I am marking this as draft. Feel free to mark it as ready for review if you think we can merge this.

**Comment by certik** [comment]
We need to first finish it in LFortran, then implement and test in LPython.

**Comment by fxcoudert** [comment]
So not all Fortran intrinsics will be an `IntrinsicFunction`? I'm thinking of non-pure subroutines, like `CPU_TIME`, `DATE_AND_TIME`, `EXECUTE_COMMAND_LINE`, `GET_ENVIRONMENT_VARIABLE`, `RANDOM_INIT`, etc.

**Comment by certik** [comment]
> I'm thinking of non-pure subroutines, like `CPU_TIME`, `DATE_AND_TIME`, `EXECUTE_COMMAND_LINE`, `GET_ENVIRONMENT_VARIABLE`, `RANDOM_INIT`, etc.

We haven't made a decision on those yet. They either will go into some node like that, or a dedicated node.

**Comment by certik** [comment]
Closing in favor of #1371.

**Pull request closed without merging**
