### PR TITLE
Draft documentation for generics

### PR DESCRIPTION
**Pull request by ansharlubis**

### CODE REVIEW

**Comment by certik** [comment]
@ansharlubis thank you, I think these look great. This captures the basics, now we just need to polish it, and add any aspects that might be missing, such as the details of instantiation (where in the code it is implemented, etc.).

**Comment by ansharlubis** [comment]
TODO:
[ ] In the`generics.md`, add the detail about the code. It's fine if I put them together in the same section.

**Comment by ansharlubis** [comment]
@certik I made a different doc just to explain how to use generics. I also added more details into the original doc about the functions related to generics.

**Comment by ansharlubis** [comment]
Got it!

**Pull request merged**
