### PR TITLE
force replace a FunctionCall when original target and --realloc-lhs is true

### PR DESCRIPTION
**Pull request by gxyd**
I'll add a test case once all the tests on CI pass, and I'll decided whether to add that test case in *simplifier_pass* branch or *main*

### CODE REVIEW

**Comment by gxyd** [comment]
I'll undo the change of MRE from this PR once tests pass, as I've already created a PR for MRE against *main* branch here: https://github.com/lfortran/lfortran/pull/5012. This will allow us to have a smaller *diff* on *simplifier_pass* branch when merging into *main*.

**Comment by gxyd** [comment]
Hopefully once https://github.com/lfortran/lfortran/pull/5010 is merged in *simplifier_pass* branch, the *expected checks* which never run will disappear.

**Comment by gxyd** [comment]
E.g.; I hadn't noticed that those CI jobs aren't *required* for merging until you pointed it out.

**Comment by certik** [comment]
The change looks good.

**Comment by certik** [comment]
I added checks from master, and remove checks that were removed from master. You should synchronize the CI yaml file. Things should work now.

**Pull request merged**
