### PR TITLE
feat: implement intrinsic `compiler_version`

### PR DESCRIPTION
**Pull request by Pranavchiku**
I am firstly sorry for duplicating efforts, I didn't checkout https://github.com/lfortran/lfortran/pull/4422. I think this approach is cleaner and fits with our design of implementing intrinsic. I am not sure if there is any further cleaning possible in this PR, I would appreciate any feedback.

### CODE REVIEW

**Review by parth121101 — APPROVED** [review]
I think this is fine. This approach aligns with the rest of the intrinsics. Great Job

**Review by HarshitaKalani — APPROVED** [review]
Looks great to me. Thanks Pranav!
I'm just a little doubtful about this, since this will work without importing `iso_fortran_env`.

**Comment by certik** [comment]
See https://github.com/lfortran/lfortran/issues/4431 for the WASM failure.

**Review by certik — APPROVED** [review]
I think that's fine.

Does this ever get instantiated? If not, maybe you can put some assert in there and not even implement it. 

Maybe later we can move this to some other ASR node, as this is not really a typical elemental function. But for now I think it's probably ok.

**Pull request merged**
