### PR TITLE
Use map to store and retrieve the type of llvm::Value

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Almost ready, `intrinsics_211.f90` seems to fail. I will check that morning.

**Review by certik — APPROVED** [review]
I reviewed all the changes, I think this looks good, you got lots of tests working!

**Comment by gxyd** [comment]
> Almost ready, `intrinsics_211.f90` seems to fail. I will check that morning.

Is that issue related to: https://github.com/lfortran/lfortran/issues/4752 ?

**Comment by Thirumalai-Shaktivel** [comment]
Yes, I think so.

**Pull request merged**
