### PR TITLE
Remove a binary from git

### PR DESCRIPTION
**Pull request by certik**
This binary was committed by a mistake in #3274.

### CODE REVIEW

**Comment by certik** [comment]
I am going to merge this, but I think we should rewrite history and prune this file from git. It seems it's about 90% of the git size.... :(

**Comment by certik** [comment]
@czgdp1807, @Shaikh-Ubaid, @Thirumalai-Shaktivel any ideas how to proceed?

**Comment by Shaikh-Ubaid** [comment]
I am in the favor of rewriting the history. If someone clones an older commit of LFortran, he simply has to download this large file.

**Comment by Thirumalai-Shaktivel** [comment]
This PR change is fine, but Ubaid's comment worries me as well. 

How about removing the commit from the main branch and submitting a PR for that change again ( use `--committer-date-is-author-date` to keep the same date)?

**Comment by certik** [comment]
The point is to reduce the size of the git repository. For that it has to be completely removed, filtered out. It will change all hashes after that commit.

All other solutions seem to keep the repository size large due to this. If it was less than 1MB file, then we would probably not worry about it. But 80MB is a lot.

**Comment by Shaikh-Ubaid** [comment]
Yes 80 mb is huge size. It should not be in the repo.

**Comment by gxyd** [comment]
First apologies for the mess.

The documentation of `git filter-branch` gives a warning (https://git-scm.com/docs/git-filter-branch):
> git filter-branch has a plethora of pitfalls that can produce non-obvious manglings of the intended history rewrite (and can leave you with little time to investigate such problems since it has such abysmal performance). These safety and performance issues cannot be backward compatibly fixed and as such, its use is not recommended. Please use an alternative history filtering tool such as [git filter-repo](https://github.com/newren/git-filter-repo/). If you still need to use git filter-branch, please carefully read [SAFETY](https://git-scm.com/docs/git-filter-branch#SAFETY) (and [PERFORMANCE](https://git-scm.com/docs/git-filter-branch#PERFORMANCE)) to learn about the land mines of filter-branch, and then vigilantly avoid as many of the hazards listed there as reasonably possible.

**Comment by certik** [comment]
@gxyd, why don't you figure out how to fix this and post here the exact instructions how to clean up the git repository (with whatever tool).

Then we'll test it several times and ensure there are no other side effects besides the hashes changing.

**Comment by gxyd** [comment]
Yes. Here're the instructions for using [git filter-repo](https://github.com/newren/git-filter-repo/):

1. Install "git filter-repo": `pip install git-filter-repo`
2. ensure to make a fresh clone of https://github.com/lfortran/lfortran where we can run the git filter-repo command (to ensure nothing bad happens on the original repo)
3. run the git filter-repo `git filter-repo --invert-paths --path src/bin/main_lfortran` (from root of lfortran repo)

I noticed that it changed commit hashes dating back to commits from May 13, 2021 (yes!!). There are several possible reasons for changes in commit hashes before the first commit where the binary file was introduced.

### Verification points:
* You can see that the file `src/bin/main_lfortran` isn't present in the repo anymore
* use `git count-objects -vH` on our current repo and one after running `git filter-repo` command:

current repo:
```
count: 99
size: 1.53 MiB
in-pack: 146090
packs: 22
size-pack: 94.56 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

on new repo, having run 'git filter-repo':
```
count: 0
size: 0 bytes
in-pack: 124493
packs: 1
size-pack: 33.87 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

* count of git commits : use command `git rev-list HEAD --count` (I got 15047, as of the last commit hash '64b25fa560c16ee22abce25869227d3b85609e81' in our repo), same is the case with our current main as well


I tried using `git filter-branch` using `git filter-branch --tree-filter 'rm -f src/bin/main_lfortran' --prune-empty HEAD` (which isn't recommended though) as well, and it just takes more time (10 minutes on my machine).

I'll think of some more ways of verification as well.

**Comment by certik** [comment]
@gxyd thanks, that's a good progress. So far this cannot be used as a solution yet, since we need to preserve all hashes until https://github.com/lfortran/lfortran/pull/3274. After that hashes will change.

We got lucky that the last release happened 1 day before that PR. So let's fix this up now and release. That way at least releases will be consistent and no hash changes there.

@gxyd go ahead and try to figure out the exact commands to preserve all hashes until #3274, then prune the binary out from then.

**Comment by gxyd** [comment]
Hello @certik , I tinkered around a little. I figured that [bfg repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) helped a bit (not fully though).

Here's the branch that I've after the "clean" (i.e. removal of `src/bin/main_lfortran`) https://github.com/gxyd/lfortran/tree/bfg_filter.

Steps to reproduce:
1. Install bfg: `brew install bfg` (for mac)
2. clone a new repo in lfortran
3. create a commit where you delete `src/bin/main_lfortran` file (just like done in this PR).
4. run bfg command from with lfortran repo: `bfg --delete-files main_lfortran` (it only expects the filename, not the full path)
5. command for pruning (`bfg` itself lists it after running the previous command): `git reflog expire --expire=now --all && git gc --prune=now --aggressive`

You can try comparing current `main` and `bfg repo-cleaner` (the branch created using the above steps), [comparison of branches](https://github.com/lfortran/lfortran/compare/main...gxyd:lfortran:bfg_filter?expand .

I notice a few extra commits whose hash is also changed (I don't know why yet): 
Screenshot 2024-03-05 at 7 14 28 PM

**Comment by gxyd** [comment]
I spent most of the time trying to figure out how to make `git filter-repo` work (using different flags, reading some of its documentation), as that's supposedly more superior to `bfg repo-cleaner`. There is quite a bit of difference in the architectures of `bfg` and `git filter-repo`.

**Comment by certik** [comment]
Here is what I tried:
```console
git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch src/bin/main_lfortran' dca110d46..HEAD
```
This is using the full merge commit before the bad PR. This seems to work and do what is needed. Only hashes after that change. I pushed the branch at https://github.com/certik/lfortran/tree/main-new

Let's now verify this very carefully. 

@czgdp1807, @Shaikh-Ubaid, @Thirumalai-Shaktivel and @gxyd can you please check out the above `main-new` branch locally and ensure it is correct? Do you see any issues at all with it?

After we are sure, we will switch `main` to `main-old`, and `main-new` to `main`.

**Comment by gxyd** [comment]
@certik Surprisingly `main-new` also has the same "extra" changed commits (i.e. commits before `dca110d46`) as the ones I put up earlier. See screenshot below. And the link for comparison: https://github.com/lfortran/lfortran/compare/main...certik:lfortran:main-new?expand=1

Screenshot 2024-03-05 at 10 16 52 PM

Am I doing something wrong?

**Comment by gxyd** [comment]
Oh no, I think all is good with that, since all of those commits were merged recently: https://github.com/lfortran/lfortran/pull/2765. Even though some of those commits were made around Oct 31, 2023.

**Comment by gxyd** [comment]
`git tag` on `main-new` gives an output:
```
v0.1.0
v0.1.1
v0.1.10
v0.1.11
v0.1.12
v0.1.13
v0.1.14
v0.1.15
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.1.9
v0.10.0
v0.11.0
v0.12.0
v0.13.0
v0.13.1
v0.14.0
v0.15.0
v0.2.0
v0.3.0
v0.4.0
v0.5.0
v0.6.0
v0.7.0
v0.8.0
v0.8.1
v0.9.0
```

while the `git tag` output on current `main` is:
```
v0.1.0
v0.1.1
v0.1.10
v0.1.11
v0.1.12
v0.1.13
v0.1.14
v0.1.15
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.1.9
v0.10.0
v0.11.0
v0.12.0
v0.13.0
v0.13.1
v0.14.0
v0.15.0
v0.16.0
v0.17.0
v0.18.0
v0.19.0
v0.2.0
v0.20.0
v0.20.1
v0.20.2
v0.20.3
v0.21.0
v0.21.1
v0.21.2
v0.21.3
v0.21.4
v0.21.5
v0.22.0
v0.23.0
v0.24.0
v0.25.0
v0.26.0
v0.27.0
v0.28.0
v0.29.0
v0.3.0
v0.30.0
v0.31.0
v0.32.0
v0.33.0
v0.33.1
v0.4.0
v0.5.0
v0.6.0
v0.7.0
v0.8.0
v0.8.1
v0.9.0
```

I'm not sure how important these are, but I guess that's one difference between the two.

**Comment by certik** [comment]
Ok, once issue is that the pitfalls mentioned here https://git-scm.com/docs/git-filter-branch#SAFETY seem quite serious, and non-obvious. We might only notice problems later.

Let's redo this with either https://github.com/rtyley/bfg-repo-cleaner or https://github.com/newren/git-filter-repo, neither of which seems maintained lately unfortunately. The https://github.com/newren/git-filter-repo seems a little more maintained.

**Comment by gxyd** [comment]
Yes, we probably should use `git filter-repo` with the below command:
```bash
git filter-repo --path src/bin/main_lfortran --invert-paths --refs dca110d46..HEAD
```

we can also use `git gc` just after that command as well. Here's the branch where I pushed the changes: [main-new](https://github.com/gxyd/lfortran/tree/main-new). It automatically preserves the `git tag`'s all of them as expected from "safety precautions"

**Comment by certik** [comment]
I pushed the latest branch at https://github.com/certik/lfortran/tree/main-new2, using git-filter-repo.

**Comment by certik** [comment]
It seems the hashes are identical to your branch as well:

https://github.com/gxyd/lfortran/commit/3d13f13a81cb0673cfca6cb4a4fef7b34cb48282
https://github.com/certik/lfortran/commit/3d13f13a81cb0673cfca6cb4a4fef7b34cb48282

That's good news.

**Comment by certik** [comment]
Ok, I just forced pushed into main.

Summary:

* Old main was moved to `old-main`
* The main branch has been replaced with the fixed branch.
* The latest commit in old main (now part of `old-main`) was bd8e83cbd9d85034eb1a9474d8d26a51bfb35117
* The equivalent commit of the new main (now part of `main`) is aafa829bb6bf942f90ea7911660933f2e6c2b9c6
* The last common shared commit in both branches is dca110d46606d068dbca0fb334b4bf612ab4011d, after which both branches diverge

All PRs and any branches that people have now must be rebased on top of the latest `main`. You can use the `old-main` branch to help the process, for example you can squash a long history into just one commit on top of `old-main` first, then rebase on top of `main`.

**Pull request closed without merging**
