### PR TITLE
Indent all test results

### PR DESCRIPTION
**Pull request by certik**
This should make it much easier to see the diffs to tests.

This seems to add about 1MB to the git repository (from 22MB to 23MB), so we should not do these changes often.

### CODE REVIEW

**Comment by certik** [comment]
Here is an example diff that one might get:
```diff
diff --git a/integration_tests/allocate_03.f90 b/integration_tests/allocate_03.f90
index 768035f09..8632d9fbe 100644
--- a/integration_tests/allocate_03.f90
+++ b/integration_tests/allocate_03.f90
@@ -17,7 +17,7 @@ contains
 subroutine f(c)
     integer, allocatable, intent(out) :: c(:, :, :)
     allocate(c(3, 3, 3))
-    c(1, 1, 1) = 99
+    c(1, 1, 2) = 98
 end subroutine
 
 function g(x) result(r)
@@ -26,7 +26,7 @@ function g(x) result(r)
     print *, x(1, 1, 1)
     call f(x)
     print *, x(1, 1, 1)
-    x(1, 1, 1) = 8
+    x(1, 1, 1) = 8+3
     r = 0
 end function
 
diff --git a/tests/reference/asr-allocate_03-e19518c.json b/tests/reference/asr-allocate_03-e19518c.json
index 3e62d3b73..58f0cc621 100644
--- a/tests/reference/asr-allocate_03-e19518c.json
+++ b/tests/reference/asr-allocate_03-e19518c.json
@@ -2,11 +2,11 @@
     "basename": "asr-allocate_03-e19518c",
     "cmd": "lfortran --indent --show-asr --no-color {infile} -o {outfile}",
     "infile": "tests/../integration_tests/allocate_03.f90",
-    "infile_hash": "cc91318a8c55753718f222c8b5aa1722c4bcad1ff8252f830ce98647",
+    "infile_hash": "9d57bde4a56c0e819c4fe6270c6a185f86f7f2964a8fbca13d59a3bf",
     "outfile": null,
     "outfile_hash": null,
     "stdout": "asr-allocate_03-e19518c.stdout",
-    "stdout_hash": "77874a8db579010590aca50f21e4c0c19ebf497bc38f096f9ae42144",
+    "stdout_hash": "8a6816bb59cbd007e850efea0707d30339d1a75687acfa2b020ce3cd",
     "stderr": null,
     "stderr_hash": null,
     "returncode": 0
diff --git a/tests/reference/asr-allocate_03-e19518c.stdout b/tests/reference/as
r-allocate_03-e19518c.stdout
index a147c693b..77aa0b858 100644
--- a/tests/reference/asr-allocate_03-e19518c.stdout
+++ b/tests/reference/asr-allocate_03-e19518c.stdout
@@ -77,12 +77,12 @@
                                             (IntegerConstant 1 (Integer 4 [])) 
                                             ())
                                             (() 
-                                            (IntegerConstant 1 (Integer 4 [])) 
+                                            (IntegerConstant 2 (Integer 4 [])) 
                                             ())] 
                                             (Integer 4 []) 
                                             ()
                                         ) 
-                                        (IntegerConstant 99 (Integer 4 [])) 
+                                        (IntegerConstant 98 (Integer 4 [])) 
                                         ()
                                     )] 
                                     () 
@@ -200,7 +200,13 @@
                                             (Integer 4 []) 
                                             ()
                                         ) 
-                                        (IntegerConstant 8 (Integer 4 [])) 
+                                        (IntegerBinOp 
+                                            (IntegerConstant 8 (Integer 4 [])) 
+                                            Add 
+                                            (IntegerConstant 3 (Integer 4 [])) 
+                                            (Integer 4 []) 
+                                            (IntegerConstant 11 (Integer 4 []))
+                                        ) 
                                         ()
                                     )
                                     (= 
```

**Comment by certik** [comment]
I don't know if we should do this, or wait until we improve our `--indent` to be maybe more succinct.

CC @konradha, @czgdp1807, @Thirumalai-Shaktivel.

**Comment by Thirumalai-Shaktivel** [comment]
I think this should be in, because later while improving the `--indent`, we reduce or alter some of the Semantic information. This PR would help us to see the difference!

**Comment by Thirumalai-Shaktivel** [comment]
> Here is an example diff that one might get from now on:
> 
> ```diff
> diff --git a/integration_tests/allocate_03.f90 b/integration_tests/allocate_03.f90
> index 768035f09..8632d9fbe 100644
> --- a/integration_tests/allocate_03.f90
> +++ b/integration_tests/allocate_03.f90
> @@ -17,7 +17,7 @@ contains
>  subroutine f(c)
>      integer, allocatable, intent(out) :: c(:, :, :)
>      allocate(c(3, 3, 3))
> -    c(1, 1, 1) = 99
> +    c(1, 1, 2) = 98
>  end subroutine
>  
>  function g(x) result(r)
> @@ -26,7 +26,7 @@ function g(x) result(r)
>      print *, x(1, 1, 1)
>      call f(x)
>      print *, x(1, 1, 1)
> -    x(1, 1, 1) = 8
> +    x(1, 1, 1) = 8+3
>      r = 0
>  end function
>  
> diff --git a/tests/reference/asr-allocate_03-e19518c.json b/tests/reference/asr-allocate_03-e19518c.json
> index 3e62d3b73..58f0cc621 100644
> --- a/tests/reference/asr-allocate_03-e19518c.json
> +++ b/tests/reference/asr-allocate_03-e19518c.json
> @@ -2,11 +2,11 @@
>      "basename": "asr-allocate_03-e19518c",
>      "cmd": "lfortran --indent --show-asr --no-color {infile} -o {outfile}",
>      "infile": "tests/../integration_tests/allocate_03.f90",
> -    "infile_hash": "cc91318a8c55753718f222c8b5aa1722c4bcad1ff8252f830ce98647",
> +    "infile_hash": "9d57bde4a56c0e819c4fe6270c6a185f86f7f2964a8fbca13d59a3bf",
>      "outfile": null,
>      "outfile_hash": null,
>      "stdout": "asr-allocate_03-e19518c.stdout",
> -    "stdout_hash": "77874a8db579010590aca50f21e4c0c19ebf497bc38f096f9ae42144",
> +    "stdout_hash": "8a6816bb59cbd007e850efea0707d30339d1a75687acfa2b020ce3cd",
>      "stderr": null,
>      "stderr_hash": null,
>      "returncode": 0
> diff --git a/tests/reference/asr-allocate_03-e19518c.stdout b/tests/reference/as
> r-allocate_03-e19518c.stdout
> index a147c693b..77aa0b858 100644
> --- a/tests/reference/asr-allocate_03-e19518c.stdout
> +++ b/tests/reference/asr-allocate_03-e19518c.stdout
> @@ -77,12 +77,12 @@
>                                              (IntegerConstant 1 (Integer 4 [])) 
>                                              ())
>                                              (() 
> -                                            (IntegerConstant 1 (Integer 4 [])) 
> +                                            (IntegerConstant 2 (Integer 4 [])) 
>                                              ())] 
>                                              (Integer 4 []) 
>                                              ()
>                                          ) 
> -                                        (IntegerConstant 99 (Integer 4 [])) 
> +                                        (IntegerConstant 98 (Integer 4 [])) 
>                                          ()
>                                      )] 
>                                      () 
> @@ -200,7 +200,13 @@
>                                              (Integer 4 []) 
>                                              ()
>                                          ) 
> -                                        (IntegerConstant 8 (Integer 4 [])) 
> +                                        (IntegerBinOp 
> +                                            (IntegerConstant 8 (Integer 4 [])) 
> +                                            Add 
> +                                            (IntegerConstant 3 (Integer 4 [])) 
> +                                            (Integer 4 []) 
> +                                            (IntegerConstant 11 (Integer 4 []))
> +                                        ) 
>                                          ()
>                                      )
>                                      (= 
> ```

Here only the some lines are altered. So, I'm +1 on this.

**Review by czgdp1807 — APPROVED** [review]
Its okay to have these. Other than a lot of spaces and new lines there is no downside to merging this.

**Review by Thirumalai-Shaktivel — APPROVED** [review]

**Comment by certik** [comment]
ok then, I'll regenerate and get this in.

**Comment by certik** [comment]
All right, let's see how it goes!

**Pull request merged**
