### PR TITLE
Use create_* type as return type for instantiate_*

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
There is some issue with the CI!! 
There are no changes in this PR. But still, the CI fails!

**Comment by Thirumalai-Shaktivel** [comment]
Aim: Compute the return type in the `create_*` function `AST-> ASR`, store it as the type for `IntrinisicFunction`, and later in the ASR pass we can use type, this reduces the repeated computing of type in the `instantiate_*`.

**Comment by Thirumalai-Shaktivel** [comment]
This is ready!

**Review by certik — APPROVED** [review]
I think this looks good, thanks!

**Comment by Thirumalai-Shaktivel** [comment]
Thank you!

**Pull request merged**
