### PR TITLE
WASM: Implement set_exit_code()

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://gitlab.com/lfortran/lfortran/-/issues/763

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
The `CI` failed on the first run for `CI / LFortran CI (3.10, macos-latest) (pull_request) `. It passed on re-run.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by certik** [comment]
The failure on macOS was most likely due to https://gitlab.com/lfortran/lfortran/-/issues/758.

**Review by certik — APPROVED** [review]
I think that looks good.

**Pull request merged**
