### PR TITLE
Implementation of `procedure(fn) :: x` (II)

### PR DESCRIPTION
**Pull request by certik**
Implements `type_declaration` in `Variable`.

### CODE REVIEW

**Comment by czgdp1807** [comment]
This fails CI tests, so marking it as draft.

**Comment by Pranavchiku** [comment]
I am trying if I can get tests pass for this PR.

**Comment by Pranavchiku** [comment]
The trouble was in `src/lfortran/tests/test_llvm.cpp` it has a hardcoded ASR check, that needs to be updated. I think the tests will now pass.

**Review by Pranavchiku — APPROVED** [review]
I cross-checked the updates, every Variable is covered. This looks good to me.

**Comment by certik** [comment]
Awesome, thanks for this @Pranavchiku !

**Pull request merged**
