### PR TITLE
Fix bug in implicit typing for function declaration

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/2722

### CODE REVIEW

**Review by certik — APPROVED** [review]
Awesome, thanks! I see, we enabled implicit typing for that dftatom test, which triggered this.

@Pranavchiku does this look good to you?

**Comment by certik** [comment]
I tested this in dftatom, it works!!

**Comment by certik** [comment]
If tests pass, let's merge it. @Pranavchiku still review it, if there are any bugs introduced, we can send a PR fixing this.

**Review by Pranavchiku — COMMENTED** [review]
The changes look good to me. Thanks for fixing this!

**Comment by certik** [comment]
Perfect, thanks!

**Pull request merged**
