### PR TITLE
Add build scripts for Windows

### PR DESCRIPTION
**Pull request by certik**
Here is how to build on Windows. From the `cmd.exe` shell, load the `lf` Conda environment (see the docs), then:
```
build0.bat
build1.bat
```
And it will build lfortran as `src/bin/lfortran.exe`.

### CODE REVIEW

**Comment by certik** [comment]
You have to install MSVC, which is free to install. I used Mambaforge: https://github.com/conda-forge/miniforge#mambaforge, which gives you a shell on a desktop that I used above.

**Comment by certik** [comment]
We should also add a Conda environment file with the exact packages and versions, so you can just install the `lf` environment with one command easily. I'll try to do that later. For now you have to install all the needed packages like `m2-bison`, `xonsh`, `re2c`, etc. by hand.

**Comment by faze-geek** [comment]
Hi @certik, I run `lpython` on Mac-OS as of now without any issue. Although I recall I had failed when I tried on my Windows machine. 
`conda env create -f environment.yml` here it gives missing `bison=3.4` error. 

Firstly is it purely for windows OS (without VM and WSL) ? And secondly is this the correct replacement -
```
conda update -q conda
conda install -c conda-forge python=3.7 re2c m2-bison xonsh llvmdev=11.1.0 jupyter xeus=1.0.1 xtl nlohmann_json cppzmq jupyter_kernel_test pytest

# Takes a lot of time to execute as far as I remember.
```

**Comment by certik** [comment]
@faze-geek I tested this PR directly on Windows (no VM, no WSL). I think what you have is correct in the Conda command.

**Comment by certik** [comment]
I am going to go ahead and merge this. We can improve upon it later if needed.

**Comment by faze-geek** [comment]
> @faze-geek I tested this PR directly on Windows (no VM, no WSL). I think what you have is correct in the Conda command.

Thanks .I'll test it on my windows machine right now !

**Comment by faze-geek** [comment]
And I'll update the Lpython [README](https://github.com/lcompilers/lpython/blob/b3553970335b776fb8bdae4c25568aa3d0f126ce/README.md) for windows as currently the command only works on Linux/mac.

**Comment by certik** [comment]
Can you create a Conda environment file for Windows and Linuix? Like `lpython/environment.yml`. Just add:
```
environment-win.yml
environment.yml
```
And the same for LPython.

**Comment by faze-geek** [comment]
```
name: lf
channels:
  - conda-forge
dependencies:
  - bison=3.4
  #- cmake
  - cppzmq
  #- flake8
  - jupyter
  - jupyter_kernel_test
  - llvmdev=11.1.0
  #- make
  - nlohmann_json
  #- pip
  - pytest
  - python=3.7
  - re2c
  #- setuptools
  #- toml
  - xeus=1.0.1
  - xonsh
  - xtl
  #- zlib
```
I came up with these dependencies for the environment, the versions as per the command mentioned above. I have added # in front of the those I was not certain about. Kindly check it once and tell me about the unnecessary ones.

**Pull request merged**
