### PR TITLE
Handle class type issues in deallocate, subroutine call and function call

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by certik** [comment]
Excellent, it would be nice to finish it, since a lot of work was already done on this. What needs to be done to finish it?

**Comment by Thirumalai-Shaktivel** [comment]
I will add some more commits from STF PR; After that, I will fix the CI and then this PR would be ready for review.

**Comment by certik** [comment]
Excellent, thanks @Thirumalai-Shaktivel!

**Comment by Thirumalai-Shaktivel** [comment]
@Smit-create I have added your commits from STF, do you want to make any changes?

Ready for review!

**Review by certik — APPROVED** [review]
I think this looks good, thanks!

**Review by Smit-create — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
