### PR TITLE
Merge main into simplifier pass

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by gxyd** [comment]
If the tests pass, this can be reviewed. As there were quite a few conflicts, and because of quite a few changes in *simplifier pass* itself as well, just a general request for the reviewer to give it an overall look.

**Comment by Pranavchiku** [comment]
Why `Check Third Party Code Compilation (macos-latest, 3.10)` and `Check Third Party Code Compilation (ubuntu-latest, 3.10)` are not running?

**Comment by gxyd** [comment]
> Check Third Party Code Compilation (macos-latest, 3.10)

Wait a minute. I didn't see that until now.

**Comment by Pranavchiku** [comment]
I reran it, let's see what happens. I do not see any change in `CI.yml` that can affect.

**Comment by gxyd** [comment]
The below jobs already succeed on our CI:
```ci
CI / Check Third Party Code Compilation - OS (macos-latest), LLVM (11) (pull_request)
CI / Check Third Party Code Compilation - OS (macos-latest), LLVM (19) (pull_request)
CI / Check Third Party Code Compilation - OS (ubuntu-latest), LLVM (11) (pull_request)
CI / Check Third Party Code Compilation - OS (ubuntu-latest), LLVM (19) (pull_request)
```

**Comment by Pranavchiku** [comment]
Ahh yes, I see. Thanks!

**Comment by gxyd** [comment]
It wouldn't allow us to merge unless all the CI jobs succeed, and the two remaining jobs are always going to be in *expected*, so this will never be allowed to merge.

We can allow merging without needing the *checks* to succeed. But, should we?

**Comment by gxyd** [comment]
@certik , do you think it's a good idea to merge this without bothering about *expected* checks?

**Comment by certik** [comment]
I merged this manually for now. I think you need to make those CI tests "pass" by simply doing nothing in them, so that GitHub allows you to merge the PR.

**Pull request merged**
