### PR TITLE
CI: update the CI job for fastGPT

### PR DESCRIPTION
**Pull request by gxyd**
I've used the Fortran compiler flag *--realloc-lhs*

### CODE REVIEW

**Review by Pranavchiku — APPROVED** [review]
This looks good but previously then why it worked without `--realloc-lhs` flag? We need to understand and document how `--realloc-lhs` affects simplifier pass.

**Comment by gxyd** [comment]
> previously then why it worked without --realloc-lhs flag? We need to understand and document how --realloc-lhs affects simplifier pass.

We had a sort of an ad hoc condition for replicating what "--realloc-lhs" does, so internally the main would eventually create a `ReAlloc` node (in `array_op` pass) in an MRE like https://github.com/lfortran/lfortran/issues/4761#issuecomment-2408887020
```f90
program main
   implicit none

   integer :: i

   type :: string
      character(:), allocatable :: s
   end type

   type(string), allocatable :: tokens(:)

   allocate(tokens(5))
   do i = 1, 5
      tokens(i)%s = "a"
   end do

   ! current *main* is smart to identify that "ReAlloc" node needs to be created for a var like below
   tokens = merge_pair(tokens, 1)

contains

   function merge_pair(intokens, idx) result(tokens)
      ! Merge the pair `idx`
      type(string), intent(in) :: intokens(:)
      integer, intent(in) :: idx
      type(string), allocatable :: tokens(:)
      type(string) :: merged_token
      merged_token%s = intokens(idx)%s // intokens(idx+1)%s
      ! The segmentation fault occurs at the below line
      tokens = [intokens(:idx-1), merged_token, intokens(idx+2:)]
   end function

end program main
```

**Comment by Pranavchiku** [comment]
Okay, let's add this as a test in main with `--realloc-lhs` and then merge main into it or simplifier to main ;)

**Comment by gxyd** [comment]
> Okay, let's add this as a test in main with --realloc-lhs and then merge main into it or simplifier to main ;)

Yes, let me do that.

I'll remember that at some point we eventually try to remove this `--realloc-lhs` compiler flag from fastGPT once we manage to merge *simplifier_pass* into *main*

**Pull request merged**
