### PR TITLE
CI: use exact version in environment.yml, check the failing nan test

### PR DESCRIPTION
**Pull request by Pranavchiku**
Refer: https://github.com/lfortran/lfortran/pull/2243#issuecomment-1693566108

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Again the test after `scipy/special/tests/test_nan_inputs.py::test_nan_inputs[eval_genlaguerre] PASSED` halts, somehow.

**Comment by Pranavchiku** [comment]
This takes around 15-20 seconds to run locally as well.

```fortran

        SUBROUTINE CGAMA(X,Y,KF,GR,GI)
        IMPLICIT DOUBLE PRECISION (A-H,O-Z)
        DIMENSION A(10)
        PI=3.141592653589793D0
        DATA A/8.333333333333333D-02,-2.777777777777778D-03, &
              7.936507936507937D-04,-5.952380952380952D-04, &
              8.417508417508418D-04,-1.917526917526918D-03, &
              6.410256410256410D-03,-2.955065359477124D-02, &
              1.796443723688307D-01,-1.39243221690590D+00/
        IF (Y.EQ.0.0D0.AND.X.EQ.INT(X).AND.X.LE.0.0D0) THEN
           GR=1.0D+300
           GI=0.0D0
           RETURN
        ELSE IF (X.LT.0.0D0) THEN
           X1=X
           Y1=Y
           X=-X
           Y=-Y
        ELSE
           Y1=0.0D0
           X1=X
        ENDIF
        X0=X
        NA=0
        IF (X.LE.7.0D0) THEN
           NA=INT(7-X)
           X0=X+NA
        ENDIF
        Z1=DSQRT(X0*X0+Y*Y)
        TH=DATAN(Y/X0)
        GR=(X0-.5D0)*DLOG(Z1)-TH*Y-X0+0.5D0*DLOG(2.0D0*PI)
        GI=TH*(X0-0.5D0)+Y*DLOG(Z1)-Y
        DO 10 K=1,10
           T=Z1**(1-2*K)
           GR=GR+A(K)*T*DCOS((2.0D0*K-1.0D0)*TH)
10         GI=GI-A(K)*T*DSIN((2.0D0*K-1.0D0)*TH)
        IF (X.LE.7.0D0) THEN
           GR1=0.0D0
           GI1=0.0D0
           DO 15 J=0,NA-1
              GR1=GR1+.5D0*DLOG((X+J)**2+Y*Y)
15            GI1=GI1+DATAN(Y/(X+J))
           GR=GR-GR1
           GI=GI-GI1
        ENDIF
        IF (X1.LT.0.0D0) THEN
           Z1=DSQRT(X*X+Y*Y)
           TH1=DATAN(Y/X)
           SR=-DSIN(PI*X)*DCOSH(PI*Y)
           SI=-DCOS(PI*X)*DSINH(PI*Y)
           Z2=DSQRT(SR*SR+SI*SI)
           TH2=DATAN(SI/SR)
           IF (SR.LT.0.0D0) TH2=PI+TH2
           GR=DLOG(PI/(Z1*Z2))-GR
           GI=-TH1-TH2-GI
           X=X1
           Y=Y1
        ENDIF
        IF (KF.EQ.1) THEN
           G0=EXP(GR)
           GR=G0*DCOS(GI)
           GI=G0*DSIN(GI)
        ENDIF
        RETURN
        END       
 
        SUBROUTINE CHGM(A,B,X)
        IMPLICIT DOUBLE PRECISION (A-B,D-H,O-Z)
        IMPLICIT COMPLEX*16 (C)
        PI=3.141592653589793D0
        A0=A
        A1=A
        X0=X
        HG=0.0D0
        IF (X.LT.0.0D0) THEN
           PRINT *, "HERE"
           A=B-A
           A0=A
           X=DABS(X)
        ENDIF
        NL=0
        LA=0
        IF (A.GE.2.0D0) THEN
           NL=1
           LA=INT(A)
           A=A-LA-1.0D0
        ENDIF
        Y0=0.0D0
        Y1=0.0D0
        PRINT *, "NL: ", NL
        DO 30 N=0,NL
           IF (A0.GE.2.0D0) A=A+1.0D0
           IF (X.LE.30.0D0+DABS(B).OR.A.LT.0.0D0) THEN
              HG=1.0D0
              RG=1.0D0
              DO 15 J=1,500
                 RG=RG*(A+J-1.0D0)/(J*(B+J-1.0D0))*X
                 HG=HG+RG
                 IF (HG.NE.0D0.AND.DABS(RG/HG).LT.1.0D-15) THEN
                    IF (X0.LT.0.0D0) HG=HG*EXP(X0)
                    GO TO 25
                 ENDIF
15            CONTINUE
           ELSE
              Y=0.0D0
              PRINT *, "CGAMA1"
              CALL CGAMA(A,Y,0,TAR,TAI)
              CTA = DCMPLX(TAR, TAI)
              Y=0.0D0
              PRINT *, "CGAMA2"
              CALL CGAMA(B,Y,0,TBR,TBI)
              CTB = DCMPLX(TBR, TBI)
              XG=B-A
              Y=0.0D0
              PRINT *, "CGAMA3"
              CALL CGAMA(XG,Y,0,TBAR,TBAI)
              CTBA = DCMPLX(TBAR, TBAI)
              SUM1=1.0D0
              SUM2=1.0D0
              R1=1.0D0
              R2=1.0D0
              DO 20 I=1,8
                 R1=-R1*(A+I-1.0D0)*(A-B+I)/(X*I)
                 R2=-R2*(B-A+I-1.0D0)*(A-I)/(X*I)
                 SUM1=SUM1+R1
20               SUM2=SUM2+R2
              IF (X0.GE.0.0D0) THEN
                 HG1=DBLE(EXP(CTB-CTBA))*X**(-A)*DCOS(PI*A)*SUM1
                 HG2=DBLE(EXP(CTB-CTA+X))*X**(A-B)*SUM2
              ELSE
                 HG1=DBLE(EXP(CTB-CTBA+X0))*X**(-A)*DCOS(PI*A)*SUM1
                 HG2=DBLE(EXP(CTB-CTA))*X**(A-B)*SUM2
              ENDIF
              HG=HG1+HG2
           ENDIF
25         IF (N.EQ.0) Y0=HG
           IF (N.EQ.1) Y1=HG
30      CONTINUE
        IF (A0.GE.2.0D0) THEN
           DO 35 I=1,LA-1
              HG=((2.0D0*A-B+X)*Y1+(B-A)*Y0)/A
              Y0=Y1
              Y1=HG
35            A=A+1.0D0
        ENDIF
        A=A1
        X=X0
        PRINT *, A, B, X, HG
        RETURN
        END

        PROGRAM MAIN
         DOUBLE PRECISION :: A, B, X, C

         A = C / 0.0D0
         B = C / 0.0D0
         X = C / 0.0D0

         CALL CHGM(A, B, C)

        END PROGRAM
```

> LFortran

```console
% time lfortran a.f90 --implicit-typing --no-warnings
NL:  1
                    inf                     inf 2.15615080202388836e-314                     nan
lfortran a.f90 --implicit-typing --no-warnings  15.77s user 0.09s system 99% cpu 15.932 total
```

> GFortran

```console
% time gfortran a.f90
a.f90:37:48:

   37 | 10         GI=GI-A(K)*T*DSIN((2.0D0*K-1.0D0)*TH)
      |                                                1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1)
a.f90:43:36:

   43 | 15            GI1=GI1+DATAN(Y/(X+J))
      |                                    1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 15 at (1)
a.f90:127:29:

  127 | 20               SUM2=SUM2+R2
      |                             1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 20 at (1)
a.f90:145:23:

  145 | 35            A=A+1.0D0
      |                       1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 35 at (1)
gfortran a.f90  0.07s user 0.03s system 90% cpu 0.108 total
% time ./a.out
 NL:            1
                  Infinity                  Infinity   2.1264142397986564E-314                       NaN
./a.out  19.91s user 0.14s system 99% cpu 20.084 total

```

**Comment by certik** [comment]
We need to create a minimal standalone reproducible example for this bug, even if we can only reproduce it at the CI.

Do you have a linux machine? If not, we need to use the CI to isolate the bug. Are you able to create a standalone Fortran code that reproduces the bug, at the CI?

As usual, creating the test is the hardest. Fixing it will be a lot easier I am guessing.

**Comment by Pranavchiku** [comment]
Yes, I have a linux machine. I will try to see if I can reproduce it there.

**Comment by Pranavchiku** [comment]
I tested on Linux Machine, the above given code halts. 
The minimal code: 
```fortran
program main
double precision :: b, c
c = 0.0D0
b = c / 0.0D0
if (b >= 2.0D0) then
print *, "b is greater than 2"
else
print *, "b is less than 2"
end if
end program
```

> Console

```console
$ lfortran b.f90
b is greater than 2
$ gfortran b.f90  && ./a.out
 b is less than 2
```

Thank you @HarshitaKalani for linux machine! This can be resolved using `OGE`, and similar.

**Comment by Pranavchiku** [comment]
I feel this will be fixed by https://github.com/lfortran/lfortran/pull/2283

**Comment by certik** [comment]
Awesome, great job figuring it out!

**Pull request closed without merging**
