### PR TITLE
Implement -I and -J (CompilerOptions edition)

### PR DESCRIPTION
**Pull request by meow464**
Not as large as it seems, most of it is just adding a new parameter to `pass_do_loop()` and friends.

What was done:

1. -I and -J are saved in [`CompilerOptions`](https://github.com/lfortran/lfortran/blob/main/src/libasr/utils.h);
2. The pass functions in [PassManager.h](https://github.com/lfortran/lfortran/blob/main/src/libasr/pass/pass_manager.h) all need to receive `CompilerOptions` because they have to be the same type. But only `fma`, `flipsign` and `sign_from_value` indirectly pass it down to [`find_and_load_module()`](https://github.com/lfortran/lfortran/blob/main/src/libasr/asr_utils.cpp#L237) through  the auxiliary functions `get_fma`, `get_flipsign` and `get_sign_from_value` in [pass_utils.cpp](https://github.com/lfortran/lfortran/blob/main/src/libasr/pass/pass_utils.cpp)

Notes:

1. Almost all visitor classes receive `rl_path` and do nothing with it. I kept this behavior but IMO would be cleaner to either pass them `const PassOptions&` and `const CompilerOptions&`;
2. I did change rl_path to `std::filesystem::path` because it is now used together with `mod_dir` and `include_dirs` which are of the same type.
3. `get_runtime_library_dir()` was moved to `libasr/utils.h` because that's the only place it's used now. `lfortran/utils.h` was deleted because it was empty. There is a comment on `libasr/utils.h`talking a bit more about this, basically PassOptions and CompilerOptions structs could be organized a bit differently but that would greatly complicate this PR.
4. There shouldn't be much to -l and -L but I kept getting ld errors and -I and -J are already blocking 3 issues.

Old [pull request](https://github.com/lfortran/lfortran/pull/598)

### CODE REVIEW

**Comment by meow464** [comment]
What is the command to run tests locally? `./run_tests.py` and `xonsh ci/build.xsh` give me different errors.

**Comment by certik** [comment]
Yes `./run_tests.py`. Let me have a look at this later today and help. Thanks for working on this, we definitely need it.

**Comment by meow464** [comment]
<details>
<summary>
ctest && ./run_tests.py
</summary>

```
$ git clone git@github.com:meow464/lfortran.git lfortran-tests
$ cd lfortran-tests/
$ ctest
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]
$ ./run_tests.py
 START TEST:  subroutine1.f90                                                                                                                                                                              
 START TEST:  ../integration_tests/template_add.f90
 START TEST:  subroutine2.f90            
 START TEST:  subroutine3.f90            
 START TEST:  subroutine3b.f90        
 START TEST:  do1.f90             
 START TEST:  do2.f90                    
 START TEST:  do3.f90              
 START TEST:  do4.f90                    
 START TEST:  do5.f90                 
 START TEST:  do6.f90                    
 START TEST:  do7.f90                    
 START TEST:  subroutine4.f90        
 START TEST:  do_concurrent_reduce.f90
 START TEST:  do_concurrent_reduce2.f90
 START TEST:  do_concurrent_reduce3.f90
subroutine3b.f90 * ast ✓       
do3.f90 * ast ✓                           
 START TEST:  subroutine5.f90    
subroutine1.f90 * tokens ✓         
do2.f90 * ast ✓                   
 START TEST:  subroutine6.f90                                                                             
subroutine3.f90 * ast ✓                 
do6.f90 * ast ✓                                                                                                                                                                                                      
 START TEST:  subroutine7.f90                 
do4.f90 * ast ✓                                                                                                                                                                                                      
 START TEST:  errors/array_size_01.f90 
do5.f90 * ast ✓                                                                                                                                                                                                      
 START TEST:  errors/array_size_02.f90 
do7.f90 * llvm ✓                                                                                                                                                                                                     
 START TEST:  errors/array_size_03.f90 
do1.f90 * ast ✓                                                                                                                                                                                                      
 START TEST:  errors/array_size_04.f90         
subroutine2.f90 * ast ✓                                                                                   
do_concurrent_reduce2.f90 * ast ✓ 
../integration_tests/template_add.f90 * ast ✓                                                                                                                                                                        
subroutine4.f90 * ast ✓      
do_concurrent_reduce.f90 * ast ✓                                                                          
do_concurrent_reduce3.f90 * ast ✓    
subroutine3b.f90 * asr ✓                           
subroutine7.f90 * ast ✓                                                                                   
subroutine5.f90 * ast ✓                                                                                   
subroutine3.f90 * asr ✓              
subroutine1.f90 * ast ✓      
subroutine6.f90 * ast ✓                                                                                   
errors/array_size_02.f90 * asr ✓                                                                          
 START TEST:  errors/array_size_05.f90                                                                    
errors/array_size_01.f90 * asr ✓        
 START TEST:  errors/matrix_transpose_01.f90 
errors/array_size_03.f90 * asr ✓                                                                                                                                                                            
 START TEST:  errors/matrix_matmul_01.f90
errors/array_size_04.f90 * asr ✓         
 START TEST:  errors/matrix_matmul_02.f90
do_concurrent_reduce3.f90 * ast_f90 ✓ 
subroutine2.f90 * julia ✓         
 START TEST:  errors/matrix_matmul_03.f90
subroutine4.f90 * ast_f90 ✓        
 START TEST:  errors/matrix_matmul_04.f90
do_concurrent_reduce2.f90 * ast_f90 ✓ 
 START TEST:  errors/matrix_matmul_05.f90
 START TEST:  errors/matrix_matmul_06.f90
do_concurrent_reduce.f90 * ast_f90 ✓ 
subroutine7.f90 * asr ✓            
subroutine5.f90 * asr ✓   
subroutine3b.f90 * julia ✓         
subroutine3.f90 * llvm ✓       
 START TEST:  errors/array_transfer_01.f90
errors/array_size_05.f90 * asr ✓ 
subroutine1.f90 * ast_indent ✓     
 START TEST:  errors/esub1.f90    
 START TEST:  errors/esub2.f90                                                                            
errors/matrix_transpose_01.f90 * asr ✓  
 START TEST:  errors/subroutine5.f90                                                                                                                                                                                 
../integration_tests/template_add.f90 * asr ✓ 
errors/matrix_matmul_01.f90 * asr ✓                                                                                                                                                                                  
 START TEST:  errors/dim_assgn_test.f90
errors/matrix_matmul_04.f90 * asr ✓                                                                                                                                                                                  
 START TEST:  errors/type_mismatch1.f90
 START TEST:  errors/redeclaration1.f90                                                                                                                                                                              
 START TEST:  errors/type_mismatch2.f90
errors/matrix_matmul_02.f90 * asr ✓                                                                                                                                                                                  
errors/matrix_matmul_05.f90 * asr ✓            
errors/matrix_matmul_03.f90 * asr ✓                                                                       
 START TEST:  errors/cpp3.f90
 START TEST:  errors/cpp1.f90                                                                                                                                                                                        
 START TEST:  errors/cpp2.f90
errors/matrix_matmul_06.f90 * asr ✓                                                                       
 START TEST:  errors/cpp4.f90        
errors/array_transfer_01.f90 * asr ✓               
subroutine7.f90 * julia ✓                                                                                 
 START TEST:  errors/cpp5.f90                                                                             
subroutine5.f90 * cpp ✓              
 START TEST:  errors/cpp6.f90
subroutine1.f90 * asr_indent ✓                                                                            
subroutine3.f90 * obj ✓                                                                                   
errors/esub1.f90 * tokens ✓                                                                               
errors/dim_assgn_test.f90 * asr ✓       
 START TEST:  errors/cpp7.f90 
errors/esub2.f90 * tokens ✓                                                                                                                                                                                 [49/1986]
errors/subroutine5.f90 * asr ✓        
 START TEST:  warnings/dim_assgn_test.f90
errors/type_mismatch2.f90 * asr ✓ 
 START TEST:  preprocessor1.f90
errors/type_mismatch1.f90 * asr ✓ 
 START TEST:  preprocessor2.f90
errors/cpp3.f90 * asr_preprocess ✓ 
 START TEST:  preprocessor3.f90
errors/redeclaration1.f90 * asr ✓ 
 START TEST:  preprocessor4.f90 
errors/cpp5.f90 * asr_preprocess ✓ 
 START TEST:  preprocessor5.f90 
errors/cpp2.f90 * asr_preprocess ✓ 
subroutine5.f90 * julia ✓ 
errors/cpp6.f90 * asr_preprocess ✓ 
 START TEST:  preprocessor6.f90
 START TEST:  preprocessor7.f90
 START TEST:  preprocessor8.f90
errors/cpp4.f90 * asr_preprocess ✓ 
subroutine1.f90 * julia ✓         
errors/cpp1.f90 * asr_preprocess ✓                                                                        
 START TEST:  preprocessor9.f90         
 START TEST:  preprocessor10.f90                                                                                                                                                                                     
 START TEST:  preprocessor11.f90
errors/cpp7.f90 * asr_preprocess ✓                                                                                                                                                                                   
errors/esub2.f90 * ast ✓   
errors/esub1.f90 * ast ✓                                                                                                                                                                                             
 START TEST:  preprocessor12.f90
 START TEST:  expr1.f90                                                                                                                                                                                              
 START TEST:  expr2.f90  
preprocessor2.f90 * asr_preprocess ✓                                                                                                                                                                                 
 START TEST:  expr3.f90                        
preprocessor1.f90 * asr_preprocess ✓                                                                      
 START TEST:  expr4.f90
subroutine3.f90 * julia ✓                                                                                                                                                                                            
 START TEST:  expr5.f90
warnings/dim_assgn_test.f90 * asr ✓                                                                       
preprocessor4.f90 * asr_preprocess ✓ 
preprocessor5.f90 * asr_preprocess ✓               
preprocessor3.f90 * asr_preprocess ✓                                                                      
preprocessor6.f90 * asr_preprocess ✓                                                                      
preprocessor8.f90 * asr_preprocess ✓ 
expr1.f90 * ast ✓ 
expr2.f90 * ast ✓                                                                                         
preprocessor9.f90 * asr_preprocess ✓                                                                      
preprocessor7.f90 * asr_preprocess ✓                                                                      
preprocessor10.f90 * asr_preprocess ✓   
preprocessor11.f90 * asr_preprocess ✓  
expr3.f90 * ast ✓ 
preprocessor12.f90 * asr_preprocess ✓ 
expr4.f90 * ast ✓ 
expr5.f90 * ast ✓ 
expr2.f90 * asr ✓ 
expr1.f90 * asr ✓ 
expr4.f90 * asr ✓ 
expr5.f90 * asr ✓ 
expr3.f90 * asr ✓ 
expr1.f90 * pass_global_stmts ✓ 
expr2.f90 * pass_global_stmts ✓ 
expr4.f90 * pass_global_stmts ✓ 
expr3.f90 * pass_global_stmts ✓ 
expr5.f90 * llvm ✓ 
expr1.f90 * llvm ✓ 
expr2.f90 * llvm ✓ 
expr3.f90 * llvm ✓ 
expr4.f90 * llvm ✓ 
expr5.f90 * obj ✓ 
expr2.f90 * obj ✓ 
Traceback (most recent call last):
  File "/home/tuco/Projetos/LFortran/lfortran-tests/./run_tests.py", line 251, in <module>
    tester_main("LFortran", single_test)
  File "/home/tuco/Projetos/LFortran/lfortran-tests/src/libasr/compiler_tester/tester.py", line 412, in tester_main
    for f in futures:
  File "/home/tuco/local/opt/miniconda3/envs/lfortran-dev/lib/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/home/tuco/local/opt/miniconda3/envs/lfortran-dev/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/tuco/local/opt/miniconda3/envs/lfortran-dev/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/tuco/local/opt/miniconda3/envs/lfortran-dev/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tuco/Projetos/LFortran/lfortran-tests/./run_tests.py", line 112, in single_test
    run_test(
  File "/home/tuco/Projetos/LFortran/lfortran-tests/src/libasr/compiler_tester/tester.py", line 329, in run_test
    raise RunException(
compiler_tester.tester.RunException: Testing with reference output failed.
subroutine4.f90 * ast_openmp
The JSON metadata differs against reference results
Reference JSON: tests/reference/ast_openmp-subroutine4-0411983.json
Output JSON:    tests/output/ast_openmp-subroutine4-0411983.json
Omitting 6 identical items
Differing items:
{'stderr_hash': '1cdcf86a8ccbac0c283b0e8020de3ad7133b058ab4d5bea9462a1578'} != {'stderr_hash': None}
{'stdout': None} != {'stdout': 'ast_openmp-subroutine4-0411983.stdout'}
{'stderr': 'ast_openmp-subroutine4-0411983.stderr'} != {'stderr': None}
{'returncode': 127} != {'returncode': 0}
{'stdout_hash': None} != {'stdout_hash': 'bfc588ec282e44ae729cf232795342f3381ef3dc2725b5641be40f23'}No output stdout_hash available for subroutine4.f90


```
</details>

**Comment by meow464** [comment]
<details>

<summary>
I'm trying to run the CI scripts on an ubuntu VM
</summary>

```
$ ./build0.sh && LFORTRAN_CMAKE_GENERATOR=Ninja CMAKE_C_COMPILER_LAUNCHER=clang CMAKE_CXX_COMPILER_LAUNCHER=clang++ xonsh ci/build_tmp.xsh

[a lot of stuff here]

If you want to connect to this kernel from an other client, you can use the /tmp/tmpmj0xvxs9.json file.
Run with XEUS 2.4.1
[NbConvertApp] Writing 11128 bytes to Variables_out.ipynb
ci/build_tmp.xsh:84:cp lfortran-$lfortran_version/test-bld/src/bin/lfortran src/bin
ci/build_tmp.xsh:85:cp lfortran-$lfortran_version/test-bld/src/bin/cpptranslate src/bin
ci/build_tmp.xsh:86:if $IS_WIN:
ci/build_tmp.xsh:89:    cp lfortran-$lfortran_version/test-bld/src/runtime/liblfortran_runtime* src/runtime/
ci/build_tmp.xsh:90:cp lfortran-$lfortran_version/test-bld/src/runtime/*.mod src/runtime/
Exception ignored in: <function _removeHandlerRef at 0x7f5450728e50>
Traceback (most recent call last):
  File "/home/tuco/miniconda3/envs/lfortran-dev/lib/python3.10/logging/__init__.py", line 836, in _removeHandlerRef
  File "/home/tuco/miniconda3/envs/lfortran-dev/lib/python3.10/site-packages/xonsh/tracer.py", line 87, in trace
TypeError: 'NoneType' object is not callable
```

</details>

**Comment by meow464** [comment]
I can replicate the errors on my machine.

**Comment by meow464** [comment]
We are almost there, gonna finish this tomorrow.

**Comment by meow464** [comment]
@certik ready for review :)

`lfortran -c sum.f90 -J mods/` 
Will generate my_module.mod under mods/

`lfortran example.f90 -J mods/`
Will compile, run and output 18.000000

example.f90
```
program example
  use my_module
  implicit none
  real :: x,y

  x = 8.0
  call sum_ten(x,y)
  print *, y
end program example
```

sum.f90
```
module my_module
  contains
    subroutine sum_ten(a,b)
      implicit none
      real, intent(in) :: a
      real, intent(out) :: b
      b = a + 10
    end subroutine sum_ten
end module my_module
```

**Comment by certik** [comment]
Shouldn't the second command use `-I` ?

**Comment by certik** [comment]
I merged with the latest main, to see if tests run.

**Comment by meow464** [comment]
-I works too.
According to the CMake [documentation](https://cmake.org/cmake/help/latest/prop_tgt/Fortran_MODULE_DIRECTORY.html) some compilers search -J for USEd modules.
[Gcc](https://gcc.gnu.org/onlinedocs/gcc-4.3.3/gfortran/Directory-Options.html#Directory-Options) is one example.

**Comment by certik** [comment]
Awesome, thanks a lot @meow464 for this!

@czgdp1807 do you want to review this PR to see how it fits with the ASR passes design?

**Comment by certik** [comment]
It seems this PR contains a few unrelated changes. I can try to simplify it. For example we might be able to use PassOptions to pass in the paths. That will avoid a lot of changes.

**Comment by meow464** [comment]
My initial idea was to use PassOptions but it's instantiated by all asr_to_lang() functions and in a few other places, and not all set the same options. I guess I could just copy it and change the options?

**Comment by meow464** [comment]
I will try to do it today and tomorrow, let's see how it goes.

**Comment by meow464** [comment]
@certik The PassOptions version is smaller https://github.com/lfortran/lfortran/pull/930

**Comment by certik** [comment]
Thanks! It's smaller but still quite big. I'll work on this later today and see if I can figure this out.

**Comment by certik** [comment]
Fixed by #930.

**Pull request closed without merging**
