### PR TITLE
Fix linking for Fortran77 files

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/2092

### CODE REVIEW

**Comment by certik** [comment]
Does the test actually fail in master? I think cmake is actually doing the two step compilation that works. It's the "lfortran .f" that I think failed?

**Comment by certik** [comment]
What I mean: if you remove the change you did in `lfortran.cpp` and run all integration tests, do they fail? It seems to me that they will not fail.

**Comment by Shaikh-Ubaid** [comment]
>What I mean: if you remove the change you did in lfortran.cpp and run all integration tests, do they fail? It seems to me that they will not fail.

Yes, you are right. The integration test added passes in main.

**Comment by Shaikh-Ubaid** [comment]
>It's the "lfortran .f" that I think failed?

Yes. Please, could you share what we should do?

**Comment by certik** [comment]
I would recommend you add the fix, but do not add any of the test changes, since those are unrelated and do not actually test this change, so we can discuss them separately (I don't actually like the test change, since I think we should treat `.f90` and `.f` exactly the same in lfortran, and by default treat both as free form modern Fortran; and if you need older features, you can use compiler options, irrespective of the source file suffix).

**Review by certik — APPROVED** [review]

**Pull request merged**
