### PR TITLE
tests: enable testing `intrinsics_311.f90` with `--realloc-lhs` flag

### PR DESCRIPTION
**Pull request by kmr-srbh**

### CODE REVIEW

**Review by certik — APPROVED** [review]

**Comment by kmr-srbh** [comment]
@gxyd can this PR be merged?

**Review by gxyd — APPROVED** [review]
I think this is actually the right way to go about it, as `minloc`'s output can change depending on the dimensions of input array (though all array arguments to `mincloc` in `intrinsics_311.f90` only have rank 1), so `--realloc-lhs` needs to be used for it.

**Comment by gxyd** [comment]
Another possibility was to have `allocate(loc(1))` in `intrinsics_311.f90` itself, but that's not always the case, once higher dimension array argument is used for `minloc`.

**Comment by certik** [comment]
Code written like this:
```
    integer, dimension(:), allocatable :: loc

    ! Find the location of the minimum value considering only elements where mas
k is true
    loc = minloc(array, mask = mask)
    print *, "Minloc with MASK:", loc
    if (any(loc /= 1)) error stop
```
Needs `--realloc-lhs`. The alternative way to write it by the user is to put the correct allocate before each call (the user knows the size of the result), and in that case that must work without `--realloc-lhs`. We can add such a test later. This PR is correct.

**Pull request merged**
