### PR TITLE
Add provision to increment do loop var in do_loops pass

### LINKED ISSUE #2067: [SciPy][Specfun]: Divergence in test output `test_riccati_yn`
This error is because of the below given subroutine in `scipy/special/specfun`, I am trying to find a minimal way to reproduce this error.
```fortran
        SUBROUTINE RCTY(N,X,NM,RY,DY)
C
C       ========================================================
C       Purpose: Compute Riccati-Bessel functions of the second
C                kind and their derivatives
C       Input:   x --- Argument of Riccati-Bessel function
C                n --- Order of yn(x)
C       Output:  RY(n) --- x·yn(x)
C                DY(n) --- [x·yn(x)]'
C                NM --- Highest order computed
C       ========================================================
C
```

```console
% python dev.py test -t scipy.special.tests.test_basic --verbose
💻  ninja -C /Users/pgoswami/Desktop/scipy/build -j8
ninja: Entering directory `/Users/pgoswami/Desktop/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /Users/pgoswami/Desktop/scipy/build-install/lib/python3.10/site-packages
Running tests for scipy version:1.12.0.dev0+1345.9b3bbc1, installed at:/Users/pgoswami/Desktop/scipy/build-install/lib/python3.10/site-packages/scipy
================================================ test session starts =================================================
platform darwin -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /Users/pgoswami/mambaforge/envs/scipy-dev/bin/python
cachedir: .pytest_cache
rootdir: /Users/pgoswami/Desktop/scipy
configfile: pytest.ini
plugins: timeout-2.1.0, cov-4.1.0, xdist-3.3.1
collected 1 item                                                                                                     

scipy/special/tests/test_basic.py::TestRiccati::test_riccati_yn FAILED                                         [100%]

====================================================== FAILURES ======================================================
____________________________________________ TestRiccati.test_riccati_yn _____________________________________________
scipy/special/tests/test_basic.py:3754: in test_riccati_yn
    assert_array_almost_equal(C, special.riccati_yn(n, x), 8)
        C          = array([[-0.98006658, -5.09900222],
       [ 0.19866933, 24.51494452]])
        N          = 2
        n          = 1
        self       = <scipy.special.tests.test_basic.TestRiccati object at 0x107a12170>
        x          = 0.2
        y          = -25.495011100006344
        yp         = 250.04977811085723
/Users/pgoswami/mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
        args       = (array([[-0.98006658, -5.09900222],
       [ 0.19866933, 24.51494452]]), (array([-0.98006658, -5.09900222]), array([0.19866933, 0.        ])), 8)
        func       = <function assert_array_almost_equal at 0x1079bb7f0>
        kwds       = {}
        self       = <contextlib._GeneratorContextManager object at 0x1079c2680>
/Users/pgoswami/mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Arrays are not almost equal to 8 decimals
E   
E   Mismatched elements: 1 / 4 (25%)
E   Max absolute difference: 24.51494452
E   Max relative difference: 5.58829599e-16
E    x: array([[-0.98006658, -5.09900222],
E          [ 0.19866933, 24.51494452]])
E    y: array([[-0.98006658, -5.09900222],
E          [ 0.19866933,  0.        ]])
        args       = (<function assert_array_almost_equal.<locals>.compare at 0x1069fd900>, array([[-0.98006658, -5.09900222],
       [ 0.19866933, 24.51494452]]), (array([-0.98006658, -5.09900222]), array([0.19866933, 0.        ])))
        func       = <function assert_array_compare at 0x1079bb640>
        kwds       = {'err_msg': '', 'header': 'Arrays are not almost equal to 8 decimals', 'precision': 8, 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x1079c25f0>
============================================== short test summary info ===============================================
FAILED scipy/special/tests/test_basic.py::TestRiccati::test_riccati_yn - AssertionError: 
================================================= 1 failed in 0.28s ==================================================
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #2067 #2078

### CODE REVIEW

**Comment by certik** [comment]
Great job!

This will have to be hidden behind another compiler option. By default we need to start giving warnings or even errors when a loop variable is used after the loop finishes. This is bad practice. The same issue came up in LPython: https://github.com/lcompilers/lpython/issues/2202

We should also check the Fortran standard, it might even be against it. Either way, since SciPy uses it, we have to support it.

As you can see, the fix you did actually makes the code slower (sometimes it can probably be optimized out by LLVM). However by default we should not make the code slower. 

Later let's add a warning by default.

To get this PR to merge, can you add a compiler option `--use-loop-variable-after-loop` and only add those fixes in this PR when this option is set? Then we need to add this to our cmake to enable this option.

**Comment by Pranavchiku** [comment]
Yeah sure! On it.

**Comment by Pranavchiku** [comment]
Implemented at #2081 :)

**Comment by Pranavchiku** [comment]
Closing with reference to #2018.

**Pull request closed without merging**
