### PR TITLE
Add provision to check `array->m_type` in data stmt

### LINKED ISSUE #1891: [SciPy][Specfun]: semantic error: Type mismatch during data initialization
```fortran
        SUBROUTINE GAM0 (X,GA)
        IMPLICIT DOUBLE PRECISION (A-H,O-Z)
        DIMENSION G(25)
        DATA G/1.0D0,0.5772156649015329D0,
     &       -0.6558780715202538D0, -0.420026350340952D-1,
     &        0.1665386113822915D0, -.421977345555443D-1,
     &        -.96219715278770D-2, .72189432466630D-2,
     &        -.11651675918591D-2, -.2152416741149D-3,
     &         .1280502823882D-3, -.201348547807D-4,
     &        -.12504934821D-5, .11330272320D-5,
     &        -.2056338417D-6, .61160950D-8,
     &         .50020075D-8, -.11812746D-8,
     &         .1043427D-9, .77823D-11,
     &        -.36968D-11, .51D-12,
     &        -.206D-13, -.54D-14, .14D-14/
        END SUBROUTINE
```

>LFortran

```console
% lfortran a.f --fixed-form --show-asr --implicit-typing --implicit-interface
semantic error: Type mismatch during data initialization
  --> a.f:4:9 - 15:43
   |
 4 |            DATA G/1.0D0,0.5772156649015329D0,
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
15 |         &        -.206D-13, -.54D-14, .14D-14/
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #1891.

### CODE REVIEW

**Comment by Pranavchiku** [comment]
I am not sure why the two tests `CI / LFortran CI (3.10, windows-2019) (pull_request)` and `CI / Test LLVM 15 (pull_request)` failed. Given code works with `FAST` locally and `windows` test fails at post run so maybe on rerun both might work.

**Review by certik — APPROVED** [review]
I think this works. I rebased it.

**Comment by certik** [comment]
I think the failure is real, we need to fix it:
```
LCOMPILERS_ASSERT failed: /home/runner/work/lfortran/lfortran/src/libasr/../libasr/asr.h
function expr_value0(), line number 47875 at 
f != nullptr
```

**Comment by Pranavchiku** [comment]
Yeah sure! I will fix this.

**Pull request merged**
