### PR TITLE
Add more __LFORTRAN__ defines

### LINKED ISSUE #2859: Implement identification and version macros (needed for good cmake support)
https://gitlab.kitware.com/cmake/cmake/-/issues/25419#note_1446778

```
#define __lfortran__ 1
#define __lfortran_major__ 0
#define __lfortran_minor__ 29
#define __lfortran_patchlevel__ 0
```

Then release.

### PR DESCRIPTION
**Pull request by junghans**
Fix #2859

### CODE REVIEW

**Comment by certik** [comment]
Perfect, thanks! To update the reference tests, do:
```
./run_tests.py -u
```
from the main project repository.

**Comment by junghans** [comment]
> Perfect, thanks! To update the reference tests, do:
> 
> ```
> ./run_tests.py -u
> ```
> 
> from the main project repository.

Thanks and done!

**Comment by junghans** [comment]
@certik ready for review

**Review by certik — APPROVED** [review]
Beautiful, thanks!

**Pull request merged**
