### PR TITLE
CI: Bump SciPy to latest commit

### PR DESCRIPTION
**Pull request by Pranavchiku**
Branch: https://github.com/certik/scipy/commits/merge_special_minpack_fitpack_02

@HarshitaKalani can you please verify the commits once?

### CODE REVIEW

**Review by HarshitaKalani — CHANGES_REQUESTED** [review]
Rather than picking these commits: https://github.com/certik/scipy/commit/c3bbc8351f6a4a2b9dca5f5f42cdcde88c3685c8 and https://github.com/certik/scipy/commit/93b4a9f2689a693aee496bba01a25ab1069547cb, it'll be better to go with: https://github.com/certik/scipy/commit/63b55b62dd71671b0ade7409c7b5b9e2712af4fc

**Comment by Pranavchiku** [comment]
I preferred to keep each package independent, this makes it easy to pick any package if we need to test it.

**Comment by Pranavchiku** [comment]
> Rather than picking these commits: https://github.com/certik/scipy/commit/c3bbc8351f6a4a2b9dca5f5f42cdcde88c3685c8 and https://github.com/certik/scipy/commit/93b4a9f2689a693aee496bba01a25ab1069547cb, it'll be better to go with: https://github.com/certik/scipy/commit/63b55b62dd71671b0ade7409c7b5b9e2712af4fc

Yes, I changed to https://github.com/certik/scipy/commit/63b55b62dd71671b0ade7409c7b5b9e2712af4fc

**Comment by Pranavchiku** [comment]
I pushed the changes, @HarshitaKalani please check at https://github.com/certik/scipy/commits/merge_special_minpack_fitpack_02.

**Comment by HarshitaKalani** [comment]
LGTM!

**Review by HarshitaKalani — APPROVED** [review]

**Comment by certik** [comment]
Is this using the latest SciPy master?

**Comment by Pranavchiku** [comment]
Yes, along with required commits.

**Pull request merged**
