### PR TITLE
Refactor: Remove `fmt` from `Print` and `FileWrite` nodes

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
This PR is ready!

I wonder if we can use StringFormat as a value for all the cases. Does the following make sense?
```diff
diff --git a/src/libasr/ASR.asdl b/src/libasr/ASR.asdl
index 7528c79af..480440014 100644
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -193,7 +193,7 @@ stmt
     | GoToTarget(int id, identifier name)
     | If(expr test, stmt* body, stmt* orelse)
     | IfArithmetic(expr test, int lt_label, int eq_label, int gt_label)
-    | Print(expr* values, expr? separator, expr? end)
+    | Print(expr value, expr? separator, expr? end)
     | FileOpen(int label, expr? newunit, expr? filename, expr? status, expr? form)
     | FileClose(int label, expr? unit, expr? iostat, expr? iomsg, expr? err, expr? status)
     | FileRead(int label, expr? unit, expr? fmt, expr? iomsg, expr? iostat, expr? id, expr* values)
@@ -297,7 +297,7 @@ expr
     | StringCompare(expr left, cmpop op, expr right, ttype type, expr? value)
     | StringOrd(expr arg, ttype type, expr? value)
     | StringChr(expr arg, ttype type, expr? value)
-    | StringFormat(expr fmt, expr* args, string_format_kind kind, ttype type, expr? value)
+    | StringFormat(expr? fmt, expr* args, string_format_kind kind, ttype type, expr? value)
 
     | CPtrCompare(expr left, cmpop op, expr right, ttype type, expr? value)
     | SymbolicCompare(expr left, cmpop op, expr right, ttype type, expr? value)
```

**Review by certik — APPROVED** [review]
I think this change is good. Needs to be rebased and conflicts fixed.

**Comment by certik** [comment]
We could do it like this:
```diff
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -193,7 +193,7 @@ stmt
     | GoToTarget(int id, identifier name)
     | If(expr test, stmt* body, stmt* orelse)
     | IfArithmetic(expr test, int lt_label, int eq_label, int gt_label)
-    | Print(expr? fmt, expr* values, expr? separator, expr? end)
+    | Print(expr text)
     | FileOpen(int label, expr? newunit, expr? filename, expr? status, expr? form)
     | FileClose(int label, expr? unit, expr? iostat, expr? iomsg, expr? err, expr? status)
     | FileRead(int label, expr? unit, expr? fmt, expr? iomsg, expr? iostat, expr? id, expr* values)
```
That makes sense to me.

Then the next question is how to support the very common case of `print *, a, b, c` (Fortran) and `print(a, b, c)` (Python), where the print formatting is automatically set based on the types. One could do that using:
```diff
-    | StringFormat(expr fmt, expr* args, string_format_kind kind, ttype type, expr? value)
+    | StringFormat(expr? fmt, expr* args, string_format_kind kind, ttype type, expr? value)
```
Where if the "fmt" is not present, the arguments will just be printed based on the `kind` argument. Regarding `separator` and `end`, those are rare cases, and I would just create an explicit format string in those cases, and not special case it in any way.

**Comment by Thirumalai-Shaktivel** [comment]
I will submit a separate PR for this https://github.com/lfortran/lfortran/pull/2471#issuecomment-1729756399.

**Comment by Thirumalai-Shaktivel** [comment]
As this PR is already approved, I'm setting this to auto-merge.

**Pull request merged**
