### PR TITLE
Use pointer type for creating auxiliary variables for nested arrays

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lfortran/lfortran/issues/1529

### CODE REVIEW

**Comment by czgdp1807** [comment]
Same thing happening here. See, https://github.com/lfortran/lfortran/pull/1532#issuecomment-1502891105 for details.

**Comment by czgdp1807** [comment]
It fixes the problem partially. Modern minpack may not work if it uses variable sized arrays.

**Review by certik — APPROVED** [review]
This looks great. I can see two changes: it makes nested_vars to use a pointer for arrays. The other change is that it fixes some issues in the LLVM backend.

We need this for minpack, so let's get this in soon I think.

**Comment by czgdp1807** [comment]
Let me test this with LPython as well. Also may be try out uncommenting minpack code and use this branch of LFortran to build minpack. If it fails then I will send more fixes here only (if they are related to nested arrays).

**Comment by czgdp1807** [comment]
Okay. Let me apply these changes to LPython and then we will merge both the PRs together.

**Pull request merged**
