### PR TITLE
Implementing present via ASR pass

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/lfortran/lfortran/issues/1111

### CODE REVIEW

**Comment by certik** [comment]
Looks good. The test should be registered with gfortran at least.

**Comment by czgdp1807** [comment]
This PR is not ready for review yet. Once ready and all testing is done, I will ping you.

**Comment by czgdp1807** [comment]
As per https://github.com/lfortran/lfortran/issues/1111#issue-1498526950, we decided to go for the first approach. **We add boolean parameters for optional arguments and replace calls like, `present(x)` with `is_x_present`. Hence those extra arguments in the LLVM signature.** The second approach is not robust and applicable to all the backends we have. There is a third approach as well,

Say you have a function, `f(a, b, c, d, e, f)`. Now consider `d`, `e`, `f` as optional arguments. So generate 8 functions, `f(a, b, c, e, f)`, `f(a, b, c, d, f)`, `f(a, b, c, d, e)`, `f(a, b, c)` and so on with all the combinations. And generate their bodies according to the signature. This approach is also clean but would require us to generate 2^number_of_optional_arguments which doesn't scale so well and would lead to duplication of lot of code.

Hence, out of these 3 approaches I went for the first one.

**Comment by certik** [comment]
I see. That's good enough for now, especially because it is just an ASR pass, so it is good. We can always implement something else later.

**Review by certik — APPROVED** [review]

**Pull request merged**
