### PR TITLE
lfortran: hand verbose option through to linker

### PR DESCRIPTION
**Pull request by junghans**
See https://gitlab.kitware.com/cmake/cmake/-/issues/26145#note_1554135

### CODE REVIEW

**Review by certik — APPROVED** [review]
I think that should work, thanks for adding it!

Go ahead and merge this if it is ready.

**Comment by junghans** [comment]
@bradking, can you confirm that work for you?

**Comment by bradking** [comment]
I built this locally and confirmed that it works.  CMake can now detect `lfortran`'s full implicit link information.

**Comment by junghans** [comment]
@bradking thanks for testing, this fix should be part of lfortran-0.40.0 then.

**Comment by certik** [comment]
@bradking thanks for testing it, much appreciated! Thanks @junghans for the fix. I wish all bugs were so simple that a one-liner fixes them. :)

**Pull request merged**
