### PR TITLE
CI: try uncommenting C/C++ CI job

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by assem2002** [comment]
I'll try handling this one.

**Comment by assem2002** [comment]
Ondrej suggested that we can just comment out the failing test `matmul_01.f90`. After merging simplifier into main, we can work on getting this single test working.
from my end it seems that `matmul_01.f90` has some issue with array_assignment. array`C2` access parts of array `C` and modifies it which makes the program fails. I'll give it a look again, but we can just modify this PR to comment out that single test to get simplifier merged. @gxyd

**Comment by certik** [comment]
Yes, as long a this matmul_01.f90 test works with LLVM, we can fix the C++ backend after we merge simplifier.

**Comment by gxyd** [comment]
Closing this PR, as it isn't needed anymore.

**Pull request closed without merging**
