### PR TITLE
Add a few improvements to UI/UX

### PR DESCRIPTION
**Pull request by tapaswenipathak**
- Header Navigation
   Screenshot 2022-08-12 at 5 52 53 PM
   Screenshot 2022-08-12 at 5 53 02 PM
   Screenshot 2022-08-12 at 5 53 08 PM
   Screenshot 2022-08-12 at 5 53 12 PM

   Screenshot 2022-08-12 at 5 53 20 PM
- Suggestions in search
   Screenshot 2022-08-12 at 5 53 42 PM
   Screenshot 2022-08-12 at 5 56 52 PM
- GitHub URL
- Toggle to dark mode
   Screenshot 2022-08-12 at 5 53 27 PM

- Sidebar navigation improvement
- Footer Navigation

### CODE REVIEW

**Comment by certik** [comment]
I think that this is fine. How does the light-mode  / dark-mode work? Is there a way to let the user choose?

I think I personally like the light mode more, but I know others might prefer the dark mode.

**Comment by tapaswenipathak** [comment]
image

image

**Comment by certik** [comment]
Perfect! Thanks for this. I merged it, let's see how it looks.

**Comment by tapaswenipathak** [comment]
Smaller device:

image

image

image

image

image

image

intrinsics looks the best! :) may be because of stress on nav indexes.

**Comment by certik** [comment]
Looks awesome!

Thank you for doing all this. Great improvement.

**Pull request merged**
