### PR TITLE
Wasm modules integration tests

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
towards https://github.com/lfortran/lfortran/issues/988

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
The tests fail currently with the following `CMake` error:
```bash
Error copying Fortran module "modules_01_a.mod".  Tried "MODULES_01_A.mod" and "modules_01_a.mod".
make[2]: *** [CMakeFiles/modules_01.dir/depend.make:8: CMakeFiles/modules_01.dir/modules_01_a.mod.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:594: CMakeFiles/modules_01.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I am unsure why `CMake` expects `.mod` files in this case. @certik please, could you possibly share if you encountered this issue before?

**Comment by Shaikh-Ubaid** [comment]
I enabled the `modules` supporting tests for `wasm` in [WASM: TEST: Enable supporting tests for modules](https://github.com/lfortran/lfortran/pull/992/commits/e2201a2a19e976eb55d31cde1dd9b5b6b71ff5e5). They work for me locally when executed using `lfortran` (without using/invoking `cmake`).

**Comment by Shaikh-Ubaid** [comment]
The `template_add` example shared here https://github.com/lfortran/lfortran/issues/988#issue-1436838448 works.

Example:
```fortran
module template_add_m
    implicit none

contains

    subroutine test_template()
        print *, "hi" ! temporary print statement added here, because wasm backend removes empty body functions/subroutines
    end subroutine

end module

program template_add
use template_add_m
implicit none

call test_template()

end program template_add
```

Output:
```bash
(lf) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lfortran$ lfortran examples/expr2.f90 --backend llvm
hi
(lf) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lfortran$ lfortran examples/expr2.f90 --backend wasm
(lf) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lfortran$ node a.out.js
hi
(lf) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lfortran$ 
```

**Comment by meow464** [comment]
Are the modfiles really where cmake is looking for them? Or in another directory?

**Comment by Shaikh-Ubaid** [comment]
>Are the modfiles really where cmake is looking for them? Or in another directory?

I am not sure. Please, could you possibly share any idea how we could check that?

**Comment by meow464** [comment]
You would need to reproduce the error locally and check the directories https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L443

**Comment by meow464** [comment]
I can't see the modfiles anywhere, not even by specifying -J. The moddir is not even created. I would suggest checking if the wasm backend is really writing modfiles.

**Comment by Shaikh-Ubaid** [comment]
I think the wasm backend is not wrting any mod files. Please, could you
possibly clarify why we need the wasm backend to write mod files?

**Comment by certik** [comment]
CMake expects mod files when compiling Fortran code for each module, so if it cannot find them, it gives an error message. I am not sure if it expects mod files if we put the module into the same file. If so, we can just check WASM like that for now.

In the long run, we'll have to figure out how to handle the mod files with the wasm backend.

**Comment by Shaikh-Ubaid** [comment]
A similar PR at LPython https://github.com/lcompilers/lpython/pull/1274,
seems to pass the tests. I guess, it is because the
`integration_tests/CMakeLists.txt` file in LPython uses `execute_process`
to run the integration test. Shall we try using `execute_process` in
`integration_tests/CMakeLists.txt` of LFortran as well?

**Comment by certik** [comment]
Try it.

**Comment by certik** [comment]
The full generics file `template_add.f90` now works:
```console
$ lfortran --no-warnings --backend=wasm template_add.f90 && node a.out.js
The result is  12.299999237060547
The result is  14
```
Great job!

Let's merge this fix even without tests so that I can test it in the browser, and we can figure out how to test this in a separate PR.

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by Shaikh-Ubaid** [comment]
Hoping that the `CI` passes now.

**Comment by certik** [comment]
I restarted the Windows build. I noticed that it sometimes fails in the interactive prompt test.

**Comment by Shaikh-Ubaid** [comment]
>I restarted the Windows build. I noticed that it sometimes fails in the interactive prompt test.

Thank you.

**Comment by Shaikh-Ubaid** [comment]
It seems we repeated some code in the `integration_tests/CMakeLists.txt` file. Dr. Ondrej, please, could you possibly review and share if it is fine?

**Review by certik — APPROVED** [review]
I tested it by hand, it seems to work, thanks!

**Pull request merged**
