### PR TITLE
AST, ASR to Json

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
towards https://github.com/lfortran/lfortran/issues/724, https://github.com/lfortran/lfortran/issues/324

I attempted to create a visualization of the generated json at https://shaikh-ubaid.github.io/ast_asr_json_visualizer/. It seems to work.

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Comment by Shaikh-Ubaid** [comment]
**Example AST:**
```bash
(lf) $ lfortran examples/expr2.f90 --show-ast --json
{
    "node": "TranslationUnit",
    "fields": {
        "items": [
            {
                "node": "Program",
                "fields": {
                    "name": "expr2",
                    "trivia": [],
                    "use": [],
                    "implicit": [
                        {
                            "node": "ImplicitNone",
                            "fields": {
                                "specs": [],
                                "trivia": {
                                    "node": "TriviaNode",
                                    "fields": {
                                        "inside": [],
                                        "after": [
                                            {
                                                "node": "EndOfLine",
                                                "fields": {}
                                            },
                                            {
                                                "node": "EndOfLine",
                                                "fields": {}
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ],
                    "decl": [
                        {
                            "node": "Declaration",
                            "fields": {
                                "vartype": {
                                    "node": "AttrType",
                                    "fields": {
                                        "type": "TypeInteger",
                                        "kind": [],
                                        "name": [],
                                        "sym": "None"
                                    }
                                },
                                "attributes": [],
                                "syms": [
                                    {
                                        "node": "var_sym",
                                        "fields": {
                                            "name": "x",
                                            "dim": [],
                                            "codim": [],
                                            "initializer": [],
                                            "sym": "None",
                                            "spec": []
                                        }
                                    }
                                ],
                                "trivia": {
                                    "node": "TriviaNode",
                                    "fields": {
                                        "inside": [],
                                        "after": [
                                            {
                                                "node": "EndOfLine",
                                                "fields": {}
                                            },
                                            {
                                                "node": "EndOfLine",
                                                "fields": {}
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ],
                    "body": [
                        {
                            "node": "Assignment",
                            "fields": {
                                "label": 0,
                                "target": {
                                    "node": "Name",
                                    "fields": {
                                        "id": "x",
                                        "member": []
                                    }
                                },
                                "value": {
                                    "node": "BinOp",
                                    "fields": {
                                        "left": {
                                            "node": "BinOp",
                                            "fields": {
                                                "left": {
                                                    "node": "Num",
                                                    "fields": {
                                                        "n": 2,
                                                        "kind": []
                                                    }
                                                },
                                                "op": "Add",
                                                "right": {
                                                    "node": "Num",
                                                    "fields": {
                                                        "n": 3,
                                                        "kind": []
                                                    }
                                                }
                                            }
                                        },
                                        "op": "Mul",
                                        "right": {
                                            "node": "Num",
                                            "fields": {
                                                "n": 5,
                                                "kind": []
                                            }
                                        }
                                    }
                                },
                                "trivia": []
                            }
                        },
                        {
                            "node": "Print",
                            "fields": {
                                "label": 0,
                                "fmt": [],
                                "values": [
                                    {
                                        "node": "Name",
                                        "fields": {
                                            "id": "x",
                                            "member": []
                                        }
                                    }
                                ],
                                "trivia": {
                                    "node": "TriviaNode",
                                    "fields": {
                                        "inside": [],
                                        "after": [
                                            {
                                                "node": "EndOfLine",
                                                "fields": {}
                                            },
                                            {
                                                "node": "EndOfLine",
                                                "fields": {}
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ],
                    "contains": []
                }
            }
        ]
    }
}
```
**Example ASR:**
```bash
(lf) $ lfortran examples/expr2.f90 --show-asr --json
{
    "node": "TranslationUnit",
    "fields": {
        "global_scope": {
            "node": "SymbolTable1",
            "fields": {
                "expr2": {
                    "node": "Program",
                    "fields": {
                        "symtab": {
                            "node": "SymbolTable2",
                            "fields": {
                                "x": {
                                    "node": "Variable",
                                    "fields": {
                                        "parent_symtab": 2,
                                        "name": "x",
                                        "intent": "Local",
                                        "symbolic_value": [],
                                        "value": [],
                                        "storage": "Default",
                                        "type": {
                                            "node": "Integer",
                                            "fields": {
                                                "kind": 4,
                                                "dims": []
                                            }
                                        },
                                        "abi": "Source",
                                        "access": "Public",
                                        "presence": "Required",
                                        "value_attr": false
                                    }
                                }
                            }
                        },
                        "name": "expr2",
                        "dependencies": [],
                        "body": [
                            {
                                "node": "Assignment",
                                "fields": {
                                    "target": {
                                        "node": "Var",
                                        "fields": {
                                            "v": {
                                                "node": "Variable",
                                                "fields": {
                                                    "parent_symtab": 2,
                                                    "name": "x",
                                                    "intent": "Local",
                                                    "symbolic_value": [],
                                                    "value": [],
                                                    "storage": "Default",
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    },
                                                    "abi": "Source",
                                                    "access": "Public",
                                                    "presence": "Required",
                                                    "value_attr": false
                                                }
                                            }
                                        }
                                    },
                                    "value": {
                                        "node": "IntegerBinOp",
                                        "fields": {
                                            "left": {
                                                "node": "IntegerBinOp",
                                                "fields": {
                                                    "left": {
                                                        "node": "IntegerConstant",
                                                        "fields": {
                                                            "n": 2,
                                                            "type": {
                                                                "node": "Integer",
                                                                "fields": {
                                                                    "kind": 4,
                                                                    "dims": []
                                                                }
                                                            }
                                                        }
                                                    },
                                                    "op": "Add",
                                                    "right": {
                                                        "node": "IntegerConstant",
                                                        "fields": {
                                                            "n": 3,
                                                            "type": {
                                                                "node": "Integer",
                                                                "fields": {
                                                                    "kind": 4,
                                                                    "dims": []
                                                                }
                                                            }
                                                        }
                                                    },
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    },
                                                    "value": {
                                                        "node": "IntegerConstant",
                                                        "fields": {
                                                            "n": 5,
                                                            "type": {
                                                                "node": "Integer",
                                                                "fields": {
                                                                    "kind": 4,
                                                                    "dims": []
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            },
                                            "op": "Mul",
                                            "right": {
                                                "node": "IntegerConstant",
                                                "fields": {
                                                    "n": 5,
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    }
                                                }
                                            },
                                            "type": {
                                                "node": "Integer",
                                                "fields": {
                                                    "kind": 4,
                                                    "dims": []
                                                }
                                            },
                                            "value": {
                                                "node": "IntegerConstant",
                                                "fields": {
                                                    "n": 25,
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    "overloaded": []
                                }
                            },
                            {
                                "node": "Print",
                                "fields": {
                                    "fmt": [],
                                    "values": [
                                        {
                                            "node": "Var",
                                            "fields": {
                                                "v": {
                                                    "node": "Variable",
                                                    "fields": {
                                                        "parent_symtab": 2,
                                                        "name": "x",
                                                        "intent": "Local",
                                                        "symbolic_value": [],
                                                        "value": [],
                                                        "storage": "Default",
                                                        "type": {
                                                            "node": "Integer",
                                                            "fields": {
                                                                "kind": 4,
                                                                "dims": []
                                                            }
                                                        },
                                                        "abi": "Source",
                                                        "access": "Public",
                                                        "presence": "Required",
                                                        "value_attr": false
                                                    }
                                                }
                                            }
                                        }
                                    ],
                                    "separator": [],
                                    "end": []
                                }
                            }
                        ]
                    }
                }
            }
        },
        "items": []
    }
}
```

**Comment by certik** [comment]
I can see one issue: the Var "v" should not replicate Variable inside, it should "point" to it. 

Essentially, the only place that "owns" the symbols is the symbol table. All other "symbol" types in ASR are not owning, which means it is just a pointer (literal pointer in C++), and in JSON should be denoted by the symbol table ID and the string.

**Comment by Shaikh-Ubaid** [comment]
>I can see one issue: the Var "v" should not replicate Variable inside, it should "point" to it.

Got it. Thank you for the guidance. I just pushed a commit to print only the symbol name and the symbol table id for symbols in ASR Json format.

```bash
 lfortran examples/expr2.f90 --show-asr --json
{
    "node": "TranslationUnit",
    "fields": {
        "global_scope": {
            "node": "SymbolTable1",
            "fields": {
                "expr2": {
                    "node": "Program",
                    "fields": {
                        "symtab": {
                            "node": "SymbolTable2",
                            "fields": {
                                "x": {
                                    "node": "Variable",
                                    "fields": {
                                        "parent_symtab": 2,
                                        "name": "x",
                                        "intent": "Local",
                                        "symbolic_value": [],
                                        "value": [],
                                        "storage": "Default",
                                        "type": {
                                            "node": "Integer",
                                            "fields": {
                                                "kind": 4,
                                                "dims": []
                                            }
                                        },
                                        "abi": "Source",
                                        "access": "Public",
                                        "presence": "Required",
                                        "value_attr": false
                                    }
                                }
                            }
                        },
                        "name": "expr2",
                        "dependencies": [],
                        "body": [
                            {
                                "node": "Assignment",
                                "fields": {
                                    "target": {
                                        "node": "Var",
                                        "fields": {
                                            "v": "x (SymbolTable2)"
                                        }
                                    },
                                    "value": {
                                        "node": "IntegerBinOp",
                                        "fields": {
                                            "left": {
                                                "node": "IntegerBinOp",
                                                "fields": {
                                                    "left": {
                                                        "node": "IntegerConstant",
                                                        "fields": {
                                                            "n": 2,
                                                            "type": {
                                                                "node": "Integer",
                                                                "fields": {
                                                                    "kind": 4,
                                                                    "dims": []
                                                                }
                                                            }
                                                        }
                                                    },
                                                    "op": "Add",
                                                    "right": {
                                                        "node": "IntegerConstant",
                                                        "fields": {
                                                            "n": 3,
                                                            "type": {
                                                                "node": "Integer",
                                                                "fields": {
                                                                    "kind": 4,
                                                                    "dims": []
                                                                }
                                                            }
                                                        }
                                                    },
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    },
                                                    "value": {
                                                        "node": "IntegerConstant",
                                                        "fields": {
                                                            "n": 5,
                                                            "type": {
                                                                "node": "Integer",
                                                                "fields": {
                                                                    "kind": 4,
                                                                    "dims": []
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            },
                                            "op": "Mul",
                                            "right": {
                                                "node": "IntegerConstant",
                                                "fields": {
                                                    "n": 5,
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    }
                                                }
                                            },
                                            "type": {
                                                "node": "Integer",
                                                "fields": {
                                                    "kind": 4,
                                                    "dims": []
                                                }
                                            },
                                            "value": {
                                                "node": "IntegerConstant",
                                                "fields": {
                                                    "n": 25,
                                                    "type": {
                                                        "node": "Integer",
                                                        "fields": {
                                                            "kind": 4,
                                                            "dims": []
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    "overloaded": []
                                }
                            },
                            {
                                "node": "Print",
                                "fields": {
                                    "fmt": [],
                                    "values": [
                                        {
                                            "node": "Var",
                                            "fields": {
                                                "v": "x (SymbolTable2)"
                                            }
                                        }
                                    ],
                                    "separator": [],
                                    "end": []
                                }
                            }
                        ]
                    }
                }
            }
        },
        "items": []
    }
}
```

**Comment by Shaikh-Ubaid** [comment]
This is ready. Please possibly review and please share feedback.

**Review by certik — APPROVED** [review]
I think this looks good, thanks!

**Comment by Shaikh-Ubaid** [comment]
Thank you for the approval.

**Pull request merged**
