### PR TITLE
chore: don't create temporary for StructInstanceMember when present as call argument

### PR DESCRIPTION
**Pull request by gxyd**
This probably completely helps us compile dftatom on *simplifier_pass* branch, (excluding ofcourse the fast test cases, which I haven't checked)

### CODE REVIEW

**Comment by gxyd** [comment]
Added the test case for this change here against *main*: https://github.com/lfortran/lfortran/pull/5022.

This PR doesn't necessarily need a separate test case in *simplifier_pass* branch, as the CI job of dftatom is kind of like a test case for it. Also, I manually checked it locally that it gets the test case present in #5022 working on *simplifier_pass* branch

**Review by certik — APPROVED** [review]
Great job!

**Comment by certik** [comment]
Can this be merged?

**Comment by gxyd** [comment]
Yes, I just merged it.

**Pull request merged**
