### PR TITLE
fix: do casting on resultant `ArrayItem` instead of the complete array for intrinsic `DotProduct`

### PR DESCRIPTION
**Pull request by kmr-srbh**
We transform `int(matrix_b, kind=4)(i)` to `int(matrix_b(i), kind=4)`.

We are now able to test `intrinsics_142.f90`, `intrinsics_143.f90` and `intrinsics_298.f90`.

### CODE REVIEW

**Comment by gxyd** [comment]
Currently in the `simplifier_pass` the test case `intrinsics_142.f90` and other test cases passing (which you've uncommented) already pass, I noticed that there was a commit 79cd4ce9cd21c8792104114516c4d13763b55dec which attempted to fix the same problem we've here.

Even though the tests already pass, I still like the approach taken in this PR in general more than the above commit I mentioned. 

Which will render the use of `force` argument as used in `avoid_cast`:
```diff
diff --git a/src/libasr/asr_builder.h b/src/libasr/asr_builder.h
index ee26ba8f4..dcb962694 100644
--- a/src/libasr/asr_builder.h
+++ b/src/libasr/asr_builder.h
@@ -259,8 +259,8 @@ class ASRBuilder {
 
     // Cast --------------------------------------------------------------------
 
-    #define avoid_cast(x, t) if( ASRUtils::extract_kind_from_ttype_t(t) <= \
-        ASRUtils::extract_kind_from_ttype_t(ASRUtils::expr_type(x)) ) { \
+    #define avoid_cast(x, t, force) if( ASRUtils::extract_kind_from_ttype_t(t) <= \
+        ASRUtils::extract_kind_from_ttype_t(ASRUtils::expr_type(x)) && !force ) { \
         return x; \
     } \
 
@@ -272,13 +272,13 @@ class ASRBuilder {
         return EXPR(ASR::make_Cast_t(al, loc, x, ASR::cast_kindType::IntegerToReal, t, nullptr));
     }
 
-    inline ASR::expr_t* i2i_t(ASR::expr_t* x, ASR::ttype_t* t) {
-        avoid_cast(x, t)
+    inline ASR::expr_t* i2i_t(ASR::expr_t* x, ASR::ttype_t* t, bool force=true) {
+        avoid_cast(x, t, force)
         return EXPR(ASR::make_Cast_t(al, loc, x, ASR::cast_kindType::IntegerToInteger, t, nullptr));
     }
 
-    inline ASR::expr_t* r2r_t(ASR::expr_t* x, ASR::ttype_t* t) {
-        avoid_cast(x, t)
+    inline ASR::expr_t* r2r_t(ASR::expr_t* x, ASR::ttype_t* t, bool force=true) {
+        avoid_cast(x, t, force)
         return EXPR(ASR::make_Cast_t(al, loc, x, ASR::cast_kindType::RealToReal, t, nullptr));
     }
 
```

Since we don't need that anymore.

Do you think it would be nice to have more test cases in `intrinsics_142.f90`:
```f90

    integer(8), dimension(3) :: a
    integer(4), dimension(3) :: b
    integer(8) :: res
    a = [1, 2, 3]
    b = [4, 5, 6]

    res = dot_product(a, b)
```

which otherwise fail in the current `simplifier_pass` branch? @certik might not really like the idea of having more test cases though.

@certik thoughts?

**Comment by kmr-srbh** [comment]
I think the above test case is tested inside `intrinsics_142.f90`?

**Comment by gxyd** [comment]
> I think the above test case is tested inside `intrinsics_142.f90`?

Ah it isn't tested with different kinds for array's `a` and `b`, it's only tested when the kind is `4` for `a`, `b` and `res`.

**Comment by gxyd** [comment]
I just checked on the latest `simplifier_pass` branch:
```f90
program intrinsics_142
    integer(8), dimension(3) :: a
    integer(4), dimension(3) :: b
    integer :: res
    a = [1, 2, 3]
    b = [4, 5, 6]
    res = dot_product(a, b)
end program intrinsics_142
```

this fails on `simplifier_pass` branch, while it does succeeds on our current `main`.

**Comment by kmr-srbh** [comment]
> Ah it isn't tested with different kinds for array's `a` and `b`, it's only tested when the kind is same for `a`, `b` and `res`.

Oh, right. Let's fix this and add the test case.

**Comment by certik** [comment]
Yes, any new test case put in both main and here. If it fails on main, simply comment it out there.

**Comment by kmr-srbh** [comment]
@gxyd can this PR be merged?

**Comment by gxyd** [comment]
> @gxyd can this PR be merged?

Oh, I thought you would be removing the diff I mentioned in the above comment, which is:
```diff
diff --git a/src/libasr/asr_builder.h b/src/libasr/asr_builder.h
index ee26ba8f4..dcb962694 100644
--- a/src/libasr/asr_builder.h
+++ b/src/libasr/asr_builder.h
@@ -259,8 +259,8 @@ class ASRBuilder {
 
     // Cast --------------------------------------------------------------------
 
-    #define avoid_cast(x, t) if( ASRUtils::extract_kind_from_ttype_t(t) <= \
-        ASRUtils::extract_kind_from_ttype_t(ASRUtils::expr_type(x)) ) { \
+    #define avoid_cast(x, t, force) if( ASRUtils::extract_kind_from_ttype_t(t) <= \
+        ASRUtils::extract_kind_from_ttype_t(ASRUtils::expr_type(x)) && !force ) { \
         return x; \
     } \
 
@@ -272,13 +272,13 @@ class ASRBuilder {
         return EXPR(ASR::make_Cast_t(al, loc, x, ASR::cast_kindType::IntegerToReal, t, nullptr));
     }
 
-    inline ASR::expr_t* i2i_t(ASR::expr_t* x, ASR::ttype_t* t) {
-        avoid_cast(x, t)
+    inline ASR::expr_t* i2i_t(ASR::expr_t* x, ASR::ttype_t* t, bool force=true) {
+        avoid_cast(x, t, force)
         return EXPR(ASR::make_Cast_t(al, loc, x, ASR::cast_kindType::IntegerToInteger, t, nullptr));
     }
 
-    inline ASR::expr_t* r2r_t(ASR::expr_t* x, ASR::ttype_t* t) {
-        avoid_cast(x, t)
+    inline ASR::expr_t* r2r_t(ASR::expr_t* x, ASR::ttype_t* t, bool force=true) {
+        avoid_cast(x, t, force)
         return EXPR(ASR::make_Cast_t(al, loc, x, ASR::cast_kindType::RealToReal, t, nullptr));
     }
```

I believe it's redundant. Other than that I'm happy with the current changes, please let me know what you think about that diff.

**Comment by kmr-srbh** [comment]
Okay, I will remove this diff as part of this PR. :+1:

**Comment by kmr-srbh** [comment]
@gxyd this PR is now ready.

**Comment by certik** [comment]
@gxyd please review.

**Comment by gxyd** [comment]
Looks good to me, I'll merge it. Thanks @kmr-srbh

**Pull request merged**
