### PR TITLE
[asr->fortran] implement `visit_StringLen`

### PR DESCRIPTION
**Pull request by khushi-411**
Used the `len()` function. Ref: https://gcc.gnu.org/onlinedocs/gcc-3.4.6/g77/Len-Intrinsic.html

### CODE REVIEW

**Comment by certik** [comment]
This looks good. Let's add a test for this.

**Review by Thirumalai-Shaktivel — APPROVED** [review]
Perfect, thanks!

From now on, we can follow this pattern.
We will enable the tests sequentially! As you can see in CMakeLists.txt, we have tested until expr_02. So, we will enable expr_03 next and fix the issue, if any; otherwise, we will make sure the output matches the file content using the --show-fortran option. And then enable expr_04 and so on...

If you face any blockers, or stuck somewhere, or you are not able to figure things out, let us know. We will help you debug it.

**Comment by Thirumalai-Shaktivel** [comment]
This PR is ready to be merged, right?

**Comment by khushi-411** [comment]
Hi, @Thirumalai-Shaktivel!
Thanks so much for reviewing. I'll follow the same pattern. 

> If you face any blockers, or stuck somewhere, or you are not able to figure things out, let us know. We will help you debug it.

Sure, I will reach out to the team in case of any doubts. Thanks :)

> This PR is ready to be merged, right?

Indeed

**Pull request merged**
