### PR TITLE
Tests fix race failure

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**
fixes https://github.com/lfortran/lfortran/issues/1825

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
This fails currently.

**Comment by certik** [comment]
Thanks. Yes, something along these lines. We just have to make it work.

**Comment by Shaikh-Ubaid** [comment]
>I think the easiest to fix is to build the fast tests in another directory

It seems building the fast tests to another directory is possible, but it seems that it might/could complicate the cmake instructions. (We are needing to override the executable directory using `CMAKE_RUNTIME_OUTPUT_DIRECTORY` and every instruction needs to have the flag `-J{CMAKE_RUNTIME_OUTPUT_DIRECTORY}` so that `lfortran` could save the mod files to this directory. Every instruction also needs to include this (`CMAKE_RUNTIME_OUTPUT_DIRECTORY`) directory so that `lfortran` can find the mod files stored in that directory.)

For the moment, in this PR, I attempted a simpler approach to run the integration tests for `fast` and `non-fast` separately. Please share if it is fine.

**Review by certik — APPROVED** [review]
I think this is a great approach. The changes look good, thanks!

**Pull request merged**
