### PR TITLE
Fix CMake test failure

### LINKED ISSUE #2475: CMake test file
CMake is sometimes trying to make LFortran compile the following file and fails:
```fortran
program CMakeFortranCompilerABI

implicit none

integer :: i(1) = 0
where (i==0) i=1
if (any(i/=1)) stop 1
! showing Fortran 90 syntax is OK

#if 0
! Address Size
#endif
#if defined(_LP64)
PRINT *, 'INFO:sizeof_dptr[8]'
#elif defined(_M_IA64)
PRINT *, 'INFO:sizeof_dptr[8]'
#elif defined(_M_X64)
PRINT *, 'INFO:sizeof_dptr[8]'
#elif defined(_M_AMD64)
PRINT *, 'INFO:sizeof_dptr[8]'
#elif defined(__x86_64__)
PRINT *, 'INFO:sizeof_dptr[8]'

#elif defined(_ILP32)
PRINT *, 'INFO:sizeof_dptr[4]'
#elif defined(_M_IX86)
PRINT *, 'INFO:sizeof_dptr[4]'
#elif defined(__i386__)
PRINT *, 'INFO:sizeof_dptr[4]'

#elif defined(__SIZEOF_POINTER__) && __SIZEOF_POINTER__ == 8
PRINT *, 'INFO:sizeof_dptr[8]'
#elif defined(__SIZEOF_POINTER__) && __SIZEOF_POINTER__ == 4
PRINT *, 'INFO:sizeof_dptr[4]'
#elif defined(__SIZEOF_SIZE_T__) && __SIZEOF_SIZE_T__ == 8
PRINT *, 'INFO:sizeof_dptr[8]'
#elif defined(__SIZEOF_SIZE_T__) && __SIZEOF_SIZE_T__ == 4
PRINT *, 'INFO:sizeof_dptr[4]'
#endif

#if 0
! Application Binary Interface
#endif
#if defined(__ELF__)
PRINT *, 'INFO:abi[ELF]'
#endif
PRINT *, 'ABI Detection'
end program
```
Because currently LFortran gives:
```console
$ lfortran -c /Users/ondrej/repos/spack/opt/spack/darwin-monterey-m1/apple-clang-13.0.0/cmake-3.23.1-3geuicgdlylivqqft4pjwrdnmb63dfxr/share/cmake-3.23/Modules/CMakeFortranCompilerABI.F90
[...]
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i32 0, [1 x i32]* %i, align 4
 [1 x i32]
```

### PR DESCRIPTION
**Pull request by Pranavchiku**
Fixes #2475.

### CODE REVIEW

**Review by certik — APPROVED** [review]
Excellent, thanks!

**Comment by certik** [comment]
@Pranavchiku go ahead and try to remove `--verbose` from the cmake build system for scipy, it might work now.

**Comment by Pranavchiku** [comment]
Nope, it is not working yet.

**Comment by Pranavchiku** [comment]
I feel this will be because of #2492

**Pull request merged**
