### PR TITLE
pre-commit fixes for clang format

### LINKED ISSUE #654: bug: pre-commit clang-format hook does not trigger
The pre-commit hook is not currently working as expected since it fails to enforce the `clang-format` hook. That in general results for pre-commit to fail. `clang-format` needs to be initialised before included in pre-commit.

### PR DESCRIPTION
**Pull request by gnikit**
Fixes #654 

@awvwgk Do we want to exclude from pre-commit the `.po` or the locale dir completely?

@certik Are you sure you want to use `Mozilla` as the formatting style? It doesn't seem to match the natural style of the code.

### CODE REVIEW

**Comment by gnikit** [comment]
Also, you need to give access to pre-commit.ci (https://pre-commit.ci/) to autofix for the CI check to run on GitHub.

**Comment by awvwgk** [comment]
You would have to run the `intl.py` script in a pre-commit hook to automatically apply updates from the documentation.

**Comment by gnikit** [comment]
Wouldn't it be a bit easier if we just ignored the .po files that are auto generated. I don't see why precommit should format those.

**Comment by certik** [comment]
I don't have a good experience with pre-commit, I almost lost my changes when I was programming, because it would reformat everything, so my few changes would get lost in an enormous patch. So I would recommend to hold off on this, until we deliver LFortran, that is, once we can compile everything, we will not need frequent modifications and we can use this. It also adds a bar to new developers, and I want to keep the bar very low right now (high quality code bar, but low entry bar in terms of technical setup).

**Comment by gnikit** [comment]
So the major diffs would only be in this PR. After that the CI bot will be running in the background so no unrelated bits of code will be formatted.

As for the dev side of things, you don't need to have precommit installed locally, the CI bot will take care of everything once you push

**Comment by certik** [comment]
Ah --- ok, that might work!

**Comment by certik** [comment]
I would change the formatting scripts to only format cpp for now. The JSON / MD stuff is problematic, so we can handle that later.

**Comment by gnikit** [comment]
> I would change the formatting scripts to only format cpp for now. The JSON / MD stuff is problematic, so we can handle that later.

Yeah, I agree (I will do a force push later today). Do you want to stick with Mozilla style formatting?
We also have to allow pre-commit.ci to run, only you can do that since I don't have admin access.

Also, I would ping everyone working on PRs with C++ code to either merge (if PR is ready) or be aware that they will have to rebase/merge after this.

**Comment by certik** [comment]
Why don't you send the improvements to the config file, but not format things?

I don't have time right now to setup the infrastructure and I need to focus on delivering "beta" of LFortran, so I don't want the added barrier to take away from it. I am setting this to a Draft, once this is ready for review, just set it as ready.

**Comment by gnikit** [comment]
Closing this. This is low priority and a nice to have, at some point setting up the pre-commit hooks might be a worthwhile venture, but I don't want to divert time from the Beta roadmap.

**Pull request closed without merging**
