### PR TITLE
Handle SIMD in generate_array_decl

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
@czgdp1807, @Thirumalai-Shaktivel I am trying to emit custom SIMD C code for arrays declared with SIMD, but so far have not figured it out. I am testing it using:
```console
$ lfortran --show-c tests/pragma2.f90
```
Do you know how to do that?

**Comment by certik** [comment]
I figured it out in 5bac62bc2a1819b0ce3ca58c7381dd68bef08a79. Apparently `v->m_type` is not the same as `v_m_type`. It seems this code is not very clean.

**Comment by Pranavchiku** [comment]
I have made progress, with following diff
```diff
diff --git a/src/libasr/codegen/asr_to_c.cpp b/src/libasr/codegen/asr_to_c.cpp
index b76a61631..4ec708a63 100644
--- a/src/libasr/codegen/asr_to_c.cpp
+++ b/src/libasr/codegen/asr_to_c.cpp
@@ -88,10 +88,12 @@ public:
                              bool is_simd_array) {
         std::string indent(indentation_level*indentation_spaces, ' ');
         std::string type_name_copy = type_name;
+        std::string original_type_name = type_name;
         type_name = c_ds_api->get_array_type(type_name, encoded_type_name, array_types_decls);
         std::string type_name_without_ptr = c_ds_api->get_array_type(type_name, encoded_type_name, array_types_decls, false);
         if (is_simd_array) {
-            sub = "float " + std::string(v_m_name) + " __attribute__ (( vector_size(sizeof(float) * 8) ));\n";
+            int64_t size = ASRUtils::get_fixed_size_of_array(m_dims, n_dims);
+            sub = original_type_name + " " + v_m_name + " __attribute__ (( vector_size(sizeof(" + original_type_name + ") * " + std::to_string(size) + ") ))";
             return;
         }
         if( declare_value ) {
@@ -1202,6 +1204,35 @@ R"(    // Initialise Numpy
         src = this->check_tmp_buffer() + out;
     }
 
+    void visit_ArrayBroadcast(const ASR::ArrayBroadcast_t& x) {
+        /*
+            !LF$ attributes simd :: A
+            real :: A(8)
+            A = 1
+            We need to generate:
+            a = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0};
+        */
+
+        CHECK_FAST_C(compiler_options, x)
+        if (x.m_value) {
+            ASR::expr_t* value = x.m_value;
+            LCOMPILERS_ASSERT(ASR::is_a<ASR::ArrayConstant_t>(*value));
+            ASR::ArrayConstant_t* array_const = ASR::down_cast<ASR::ArrayConstant_t>(value);
+            src = "{}";
+            std::string array_const_str = "{";
+            for( size_t i = 0; i < array_const->n_args; i++ ) {
+                ASR::expr_t* array_const_arg = array_const->m_args[i];
+                this->visit_expr(*array_const_arg);
+                array_const_str += src + ", ";
+            }
+            array_const_str.pop_back();
+            array_const_str.pop_back();
+            array_const_str += "}";
+
+            src = array_const_str;
+        }
+    }
+
     void visit_ArraySize(const ASR::ArraySize_t& x) {
         CHECK_FAST_C(compiler_options, x)
         visit_expr(*x.m_v);
diff --git a/src/libasr/codegen/asr_to_c_cpp.h b/src/libasr/codegen/asr_to_c_cpp.h
index 2d4465bf5..e8d4d5a89 100644
--- a/src/libasr/codegen/asr_to_c_cpp.h
+++ b/src/libasr/codegen/asr_to_c_cpp.h
@@ -1353,7 +1353,7 @@ PyMODINIT_FUNC PyInit_lpython_module_)" + fn_name + R"((void) {
                     bool is_target_data_only_array = ASRUtils::is_fixed_size_array(m_target_dims, n_target_dims) &&
                                                      ASR::is_a<ASR::StructType_t>(*ASRUtils::get_asr_owner(x.m_target));
                     bool is_value_data_only_array = ASRUtils::is_fixed_size_array(m_value_dims, n_value_dims) &&
-                                                    ASR::is_a<ASR::StructType_t>(*ASRUtils::get_asr_owner(x.m_value));
+                                                    ASRUtils::get_asr_owner(x.m_value) && ASR::is_a<ASR::StructType_t>(*ASRUtils::get_asr_owner(x.m_value));
                     if( is_target_data_only_array || is_value_data_only_array ) {
                         int64_t target_size = -1, value_size = -1;
                         if( !is_target_data_only_array ) {
```

I am able to generate

```c
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <lfortran_intrinsics.h>


struct dimension_descriptor
{
    int32_t lower_bound, length;
};

struct r32
{
    float *data;
    struct dimension_descriptor dims[32];
    int32_t n_dims;
    bool is_allocated;
};




// Implementations
int main(int argc, char* argv[])
{
    _lpython_set_argv(argc, argv);
    float a __attribute__ (( vector_size(sizeof(float) * 8) ));
    a = {(float)(1), (float)(1), (float)(1), (float)(1), (float)(1), (float)(1), (float)(1), (float)(1)};
    return 0;
}
```

**Comment by Pranavchiku** [comment]
Pushed changes at #2517.

**Comment by certik** [comment]
Finished in https://github.com/lfortran/lfortran/pull/2517.

**Comment by Pranavchiku** [comment]
Closing with reference to https://github.com/lfortran/lfortran/pull/2502#issuecomment-1736252123

**Pull request closed without merging**
