### PR TITLE
i18n: Add Polish and Bengali po files

### LINKED ISSUE #830: Add Bengali (bn) translation
Requested via Weblate. Bengali is supported with the language code `bn`.

Last new language added in https://github.com/lfortran/lfortran/pull/811.

### LINKED ISSUE #832: Add Polish (pl) translation
Requested via Weblate. Polish is supported with the language code `pl`.

Last new language added in https://github.com/lfortran/lfortran/pull/811.

### PR DESCRIPTION
**Pull request by certik**
Fixes #830
Fixes #832

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
Thanks, looks good to me.

**Comment by awvwgk** [comment]
Any idea why the GFortran integration_tests are failing? This PR doesn't touch any relevant files, does it?

**Comment by certik** [comment]
The gfortran failures are fixed by #846.

**Comment by certik** [comment]
Thanks for the review. Things should pass now.

**Comment by certik** [comment]
The two languages are now available at https://docs.lfortran.org/en/

**Pull request merged**
