### PR TITLE
[Sprint] Bug fixes for AST->ASR transition to compile FPM

### PR DESCRIPTION
**Pull request by czgdp1807**
Continues https://github.com/lfortran/lfortran/pull/1037

Commits to be added in `main`,

- [ ] 7f94ae266b61ffd5938c3725339be5b015d623cc - https://github.com/lfortran/lfortran/pull/1146
- [ ] 2a9205c13f89a70762592d6111dfc98fccefe9b4 - https://github.com/lfortran/lfortran/pull/1146
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/1d1eaaca20426785d0126415a382cb1cbeddbd1d - https://github.com/lfortran/lfortran/pull/1151
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/8369010066567d04ca89aeca860dc852e88e0ac7 - https://github.com/lfortran/lfortran/pull/1151
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/bd4f240db49d292a46c3c3f773c47821dffe6f42 - https://github.com/lfortran/lfortran/pull/1151
- [x] https://github.com/lfortran/lfortran/pull/1109/commits/e45d2f28c0839494187f3cc6865849664c84bb3a - https://github.com/lfortran/lfortran/pull/1104 (936b55a93a3b33cec324d9fd2741bbaa05ec090d)
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/36ec2030027ec2d26591721d1fcbf359e6bf65a3 - https://github.com/lfortran/lfortran/pull/1151
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/e6e79982b032a435c668f9cef50d12fc31788b10 - https://github.com/lfortran/lfortran/pull/1147
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/af13b8ae5eb931a0c7b0c988ce64d14c401fd117 - https://github.com/lfortran/lfortran/pull/1152
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/2f082684bd6f2d30a6a0ea904d1741f822046ad6 - https://github.com/lfortran/lfortran/pull/1152
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/88c0476c7f28074352db574285bfd515075b63a0 - https://github.com/lfortran/lfortran/pull/1148
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/2cc6460b37b5545676178e4b7f7821356d774f8d - https://github.com/lfortran/lfortran/pull/1149
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/aaea271d3bc3e826dec456bf5f3776a69d4aaec5 - https://github.com/lfortran/lfortran/pull/1149
- [ ] https://github.com/lfortran/lfortran/pull/1109/commits/6aa545c611beb0370b60a084542648d750e195ad - https://github.com/lfortran/lfortran/pull/1149 
- [ ] 85d948ddb179b4119a968ef5ff6298bef5fe515b - https://github.com/lfortran/lfortran/pull/1145
- [ ] a708951349ac6a31b33305b6a97a864c2e352a15 - https://github.com/lfortran/lfortran/pull/1151 
- [ ] 4a7e81e7a9a7ed37afc8eef91b3624690697c40e - https://github.com/lfortran/lfortran/pull/1151

Commit to be taken care of - https://github.com/lfortran/lfortran/pull/1109/commits/6d3e81c187ca5a04e365186a45c3ddfa433bf4cf - @czgdp1807 

@Thirumalai-Shaktivel Please continue your sprint here. Also please **do not rebase on top of `main` branch**. I need the commits to cherry-pick in future, so please **do not change the git history of the PR**. Just add new commits and push.

Progress:
```zsh
 <INFO> BUILD_NAME: build/lfortran
 <INFO> COMPILER:  lfortran
 <INFO> C COMPILER:  cc
 <INFO> CXX COMPILER: cc
 <INFO> COMPILER OPTIONS:  
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:  
 <INFO> INCLUDE DIRECTORIES:  []
 + mkdir -p build/lfortran_00000000811C9DC5
[  0%]        fpm_backend_console.f90
 + mkdir -p build/lfortran_00000000811C9DC5/fpm/
 + lfortran -c ././src/fpm_backend_console.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_backend_console.f90.o
[  1%]        fpm_backend_console.f90  done.
[  1%]         filesystem_utilities.c
 + cc -c ././src/filesystem_utilities.c  -o build/lfortran_00000000811C9DC5/fpm/src_filesystem_utilities.c.o
[  2%]         filesystem_utilities.c  done.
[  2%]                fpm_strings.f90
 + lfortran -c ././src/fpm_strings.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_strings.f90.o
[  4%]                fpm_strings.f90  done.
[  4%]                       isatty.c
 + cc -c ././src/ptycheck/isatty.c  -o build/lfortran_00000000811C9DC5/fpm/src_ptycheck_isatty.c.o
[  5%]                       isatty.c  done.
[  5%]                     iscygpty.c
 + cc -c ././src/ptycheck/iscygpty.c  -o build/lfortran_00000000811C9DC5/fpm/src_ptycheck_iscygpty.c.o
[  7%]                     iscygpty.c  done.
[  7%]                    version.f90
 + lfortran -c build/dependencies/toml-f/src/tomlf/version.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/build_dependencies_toml-f_src_tomlf_version.f90.o
[  8%]                    version.f90  done.
[  8%]                  constants.f90
 + lfortran -c build/dependencies/toml-f/src/tomlf/constants.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/build_dependencies_toml-f_src_tomlf_constants.f90.o
[ 10%]                  constants.f90  done.
[ 10%]                     M_CLI2.F90
 + lfortran -c build/dependencies/M_CLI2/src/M_CLI2.F90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/build_dependencies_M_CLI2_src_M_CLI2.F90.o
[ 11%]                     M_CLI2.F90  done.
[ 11%]                      error.f90
 + lfortran -c ././src/fpm/error.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_error.f90.o
[ 13%]                      error.f90  done.
[ 13%]                   datetime.f90
 + lfortran -c build/dependencies/toml-f/src/tomlf/datetime.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/build_dependencies_toml-f_src_tomlf_datetime.f90.o
[ 14%]                   datetime.f90  done.
[ 14%]                      error.f90
 + lfortran -c build/dependencies/toml-f/src/tomlf/error.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/build_dependencies_toml-f_src_tomlf_error.f90.o
[ 16%]                      error.f90  done.
[ 16%]                     verify.f90
 + lfortran -c build/dependencies/toml-f/src/tomlf/utils/verify.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/build_dependencies_toml-f_src_tomlf_utils_verify.f90.o
[ 17%]                     verify.f90  done.
[ 17%]            fpm_environment.f90
 + lfortran -c ././src/fpm_environment.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_environment.f90.o
[ 19%]            fpm_environment.f90  done.
[ 19%]                     fpm_os.F90
 + lfortran -c ././src/fpm_os.F90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_os.F90.o
[ 20%]                     fpm_os.F90  done.
[ 20%]                 versioning.f90
 + lfortran -c ././src/fpm/versioning.f90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_versioning.f90.o
Internal Compiler Error: Unhandled exception
...
LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_procedure_decl(LFortran::AST::procedure_decl_t const&)
    void visit_procedure_decl(const procedure_decl_t &b) { visit_procedure_decl_t(b, self()); }
  File "/home/thirumalai/Open_Source/lfortran/src/lfortran/ast.h", line 4569, in ??
    case procedure_declType::GenericOperator: { v.visit_GenericOperator((const GenericOperator_t &)x); return; }
LCompilersException: visit_GenericOperator() not implemented
[ 22%]                 versioning.f90  done.

Internal Compiler Error: Unhandled exception
...
LFortran::AST::BaseVisitor<LFortran::SymbolTableVisitor>::visit_procedure_decl(LFortran::AST::procedure_decl_t const&)
    void visit_procedure_decl(const procedure_decl_t &b) { visit_procedure_decl_t(b, self()); }
  File "/home/thirumalai/Open_Source/lfortran/src/lfortran/ast.h", line 4569, in ??
    case procedure_declType::GenericOperator: { v.visit_GenericOperator((const GenericOperator_t &)x); return; }
LCompilersException: visit_GenericOperator() not implemented
<ERROR> Compilation failed for object " src_fpm_versioning.f90.o "
<ERROR>stopping due to failed compilation
STOP 1
```

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
@czgdp1807 are the dependencies issues already fixed here? For example, is [this](https://github.com/lfortran/lfortran/pull/1037#issuecomment-1347674975) example already fixed here?

**Comment by Thirumalai-Shaktivel** [comment]
Also, can you please update the current status of compiling FPM in the description?

**Comment by czgdp1807** [comment]
> are the dependencies issues already fixed?

We will see those later, once the sprints are fixed. For now just fetch the branch `stf_sprint_02` (the one in this PR) from my fork and continue the sprint.

> Also, can you please update the current status of compiling FPM in the description?

Run, `FPM_FC=lfortran fpm build` inside `fpm` source and update the description of the PR with the  progress.

**Comment by Thirumalai-Shaktivel** [comment]
Consider an example
```fortran
module x
    type :: toml_date
        integer :: year = 0
        integer :: month = 0
        integer :: day = 0
    contains
        generic :: assignment(=) => to_string                 <----------- (1)
        procedure, pass(rhs) :: to_string => date_to_string
    end type
contains
    subroutine date_to_string(lhs, rhs)
    character(kind=1, len=:), allocatable, intent(out) :: lhs
    class(toml_date), intent(in) :: rhs
    allocate(character(kind=1, len=10) :: lhs)
    write(lhs, '(i4.4,"-",i2.2,"-",i2.2)') &
        &  rhs%year, rhs%month, rhs%day
    end subroutine date_to_string
end module

program debug
    use x
    implicit none
    character(:), allocatable :: a
    type(toml_date) :: b
    b%year = 2022; b%month = 12; b%day = 20
    call date_to_string(a, b)
    print *, a
end program debug
```
Currently, we have not implemented GenericAssignment. How should I represent this in ASR? Create a new node? or something else?
@certik

**Comment by Thirumalai-Shaktivel** [comment]
Consider two examples:
a.f90
```fortran
module a
    implicit none
    integer, public, parameter :: tfc = selected_char_kind('DEFAULT')
    type y
        character(len=1, kind=tfc) :: newline = achar(10, kind=tfc)
    end type y
end module a

program abc
    use a, only: tfc
    implicit none
end program abc
```
b.f90
```fortran
program b
use a, only: tfc
implicit none
print *, tfc
end program
```
Error:
```console
$ lfortran -c a.py
$ lfortran b.py --show-asr --indent
...
    LFORTRAN_ASSERT(asr_verify(*tu, false, diagnostics));
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/asr_verify.cpp", line 741, in LFortran::asr_verify(LFortran::ASR::TranslationUnit_t const&, bool, LFortran::diag::Diagnostics&)
    v.visit_TranslationUnit(unit);
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/asr_verify.cpp", line 119, in LFortran::ASR::VerifyVisitor::visit_TranslationUnit(LFortran::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/../libasr/asr.h", line 4335, in LFortran::ASR::BaseVisitor<LFortran::ASR::VerifyVisitor>::visit_symbol(LFortran::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/../libasr/asr.h", line 4081, in ??
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/asr_verify.cpp", line 234, in LFortran::ASR::VerifyVisitor::visit_Module(LFortran::ASR::Module_t const&)
    this->visit_symbol(*a.second);
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/../libasr/asr.h", line 4335, in LFortran::ASR::BaseVisitor<LFortran::ASR::VerifyVisitor>::visit_symbol(LFortran::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/../libasr/asr.h", line 4086, in ??
    case symbolType::StructType: { v.visit_StructType((const StructType_t &)x); return; }
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/asr_verify.cpp", line 376, in LFortran::ASR::VerifyVisitor::visit_StructType(LFortran::ASR::StructType_t const&)
    visit_StructTypeEnumTypeUnionType(x);
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/asr_verify.cpp", line 347, in void LFortran::ASR::VerifyVisitor::visit_StructTypeEnumTypeUnionType<LFortran::ASR::StructType_t>(LFortran::ASR::StructType_t const&)
    ASR::ttype_t* var_type = ASRUtils::type_get_past_pointer(ASRUtils::symbol_type(a.second));
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/../libasr/asr_utils.h", line 110, in ??
    return symbol_type(ASRUtils::symbol_get_past_external(f));
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/../libasr/asr_utils.h", line 65, in ??
    LFORTRAN_ASSERT(!ASR::is_a<ASR::ExternalSymbol_t>(*e->m_external));
  File "/home/thirumalai/Open_Source/lfortran/src/libasr/asr.h", line 31, in bool LFortran::ASR::is_a<LFortran::ASR::ExternalSymbol_t, LFortran::ASR::symbol_t>(LFortran::ASR::symbol_t const&)
    return T::class_type == x.type;
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", in __GI___sigaction()
Segfault: Signal SIGSEGV (segmentation fault) received
```
But the ASR is correct:
```fortran
achar:
    (ExternalSymbol
        5
        achar
        16 achar                <-------- (1)
        lfortran_intrinsic_builtin
        []
        achar
        Private
    ),
```
(1) is causing the SegFault

**Comment by Thirumalai-Shaktivel** [comment]
TODO:
- [ ] https://github.com/lfortran/lfortran/pull/1109#issuecomment-1360954156
- [ ] https://github.com/lfortran/lfortran/pull/1109#issuecomment-1360815111
- [ ] https://github.com/lfortran/lfortran/pull/1117#issuecomment-1358840964
- [ ] https://github.com/lfortran/lfortran/pull/1104#discussion_r1045715197

**Comment by czgdp1807** [comment]
So, we have compiled till 19% of FPM in this PR (see [description of this PR](https://github.com/lfortran/lfortran/pull/1109#issue-1496359320)). So the time has arrived to add the fixes here to LFortran main in separate new PRs (with proper regression tests).

@Thirumalai-Shaktivel There is a syntax error while compiling FPM with this PR (see below). It would be great if you can fix this before our next sprint. Thanks.

```zsh
+ lfortran -c ././src/fpm_os.F90  -J build/lfortran_00000000811C9DC5 -Ibuild/lfortran_00000000811C9DC5 -o build/lfortran_00000000811C9DC5/fpm/src_fpm_os.F90.o
syntax error: Token '::' is unexpected here
  --> ././src/fpm_os.F90:21:20
   |
21 |             import :: c_char, c_int
   |                    ^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

@Thirumalai-Shaktivel In future sprint PRs, I would request you to add regression tests for each fix (in the same commit in which you are adding your fix). This helps in looking what each commit fixes. See my commits for examples.

**Comment by certik** [comment]
Amazing, 19% is really good, the rest will go much quicker.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, Got it @czgdp1807. 
Now, we compile it 21%, I will submit the PRs

**Comment by czgdp1807** [comment]
Closing in favour of https://github.com/lfortran/lfortran/pull/1153. I will take care of https://github.com/lfortran/lfortran/commit/6d3e81c187ca5a04e365186a45c3ddfa433bf4cf now.

**Comment by Thirumalai-Shaktivel** [comment]
Ah, I see we create new PR for every new sprint. Got it. I will start working there.

**Comment by Thirumalai-Shaktivel** [comment]
@czgdp1807 is this: 6d3e81c187ca5a04e365186a45c3ddfa433bf4cf changes got into main?
ef856db4247396b8f309b35dc7d48344d3abd47b is dependent on it

**Comment by czgdp1807** [comment]
> [6d3e81c](https://github.com/lfortran/lfortran/commit/6d3e81c187ca5a04e365186a45c3ddfa433bf4cf) changes got into main?

Its a workaround commit. Not supposed to go in `main`. Apply your commit, make a PR and keep fixing the dependency issue afterwards.

**Pull request closed without merging**
