### PR TITLE
Check the expression types in the Assignment

### PR DESCRIPTION
**Pull request by Thirumalai-Shaktivel**

### CODE REVIEW

**Comment by certik** [comment]
It looks like the test case that this PR is needed for is at https://github.com/lfortran/lfortran/pull/2083/files#r1282069448. But as indicated there, I would rather just insert an explicit cast there, and not do any kind of implicit casting in ASR builder.

**Comment by certik** [comment]
Let's do the following: let's check the types in the assignment with an assert statement. But let's not do implicit casting.

**Comment by Thirumalai-Shaktivel** [comment]
Ready for review!

**Review by certik — APPROVED** [review]
I think that this is fine!

**Pull request merged**
