### PR TITLE
Explicitly set lfortran_lib and asr as STATIC

### PR DESCRIPTION
**Pull request by topazus**
The `%cmake` rpm macro used in rpm packaging for Fedora enables the option `-DBUILD_SHARED_LIBS:BOOL=ON` by default. It can solve the problem of #1373 by explicitly declaring these 2 libs as static.

ref: https://src.fedoraproject.org/rpms/cmake/blob/rawhide/f/macros.cmake#_5

### CODE REVIEW

**Comment by topazus** [comment]
```
%bcond_without toolchain_clang

%if %{with toolchain_clang}
%global toolchain clang
%else
%global toolchain gcc
%endif

Name:           lfortran
Version:        0.17.0
Release:        %autorelease
Summary:        a modern open-source (BSD licensed) interactive Fortran compiler
License:        BSD-Protection
URL:            https://lfortran.org/
Source:         https://lfortran.github.io/tarballs/release/lfortran-%{version}.tar.gz
Patch0:         https://gist.githubusercontent.com/topazus/ad9358a9544af9b1aad99a84145ce5ac/raw/35859ca8f9f10950c26edf913016232c1190b8b8/lfortran-fix-header.patch
Patch1:         https://raw.githubusercontent.com/topazus/fedora-src/main/lfortran-fix-static-linking.patch

%if %{with toolchain_clang}
BuildRequires:	clang
%else
BuildRequires:	gcc-c++
%endif

BuildRequires:  cmake
BuildRequires:  ninja-build
BuildRequires:  zlib-devel
BuildRequires:  zlib-static
BuildRequires:  llvm-devel
BuildRequires:  xeus-devel
BuildRequires:  xtl-devel
BuildRequires:  json-devel
BuildRequires:  cppzmq-devel

%description
LFortran is a modern open-source (BSD licensed) interactive Fortran compiler
built on top of LLVM. It can execute user's code interactively to allow
exploratory work (much like Python, MATLAB or Julia) as well as compile to
binaries with the goal to run user's code on modern architectures such as
multi-core CPUs and GPUs.

%prep
%autosetup -p1

%build
%cmake \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_LLVM=yes
%cmake_build

%install
%cmake_install

%check
%ctest

%files
%license LICENSE
%doc README.md
%{_bindir}/lfortran
%dir %{_datadir}/lfortran
%{_datadir}/lfortran/lib/

%changelog
%autochangelog
```
It was built successfully on Fedora x86_64 using the above spec file to build and make the rpm package with applying the following patch.

```patch
diff --git a/src/lfortran/CMakeLists.txt b/src/lfortran/CMakeLists.txt
index 29a307a..a0efb57 100644
--- a/src/lfortran/CMakeLists.txt
+++ b/src/lfortran/CMakeLists.txt
@@ -37,7 +37,7 @@ if (WITH_JSON)
         ast_to_json.cpp
     )
 endif()
-add_library(lfortran_lib ${SRC})
+add_library(lfortran_lib STATIC ${SRC})
 target_link_libraries(lfortran_lib asr lfortran_runtime_static)
 
 if (WITH_ZLIB)
diff --git a/src/libasr/CMakeLists.txt b/src/libasr/CMakeLists.txt
index db72e35..86d6e9a 100644
--- a/src/libasr/CMakeLists.txt
+++ b/src/libasr/CMakeLists.txt
@@ -82,7 +82,7 @@ if (WITH_LLVM)
             COMPILE_FLAGS -Wno-deprecated-declarations)
     endif()
 endif()
-add_library(asr ${SRC})
+add_library(asr STATIC ${SRC})
 target_include_directories(asr BEFORE PUBLIC ${libasr_SOURCE_DIR}/..)
 target_include_directories(asr BEFORE PUBLIC ${libasr_BINARY_DIR}/..)
 if (WITH_BFD)
 
```

ref:
build url: https://copr.fedorainfracloud.org/coprs/topazus/test/build/5746014/

**Review by czgdp1807 — COMMENTED** [review]
@certik is the right person to review this. However please wait for the ``libasr`` sync to be complete before merging this in. Thanks for the work.

**Comment by certik** [comment]
Thanks @topazus! I think this change is fine, it always uses static libraries for the intermediate steps in cmake.

However, I just want to understand the problem more --- what is the issue with using shared libraries? Ideally it should work with both, but if it doesn't then we should merge this PR and only support static libraries.

**Comment by topazus** [comment]
> Thanks @topazus! I think this change is fine, it always uses static libraries for the intermediate steps in cmake.
> 
> However, I just want to understand the problem more --- what is the issue with using shared libraries? Ideally it should work with both, but if it doesn't then we should merge this PR and only support static libraries.

In Fedora RPM packaging, the `%cmake` macro is used and the `-DBUILD_SHARED_LIBS` option is ON by default. So the 2 libs needs to be declared `STATIC` to build lfortran, or they will be built as shared libs and the shared libs should be  included in the packaged files by using `%cmake` macro without passing `-DBUILD_SHARED_LIBS=OFF`, which no issue with building with shared libraries except the shared libs need to be included in the package files. In my oppinion, I think it is better to explicitly set the two internal
the library as STATIC.

**Comment by certik** [comment]
Ok, we can do that. Thanks for the explanation and the patch.

**Pull request merged**
