### PR TITLE
LLVM_WASM: Support linking via `emscripten`

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
Example from https://github.com/lfortran/lfortran/issues/3823#issuecomment-2053923507 in browser looks as follows:

image

**Review by certik — APPROVED** [review]
I think this looks good. Thanks!

**Comment by certik** [comment]
Is non-emscripten WASM still supported?

**Comment by Shaikh-Ubaid** [comment]
>Is non-emscripten WASM still supported?

The one from `clang` (for wasi)? Yes that is still supported.

**Pull request merged**
