### PR TITLE
C++ backend: fix do loops without a header

### LINKED ISSUE #821: dev.lfortran.org: the example program throws a runtime error on the cpp tab
I was checking out the online playground at https://dev.lfortran.org/ and when I run the default program on the website the code executes successfully but in the cpp tab it shows an error saying:

```
RuntimeError: Aborted(native code called abort())
ERROR: CPP could not be generated from the code
```

<details>
  <summary>Relevant screenshots</summary>

## stdout tab

image

## cpp tab

image
</details>

I also checked with a simple hello world program and the cpp tab works and generates code.

### PR DESCRIPTION
**Pull request by certik**
We use a while loop for that.

Fixes #821.

### CODE REVIEW

**Comment by certik** [comment]
We should add a test for this as well.

@sloorush or @lucifer1004 do you want to add it?

**Comment by lucifer1004** [comment]
Aha, you are one step ahead of me! I am just going to push this PR.

**Comment by lucifer1004** [comment]
I also need to make a similar change for the Julia backend.

**Comment by certik** [comment]
@lucifer1004 go ahead and take over.

**Comment by certik** [comment]
There are probably more combinations that don't work yet, I just did the minimal fix to get it working for that example.

**Comment by sloorush** [comment]
> We should add a test

I can try! (if the test is not a hurry for development, cause I might take some time to learn how to write tests. I am very new to the code base)

**Comment by lucifer1004** [comment]
> @lucifer1004 go ahead and take over.

Should I start a new PR since I cannot push on yours?

**Comment by sloorush** [comment]
> Also, how do we get @sloorush in?

I can probably make a new PR for the test once this pr is merged?

**Comment by certik** [comment]
@lucifer1004 I gave you push access, you can merge reviewed PRs. You can for example go ahead and review this PR and you can merge it and send a new one with a test, or you can push into my branch, or you can copy my branch and open a new PR yourself, whatever you prefer.

**Comment by lucifer1004** [comment]
Closed as duplicate of #823

**Pull request closed without merging**
